CorporationX/god_bless

src/main/java/school/faang/task_44473/EventType.java
src/main/java/school/faang/task_44473/HogwartsSpells.java
src/main/java/school/faang/task_44473/Main.java
src/main/java/school/faang/task_44473/SpellEvent.java

Ловим события
[BJS2-44473]
[BJS2-44473]: https://faang-school.atlassian.net/browse/BJS2-44473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BJS2-44473

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/task_43969/Main.java
src/main/java/school/faang/task_43969/User.java

BJS2-43969 was completed.

---

src/main/java/school/faang/task_43502/Archer.java
src/main/java/school/faang/task_43502/Character.java
src/main/java/school/faang/task_43502/Main.java
src/main/java/school/faang/task_43502/Warrior.java

Abstraction

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/task_43976/Main.java
src/main/java/school/faang/task_43976/User.java

Создан класс User с необходимыми полями
Реализован метод groupUsers, возвращающий интерфейс "возраст - список пользователей" 
Реализован вывод в консоль

BJS2-43976: Группировка пользователей по возрасту

---

src/main/java/school/faang/task_45253/Book.java
src/main/java/school/faang/task_45253/LibrarySystem.java
src/main/java/school/faang/task_45253/Main.java

Библиотека Вестеросса
BJS2-45253

BJS2-45253

---

src/main/java/school/faang/tack_45275/Book.java
src/main/java/school/faang/tack_45275/BookNotFoundException.java
src/main/java/school/faang/tack_45275/LibrarySystem.java
src/main/java/school/faang/tack_45275/Main.java

Некоторые методы возвращают boolean. Подумал, что это может быть полезным, просто в задаче это никак не используется

BJS2-45275 Done

---

build.gradle
src/main/java/school/faang/task_43939/Address.java
src/main/java/school/faang/task_43939/Job.java
src/main/java/school/faang/task_43939/Main.java
src/main/java/school/faang/task_43939/Name.java
src/main/java/school/faang/task_43939/User.java
src/main/java/school/faang/task_43939/Utilities.java

the task BJS2-43939 - group users by age is ready

Atanoly-BJS2-43939 group users by age

---

src/main/java/school/faang/abstraction_abstraction/Archer.java
src/main/java/school/faang/abstraction_abstraction/Character.java
src/main/java/school/faang/abstraction_abstraction/Main.java
src/main/java/school/faang/abstraction_abstraction/Warrior.java

Ne dis cord bjs2 43824 - Абстракция, Абстракция

---

src/main/java/school/faang/sprint_1/task_43833/Archer.java
src/main/java/school/faang/sprint_1/task_43833/Character.java
src/main/java/school/faang/sprint_1/task_43833/Warrior.java

BJS2-43833: Абстракция, абстракция!

---

src/main/java/school/faang/capturingEvents/HogwartsSpells.java
src/main/java/school/faang/capturingEvents/SpellEvent.java

* task Ловим события from first spring is done

parvin02-BJS2-44505:

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/User.java

grouping users by age - alpha release

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/sprint1/task_43660/Main.java
src/main/java/school/faang/sprint1/task_43660/User.java
src/main/java/school/faang/sprint1/task_43819/Archer.java
src/main/java/school/faang/sprint1/task_43819/Character.java
src/main/java/school/faang/sprint1/task_43819/Main.java
src/main/java/school/faang/sprint1/task_43819/Warrior.java
src/main/java/school/faang/sprint1/task_43866/User.java

BJS2-43819 done

---

src/main/java/school/faang/task_43672/Main.java
src/main/java/school/faang/task_43672/User.java

не знаю, надо ли потом в мейн классе как то объект юзера инициализировать для примера

Bocchineko bjs2 43672

---

src/main/java/school/faang/task_43972/Main.java
src/main/java/school/faang/task_43972/User.java
src/main/java/school/faang/task_43972/Utility.java

the task BJS2-43972 - collecting users - is ready

Atanoly-BJS2-43972 - collecting users

---

src/main/java/ru/maks1979/ArrayReverse/Example.java
src/main/java/ru/maks1979/ArrayReverse/Main.java

Решение задачи с реверсом массива

Решение задачи с реверсом массива

---

src/main/java/school/faang/task_43745/Demo.java
src/main/java/school/faang/task_43745/User.java

Создан класс User, который в конструкторе выполняет валидацию входных данных.

BJS2-43745: Регистрация пользователей

---

src/main/java/school/faang/task_43732/Main.java
src/main/java/school/faang/task_43732/User.java

Create validation methods and add in constructor

BJS2-43732

---

src/main/java/school/faang/s12task43925/Main.java
src/main/java/school/faang/s12task43925/User.java

sprint 1.2 task BJS2-43925 - grouping users by age

---

src/main/java/school/faang/bjs243730/User.java
src/main/java/school/faang/capturingevents/HogwartsSpells.java
src/main/java/school/faang/capturingevents/SpellEvent.java

* task Регистрация пользователей from first spring is done

parvin02-BJS2-43730:

---

src/main/java/school/faang/sprint_1/task_43752/Main.java
src/main/java/school/faang/sprint_1/task_43752/User.java
src/main/java/school/faang/sprint_1/task_43895/Main.java
src/main/java/school/faang/sprint_1/task_43895/User.java

Решил задачу "Группировка пользователей по возрасту". Проверьте пожалуйста.

Erik bjs2 43895

---

src/main/java/derschrank/task02/bjstwo_43966/Activity.java
src/main/java/derschrank/task02/bjstwo_43966/Main.java
src/main/java/derschrank/task02/bjstwo_43966/User.java

Описание
Вам поручено разработать метод для анализа увлечений пользователей. Каждый пользователь имеет уникальный идентификатор, имя, возраст, и список активностей, которыми он увлекается. Целью является создание механизма, который может находить пользователей, увлекающихся конкретными хобби, и возвращать их в удобном формате.
Цель:
Создайте метод на Java, который принимает список пользователей и множество интересующих активностей, а затем возвращает Map, где ключом является пользователь, а значением — найденное совпадающее увлечение. Это поможет эффективно анализировать увлечения пользователей и сопоставлять их с заданными активностями.
Требования:
Создать класс User с полями:
id;
имя;
возраст;
множество активностей (строки).
Создать в этом классе метод findHobbyLovers, который принимает …

BJS2-43966 Task02. Map<User, Activity>

---

src/main/java/school/module1/task43832/Archer.java
src/main/java/school/module1/task43832/Character.java
src/main/java/school/module1/task43832/Main.java
src/main/java/school/module1/task43832/Warrior.java

added RPG-game

---

src/main/java/derschrank/task04/s3/bjstwo_44395/App.java

Условия задачи
Продолжаем создавать новый сервис — платформу для онлайн-продажи редких книг.
Разработка. Тренируем конфликты
Создайте ветку от главной ветки, например feature-a, в неё нужно будет добавить новый файл App.java с классом App с main методом, который будет печатать объявление: «Открытие магазина ожидается через 2 месяца». Сделайте коммит;
Создайте еще одну ветку, например feature-b, также добавьте в неё класс App с main методом, который должен печатать объявление: «Открытие магазина ожидается через 4 дня». Закоммитьте изменения и запуште ветку в удаленный репозиторий;
Влейте в feature-a ветку feature-b, исправьте конфликт в файле App.java, сохраните изменения и закоммитьте и залейте в удаленный репозиторий;
**Теперь залейте feature-a в мастер с помощью PR;
А теперь создадим PR …

Task04. Rare Books Store. Step 3. Feature-B

---

build.gradle
src/main/java/school/faang/Main.java
src/main/java/school/faang/abstraction/Archer.java
src/main/java/school/faang/abstraction/Character.java
src/main/java/school/faang/abstraction/Main.java
src/main/java/school/faang/abstraction/Warrior.java

В классе main проверки метода attack

BJS2-43827: Абстракция, абстракция!

---

src/main/java/school/faang/task_43846/Archer.java
src/main/java/school/faang/task_43846/Character.java
src/main/java/school/faang/task_43846/Demo.java
src/main/java/school/faang/task_43846/Warrior.java

Создан абстрактный класс Character
В нем реализован абстрактный метод атаки, который впоследствии переопределен в классах-наследниках 
Персонажи атакуют оппонента, который предается в метод 
В Demo создаются персонажи разных классов, с выводом информации о них до и после атаки

BJS2-43846: Абстракция, абстракция!

---

src/main/java/school/faang/sprint_1/task_44439/HogwartsSpells.java
src/main/java/school/faang/sprint_1/task_44439/Main.java
src/main/java/school/faang/sprint_1/task_44439/SpellEvent.java

Создан класс SpellEvent и HogwartsSpells
Создан класс SpellEvent с базовыми полями
Создан класс HogwartsSpells с взаимодействием объекта SpellEvent внутри Map

BJS2-44439: Ловим события

---

src/main/java/school/faang/task_44522/HogwartsSpells.java
src/main/java/school/faang/task_44522/Main.java
src/main/java/school/faang/task_44522/SpellEvent.java

1) Создан класс SpellEvent с полями, конструктором и двумя методами equals и hashCode.
2) Создан класс HogwartsSpells, в котором созданы две мапы spellById и spellsByType. 
3) в этом же классе реализованы 5 методов: addSpellEvent, getSpellEventById, getSpellEventsByType, deleteSpellEvent и printAllSpellEvents. 
5) создан класс Main с методом main, в котором используются все методы класса HogwartsSpells.

BJS2-44522: Ловим события

---

src/main/java/school/faang/sprint1/bjs_43755/Main.java
src/main/java/school/faang/sprint1/bjs_43755/User.java
src/main/java/school/faang/sprint1/bjs_43995/Main.java
src/main/java/school/faang/sprint1/bjs_43995/User.java

Просьба к ревьюеру: помоги пж нормальную структуру папок сделать в master ветке, чтобы в school.fang лежал пакет sprint1, а в нем уже все мои задачи, а то я уже задолбался удалять или перемещать папки с задачами по нужному адресу в своих ветках, а потом пулл ветки делаю и все опять криво структурированно, заранее спасибо за помощь :)

BJS2-43995: Группировка пользователей по возрасту

---

src/main/java/school/faang/task_44470/HogwartsSpells.java
src/main/java/school/faang/task_44470/Main.java
src/main/java/school/faang/task_44470/SpellEvent.java

BJS2-44470 was completed.

---

src/main/java/school/faang/sprint_1/task_43644/Example.java
src/main/java/school/faang/sprint_1/task_43644/Main.java

BJS2-43644: Развернитесь!

---

src/main/java/school/faang/task_43793/Main.java
src/main/java/school/faang/task_43793/User.java

- в классе User заданы сеттеры, валидирующие входные параметры

BJS2-43793: Регистрация пользователя

---

src/main/java/school/faang/bsj_44006/Main.java
src/main/java/school/faang/bsj_44006/User.java

Решение задачи "Коллекционируем пользователей"

Anton graf bjs2 44006

---

build.gradle
src/main/java/school/faang/catchingevents/HogwartsSpells.java
src/main/java/school/faang/catchingevents/Main.java
src/main/java/school/faang/catchingevents/SpellEvent.java

Добавлен класс SpellEvent , на его основе реализованы методы в классе HogwartsSpells. В классе main проверки.

BJS2-44497: Ловим события

---

src/main/java/school/faang/sprint_1/task_43752/Main.java
src/main/java/school/faang/sprint_1/task_43752/User.java

Выполнил задачу "Регистрация пользователя". Проверьте пожалуйста.

Выполнил задачу "Группировка пользователей по возрасту"

---

src/main/java/school/faang/sprint_1/task_bjs244000/Main.java
src/main/java/school/faang/sprint_1/task_bjs244000/ParseTestData.java
src/main/java/school/faang/sprint_1/task_bjs244000/User.java

BJS2-44000

---

src/main/java/school/faang/task43920/Main.java
src/main/java/school/faang/task43920/model/Archer.java
src/main/java/school/faang/task43920/model/Character.java
src/main/java/school/faang/task43920/model/Warrior.java

не нашел применения конструктору Character(name), сделал без него.

Абстракция

---

src/main/java/school/faang/task_43848/Archer.java
src/main/java/school/faang/task_43848/Character.java
src/main/java/school/faang/task_43848/CharactersStats.java
src/main/java/school/faang/task_43848/GameConfig.java
src/main/java/school/faang/task_43848/Main.java
src/main/java/school/faang/task_43848/Warrior.java

Заимплементировал также систему боя, не знаю конечно насколько это было обязательно.

solved task_43848

---

src/main/java/school/faang/task_43674/Example.java
src/main/java/school/faang/task_43674/Main.java

BJS2-43674

---

src/main/java/school/faang/bjs_45311/Book.java
src/main/java/school/faang/bjs_45311/LibrarySystem.java
src/main/java/school/faang/bjs_45311/Main.java
src/main/java/school/faang/bjs_45311/exception/BookNotFoundException.java

Решение задачи "Библиотека Вестеросса"

Anton graf bjs2 45311

---

src/main/java/school/faang/task_44537/HogwartsSpells.java
src/main/java/school/faang/task_44537/Main.java
src/main/java/school/faang/task_44537/SpellEvent.java

Реализована система управления заклинаниями для Хогвартса.

реализована система управления заклинаниями для Хогвартса.

---

src/main/java/ru/task_43860/Archer.java
src/main/java/ru/task_43860/Character.java
src/main/java/ru/task_43860/Main.java
src/main/java/ru/task_43860/Warrior.java

Решение задачи с абстрактным классом

---

src/main/java/school/faang/task_44010/Main.java
src/main/java/school/faang/task_44010/User.java

Create User class and method findHobbyLovers

BJS2-44010

---

src/main/java/school/faang/task_45328/Book.java
src/main/java/school/faang/task_45328/LibrarySystem.java
src/main/java/school/faang/task_45328/Main.java

Верно ли я использовал логирование? Или следует сделать методы void -> boolean, и уже от их возращенных значений выводить log.info()?

Библиотека Вестеросса

---

src/main/java/derschrank/task05/bjstwo_43912/Main.java
src/main/java/derschrank/task05/bjstwo_43912/User.java

**Условия задачи**
Создать класс 
User со следующими полями:
имя;
возраст;
место работы;
адрес.
В этом же классе создать статический метод 
groupUsers, который принимает List из объектов User и возвращqает Map, где ключом является возраст пользователя, а значением — список из всех пользователей в оригинальном списке, которые имеют соответствующий возраст.

BJS2-43912 Task05. Group users by age

---

src/main/java/school/faang/sprint_1/task_bjs245369/Book.java
src/main/java/school/faang/sprint_1/task_bjs245369/LibrarySystem.java
src/main/java/school/faang/sprint_1/task_bjs245369/Main.java

BJS2-45369

---

src/main/java/school/faang/sprint_1/task_44053/Main.java
src/main/java/school/faang/sprint_1/task_44053/User.java

Создан объект User и метод поиска хобби в классе Main

BJS2-44053: Коллекционируем пользователей

---

src/main/java/school/faang/task_44597/HogwartsSpells.java
src/main/java/school/faang/task_44597/Main.java
src/main/java/school/faang/task_44597/SpellEvent.java

Создан класс  SpellEvent с необходимыми параметрами заклинаний.
Реализован класс HogwartsSpells, включающий HashMap<Integer, SpellEvent> и HashMap<String, List<SpellEvent>>.
Так же в HogwartsSpells реализованы методы для работы с мапами (добавление в обе карты, поиск заклинаний по id и по типу, удаление из обеих карт по id и вывод на консоль существующий заклинаний.
В Main продемонстрирована работа всех методов.

BJS2-44597: Ловим события

---

src/main/java/school/faang/sprint_1/task_44895/FrequentUpdateWeatherCache.java
src/main/java/school/faang/sprint_1/task_44895/Main.java
src/main/java/school/faang/sprint_1/task_44895/StandardWeatherCache.java
src/main/java/school/faang/sprint_1/task_44895/WeatherCacheTemplate.java
src/main/java/school/faang/sprint_1/task_44895/WeatherData.java
src/main/java/school/faang/sprint_1/task_44895/WeatherProvider.java
src/main/java/school/faang/sprint_1/task_44895/WeatherService.java

Cоздан интерфейс WeatherProvider и абстрактный класс WeatherCacheTemplate
Создан объект WeatherData
Создан класс WeatherService реализующий интерфейс WeatherProvider с логикой получения данных для объекта WeatherData Созданы вложенные классы StandardWeatherCache FrequentUpdateWeatherCache наследующие абстрактный класс WeatherCacheTemplate с логикой проверки актуальности данных Создан класс Main с проверкой работы методов классов.

BJS2-44895: Кэшируем, кэшируем

---

src/main/java/school/faang/sprint_1/task_45232/Main.java
src/main/java/school/faang/sprint_1/task_45232/Student.java
src/main/java/school/faang/sprint_1/task_45232/StudentDatabase.java
src/main/java/school/faang/sprint_1/task_45232/Subject.java
src/test/java/school/faang/sprint_1/task_45232/TestStudentDatabase.java

Создан класс StudentDatabase c методами работы с Map
Созданы объекты Subject и Student
Добавлены тесты для проверки работы класса StudentDatabase

BJS2-45232: Двойной кэш-кэш

---

src/main/java/derschrank/task08/bjstwo_45248/Book.java
src/main/java/derschrank/task08/bjstwo_45248/LibrarySystem.java
src/main/java/derschrank/task08/bjstwo_45248/Main.java
src/main/java/derschrank/task08/bjstwo_45248/info.txt

В королевстве Вестероса хранится огромное количество книг, и король поручил вам создать систему учёта этих книг, чтобы обеспечить легкий доступ к ним для жителей королевства. Вы решаете создать программу на Java, используя HashMap для хранения книг и их авторов.
Цель:
Создайте программу на Java, которая будет хранить информацию о библиотеке королевства, используя HashMap для хранения книг и их авторов. Вам нужно будет учесть особенности методов equals и hashCode.
Требования:
Создайте класс Book с полями:
title;
author;
year.
Переопределите методы equals и hashCode в классе Book, чтобы учитывать название книги, автора и год издания при сравнении книг и расчёте их хэш-кода.
В классе Main, создайте HashMap с ключом типа Book и значением типа String (местонахождение книги в …

BJS2-45248 Task08. LibrarySystem

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/bsj_43843/Archer.java
src/main/java/school/faang/bsj_43843/Character.java
src/main/java/school/faang/bsj_43843/DefaultsParameters.java
src/main/java/school/faang/bsj_43843/Warrior.java

Решение задачи "Абстракция, абстракция!"

Anton graf bjs2 43843

---

src/main/java/school/faang/sprint_1/taskbjs244629/HogwartsSpells.java
src/main/java/school/faang/sprint_1/taskbjs244629/Main.java
src/main/java/school/faang/sprint_1/taskbjs244629/SpellEvent.java
src/main/java/school/faang/sprint_1/taskbjs244629/SpellEventType.java

BJS2-44629

---

src/main/java/school/faang/task_43513/HogwartsSpells.java
src/main/java/school/faang/task_43513/Main.java
src/main/java/school/faang/task_43513/SpellEvent.java

Catch events

---

src/main/java/school/faang/task_45107/Category.java
src/main/java/school/faang/task_45107/Main.java
src/main/java/school/faang/task_45107/Product.java

BJS2-45107

---

src/main/java/school/faang/amazonstore/Main.java
src/main/java/school/faang/amazonstore/Product.java
src/main/java/school/faang/amazonstore/ProductActions.java
src/main/java/school/faang/amazonstore/ProductService.java

Добавлен класс Product, на его основе реализованы методы в классе ProductActions + проверки этих методов. В классе main находятся методы группировки продуктов + их проверки.

BJS2-45117: Разбираем склад Amazon

---

src/main/java/school/faang/task_45149/Main.java
src/main/java/school/faang/task_45149/Product.java
src/main/java/school/faang/task_45149/WarehouseSystem.java

Создан класс Product
Реализован класс WarehouseSystem  с методами работы с Map<String, List<Product>>
В классе Main реализованы методы группировки товаров по категориям из HashSet<Product> и вывода информации о товарах в каждой категории, также в main продемонстрирована работа.

BJS2-45149: Разбираем склад Amazon

---

src/main/java/school/faang/task_45300/Book.java
src/main/java/school/faang/task_45300/LibrarySystem.java
src/main/java/school/faang/task_45300/Main.java

Переопределение методов equals и hashCode, можно было сделать через аннотацию @EqualsAndHashCode
Не понял для чего нужен класс LibrarySystem

создана библиотека Вестеросса

---

src/main/java/school/faang/caching_caching/FrequentUpdateWeatherCache.java
src/main/java/school/faang/caching_caching/Main.java
src/main/java/school/faang/caching_caching/StandardWeatherCache.java
src/main/java/school/faang/caching_caching/WeatherCacheTemplate.java
src/main/java/school/faang/caching_caching/WeatherData.java
src/main/java/school/faang/caching_caching/WeatherProvider.java
src/main/java/school/faang/caching_caching/WeatherService.java

в main'е я старался код сделать более читаемым, но не шибко вышло(

task solution

---

src/main/java/school/faang/task_44836/FrequentUpdateWeatherCache.java
src/main/java/school/faang/task_44836/Main.java
src/main/java/school/faang/task_44836/StandardWeatherCache.java
src/main/java/school/faang/task_44836/WeatherCacheTemplate.java
src/main/java/school/faang/task_44836/WeatherData.java
src/main/java/school/faang/task_44836/WeatherProvider.java
src/main/java/school/faang/task_44836/WeatherService.java

Реализован алгоритм получения и кэширования данных о погоде с использованием паттерна "Шаблонный метод".

Реализован алгоритм получения и кэширования данных о погоде с использованием паттерна "Шаблонный метод".

---

src/main/java/school/faang/task_44719/BOOKING_STATUS.java
src/main/java/school/faang/task_44719/Booking.java
src/main/java/school/faang/task_44719/BookingNotifier.java
src/main/java/school/faang/task_44719/BookingObserver.java
src/main/java/school/faang/task_44719/BookingStatus.java
src/main/java/school/faang/task_44719/BookingSystem.java
src/main/java/school/faang/task_44719/HotelObserver.java
src/main/java/school/faang/task_44719/Main.java
src/main/java/school/faang/task_44719/Room.java
src/main/java/school/faang/task_44719/UserObserver.java

BJS2-44719 was completed.

---

src/main/java/school/faang/doublecash/Main.java
src/main/java/school/faang/doublecash/Student.java
src/main/java/school/faang/doublecash/StudentDatabase.java
src/main/java/school/faang/doublecash/Subject.java

Добавлены классы Student и Subject, на их основе реализованы методы в классе StudentDatabase + проверки этих методов в классе main.

BJS2-45257: Двойной кэш-кэш

---

src/main/java/derschrank/task06/bjstwo_43684/Main.java
src/main/java/derschrank/task06/bjstwo_43684/User.java

В компании "Мир Будущего" разработали новую платформу для управления данными о пользователях. Вам поручено создать модуль, который обеспечит корректное создание объектов пользователей с учётом строгих критериев валидации. Это поможет избежать ошибок при обработке данных и сохранить целостность информации.
Цель:
Создать класс пользователя с конструктором, который выполняет валидацию входных данных на основе заранее определённых критериев. Программа должна демонстрировать использование статических констант, множеств (Set), проверки условий и обработки исключений.
Требования:
Создайте класс User, который представляет пользователя и содержит следующие поля:
name — имя пользователя.
age — возраст пользователя.
job — место работы.
address — адрес.
Объявите и инициализируйте статические …

BJS2-43684 Task06. User registration

---

src/main/java/school/faang/task_44609/HogwartsSpells.java
src/main/java/school/faang/task_44609/Main.java
src/main/java/school/faang/task_44609/SpellEvent.java

Ох уж этот SpellEvent

---

src/main/java/school/faang/sprint_1/task_45027/DataCenter.java
src/main/java/school/faang/sprint_1/task_45027/DataCenterService.java
src/main/java/school/faang/sprint_1/task_45027/EnergyEfficiencyOptimizationStrategy.java
src/main/java/school/faang/sprint_1/task_45027/LoadBalancingOptimizationStrategy.java
src/main/java/school/faang/sprint_1/task_45027/OptimizationStrategy.java
src/main/java/school/faang/sprint_1/task_45027/ResourceRequest.java
src/main/java/school/faang/sprint_1/task_45027/Server.java
src/test/java/school/faang/sprint_1/task_45027/DataCenterServiceTest.java
src/test/java/school/faang/sprint_1/task_45027/TestDataCenterService.java

Реализована логика оптимального распределения ресурсов объекта DataCenter
Создан класс Server
Создан класс DataCenter
Создан класс ResourceRequest
Создан класс DataCenterService с логикой распределения ресурсов класса ResourceRequest для DataCenter. Реализован метод с выбором стратегии оптимизации Создан интерфейс OptimizationStrategy
Создан класс EnergyEfficiencyOptimizationStrategy реализующий OptimizationStrategy Создан класс LoadBalancingOptimizationStrategy реализующий OptimizationStrategy Добавлена проверка тестами

BJS2-45027: Оптимизируем работу дата-центра

---

src/main/java/school/faang/task_45416/DictionaryProcessor.java
src/main/java/school/faang/task_45416/Main.java

The task BJS2-45416 - google translator - is ready

Atanoly-BJS2-45416 - google translator - is ready

---

src/main/java/school/faang/sprint_2/task_45454/Main.java
src/main/java/school/faang/sprint_2/task_45454/SpellAction.java
src/main/java/school/faang/sprint_2/task_45454/SpellCaster.java

Создан функциональный интерфейс SpellAction c реализацией в классе SpellCaster
Добавлена проверка работоспособности в классе Main

BJS2-45454: Хогвартс, Хогвартс, наш любимый Хогвартс

---

src/main/java/school/faang/sprint1/task_43737/Main.java
src/main/java/school/faang/sprint1/task_43737/User.java

BJS2-43737 users registrations.

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/userregister/Main.java
src/main/java/school/faang/userregister/User.java

Создал класс User для пользователей, в конструкторе добавил валидации для каждого элемента класса.

azamat71-BJS2-43760 Создал класс User для пользователей, в конструктор

---

src/main/java/school/faang/sprint_2/task_43539/ListOperations.java
src/main/java/school/faang/sprint_2/task_43539/Main.java

Training stream

---

src/main/java/school/faang/task_45447/Main.java
src/main/java/school/faang/task_45447/Spell.java
src/main/java/school/faang/task_45447/SpellAction.java
src/main/java/school/faang/task_45447/SpellCaster.java

the task BJS2-45447 - our lovely Hogvards - is ready

Atanoly-BJS2-45447 our lovely Hogvards 

---

src/main/java/school/faang/task_45455/Main.java
src/main/java/school/faang/task_45455/SpellAction.java
src/main/java/school/faang/task_45455/SpellCaster.java

1) Создан интерфейс SpellAction с абстрактным методом SpellAction, который принимает в себя строку, и возвращает строку.
2) Создан класс SpellCaster с реализованными полями класса и методом cast.
3) Метод cast принимает в себя строку (название заклинания) и объект интерфейса SpellAction.
4) В теле метода cast строке result присваивается значение метода castSpell входящего параметра и выводиться на экран.
5) В методе main создается объект класса SpellCaster и вызывается метод cast. 
6) В аргументы метода cast передается строка с названием заклинания и лямбда функции.

BJS2-45455: Хогвартс, Хогвартс, наш любимый Хогвартс

---

build.gradle
src/main/java/school/faang/bjs_45459/SpellAction.java
src/main/java/school/faang/bjs_45459/SpellCaster.java
src/main/java/school/faang/bjs_45459/SpellCasterTest.java

Решение задачи "Хогвартс, Хогвартс, наш любимый Хогвартс"

Anton graf bjs2 45459

---

src/main/java/school/faang/favoritehogwarts/Main.java
src/main/java/school/faang/favoritehogwarts/SpellAction.java
src/main/java/school/faang/favoritehogwarts/SpellCaster.java

Добавлен класс SpellCaster с методом cast, который принимает заклинание и лямбда-выражение, описывающее действие этого заклинания

BJS2-45487: Хогвартс, Хогвартс, наш любимый Хогвартс

---

src/main/java/school/faang/bjs245493/Main.java
src/main/java/school/faang/bjs245493/SpellAction.java
src/main/java/school/faang/bjs245493/SpellCaster.java

* Хогвартс, Хогвартс, наш любимый Хогвартс is finished

bjs2-45493

---

src/main/java/school/faang/sprint1/task_43964/Main.java
src/main/java/school/faang/sprint1/task_43964/User.java

BJS2-43964 group users by age.

---

src/main/java/school/faang/task_44843/FrequentUpdateWeatherCache.java
src/main/java/school/faang/task_44843/Main.java
src/main/java/school/faang/task_44843/StandardWeatherCache.java
src/main/java/school/faang/task_44843/WeatherCacheTemplate.java
src/main/java/school/faang/task_44843/WeatherData.java
src/main/java/school/faang/task_44843/WeatherProvider.java
src/main/java/school/faang/task_44843/WeatherService.java

BJS2-44843 Кэшируем, кэшируем

---

src/main/java/school/faang/task_45159/Main.java
src/main/java/school/faang/task_45159/Product.java

Склад AMAZON

---

src/main/java/derschrank/task03/bjstwo_43815/Archer.java
src/main/java/derschrank/task03/bjstwo_43815/Character.java
src/main/java/derschrank/task03/bjstwo_43815/Main.java
src/main/java/derschrank/task03/bjstwo_43815/Warrior.java

https://faang-school.atlassian.net/browse/BJS2-43815
Описание
Вы разрабатываете базовый модуль для RPG-игры. В игре персонажи обладают различными характеристиками, которые влияют на их способности в бою. Главная задача — реализовать базовый класс для персонажей и классы-наследники для различных типов (воин и лучник), обеспечив уникальные механики атаки для каждого типа.
Цель:
Создать иерархию классов для персонажей игры с использованием наследования и полиморфизма. В задаче рассматривается создание абстрактного класса, наследников с уникальными особенностями и механизма взаимодействия между персонажами через полиморфизм.
Требования:
Создать абстрактный класс Character со следующими полями:
Имя;
Сила;
Ловкость;
Интеллект;
Здоровье. У всех персонажей по умолчанию 100.
Сделать в Character …

BJS2-43815 Task03. Абстракция, абстракция!

---

src/main/java/school/faang/bjs_45147/GeneratorId.java
src/main/java/school/faang/bjs_45147/Main.java
src/main/java/school/faang/bjs_45147/Product.java
src/main/java/school/faang/bjs_45147/Store.java
src/main/java/school/faang/bjs_45147/enums/Category.java
src/main/java/school/faang/bjs_45147/exception/CategoryNotFoundException.java
src/main/java/school/faang/bjs_45147/exception/ProductNotFoundException.java

Решение задачи "Разбираем склад Amazon"

Anton graf bjs2 45147

---

src/main/java/school/faang/task_43519/Main.java
src/main/java/school/faang/task_43519/Student.java
src/main/java/school/faang/task_43519/StudentDatabase.java
src/main/java/school/faang/task_43519/Subject.java

Cache cache

---

src/main/java/school/faang/task_45137/Main.java
src/main/java/school/faang/task_45137/Product.java

Реализована система управления товарами с группировкой по категориям.

Реализована система управления товарами с группировкой по категориям.

---

src/main/java/school/faang/sprint1task44639/HogwartsSpells.java
src/main/java/school/faang/sprint1task44639/Main.java
src/main/java/school/faang/sprint1task44639/SpellEvent.java

Task: BJS2-44639 Done

---

src/main/java/school/faang/bjs245818/Character.java
src/main/java/school/faang/bjs245818/InventoryManager.java
src/main/java/school/faang/bjs245818/Item.java
src/main/java/school/faang/bjs245818/Main.java

* Lord of the Rings RPG is finished

bjs2-45818

---

src/main/java/school/faang/task_45562/Coordinates.java
src/main/java/school/faang/task_45562/FlipDirection.java
src/main/java/school/faang/task_45562/Main.java
src/main/java/school/faang/task_45562/MatrixTransformer.java

BJS2-45562

---

src/main/java/school/faang/task_46191/Droid.java
src/main/java/school/faang/task_46191/DroidMessageEncryptor.java
src/main/java/school/faang/task_46191/Main.java

BJS2-46191

---

src/main/java/school/faang/task_46233/FilterProcessor.java
src/main/java/school/faang/task_46233/Image.java
src/main/java/school/faang/task_46233/Main.java

BJS2-46233

---

src/main/java/school/faang/sprint_1/task_bjs245269/Main.java
src/main/java/school/faang/sprint_1/task_bjs245269/Student.java
src/main/java/school/faang/sprint_1/task_bjs245269/StudentDatabase.java
src/main/java/school/faang/sprint_1/task_bjs245269/Subject.java

BJS2-45269

---

src/main/java/school/faang/sprint_2/task_46610/Main.java
src/main/java/school/faang/sprint_2/task_46610/Notification.java
src/main/java/school/faang/sprint_2/task_46610/NotificationManager.java

Создан класс NotificationManager с проверкой работы в классе Main

BJS2-46610: Meta-вселенная?

---

build.gradle
src/main/java/school/faang/task_46597/Main.java
src/main/java/school/faang/task_46597/Notification.java
src/main/java/school/faang/task_46597/NotificationManager.java

BJS2-46597

---

src/main/java/school/faang/task_45774/Email.java
src/main/java/school/faang/task_45774/EmailProcessor.java
src/main/java/school/faang/task_45774/Main.java
src/test/java/tests/GmailRichTests.java

BJS2-45774

---

src/main/java/school/faang/metauniverse/Main.java
src/main/java/school/faang/metauniverse/Notification.java
src/main/java/school/faang/metauniverse/NotificationManager.java

Добавлен класс NotificationManager, который содержит Map для связывания идентификаторов оповещений с их обработчиками.

BJS2-46627: Meta-вселенная?

---

src/main/java/school/faang/sprint_2/task_bjs245535/Main.java
src/main/java/school/faang/sprint_2/task_bjs245535/SpellAction.java
src/main/java/school/faang/sprint_2/task_bjs245535/SpellCaster.java

BJS2-45535
Хогвартс, Хогвартс, наш любимый Хогвартс

BJS2-45535

---

src/main/java/school/faang/task_46677/Main.java
src/main/java/school/faang/task_46677/Notification.java
src/main/java/school/faang/task_46677/NotificationManager.java

BJS2-46677 was completed.

---

src/main/java/school/faang/sprint_1/task_abstractionbsj2n43974/Archer.java
src/main/java/school/faang/sprint_1/task_abstractionbsj2n43974/Character.java
src/main/java/school/faang/sprint_1/task_abstractionbsj2n43974/Main.java
src/main/java/school/faang/sprint_1/task_abstractionbsj2n43974/Warrior.java

Оставил конструкторы с несколькими параметрами в классах Warrior and Archer
т.к. было не ясно зачем делать конструктор, если его переменные не используются для создания объекта,
хотя по заданию, если нужно переопределить и чтобы всегда были только константные значения нужно делать так:
```
public Warrior(String name, int strength, int agility, int intellect) {
super(name);
this.strength = WARRIOR_STRENGTH;
this.agility = WARRIOR_AGILITY;
this.intellect = WARRIOR_INTELLECT;
}
```

Alexeyrnd bjs2 43873

---

src/main/java/school/faang/bjs246651/Main.java
src/main/java/school/faang/bjs246651/Notification.java
src/main/java/school/faang/bjs246651/NotificationManager.java

bjs2-46651

---

src/main/java/derschrank/task11/bjstwo_44817/FrequentUpdateWeatherCache.java
src/main/java/derschrank/task11/bjstwo_44817/Main.java
src/main/java/derschrank/task11/bjstwo_44817/StandardWeatherCache.java
src/main/java/derschrank/task11/bjstwo_44817/WeatherCache.java
src/main/java/derschrank/task11/bjstwo_44817/WeatherCacheTemplate.java
src/main/java/derschrank/task11/bjstwo_44817/WeatherData.java
src/main/java/derschrank/task11/bjstwo_44817/WeatherProvider.java
src/main/java/derschrank/task11/bjstwo_44817/WeatherService.java
src/main/java/derschrank/task11/bjstwo_44817/info.txt

https://faang-school.atlassian.net/browse/BJS2-44817
Создайте систему для получения и кэширования данных о погоде в разных городах с учетом срока их актуальности. Используйте паттерн "Шаблонный метод" для создания общего алгоритма с возможностью настройки шагов, таких как обновление данных или проверка актуальности кэша.
Цель: Изучить паттерн "Шаблонный метод" (Template Method) для создания гибкого алгоритма получения и кэширования данных, а также научиться управлять сроками действия кэша и оптимизировать запросы к внешним источникам данных.
Требования:
Создайте класс WeatherData с полями:
String city — название города;
double temperature — текущая температура;
double humidity — текущая влажность;
long timestamp — время получения данных (в миллисекундах), чтобы отслеживать …

BJS2-44817 Task11. WeatherCache

---

src/main/java/school/faang/task_45548/Main.java
src/main/java/school/faang/task_45548/SpellAction.java
src/main/java/school/faang/task_45548/SpellCaster.java

Создан функциональный интерфейс SpellAction с методом theEffectOfTheSpell, принимающим название заклинания, возвращающим его реализацию
Реализован класс SpellCaster с методом cast, который принимает название заклинания и лямбда выражение SpellAction. В нем реализован вызов лямбда-выражения и вывод на консоль названия заклинания

BJS2-45548: Хогвартс, Хогвартс, наш любимый Хогвартс

---

src/main/java/school/faang/task_45815/Email.java
src/main/java/school/faang/task_45815/EmailProcessor.java
src/main/java/school/faang/task_45815/Main.java

BJS2-45815 was completed.

---

src/main/java/school/faang/gmailfilters/Email.java
src/main/java/school/faang/gmailfilters/EmailProcessor.java
src/main/java/school/faang/gmailfilters/Main.java

Добавлен класс EmailProcessor, который применяет Predicate для фильтрации писем, Consumer для их обработки и Function для преобразования

BJS2-45857: Gmail Rich Filters

---

src/main/java/school/faang/bjs246058/Email.java
src/main/java/school/faang/bjs246058/EmailProcessor.java
src/main/java/school/faang/bjs246058/Main.java

* Gmail Rich Filters is finished

bjs2-46058

---

src/main/java/school/faang/sprint_2/task_46215/Droid.java
src/main/java/school/faang/sprint_2/task_46215/DroidMessageEncryptor.java
src/main/java/school/faang/sprint_2/task_46215/DroidMessageManager.java
src/main/java/school/faang/sprint_2/task_46215/Main.java

Создан класс Droid который принимает и отправляет зашифрованные сообщения

BJS2-46215: Секреты дроидов

---

build.gradle
src/main/java/school/faang/bjs_46652/Notification.java
src/main/java/school/faang/bjs_46652/NotificationManager.java
src/main/java/school/faang/bjs_46652/NotificationType.java
src/test/java/school/faang/bjs_46652/NotificationManagerTest.java

Решение задачи "Meta-вселенная?"

AntonGraf-BJS2-46652

---

src/main/java/school/faang/task_46661/Main.java
src/main/java/school/faang/task_46661/Notification.java
src/main/java/school/faang/task_46661/NotificationManager.java

1) Создан класс Notification, c полями, конструктором и с реализацией методов HashCode и equals.
2) Создан класс NotificationManager с двумя методами:
- метод registerHandler производит наполнение HashMap (**ключ** - тип оповещение, **значение** - классы, реализующие интерфейс Consumer.)
- метод sendNotification принимает в себя объект класса Notification, находит по ключу значение в HashMap, и отрабатывает метод класса, который находился в значении.
3) В методе main тестируем работу программы.

BJS2-46661: Meta-вселенная?

---

src/main/java/school/faang/bjs246249/FilterProcessor.java
src/main/java/school/faang/bjs246249/Image.java
src/main/java/school/faang/bjs246249/Main.java

* Фильтры Instagram is finished

bjs2-46249

---

src/main/java/school/faang/sprint_2/task_45520/Character.java
src/main/java/school/faang/sprint_2/task_45520/InventoryManager.java
src/main/java/school/faang/sprint_2/task_45520/Item.java
src/main/java/school/faang/sprint_2/task_45520/Main.java

Создан класс InventoryManager, который управляет инвентарем персонажа с использованием функциональных интерфейсов

BJS2-45520: Lord of the Rings RPG

---

src/main/java/school/faang/sprint_2/task_46410/ErrorHandler.java
src/main/java/school/faang/sprint_2/task_46410/ExceptionHandler.java
src/main/java/school/faang/sprint_2/task_46410/Main.java

Создан класс ErrorHandler с методом, который возвращает значение в случае исключения

BJS2-46410: Обрабатываем ошибки красиво

---

src/main/java/derschrank/task12/bjstwo_45017/DataCenter.java
src/main/java/derschrank/task12/bjstwo_45017/DataCenterService.java
src/main/java/derschrank/task12/bjstwo_45017/Main.java
src/main/java/derschrank/task12/bjstwo_45017/ResourceRequest.java
src/main/java/derschrank/task12/bjstwo_45017/info.txt
src/main/java/derschrank/task12/bjstwo_45017/optimization/EnergyEfficiencyOptimizationStrategy.java
src/main/java/derschrank/task12/bjstwo_45017/optimization/LoadBalancingOptimizationStrategy.java
src/main/java/derschrank/task12/bjstwo_45017/optimization/OptimizationStrategy.java
src/main/java/derschrank/task12/bjstwo_45017/servers/Server.java
src/main/java/derschrank/task12/bjstwo_45017/servers/ServersPattern.java

Описание
Представьте, что вы работаете в крупнейшей компании, имеющей дата-центры по всему миру. Ваша задача — создать систему для оптимального распределения ресурсов, которая обеспечит эффективное использование серверов в дата-центре.
Выполнение этой задачи поможет лучше понять концепции ООП, реализовать паттерн Стратегия и в целом попрактиковать навыки проектирования и реализации систем с использованием различных компонентов.
Цель: Научиться проектировать систему для управления ресурсами с использованием ООП и паттерна Стратегия, реализовав алгоритмы распределения нагрузки и управления энергопотреблением.
Требования:
Создайте класс Server с характеристиками:
double load — текущая нагрузка на сервер;
double maxLoad — максимальная нагрузка, которую сервер может выдержать; …

BJS2-45017 Task12. DataCenterServer and OptimizationStrategy

---

src/main/java/school/faang/sprint_2/task_bjs246727/Main.java
src/main/java/school/faang/sprint_2/task_bjs246727/Notification.java
src/main/java/school/faang/sprint_2/task_bjs246727/NotificationManager.java
src/main/java/school/faang/sprint_2/task_bjs246727/NotificationType.java

BJS2-46727

---

src/main/java/school/faang/task_45235/Main.java
src/main/java/school/faang/task_45235/Student.java
src/main/java/school/faang/task_45235/StudentDatabase.java
src/main/java/school/faang/task_45235/Subject.java

1) Cозданы два класса Student и Subject с полями класса, конструкторами и переопределенными методами HashCode и equals.
2) Создан класс StudentDatabase с двумя HashMap, и 8-ю методами для работы с HashMap.
3) Создан класс Main, для тестирования методов класса StudentDatabase.
P.S. Часа 2 пытался сделать юнит тесты, но нечего не вышло. Надеюсь пока можно без них сдавать на проверку?

BJS2-45235: Двойной кэш-кэш

---

src/main/java/school/faang/task_43518/Main.java
src/main/java/school/faang/task_43518/Product.java

Amazon warehouse

---

src/main/java/school/faang/task_46222/ErrorHandler.java
src/main/java/school/faang/task_46222/ExceptionHandler.java
src/main/java/school/faang/task_46222/Main.java
src/main/java/school/faang/task_46222/RemoteService.java

BJS2-46222 was completed.

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/User.java

на проверку отправляю её впервые... 
_Сейчас заметил, что в классе "User" у меня лишняя 18 пустая строка. Не стал уже делать новый комит._

BJS2-44021: Группировка пользователей по возрасту

---

src/main/java/school/faang/sprint_2/task_46845/ListOperations.java
src/main/java/school/faang/sprint_2/task_46845/Main.java

Создан класс ListOperations с методами которые выполняет операции через Stream API

BJS2-46845: Потренируем StreamAPI 1

---

src/main/java/school/faang/bjs246958/ListOperations.java
src/main/java/school/faang/bjs246958/Main.java

* Потренируем StreamAPI 1 is finished

bjs2-46958

---

src/main/java/school/faang/ourbelovehogwartsbjs45573/Main.java
src/main/java/school/faang/ourbelovehogwartsbjs45573/SpellAction.java
src/main/java/school/faang/ourbelovehogwartsbjs45573/SpellCaster.java

…линаний с использованием лямбда-выражений

BJS2-45573 - Хогвартс, Хогвартс, наш любимый Хогвартс 

---

src/main/java/school/faang/bjs_46193/ErrorHandler.java
src/test/java/school/faang/bjs_46193/ErrorHandlerTest.java

Решение задачи "Обрабатываем ошибки красиво"

AntonGraf-BJS2-46193

---

src/main/java/school/faang/sprint_2/task_bjs246345/FilterProcessor.java
src/main/java/school/faang/sprint_2/task_bjs246345/Image.java
src/main/java/school/faang/sprint_2/task_bjs246345/ImageDescription.java
src/main/java/school/faang/sprint_2/task_bjs246345/Main.java

BJS2-46345

---

src/main/java/school/faang/bjs_46327/FilterProcessor.java
src/main/java/school/faang/bjs_46327/Image.java
src/test/java/school/faang/bjs_46327/FilterProcessorTest.java

Решение задачи "Фильтры Instagram"

AntonGraf-BJS2-46327

---

src/main/java/school/faang/task_45820/Email.java
src/main/java/school/faang/task_45820/EmailProcessor.java
src/main/java/school/faang/task_45820/Main.java

1) создан класс Email с полями класса и конструктором.
2) создан класс EmailProcessor с методом processEmails, который принимает в себя список сообщений и 3 фильтра.
3) создан класс Main, в котором:
- наполняется ArrayList объектами класса Email;
- при помощи лямбд создается 3 фильтра;
- тестируется метод processEmails;

BJS2-45820: Gmail Rich Filters

---

src/main/java/school/faang/sprint_2/task_bjs245920/Email.java
src/main/java/school/faang/sprint_2/task_bjs245920/EmailProcessor.java
src/main/java/school/faang/sprint_2/task_bjs245920/Main.java

BJS2-45920

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/bjs245280/Main.java
src/main/java/school/faang/bjs245280/Student.java
src/main/java/school/faang/bjs245280/StudentDatabase.java
src/main/java/school/faang/bjs245280/Subject.java

BJS2_45280 Double Cache-Cache - release

Madmax bjs2 45280

---

src/main/java/school/faang/task_46800/ListOperations.java
src/main/java/school/faang/task_46800/Main.java

BJS2-46800

---

src/main/java/school/faang/task_46571/Location.java
src/main/java/school/faang/task_46571/LocationSearchEngine.java
src/main/java/school/faang/task_46571/Main.java

BJS2-46571

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/task_44016/Main.java
src/main/java/school/faang/task_44016/User.java

Задача "Группировка пользователей по возрасту"

BJS2-44016 - the task "Grouping users by age"

---

src/main/java/derschrank/sprint02/task02/bjstwo_46670/Main.java
src/main/java/derschrank/sprint02/task02/bjstwo_46670/Notification.java
src/main/java/derschrank/sprint02/task02/bjstwo_46670/NotificationManager.java
src/main/java/derschrank/sprint02/task02/bjstwo_46670/NotificationManagerInterface.java
src/main/java/derschrank/sprint02/task02/bjstwo_46670/NotificationType.java

Вы являетесь разработчиком в компании Meta и работаете над новым приложением для управления оповещениями. Ваша задача — создать систему, которая позволяет пользователям выбирать различные типы оповещений на основе их предпочтений. Для реализации этой системы вы будете использовать стандартные функциональные интерфейсы Java, такие как Consumer.
Цель:
Создайте класс NotificationManager, который будет содержать Map для связывания идентификаторов оповещений с их обработчиками.
В данном случае, обработчик оповещения — это функциональный интерфейс, который получает объект Notification и выполняет какое-либо действие, связанное с этим оповещением (например, отправляет сообщение, выводит текст на экран и т.д.).
Требования:
1. Создайте класс Notification с полями type (тип оповещения) и message …

BJS2-46670 Sprint02. Task02. Notification and NotificationManager

---

src/main/java/school/faang/sprint_2/task_45880/TriangleAreaCalculator.java

Реализован метод вычисления площади треугольника с помощью лямбд-выражений

BJS2-45880: Вспомним школу

---

src/main/java/school/faang/droidsecrets/Droid.java
src/main/java/school/faang/droidsecrets/DroidMessageEncryptor.java
src/main/java/school/faang/droidsecrets/Main.java

Добавлен класс Droid, который умеет шифровать и расшифровывать сообщения

BJS2-46197: Секреты дроидов

---

src/main/java/school/faang/sprint_2/task_47420/Employee.java
src/main/java/school/faang/sprint_2/task_47420/Main.java
src/main/java/school/faang/sprint_2/task_47420/StreamOperations.java
src/test/java/school/faang/sprint_2/task_47420/StreamOperationsTest.java

Создан класс StreamOperations с методами, которые выполняют операции с помощью Stream API
Добавлены тесты

BJS2-47420: Потренируем StreamAPI 3

---

src/main/java/school/faang/sprint1/bjs_45155/Main.java
src/main/java/school/faang/sprint1/bjs_45155/Product.java

Уважаемый ревьюер, сил тебе и здоровья разобрать то, что я тут наговнокодил))

BJS2-45155: Разбираем склад Amazon

---

src/main/java/school/faang/bjs247547/ActionType.java
src/main/java/school/faang/bjs247547/Main.java
src/main/java/school/faang/bjs247547/UserAction.java
src/main/java/school/faang/bjs247547/UserActionAnalyzer.java

* Анализ активности пользователей в социальной сети is finished

bjs2-47079

---

src/main/java/school/faang/bjs45371/Book.java
src/main/java/school/faang/bjs45371/LibrarySystem.java
src/main/java/school/faang/bjs45371/Main.java

created LibrarySystem + Book classes according to task, tested in Main

ztsv-BJS2-45371 - библиотека Вестероса

---

src/main/java/school/faang/bjs_45873/Email.java
src/main/java/school/faang/bjs_45873/EmailProcessor.java
src/main/java/school/faang/bjs_45873/Main.java
src/test/java/school/faang/bjs_45873/EmailProcessorTest.java

Решение задачи "Gmail Rich Filters"

AntonGraf-BJS2-45873

---

src/main/java/derschrank/sprint02/task01/bjstwo_45458/Main.java
src/main/java/derschrank/sprint02/task01/bjstwo_45458/SpellAction.java
src/main/java/derschrank/sprint02/task01/bjstwo_45458/SpellCaster.java

Описание
Вы — ученик школы чародейства и волшебства «Хогвартс», и вам поручено создать систему для управления заклинаниями. Ваша система должна быть способна выполнять различные магические действия, передавая эти действия в виде лямбда-выражений.
Цель:
Создайте класс SpellCaster с методом cast, который принимает строку с названием заклинания и лямбда-выражение, описывающее действие этого заклинания. Используйте этот метод для выполнения различных магических действий.
Требования:
1. Создайте функциональный интерфейс SpellAction, который имеет один метод, принимающий строку с названием заклинания и возвращающий строку с результатом выполнения заклинания.
2. Создайте класс SpellCaster с методом cast, который:
Принимает два аргумента: строку с названием заклинания и лямбда-выражение типа …

BJS2-45458 Sprint02. Task01. SpellAction and SpellCaster

---

src/main/java/derschrank/sprint02/task06/bjstwo_46575/ErrorHandler.java
src/main/java/derschrank/sprint02/task06/bjstwo_46575/Main.java
src/main/java/derschrank/sprint02/task06/bjstwo_46575/RemoteService.java
src/main/java/derschrank/sprint02/task06/bjstwo_46575/info.txt

BJS2-46575 Sprint02. Task06. ErrorHanlder. Supplier and Function

---

src/main/java/derschrank/sprint02/task05/bjstwo_45515/Character.java
src/main/java/derschrank/sprint02/task05/bjstwo_45515/InventoryManager.java
src/main/java/derschrank/sprint02/task05/bjstwo_45515/InventoryManagerInterface.java
src/main/java/derschrank/sprint02/task05/bjstwo_45515/Item.java
src/main/java/derschrank/sprint02/task05/bjstwo_45515/Main.java
src/main/java/derschrank/sprint02/task05/bjstwo_45515/info.txt

BJS2-45515 Sprint02. Task05. Lord of the Rings RPG. Predicate, Consumer, Function

---

src/main/java/school/faang/bjs_46893/ListOperations.java
src/test/java/school/faang/bjs_46893/ListOperationsTest.java

Решение задачи "Потренируем StreamAPI 1"

AntonGraf-BJS2-46893

---

src/main/java/school/faang/bjs246902/ListOperations.java
src/main/java/school/faang/bjs246902/Main.java

lcodio bjs2-46902 stream api1

---

src/main/java/derschrank/sprint02/task03/bjstwo_46685/FilterProcessor.java
src/main/java/derschrank/sprint02/task03/bjstwo_46685/FilterType.java
src/main/java/derschrank/sprint02/task03/bjstwo_46685/Image.java
src/main/java/derschrank/sprint02/task03/bjstwo_46685/Main.java

Вы работаете над функцией для Instagram, которая позволяет пользователям накладывать фильтры на свои фотографии. Ваша задача — создать систему, где можно выбрать фильтры и применить их к фотографиям с помощью функций высокого порядка в Java.
Цель:
Создать класс FilterProcessor, который поможет вам применять фильтры к изображениям с помощью функций.
Требования:
1. Создать класс Image, который хранит информацию о фотографии:
name (имя файла),
description (описание, которое обновляется с каждым применённым фильтром).
2. Создать класс FilterProcessor с двумя методами:
applyFilter: применяет фильтр к изображению. Фильтр — это функция, которая берёт одно изображение и возвращает новое с изменениями. Метод applyFilter принимает объект типа Image и функцию высокого порядка для применения фильтра …

BJS2-46685 Sprint02. Task03. FilterProcessor. Function -> UnaryOperator<Image>

---

src/main/java/school/faang/task_47008/ListOperations.java
src/main/java/school/faang/task_47008/Main.java

Возможно где-то будут неправильные проверки на null

BJS2-47008 API 1ч

---

src/main/java/school/faang/task_47100/ListOperations.java
src/main/java/school/faang/task_47100/Main.java

BJS2-47100 was completed.

---

src/main/java/school/faang/task_47069/Main.java

BJS2-47069

---

src/main/java/school/faang/bsj43913/Archer.java
src/main/java/school/faang/bsj43913/Character.java
src/main/java/school/faang/bsj43913/Main.java
src/main/java/school/faang/bsj43913/Warior.java

created class Character, Warior, Archer according to the task

ztsv-BJS2-43913 - Abstraction, Abstraction

---

src/main/java/derschrank/sprint02/task04/bjstwo_45769/Email.java
src/main/java/derschrank/sprint02/task04/bjstwo_45769/EmailProcessor.java
src/main/java/derschrank/sprint02/task04/bjstwo_45769/Main.java
src/main/java/derschrank/sprint02/task04/bjstwo_45769/info.txt

Вы — разработчик приложения GMail и сейчас работаете над функцией, которая позволит пользователям настраивать фильтры для входящих писем. Задача — создать систему, которая будет фильтровать, обрабатывать и преобразовывать письма с использованием функциональных интерфейсов: Predicate, Consumer, и Function.
Цель:
Создайте класс EmailProcessor, который будет применять Predicate для фильтрации писем, Consumer для их обработки и Function для преобразования.
Требования:
1. Создайте класс Email с полями:
subject — тема письма;
body — текст письма;
isImportant — флаг, указывающий, важное письмо или нет.
2. Создайте класс EmailProcessor с методом processEmails.
3. Метод processEmails должен:
принимать список входящих писем;
фильтровать их с помощью Predicate<Email>
преобразовывать тело письма с …

BJS2-45769 Sprint02. Task04. GMail. Predicate, Consumer, Function

---

src/main/java/school/faang/task_46785/Main.java
src/main/java/school/faang/task_46785/Notification.java
src/main/java/school/faang/task_46785/NotificationManager.java
src/main/java/school/faang/task_46785/NotificationType.java

Создан класс Notification с полями type и message;
Реализован класс NotificationManager: 
- метод registerHandler добавляет в Map идентификатор оповещения как ключ и лямбду интерфейса Consumer<Notification>
- метод sendNotification вызывает обработчик по корректировке слов сообщения и вызывает обработчик оповещения из Map по типу этого оповещения.

BJS2-46785: Meta-вселенная?

---

src/main/java/school/faang/sprint_1/task_bjs245200/Main.java
src/main/java/school/faang/sprint_1/task_bjs245200/NameValidator.java
src/main/java/school/faang/sprint_1/task_bjs245200/Product.java
src/main/java/school/faang/sprint_1/task_bjs245200/ProductCategory.java
src/main/java/school/faang/sprint_1/task_bjs245200/Store.java

Разбираем склад Amazon
В коде намеренно использован String Category, а не Enum Category, чтобы соответствовать условию: "добавляет новый товар в указанную категорию. Если категории нет, создайте её".

BJS2-45200

---

src/main/java/school/faang/sprint_2/task_bjs245615/Character.java
src/main/java/school/faang/sprint_2/task_bjs245615/InventoryManager.java
src/main/java/school/faang/sprint_2/task_bjs245615/Item.java
src/main/java/school/faang/sprint_2/task_bjs245615/Main.java

BJS2-45615
Lord of the Rings RPG

BJS2-45615

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/task_46356/FilterProcessor.java
src/main/java/school/faang/task_46356/Image.java
src/main/java/school/faang/task_46356/Main.java

Спасибо Идеи, я вообще не понял нечего.
Function<Image, Image> combinedFilter
я понял одно, что у Function можно добавить методы, и выполнить их последовательно через .andThen().
Ну как этого дойти самому, я так и не понял.

Andrey s nosov bjs2 46356

---

src/main/java/school/faang/task_46393/FilterProcessor.java
src/main/java/school/faang/task_46393/Image.java
src/test/java/school/faang/task_46393/FilterProcessorTest.java

First working solution

---

src/main/java/school/faang/task_45583/Character.java
src/main/java/school/faang/task_45583/InventoryManager.java
src/main/java/school/faang/task_45583/Item.java
src/main/java/school/faang/task_45583/Main.java

Реализована система управления инвентарем персонажей для игры.

Реализована система управления инвентарем персонажей для игры.

---

src/main/java/school/faang/sprint_2/task_bjs246224/ErrorHandler.java
src/main/java/school/faang/sprint_2/task_bjs246224/Main.java
src/main/java/school/faang/sprint_2/task_bjs246224/RemoteService.java

BJS2-46224
Обрабатываем ошибки красиво

BJS2-46224

---

src/main/java/school/faang/s13task44826/City.java
src/main/java/school/faang/s13task44826/FrequentUpdateWeatherCache.java
src/main/java/school/faang/s13task44826/Main.java
src/main/java/school/faang/s13task44826/StandardWeatherCache.java
src/main/java/school/faang/s13task44826/WeatherCacheTemplate.java
src/main/java/school/faang/s13task44826/WeatherData.java
src/main/java/school/faang/s13task44826/WeatherProvider.java
src/main/java/school/faang/s13task44826/WeatherService.java

sprint 1.3 task BJS2-44826

---

src/main/java/school/faang/sprint2/task_46817/Main.java
src/main/java/school/faang/sprint2/task_46817/Notification.java
src/main/java/school/faang/sprint2/task_46817/NotificationManager.java

Честно, вообще ничего не лезет в голову по 4-му пункту задания

BJS2-46817

---

src/main/java/school/faang/task_46217/Action.java
src/main/java/school/faang/task_46217/Main.java
src/main/java/school/faang/task_46217/RemoteService.java

Working solution BJS2-46217 

---

src/main/java/school/faang/s12task45216/Main.java
src/main/java/school/faang/s12task45216/Student.java
src/main/java/school/faang/s12task45216/StudentDatabase.java
src/main/java/school/faang/s12task45216/Subject.java

lcodio BJS2-45216 double cache

---

src/main/java/school/faang/task_43790/Example.java
src/main/java/school/faang/task_43790/Main.java
src/test/java/school/faang/task_43790/ExampleTest.java

https://faang-school.com/courses/4jnzmndg/gnzgrbyd

romankondratev-BJS2-43790/task-reverse

---

src/main/java/school/faang/task_46948/ListOperations.java
src/test/java/school/faang/task_46948/ListOperationsTest.java

Правильно ли я обработал возможные исключения на null? Может следовало явно указывать .orElseThrow() в каждом методе с Optional?

Потренируем StreamAPI 1 

---

src/main/java/school/faang/bjs246514/ErrorHandler.java
src/main/java/school/faang/bjs246514/ExceptionHandler.java
src/main/java/school/faang/bjs246514/ExceptionSupplier.java
src/main/java/school/faang/bjs246514/Main.java

* Обрабатываем ошибки красиво is finished

bjs2-46514

---

src/main/java/school/faang/trainingstreamapi1/ListOperations.java
src/main/java/school/faang/trainingstreamapi1/Main.java

Добавлен класс ListOperations со статическими методами, которые выполняют различные операции с числами и строками в списках

BJS2-47057: Потренируем StreamAPI 1

---

src/main/java/school/faang/metabjs46838/Main.java
src/main/java/school/faang/metabjs46838/Notification.java
src/main/java/school/faang/metabjs46838/NotificationManager.java
src/main/java/school/faang/metabjs46838/NotificationType.java

…ениями. Реализованы методы регистрации обработчиков и отправки уведомлений

Meta- вселенная? - BJS2-46838

---

src/main/java/school/faang/s13task45124/Category.java
src/main/java/school/faang/s13task45124/IdGenerator.java
src/main/java/school/faang/s13task45124/Main.java
src/main/java/school/faang/s13task45124/Product.java
src/main/java/school/faang/s13task45124/WarehouseManagement.java

sprint 1 task BJS2-45124

---

src/main/java/school/faang/task_48039/MailSender.java
src/main/java/school/faang/task_48039/SenderRunnable.java

BJS2-48039

---

src/main/java/school/faang/task_47727/FoodDeliveryTask.java
src/main/java/school/faang/task_47727/GriffinsFoodDelivery.java
src/main/java/school/faang/task_48164/Main.java

BJS2-47727

---

src/main/java/school/faang/task_46820/Main.java
src/main/java/school/faang/task_46820/WorkingWithValues.java

1) Создал класс WorkingWithValues c 9-ю статическими методами для работы с ArrayList, используя Stream API
2) Создал класс Main в котором наполнил два ArrayList и протестировал все статистические методы.

BJS2-46820: Потренируем StreamAPI 1

---

src/main/java/school/faang/sprint_1/task_44687/HogwartsSpells.java
src/main/java/school/faang/sprint_1/task_44687/Main.java
src/main/java/school/faang/sprint_1/task_44687/SpellEvent.java

Выполнил задачу "Ловим события". Проверьте пожалуйста.

Выполнил задачу "Ловим события"

---

src/main/java/school/faang/task_45405/Book.java
src/main/java/school/faang/task_45405/LibrarySystem.java
src/main/java/school/faang/task_45405/Main.java
src/test/java/school/faang/task_45405/LibrarySystemTest.java

https://faang-school.com/courses/4jnzmndg/vxdj8n3d

BJS2-45405 bootcamp: westeros library

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/bjs45629/SpellAction.java
src/main/java/school/faang/bjs45629/SpellCaster.java

created classes according to the task

ztsv-BJS2-45629 - Хогвартс, Хогвартс, наш любимый Хогвартс

---

src/main/java/school/faang/bjs_47121/ListOperations2.java
src/test/java/school/faang/bjs_47121/ListOperations2Test.java

Решение задачи "Потренируем StreamAPI 2"

AntonGraf-BJS2-47121

---

src/main/java/school/faang/bjs246600/FareCalculator.java
src/main/java/school/faang/bjs246600/Main.java

bjs2 46600 millions ubers

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/task_46867/Main.java
src/main/java/school/faang/task_46867/Notification.java
src/main/java/school/faang/task_46867/NotificationManager.java

Реализовал обработчик нотификаций 
Так же добавил фильтрацию для нотификаций и обработку для них

Meta-вселенная

---

src/main/java/school/faang/task_47101/Main.java
src/main/java/school/faang/task_47101/MultiOperations.java

BJS2-47101 was completed.

---

src/main/java/school/faang/sprint_2/task_43526/Coordinates.java
src/main/java/school/faang/sprint_2/task_43526/FlipDirection.java
src/main/java/school/faang/sprint_2/task_43526/Main.java
src/main/java/school/faang/sprint_2/task_43526/MatrixTransformer.java

Flip matrix

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/bjs46462/FilterProcessor.java
src/main/java/school/faang/bjs46462/Image.java
src/main/java/school/faang/bjs46462/Main.java

created classes according to the task, +Main tested

ztsv-BJS2-46462 - фильтры Instagram

---

src/main/java/school/faang/task_47209/BinaryConverter.java
src/main/java/school/faang/task_47209/FilterAndSortStrings.java
src/main/java/school/faang/task_47209/FilterStringsByAlphabet.java
src/main/java/school/faang/task_47209/SortedCapitals.java
src/main/java/school/faang/task_47209/UniquePairsOptimized.java

Реализовано пять задач.

---

src/main/java/school/faang/task_47046/ListOperations.java
src/main/java/school/faang/task_47046/Main.java

Реализован утилитарный класс для различных операций со списками.

Реализован утилитарный класс для различных операций со списками.

---

src/main/java/school/faang/sprint2/task_4/Email.java
src/main/java/school/faang/sprint2/task_4/EmailProcessor.java
src/main/java/school/faang/sprint2/task_4/Main.java

В строчке 20 в файле Main.java предлагает email -> email.isImportant(); заменить на Email::isImportant; Я не очень понимаю смысл выражения, в смысле такой синтаксис еще не трогали

фильтры на эмейл работают

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/bjs46858/Main.java
src/main/java/school/faang/bjs46858/Notification.java
src/main/java/school/faang/bjs46858/NotificationManager.java

created classes according to the task

ztsv-BJS2-46858 - Meta-вселенная?

---

src/main/java/school/faang/bjs45943/Email.java
src/main/java/school/faang/bjs45943/EmailProcessor.java
src/main/java/school/faang/bjs45943/Main.java

created classes acording to the task

ztsv-BJS2-45943 - Gmail filters

---

src/main/java/school/faang/sprint_1/task_processerrorsbjs2n46218/ExceptionHandler.java
src/main/java/school/faang/sprint_1/task_processerrorsbjs2n46218/ProcessErrorsMain.java

Сделал для интереса метод на основе стандартных интерфейсов Supplier and Function
```
public static <R> R withErrorHandlingProto(Supplier<R> supplierAction, Function<Exception, R> function) {
try {
return supplierAction.get();
} catch (Exception e) {
return function.apply(e);
}
}
```
и из задания оригинальный метод тоже есть.

BJS2-46218. Обрабатываем ошибки красиво.initial

---

src/main/java/school/faang/sprint_3/task_48305/MailSender.java
src/main/java/school/faang/sprint_3/task_48305/SenderRunnable.java

Реализован процесс распределения отправки писем через многопоточность.

BJS2-48305: Вы работаете в Microsoft!

---

src/main/java/school/faang/sprint_3/task_47707/Archer.java
src/main/java/school/faang/sprint_3/task_47707/Army.java
src/main/java/school/faang/sprint_3/task_47707/Mage.java
src/main/java/school/faang/sprint_3/task_47707/Main.java
src/main/java/school/faang/sprint_3/task_47707/PowerCalculator.java
src/main/java/school/faang/sprint_3/task_47707/Swordsman.java
src/main/java/school/faang/sprint_3/task_47707/Unit.java

Создан сервис расчета силы армии героев в отдельных потоках

BJS2-47707: Распределенная армия героев меча и магии

---

src/main/java/school/faang/task_45023/DataCenter.java
src/main/java/school/faang/task_45023/DataCenterService.java
src/main/java/school/faang/task_45023/LoadBalancingOptimizationStrategy.java
src/main/java/school/faang/task_45023/Main.java
src/main/java/school/faang/task_45023/OptimizationStrategy.java
src/main/java/school/faang/task_45023/ResourceRequest.java
src/main/java/school/faang/task_45023/Server.java

Смотрел подсказки в процессе, чтобы понять в каком направлении двигаться, потом стало интересно почему метод allocate - boolean, a release - void и как метод optimize запускается каждые полчаса. Особенно был интересен последний вопрос, но ответа не оказалось и сам я это реализовывать не стал, немного погуглил, похоже не так просто, поэтому оставлю такие штуки на потом.

Solve task_45023

---

src/main/java/school/faang/task_48164/City.java
src/main/java/school/faang/task_48164/CityWorker.java
src/main/java/school/faang/task_48164/Location.java
src/main/java/school/faang/task_48164/Monster.java
src/main/java/school/faang/task_48164/Witcher.java

BJS2-48164

---

src/main/java/school/faang/bjs24722/ListOperations.java
src/main/java/school/faang/bjs24722/Main.java

BJS2-47222 stream api2

---

src/main/java/school/faang/bjs247633/Archer.java
src/main/java/school/faang/bjs247633/Army.java
src/main/java/school/faang/bjs247633/Fighter.java
src/main/java/school/faang/bjs247633/Mage.java
src/main/java/school/faang/bjs247633/Main.java
src/main/java/school/faang/bjs247633/Swordsman.java
src/main/java/school/faang/bjs247633/TheadForCalculation.java

BJS2-47633 distributed army of heroes

---

src/main/java/school/faang/sprint_3/task_43554/MailSender.java
src/main/java/school/faang/sprint_3/task_43554/SenderRunnable.java

Задача Вы работаете в Microsoft!

Send emails

---

src/main/java/school/faang/sprint2task45951/Email.java
src/main/java/school/faang/sprint2task45951/EmailProcessor.java
src/main/java/school/faang/sprint2task45951/Main.java

Task: BJS2-45951 "Gmail Rich Filters"

---

src/main/java/school/faang/gmailrichfilters45992/Email.java
src/main/java/school/faang/gmailrichfilters45992/EmailProcessor.java
src/main/java/school/faang/gmailrichfilters45992/Main.java

…разования писем. Реализованы функциональные интерфейсы Predicate, Consumer и Function. Добавлены тесты для проверки работы системы

Ne dis cord bjs2 45992 - Gmail Rich Filters

---

src/main/java/school/faang/sprint_3/task_43550/Archer.java
src/main/java/school/faang/sprint_3/task_43550/Army.java
src/main/java/school/faang/sprint_3/task_43550/Mage.java
src/main/java/school/faang/sprint_3/task_43550/Main.java
src/main/java/school/faang/sprint_3/task_43550/PowerCalculator.java
src/main/java/school/faang/sprint_3/task_43550/Swordsman.java
src/main/java/school/faang/sprint_3/task_43550/Unit.java

Задача Распределенная армия героев меча и магии

Army of heroes

---

src/main/java/school/faang/sprint_2/task_bjs247313/Main.java
src/main/java/school/faang/sprint_2/task_bjs247313/Student.java
src/main/java/school/faang/sprint_2/task_bjs247313/StudentLoader.java
src/main/java/school/faang/sprint_2/task_bjs247313/StudentService.java

BJS2-47313
Электронный дневник
main output:

BJS2-47313

---

src/main/java/school/faang/bjs248399/BigBangTheory.java
src/main/java/school/faang/bjs248399/Task.java

bjs2-48399 the big bang theory

---

src/main/java/school/faang/sprint_3/task_43553/FoodDeliveryTask.java
src/main/java/school/faang/sprint_3/task_43553/GriffinsFoodDelivery.java

Задача Накормите Питера Гриффина

Feed Peter

---

src/main/java/school/faang/sprint2task45647/Main.java
src/main/java/school/faang/sprint2task45647/SpellAction.java
src/main/java/school/faang/sprint2task45647/SpellCaster.java

Task: BJS2-45647

---

src/main/java/school/faang/sprint_3/task_43557/Chore.java
src/main/java/school/faang/sprint_3/task_43557/Main.java
src/main/java/school/faang/sprint_3/task_43557/WeasleyFamily.java

Задача They were very nice but extremely poor

Weasley family chores

---

src/main/java/school/faang/bjs248200/Chore.java
src/main/java/school/faang/bjs248200/Main.java

BJS2-48200 they were very nice

---

src/main/java/school/faang/task_46222/ErrorHandler.java
src/main/java/school/faang/task_46222/Main.java
src/main/java/school/faang/task_46222/RiskyAction.java

Изменил решение, добавил свой функциональный интерфейс.

BJS2-46222 was changed. The custom functional interface was added.

---

src/main/java/school/faang/sprint2task46483/FilterProcessor.java
src/main/java/school/faang/sprint2task46483/Image.java
src/main/java/school/faang/sprint2task46483/Main.java

Task: BJS2-46483

---

src/main/java/derschrank/sprint02/task11/bjstwo_47572/Employee.java
src/main/java/derschrank/sprint02/task11/bjstwo_47572/Main.java
src/main/java/derschrank/sprint02/task11/bjstwo_47572/StreamApi3.java
src/main/java/derschrank/sprint02/task11/bjstwo_47572/info.txt

BJS2-47572 Sprint02. Task11. Stream API 3

---

src/main/java/school/faang/sprint_3/task_43558/BigBangTheory.java
src/main/java/school/faang/sprint_3/task_43558/Task.java

BigBangTheory

---

src/main/java/school/faang/bjs249150/Music.java
src/main/java/school/faang/bjs249150/Player.java

bjs2-49150 spotify block

---

src/main/java/school/faang/sprint_3/task_bjs248285/MailSender.java
src/main/java/school/faang/sprint_3/task_bjs248285/SenderRunnable.java

BJS2-48285
Вы работаете в Microsoft!

BJS2-48285

---

src/main/java/school/faang/task_bjs246254/ErrorHandler.java
src/main/java/school/faang/task_bjs246254/ExceptionHandler.java
src/main/java/school/faang/task_bjs246254/Main.java

почему-то с Exeption, как в примере, всё перестает работать, джава просит обработать метод выброса исключения явно(

задание с обработкой ошибок

---

src/main/java/school/faang/task_45622/Character.java
src/main/java/school/faang/task_45622/InventoryManager.java
src/main/java/school/faang/task_45622/Item.java
src/main/java/school/faang/task_45622/Main.java

Создан класс Item
Создан класс Character c инвентарем List<Item>
Реализована система для управления инвентарем персонажей InventoryManager с методами добавления, удаления и изменения предмета.

BJS2-45622: Lord of the Rings RPG

---

src/main/java/school/faang/task_46271/Droid.java
src/main/java/school/faang/task_46271/DroidMessageEncryptor.java
src/main/java/school/faang/task_46271/Main.java

Создан функциональный интерфейс DroidMessageEncryptor, который принимает сообщение и ключ шифрования, а возвращает зашифрованное или расшифрованное сообщение.
Реализован класс Droid, содержащий в себе:
- метод encryptMessage, который шифрует сообщение с помощью DroidMessageEncryptor;
- метод decryptMessage, который расшифровывает сообщение;
- метод sendMessage, необходимый для отправки зашифрованного сообщения другому дроиду.
- метод receiveMessage — метод для получения зашифрованного сообщения.

BJS2-46271: Секреты дроидов

---

src/main/java/school/faang/socialnetworkuseranalysis/ActionType.java
src/main/java/school/faang/socialnetworkuseranalysis/Main.java
src/main/java/school/faang/socialnetworkuseranalysis/UserAction.java
src/main/java/school/faang/socialnetworkuseranalysis/UserActionAnalyzer.java

Добавлен класс UserActionAnalyzer со статическими методами, которые анализируют активность пользователей

BJS2-47197: Анализ активности пользователей в социальной сети

---

src/main/java/school/faang/task_47232/ListOperations.java
src/main/java/school/faang/task_47232/Main.java

1) Создал класс ListOperations, в котором создал 5 методов по работе с коллекциями, используя StreamAPI.
2) Создал класс Main и протестировал работу каждого метода.

BJS2-47232: Потренируем StreamAPI 2

---

src/main/java/school/faang/task_49173/Main.java
src/main/java/school/faang/task_49173/VideoManager.java

BJS2-49173

---

src/main/java/school/faang/sprint2/task_7/Droid.java
src/main/java/school/faang/sprint2/task_7/DroidMessageEncryptor.java
src/main/java/school/faang/sprint2/task_7/Main.java

Шифруемся от имперцев

---

src/main/java/derschrank/sprint02/task13/bjstwo_45421/DictionaryProcessor.java
src/main/java/derschrank/sprint02/task13/bjstwo_45421/Main.java

Вы — разработчик приложения Google Translator и работаете над функцией, которая позволит пользователям добавлять слова и их переводы в словарь. Нужно создать систему, которая будет принимать слово и его перевод, а затем сохранять их в словарь с помощью интерфейса BiConsumer.
Цель:
Создайте класс DictionaryProcessor, который будет использовать BiConsumer для обработки словаря.
Требования:
1️⃣ Создайте класс DictionaryProcessor с методом processWord, который добавляет слово и его перевод в словарь.
2️⃣ Метод processWord должен принимать на вход слово, его перевод и BiConsumer<String, String> для добавления в словарь.
3️⃣ Создайте лямбда-выражение для сохранения слова и его перевода в словарь, используя интерфейс BiConsumer.
4️⃣ Протестируйте свою систему, добавив несколько …

BJS2-45421 Sprint02. Task13. Lambda. Google Translater

---

src/main/java/school/faang/sprint_2/task_45676/Main.java
src/main/java/school/faang/sprint_2/task_45676/SpellAction.java
src/main/java/school/faang/sprint_2/task_45676/SpellCaster.java

Решил задачу Хогвартс, Хогвартс, наш любимый Хогвартс. Проверьте пожалуйста.

BJS2-45676

---

src/main/java/derschrank/sprint02/task15/bjstwo_46577/FareCalculator.java
src/main/java/derschrank/sprint02/task15/bjstwo_46577/Main.java

Вы — разработчик приложения Uber, и сейчас работаете над функцией, которая позволяет пользователям оценить стоимость поездки до выбора водителя. Нужно сделать систему, которая будет принимать расстояние и время поездки, а потом рассчитывать стоимость в зависимости от выбранного тарифа.
Цель:
Создайте класс FareCalculator, который будет использовать BiFunction для подсчёта стоимости поездки.
Требования:
1️⃣ Создайте класс FareCalculator с методом calculateFare, который будет считать стоимость поездки.
2️⃣ Метод calculateFare должен:
принимать на вход два параметра: расстояние и время поездки;
также принимать BiFunction, которая и будет заниматься вычислением стоимости поездки.
3️⃣ Создайте несколько тарифов с помощью лямбда-выражений и интерфейса BiFunction. Каждый тариф …

BJS2-46577 Sprint02. Task15. Lambda. Uber Taxi

---

src/main/java/derschrank/sprint02/task17/bjstwo_47124/Location.java
src/main/java/derschrank/sprint02/task17/bjstwo_47124/LocationSearchEngine.java
src/main/java/derschrank/sprint02/task17/bjstwo_47124/LocationSearchEngineInterface.java
src/main/java/derschrank/sprint02/task17/bjstwo_47124/Main.java

Вы — разработчик в компании Google и работаете над приложением Google Maps. Вам поручено создать систему поиска местоположений, которая будет использовать стандартные функциональные интерфейсы Java, такие как Function, Predicate и Consumer, для фильтрации и обработки результатов поиска.
Цель:
Разработайте класс LocationSearchEngine с методами для фильтрации и обработки местоположений, применяя стандартные функциональные интерфейсы Java.
Требования:
1️⃣ Создайте класс Location с полями:
name (название местоположения),
latitude (широта),
longitude (долгота).
2️⃣ Создайте класс LocationSearchEngine с тремя методами:
filterLocations:
принимает список объектов типа Location и объект типа Predicate<Location>,
возвращает список местоположений, которые соответствуют условию, …

BJS2-47124 Sprint02. Task17. Lambda. Google Maps

---

src/main/java/school/faang/sprint_3/task_bjs247927/Archer.java
src/main/java/school/faang/sprint_3/task_bjs247927/Army.java
src/main/java/school/faang/sprint_3/task_bjs247927/Mage.java
src/main/java/school/faang/sprint_3/task_bjs247927/Main.java
src/main/java/school/faang/sprint_3/task_bjs247927/PowerCalculateThread.java
src/main/java/school/faang/sprint_3/task_bjs247927/Swordsman.java
src/main/java/school/faang/sprint_3/task_bjs247927/TestDataGenerator.java
src/main/java/school/faang/sprint_3/task_bjs247927/Unit.java
src/main/java/school/faang/sprint_3/task_bjs247927/UnitType.java

BJS2-47927

---

src/main/java/school/faang/task_47312/CollectionStreamProcessor.java
src/main/java/school/faang/task_47312/Main.java

Реализованы методы:
- findPair для поиска уникальных пар чисел, сумма которых равна заданному числу;
- sortingCapitals сортирует страны по алфавиту и выводит список названий их столиц;
- sortingList фильтрует строки, начинающиеся с заданного символа, и сортирует их по длине;
- convertToBinary преобразует список целых чисел в список строк в двоичном виде;
- stringFiltering  фильтрует строки, содержащие только буквы из заданного алфавита, и сортирует их по длине.

BJS2-47312: Потренируем StreamAPI 2

---

src/main/java/school/faang/bjs248950/Chore.java
src/main/java/school/faang/bjs248950/WeasleyFamily.java

* They were very nice but extremely poor is finished

bjs2-48049

---

src/main/java/school/faang/task_45686/Main.java
src/main/java/school/faang/task_45686/SpellAction.java
src/main/java/school/faang/task_45686/SpellCaster.java

BJS2-45686 - задача "Хогвартс, Хогвартс, наш любимый Хогвартс"

BJS2-45686 - the task "Hogwarts, Hogwarts, our beloved Hogwarts"

---

src/main/java/school/faang/sprint_3/task_48484/Main.java
src/main/java/school/faang/sprint_3/task_48484/RocketLaunch.java

Реализована система, которая планирует запуски ракет в определенное время

BJS2-48484: Космическая программа SpaceX

---

src/main/java/school/faang/task_48814/House.java
src/main/java/school/faang/task_48814/Main.java
src/main/java/school/faang/task_48814/Role.java
src/main/java/school/faang/task_48814/User.java

BJS2-48814

---

src/main/java/school/faang/task_49138/Chat.java
src/main/java/school/faang/task_49138/ChatManager.java
src/main/java/school/faang/task_49138/Main.java
src/main/java/school/faang/task_49138/User.java
src/main/java/school/faang/task_49138/UserList.java

BJS2-49138

---

src/main/java/school/faang/bjs246411/Droid.java
src/main/java/school/faang/bjs246411/DroidMessageEncryptor.java
src/main/java/school/faang/bjs246411/Main.java

BJS2-46411, Secrets of the Druids  - alpha release

BJS2-46411, Secrets of the Druids

---

src/main/java/school/faang/sprint_3/task_49461/Music.java
src/main/java/school/faang/sprint_3/task_49461/Player.java

Реализован функционал музыкального плеера с использованием синхронизации

BJS2-49461: Блокировка Spotify

---

src/main/java/faang/school/godbless/SecondSprint/BJS2_46662/Location.java
src/main/java/faang/school/godbless/SecondSprint/BJS2_46662/LocationSearchEngine.java
src/main/java/faang/school/godbless/SecondSprint/BJS2_46662/Main.java

Задача: Google Maps

---

src/main/java/school/faang/bjs247622/King.java
src/main/java/school/faang/bjs247622/Knight.java
src/main/java/school/faang/bjs247622/Trial.java

bjs2-47622 tournament in kings landing

---

src/main/java/school/faang/bjs249585/Action.java
src/main/java/school/faang/bjs249585/Controller.java
src/main/java/school/faang/bjs249585/Main.java
src/main/java/school/faang/bjs249585/Tamagotchi.java

bjs2-49585 tamagochi

---

src/main/java/school/faang/bjs248062/Knight.java
src/main/java/school/faang/bjs248062/Main.java
src/main/java/school/faang/bjs248062/Trial.java

* Турнир в Королевской гавани is finished

bjs2-48062

---

src/main/java/school/faang/sprint_2/task_46918/Main.java
src/main/java/school/faang/sprint_2/task_46918/Notification.java
src/main/java/school/faang/sprint_2/task_46918/NotificationManager.java

Выполнил задачу "Meta-вселенная?", проверьте пожалуйста.

BJS2-46918

---

src/main/java/school/faang/task_48417/Chore.java
src/main/java/school/faang/task_48417/Main.java
src/main/java/school/faang/task_48417/WeasleyFamily.java

1) Создал класс Chore реализующий интерфейс Runnable, с переменной chore типа String, с конструктором и реализованным методом run();
2) Создал класс WeasleyFamily, в котором:
- создал ArrayList и наполнил его списком дел
- создал метод startingChore который создает объекты класса Chore и наполняет их списком дел.
- данные объекты передается в пул задач
3) в классе main протестировал работу метода startingChore класса WeasleyFamily.

BJS2-48417: They were very nice but extremely poor

---

src/main/java/school/faang/bjs248203/CashierThread.java
src/main/java/school/faang/bjs248203/Main.java

* Очередь в Walmart is finished

bjs2-48203

---

src/main/java/school/faang/bjs247433/ListOperations.java
src/main/java/school/faang/bjs247433/Main.java

BJS2-47433, Let's practice the Stream API 1 - alpha release

BJS2-47433, Let's practice the Stream API 1

---

src/main/java/school/faang/bjs248219/Main.java
src/main/java/school/faang/bjs248219/Person.java
src/main/java/school/faang/bjs248219/PersonInfoPrinter.java

* Помогите коллеге is finished

bjs2-48219

---

src/main/java/school/faang/bjs248139/Pig1Thread.java
src/main/java/school/faang/bjs248139/Pig2Thread.java
src/main/java/school/faang/bjs248139/Pig3Thread.java
src/main/java/school/faang/bjs248139/PigThread.java
src/main/java/school/faang/bjs248139/ThreeLittlePigs.java

* Наконец-то нормальная игра is finished

bjs2-48139

---

src/main/java/school/faang/sprint_3/task_bjs249193/Main.java
src/main/java/school/faang/sprint_3/task_bjs249193/Player.java

BJS2-49193
Блокировка Spotify
main output:

BJS2-49193

---

src/main/java/school/faang/bjs249531/Music.java
src/main/java/school/faang/bjs249531/Player.java

* Блокировка Spotify is finished

bjs2-49531

---

src/main/java/school/faang/lordoftheringsrpg45704/Character.java
src/main/java/school/faang/lordoftheringsrpg45704/InventoryManager.java
src/main/java/school/faang/lordoftheringsrpg45704/Item.java
src/main/java/school/faang/lordoftheringsrpg45704/Main.java

…й с использованием функциональных интерфейсов Java

Ne dis cord bjs2 45704- Lord of the Rings RPG

---

src/main/java/school/faang/bjs248844/GooglePhotosAutoUploader.java
src/main/java/school/faang/bjs248844/Main.java
src/main/java/school/faang/bjs248844/PhotoAdder.java
src/main/java/school/faang/bjs248844/PhotoAutoUploader.java

bjs2-48844 google photo sync

---

src/main/java/school/faang/handleerrorsbeautifullybjs46342/ErrorHandler.java
src/main/java/school/faang/handleerrorsbeautifullybjs46342/Main.java
src/main/java/school/faang/handleerrorsbeautifullybjs46342/RemoteService.java
src/main/java/school/faang/handleerrorsbeautifullybjs46342/ServiceUnavailableException.java

Ne dis cord bjs2 46342- Обрабатываем ошибки красиво

---

src/main/java/school/faang/secretdroidsbjs46370/Droid.java
src/main/java/school/faang/secretdroidsbjs46370/DroidMessageEncryptor.java
src/main/java/school/faang/secretdroidsbjs46370/Main.java

… Реализована система обмена зашифрованными сообщениями между дроидами

Ne dis cord bjs2 46370 - Секреты дроидов

---

src/main/java/school/faang/sprint_3/task_48370/City.java
src/main/java/school/faang/sprint_3/task_48370/CityWorker.java
src/main/java/school/faang/sprint_3/task_48370/Data.java
src/main/java/school/faang/sprint_3/task_48370/Location.java
src/main/java/school/faang/sprint_3/task_48370/Monster.java
src/main/java/school/faang/sprint_3/task_48370/ValidationUtils.java
src/main/java/school/faang/sprint_3/task_48370/Witcher.java

Разработан сервис расчета дистанции до города и ближайшего монстра с помощью многопоточности

BJS2-48370: Путь пальцем проложи

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/bjs245477/DictionaryProcessor.java
src/main/java/school/faang/bjs245477/Main.java

BJS2-45477, Google Translator is under our control - alpha release

BJS2-45477, Google Translator is under our control

---

src/main/java/school/faang/task_48367/MailSender.java
src/main/java/school/faang/task_48367/SenderRunnable.java

Реализована параллельная отправка писем в 5 потоках.

Реализована параллельная отправка писем в 5 потоках.

---

src/main/java/school/faang/bjs248511/MailSender.java
src/main/java/school/faang/bjs248511/SenderRunnable.java

BJS2-48511, Do you work for Microsoft - alpha release

BJS2-48511, Do you work for Microsoft

---

src/main/java/derschrank/sprint02/task18/bjstwo_45912/Triangle.java
src/main/java/derschrank/sprint02/task18/bjstwo_45912/TriangleAreaCalculator.java

Вам нужно вычислить площадь треугольника, используя только лямбда-выражения. Операции сложения, умножения, деления и другие стандартные арифметические операции нельзя использовать напрямую — только через заранее определённые лямбда-функции.
Требования:
1️⃣ Даны три стороны треугольника — a, b и c. Ваша задача — вычислить площадь треугольника с помощью лямбда-функций.
2️⃣ В коде уже есть лямбда-функции для сложения, умножения, вычитания, деления и вычисления квадратного корня. Вам нужно использовать их для вычисления площади.
3️⃣ Нельзя использовать арифметические операторы (+, -, *, /) или стандартные методы вроде Math.sqrt.
4️⃣ Добавьте проверку корректности входных параметров (валидацию), чтобы три стороны могли образовать треугольник.
Исходный код:
public class …

BJS2-45912 Sprint02. Task18. Lambda. TriangleAreaCalculator

---

src/main/java/school/faang/trainstreamapi1bjs47294/ListOperations.java
src/main/java/school/faang/trainstreamapi1bjs47294/Main.java

…ерации с числами и строками в списках

BJS2-47294 - Потренируем StreamAPI 1

---

src/main/java/school/faang/bjs247359/Main.java
src/main/java/school/faang/bjs247359/UserAction.java
src/main/java/school/faang/bjs247359/UserActionAnalyzer.java
src/main/java/school/faang/bjs247359/UserActionGenerator.java

Немного отличается от условия задачи: у меня получилось так что ID_COUNTER генерирует ID для каждого действия пользователя, по-моему логично)

Анализ активности пользователей

---

src/main/java/school/faang/sprint_3/task_bjs248925/GooglePhotosAutoUploader.java
src/main/java/school/faang/sprint_3/task_bjs248925/Main.java
src/main/java/school/faang/sprint_3/task_bjs248925/TestDataGenerator.java

BJS2-48925
Google Photo sync
main output:

BJS2-48925

---

src/main/java/school/faang/task_49658/Boss.java
src/main/java/school/faang/task_49658/Main.java
src/main/java/school/faang/task_49658/Player.java

1) Создан класс Boss с двумя полями. Поле maxPlayers контролирует количество слотов для сражения с босом.
2) В этом же классе созданы два Synchronizet метода для увеличения и уменьшения поля currentPlayers.
3) Создан класс Player с полем name и методом startBattle, который запускает методы класса Boss.
4) в методе main создал 6 персонажей, и запустил их в 6-ти потоках.

BJS2-49658: Supercow!

---

src/main/java/school/faang/task_46305/ExceptionCatch.java
src/main/java/school/faang/task_46305/Main.java
src/main/java/school/faang/task_46305/RemoteService.java

BJS2-46305 - задача "Обрабатываем ошибки красиво"

BJS2-46305 - the task "We handle errors beautifully"

---

src/main/java/school/faang/sprint2task47237/Main.java
src/main/java/school/faang/sprint2task47237/UserAction.java
src/main/java/school/faang/sprint2task47237/UserActionAnalyzer.java
src/main/java/school/faang/sprint2task47237/UserActionData.java

Done Анализ активности пользователей в социальной сети

Tahirzade bjs2 47237

---

src/main/java/school/faang/task_46907/Main.java
src/main/java/school/faang/task_46907/Notification.java
src/main/java/school/faang/task_46907/NotificationManager.java

BJS2-46907 - задание "Meta-вселенная?"

BJS2-46907 - the task "Meta-universe?"

---

src/main/java/school/faang/bjs248388/Archer.java
src/main/java/school/faang/bjs248388/Army.java
src/main/java/school/faang/bjs248388/Mage.java
src/main/java/school/faang/bjs248388/Main.java
src/main/java/school/faang/bjs248388/PowerCalculator.java
src/main/java/school/faang/bjs248388/Swordsman.java
src/main/java/school/faang/bjs248388/Unit.java

BJS2-48388, A distributed army of heroes of might and magic - alpha

BJS2-48388, A distributed army of heroes of might and magic

---

src/main/java/school/faang/bjs248587/GoodDeliveryTask.java
src/main/java/school/faang/bjs248587/GriffinsFoodDelivery.java

* Накормите Питера Гриффина is finished

bjs2-48587

---

src/main/java/school/faang/bjs_48472/MailSender.java
src/main/java/school/faang/bjs_48472/SenderRunnable.java
src/test/java/school/faang/bjs_48472/MailSenderTest.java

Решение задачи "Вы работаете в Microsoft!"

AntonGraf-BJS2-48472

---

src/main/java/school/faang/bjs248436/Archer.java
src/main/java/school/faang/bjs248436/Army.java
src/main/java/school/faang/bjs248436/Fighter.java
src/main/java/school/faang/bjs248436/Mage.java
src/main/java/school/faang/bjs248436/Main.java
src/main/java/school/faang/bjs248436/PowerCalculator.java
src/main/java/school/faang/bjs248436/Swordsman.java

* Распределенная армия героев меча и магии is finished

bjs2-48436

---

src/main/java/school/faang/task_45979/Email.java
src/main/java/school/faang/task_45979/EmailProcessor.java
src/main/java/school/faang/task_45979/Main.java

BJS2-45979 - задача "Gmail Rich Filters"

BJS2-45979 - the task "Gmail Rich Filters"

---

src/main/java/school/faang/bjs246605/Location.java
src/main/java/school/faang/bjs246605/LocationSearchEngine.java
src/main/java/school/faang/bjs246605/Main.java

bjs2-46605 google maps

---

src/main/java/school/faang/task_47245/Main.java

BJS2-47245 - задача "Stream API 1"

BJS2-47245 - the task "Stream API 1"

---

src/main/java/school/faang/bjs248966/Chore.java
src/main/java/school/faang/bjs248966/Main.java
src/main/java/school/faang/bjs248966/WeasleyFamily.java

BJS2-48966, They were very nice but extremely poor - alpha release

BJS2-48966, They were very nice but extremely poor

---

src/main/java/school/faang/bjs249007/BigBangTheory.java
src/main/java/school/faang/bjs249007/Task.java

* The Big Bang Theory is finished

bjs2-49007

---

src/main/java/school/faang/bjs248993/Food.java
src/main/java/school/faang/bjs248993/House.java
src/main/java/school/faang/bjs248993/Main.java
src/main/java/school/faang/bjs248993/Room.java

* Mice are very nice! is finished

bjs2-48993

---

src/main/java/school/faang/bjs246205/ErrorHandler.java
src/main/java/school/faang/bjs246205/ExceptionHandler.java
src/main/java/school/faang/bjs246205/FileUpload.java
src/main/java/school/faang/bjs246205/Main.java

commit with questions:
в методе main в строке  () -> FileUpload.uploadFile("C:\\data.txt")
метод uploadFile Idea просит обернуть в try-catch, почему?

bjs2-46205 handle errors nicely

---

src/main/java/school/faang/bjs246781/Main.java
src/main/java/school/faang/bjs246781/Operations.java

bjs2-46781 stream api3

---

src/main/java/school/faang/bjs245699/Calculator.java
src/main/java/school/faang/bjs245699/Main.java

bjs2-45699 calculator

---

src/main/java/school/faang/sprint_3/task_bjs249673/Boss.java
src/main/java/school/faang/sprint_3/task_bjs249673/Main.java
src/main/java/school/faang/sprint_3/task_bjs249673/Player.java
src/main/java/school/faang/sprint_3/task_bjs249673/TestDataGenerator.java

BJS2-49673
Supercow!
Для легкости чтения использовал SneakyThrows, не знаю можно ли.
main out:

BJS2-49673

---

src/main/java/school/faang/task_48354/Food.java
src/main/java/school/faang/task_48354/House.java
src/main/java/school/faang/task_48354/Main.java
src/main/java/school/faang/task_48354/Room.java

Реализована многопоточная программа для сбора еды Томом и Джерри.

Реализована многопоточная программа для сбора еды Томом и Джерри.

---

src/main/java/derschrank/sprint03/task02/bjstwo_47918/Army.java
src/main/java/derschrank/sprint03/task02/bjstwo_47918/ArmyInterface.java
src/main/java/derschrank/sprint03/task02/bjstwo_47918/CalculatorThread.java
src/main/java/derschrank/sprint03/task02/bjstwo_47918/Main.java
src/main/java/derschrank/sprint03/task02/bjstwo_47918/units/Archer.java
src/main/java/derschrank/sprint03/task02/bjstwo_47918/units/Mage.java
src/main/java/derschrank/sprint03/task02/bjstwo_47918/units/Swordsman.java
src/main/java/derschrank/sprint03/task02/bjstwo_47918/units/Unit.java

👩‍💻 🧠
Вы — командующий армией героев меча и магии, и вам поручено вычислить общую силу армии, состоящей из разных подразделений: лучники, мечники, маги и т.д. Но армия большая, так что нужно распределить расчёты между несколькими потоками, чтобы быстрее получить результат.
Требования:
1️⃣ Создайте классы:
Archer (лучник)
Swordsman (мечник)
Mage (маг)
Если хотите, добавьте другие подразделения.
У каждого бойца должно быть поле power — это его сила. Например, лучник может иметь силу 25, а маг — 50.
2️⃣ Напишите класс Army, который будет содержать список всех ваших бойцов. Внутри этого класса напишите метод calculateTotalPower(), который вычисляет общую силу армии.
3️⃣ Метод calculateTotalPower() должен использовать распараллеливание. …

BJS2-47918 Sprint03. Task02. Parallelism. Power of Army

---

src/main/java/derschrank/sprint03/task03/bjstwo_48427/Chore.java
src/main/java/derschrank/sprint03/task03/bjstwo_48427/Main.java
src/main/java/derschrank/sprint03/task03/bjstwo_48427/WeasleyFamily.java

They were very nice but extremely poor
👩‍💻 🧠
Условия задачи
В семье Уизли всегда полно домашних хлопот, и чтобы справиться с этим волшебным хаосом, Перси решил автоматизировать выполнение задач. Его идея — использовать пул потоков с помощью метода newCachedThreadPool(), чтобы поручить выполнение всех дел сразу нескольким потокам.
Требования:
1️⃣ Создайте класс Chore, который будет реализовывать интерфейс Runnable. Этот класс будет описывать каждую домашнюю задачу, которую нужно выполнить.
2️⃣ Добавьте поле chore типа String в класс Chore, чтобы хранить название задачи (например, "помыть посуду", "подмести пол"). Создайте конструктор, который принимает название задачи как параметр.
3️⃣ В методе run() класса Chore опишите логику выполнения задачи. Используйте …

BJS2-48427 Sprint03. Task03. Parallelism. WeasleyFamily

---

src/main/java/derschrank/sprint03/task01/bjstwo_48423/Mail.java
src/main/java/derschrank/sprint03/task01/bjstwo_48423/MailSender.java
src/main/java/derschrank/sprint03/task01/bjstwo_48423/MailSenderInterface.java
src/main/java/derschrank/sprint03/task01/bjstwo_48423/Main.java
src/main/java/derschrank/sprint03/task01/bjstwo_48423/SenderRunnable.java

Вы работаете в Microsoft!
👩‍💻 🧠
Вы работаете над проектом почтового клиента (что-то вроде Microsoft Outlook). В текущей реализации все сообщения отправляются последовательно в одном потоке — ваш сервис отправляет их по очереди. Но вы, как инициативный разработчик, решаете улучшить производительность и предложить параллельную отправку сообщений.
На данный момент в очереди скопилось 1000 писем, и задача состоит в том, чтобы разбить их на 5 потоков, где каждый поток будет обрабатывать и отправлять по 200 писем. Ваша цель — реализовать это распределение, чтобы ускорить процесс и сделать его более эффективным.
Требования:
1️⃣ Создать класс SenderRunnable, который реализует интерфейс Runnable. У каждого потока будет своя порция писем, поэтому в конструкторе класса передайте два …

BJS2-48423 Sprint03. Task01. Parallelism. MailSender

---

src/main/java/school/faang/task_48108/MailSender.java
src/main/java/school/faang/task_48108/SenderRunnable.java

BJS2-48108 was completed.

---

src/main/java/school/faang/task_46328/Droid.java
src/main/java/school/faang/task_46328/DroidMessageEncryptor.java
src/main/java/school/faang/task_46328/Main.java

BJS2-46328 - задача "Секреты дроидов"

BJS2-46328 - the task "Secrets of the Droid"

---

src/main/java/school/faang/task_46491/FilterProcessor.java
src/main/java/school/faang/task_46491/Image.java
src/main/java/school/faang/task_46491/Main.java

BJS2-46491 - задание "Фильтры Instagram"

BJS2-46491 - the task "Instagram Filters"

---

src/main/java/school/faang/sprint_3/task_49199/Main.java
src/main/java/school/faang/sprint_3/task_49199/ValidationUtils.java
src/main/java/school/faang/sprint_3/task_49199/VideoManager.java

Создан класс с потокобезопасными методами для управления просмотрами видео

BJS2-49199: Счетчик просмотров на YouTube

---

src/main/java/school/faang/sprint_3/task_49075/House.java
src/main/java/school/faang/sprint_3/task_49075/Main.java
src/main/java/school/faang/sprint_3/task_49075/User.java

Реализован механизм использования ограниченного числа ролей с помощью синхронизации потоков

BJS2-49075: Железный трон любой ценой

---

src/main/java/school/faang/task_48894/GooglePhotosAutoUploader.java
src/main/java/school/faang/task_48894/Main.java

1) Создан класс GooglePhotosAutoUploader, в котором реализован паттерн Producer-Consumer.
2) при помощи 3-х методов, этого же класса, произвели добавление фото в List и загрузку фото из List не сервер. 
3) в методе main создали два потока:
- первый поток добавляет фото в List.
- второй загружает фото на сервер и удаляет из листа.

BJS2-48894: Google Photo sync

---

src/main/java/school/faang/bjs249118/GooglePhotosAutoUploader.java
src/main/java/school/faang/bjs249118/Main.java

* Google Photo sync is finished

bjs2-49118

---

src/main/java/school/faang/bjs249733/Boss.java
src/main/java/school/faang/bjs249733/Main.java
src/main/java/school/faang/bjs249733/Player.java

bjs2-49733

---

src/main/java/school/faang/bjs249651/Game.java
src/main/java/school/faang/bjs249651/Main.java
src/main/java/school/faang/bjs249651/version2/Game2.java
src/main/java/school/faang/bjs249651/version2/Main.java
src/main/java/school/faang/bjs249651/version2/Player.java

bjs2-49651

---

src/main/java/school/faang/bjs_48017/Archer.java
src/main/java/school/faang/bjs_48017/Army.java
src/main/java/school/faang/bjs_48017/CalculatePower.java
src/main/java/school/faang/bjs_48017/Character.java
src/main/java/school/faang/bjs_48017/Mage.java
src/main/java/school/faang/bjs_48017/Swordsman.java
src/test/java/school/faang/bjs_48017/ArmyTest.java

Решение задачи "Распределенная армия героев меча и магии"

Решение задачи "Распределенная армия героев меча и магии"

---

src/main/java/school/faang/trainstreamapi2bjs47485/Main.java
src/main/java/school/faang/trainstreamapi2bjs47485/StreamUtility.java
src/main/java/school/faang/trainstreamapi2bjs47485/Utility.java

- поиск уникальных пар чисел
- сортировка стран по алфавиту и вывод столиц
- фильтр строк по первому символу и сортировка по длине
- преобразование целых чисел в двоичный формат
- фильтр строк по заданному алфавиту и сортировка по длине

BJS2-47485 - Потренируем StreamAPI 2

---

src/main/java/school/faang/sprint_3/task_49494/Chat.java
src/main/java/school/faang/sprint_3/task_49494/ChatManager.java
src/main/java/school/faang/sprint_3/task_49494/Main.java
src/main/java/school/faang/sprint_3/task_49494/User.java
src/main/java/school/faang/sprint_3/task_49494/UserList.java
src/main/java/school/faang/sprint_3/task_49494/ValidationUtils.java

Разработано приложение, которое работает в многопоточной среде с чатами и пользователями

BJS2-49494: Matters of the heart

---

src/main/java/school/faang/sprint_3/task_49565/Main.java
src/main/java/school/faang/sprint_3/task_49565/TelegramBot.java

Реализован механизм управления количеством запросов при отправке сообщений

BJS2-49565: Telegram-бот

---

src/main/java/school/faang/sprint_4/task_49959/Difficulty.java
src/main/java/school/faang/sprint_4/task_49959/Main.java
src/main/java/school/faang/sprint_4/task_49959/Player.java
src/main/java/school/faang/sprint_4/task_49959/Quest.java
src/main/java/school/faang/sprint_4/task_49959/QuestSystem.java

Разработана асинхронная модель выполнения квестов

BJS2-49959: WOW

---

src/main/java/school/faang/task_49259/Music.java
src/main/java/school/faang/task_49259/Player.java
src/main/java/school/faang/task_49259/PlayerStatus.java

BJS2-49259 was completed.

---

src/main/java/school/faang/distributedhomambjs48143/Archer.java
src/main/java/school/faang/distributedhomambjs48143/Army.java
src/main/java/school/faang/distributedhomambjs48143/Mage.java
src/main/java/school/faang/distributedhomambjs48143/Main.java
src/main/java/school/faang/distributedhomambjs48143/Swordsman.java
src/main/java/school/faang/distributedhomambjs48143/Warrior.java

- создал абстрактный класс Warrior с которого наследовал силу в класы бойцов
- реализовал метод calculateTotalPower, который вычисляет общую силу армии

BJS2-48143 - Распределенная армия героев меча и магии

---

src/main/java/school/faang/sprint_3/task_bjs249291/Game.java
src/main/java/school/faang/sprint_3/task_bjs249291/Main.java

BJS2-49291

---

src/main/java/school/faang/task_49705/Boss.java
src/main/java/school/faang/task_49705/Main.java
src/main/java/school/faang/task_49705/Player.java

- @ToString потому что нужно только имя
- Использую логирование

BJS2-49705 Supercow!

---

src/main/java/school/faang/bjs_48984/GooglePhotosAutoUploader.java
src/main/java/school/faang/bjs_48984/UploadService.java
src/test/java/school/faang/bjs_48984/UploadServiceTest.java

Решение задачи "Google Photo sync"

AntonGraf-BJS2-48984

---

src/main/java/school/faang/sprint_4/task_51820/Data.java
src/main/java/school/faang/sprint_4/task_51820/Difficulty.java
src/main/java/school/faang/sprint_4/task_51820/Main.java
src/main/java/school/faang/sprint_4/task_51820/School.java
src/main/java/school/faang/sprint_4/task_51820/Student.java
src/main/java/school/faang/sprint_4/task_51820/Task.java
src/main/java/school/faang/sprint_4/task_51820/Tournament.java

Реализован класс Tournament для асинхронного запуска заданий с последующим объединением результатов

BJS2-51820: Турнир трех волшебников

---

src/main/java/school/faang/sprint_3/task_bjs248553/Food.java
src/main/java/school/faang/sprint_3/task_bjs248553/House.java
src/main/java/school/faang/sprint_3/task_bjs248553/Main.java
src/main/java/school/faang/sprint_3/task_bjs248553/Room.java
src/main/java/school/faang/sprint_3/task_bjs248553/TestDataGenerator.java

BJS2-48553
Mice are very nice!
В коде скорее всего переборщил с логгированием.
main output:

BJS2-48553

---

src/main/java/school/faang/bjs_49249/Music.java
src/main/java/school/faang/bjs_49249/Player.java
src/test/java/school/faang/bjs_49249/MusicTest.java

Решение задачи "Блокировка Spotify"

AntonGraf-BJS2-49249

---

src/main/java/school/faang/sprint_3/task_43548/Main.java
src/main/java/school/faang/sprint_3/task_43548/Person.java
src/main/java/school/faang/sprint_3/task_43548/PersonInfoPrinter.java

Help a colleague

---

src/main/java/school/faang/bjs_48625/Chore.java
src/main/java/school/faang/bjs_48625/WeasleyFamily.java
src/test/java/school/faang/bjs_48625/WeasleyFamilyTest.java

Решение задачи "They were very nice but extremely poor"

AntonGraf-BJS2-48625

---

src/main/java/school/faang/sprint_3/task_43560/House.java
src/main/java/school/faang/sprint_3/task_43560/Main.java
src/main/java/school/faang/sprint_3/task_43560/Role.java
src/main/java/school/faang/sprint_3/task_43560/User.java

Задача Железный трон любой ценой

Iron throne

---

src/main/java/school/faang/sprint_4/task_50235/Main.java
src/main/java/school/faang/sprint_4/task_50235/ResultConsumer.java
src/main/java/school/faang/sprint_4/task_50235/SquareRequest.java

Реализован программа, которая выполняет вычисление суммы квадратов чисел с использованием параллельных потоков

BJS2-50235: Fan out – Fan In

---

src/main/java/school/faang/bjs49802/Main.java
src/main/java/school/faang/bjs49802/TamagotchiVlad.java
src/main/java/school/faang/bjs49802/VladController.java

bjs2-49802

---

src/main/java/school/faang/task_49910/Main.java
src/main/java/school/faang/task_49910/MasterCardService.java

BJS2-49910 was completed.

---

src/main/java/school/faang/bjs249591/Main.java
src/main/java/school/faang/bjs249591/VideoManager.java

* Счетчик просмотров на YouTube is done

bjs2-49591

---

src/main/java/school/faang/bjs_48570/Cleaning.java
src/main/java/school/faang/bjs_48570/Food.java
src/main/java/school/faang/bjs_48570/House.java
src/main/java/school/faang/bjs_48570/Room.java
src/test/java/school/faang/bjs_48570/CleaningTest.java

Решение задачи "Mice are very nice!"

Решение задачи "Mice are very nice!"

---

src/main/java/school/faang/bjs_49692/BattleService.java
src/main/java/school/faang/bjs_49692/Boss.java
src/main/java/school/faang/bjs_49692/Player.java
src/test/java/school/faang/bjs_49692/BattleServiceTest.java

AntonGraf-BJS2-49692

---

src/main/java/school/faang/bjs_49299/Game.java
src/main/java/school/faang/bjs_49299/GameService.java
src/test/java/school/faang/bjs_49299/GameServiceTest.java

AntonGraf-BJS2-49299

---

src/main/java/school/faang/task_47642/Archer.java
src/main/java/school/faang/task_47642/Army.java
src/main/java/school/faang/task_47642/Mage.java
src/main/java/school/faang/task_47642/Main.java
src/main/java/school/faang/task_47642/PowerCalculator.java
src/main/java/school/faang/task_47642/Swordsman.java
src/main/java/school/faang/task_47642/Unit.java

Попытался сделать без дополнительных материалов к задаче. В итоге решение немного отличается.
1) Создал класс Unit с полем power
2) Унаследовал от класса Unit три класса: Archer, Mage и Swordsman
3) Создал класс Army, в котором в методе calculateTotalPower() произвожу подсчет power в 3-х потоках.
4) В классе main наполняю ArrayList юнитами, и тестирую метод calculateTotalPower() класса Army.

BJS2-47642: Распределенная армия героев меча и магии

---

build.gradle
src/main/java/school/faang/bjs247244/DataAnalyzer.java
src/main/java/school/faang/bjs247244/Job.java
src/main/java/school/faang/bjs247244/JobScraper.java
src/main/java/school/faang/bjs247244/JobStreamProcessor.java
src/main/java/school/faang/bjs247244/Main.java
vacancies.json

BJS2-47244, Job Analyzer - alpha release

BJS2-47244, Job Analyzer

---

src/main/java/school/faang/workedinmicrosoftbjs48772/MailSender.java
src/main/java/school/faang/workedinmicrosoftbjs48772/SenderRunnable.java

- создал 5 потоков в классе MailSender
- после завершения всех потоков вывел финальное сообщение

BJS2-48772 - Вы работаете в Microsoft!

---

src/main/java/school/faang/theywherevery48758/Chore.java
src/main/java/school/faang/theywherevery48758/WeasleyFamily.java

Cоздан класс Chore и реализация пула потоков в классе WeasleyFamily

BJS2-48758 - They were very nice but extremely poor

---

src/main/java/school/faang/bjs_49275/VideoManager.java
src/main/java/school/faang/bjs_49275/VideoManagerService.java
src/test/java/school/faang/bjs_49275/VideoManagerServiceTest.java

Решение задачи "Счетчик просмотров на YouTube"

AntonGraf-BJS2-49275

---

src/main/java/school/faang/sprint_4/task_bjs250835/Main.java
src/main/java/school/faang/sprint_4/task_bjs250835/School.java
src/main/java/school/faang/sprint_4/task_bjs250835/Student.java
src/main/java/school/faang/sprint_4/task_bjs250835/Task.java
src/main/java/school/faang/sprint_4/task_bjs250835/Tournament.java

BJS2-50835
Турнир трех волшебников

BJS2-50835

---

src/main/java/derschrank/sprint03/task06/bjstwo_48908/GooglePhotosAutoUploader.java
src/main/java/derschrank/sprint03/task06/bjstwo_48908/GooglePhotosAutoUploaderInterface.java
src/main/java/derschrank/sprint03/task06/bjstwo_48908/Main.java

Google Photo sync
👩‍💻 🧠
Условия задачи
Вы разработчик в Google, и ваша задача — создать приложение для автоматической загрузки фотографий в Google Photos. Приложение должно загружать фотографии из папки на компьютере пользователя на сервер Google Photos. Если в папке нет новых фотографий, приложение должно приостановить работу (перейти в режим ожидания) и возобновить загрузку, когда новые фотографии будут добавлены в папку.
Требования:
1️⃣ Создайте класс GooglePhotosAutoUploader, который будет использовать объект lock для синхронизации потоков.
2️⃣ Создайте список photosToUpload, в котором будут храниться пути к фотографиям (строки), которые нужно загрузить.
3️⃣ Реализуйте метод startAutoUpload(), который будет:
Проверять, есть ли фотографии для загрузки.
Если список пуст, программа …

BJS2-48908 Sprint03. Task06. Synchro. Google Photo sync

---

src/main/java/school/faang/miceareverynicebjs48761/Food.java
src/main/java/school/faang/miceareverynicebjs48761/House.java
src/main/java/school/faang/miceareverynicebjs48761/Main.java
src/main/java/school/faang/miceareverynicebjs48761/Room.java

- реализовал метод сollectFood(), который:
Собирает еду из двух случайно выбранных комнат.
Удаляет собранную еду из списков еды этих комнат.
Добавляет собранную еду в общий список собранной еды

BJS2-48761 - Mice are very nice!

---

src/main/java/school/faang/sprint_4/task_50690/Inventory.java
src/main/java/school/faang/sprint_4/task_50690/Item.java
src/main/java/school/faang/sprint_4/task_50690/Main.java

Реализована программа, которая асинхронно собирает предметы и комбинирует в новый

BJS2-50690: Carry отожрался

---

src/main/java/school/faang/bjs249833/Boss.java
src/main/java/school/faang/bjs249833/Main.java
src/main/java/school/faang/bjs249833/Player.java

BJS2-49833, Supercow - alpha release

BJS2-49833, Supercow

---

src/main/java/school/faang/sprint_3/task_48487/Food.java
src/main/java/school/faang/sprint_3/task_48487/House.java
src/main/java/school/faang/sprint_3/task_48487/Main.java
src/main/java/school/faang/sprint_3/task_48487/Room.java

Я хз чет тут просходит, тупо скопипастил, в будущем разберу когда нить

tiroxin BJS2-48487

---

src/main/java/school/faang/bjs250423/Main.java
src/main/java/school/faang/bjs250423/Order.java
src/main/java/school/faang/bjs250423/OrderProcessor.java

* Собираем заказы в Amazon is done

bjs2-50423

---

src/main/java/school/faang/task_49873/Main.java
src/main/java/school/faang/task_49873/MasterCardService.java

1) Создан класс MasterCardService с двумя методами для проведения процесса оплаты и отправки аналитики.
2) Создан класс Main с методом startThreads() в котором запускаем методы в разных потоках с использованием Future.
3) в методе main тестируем работу метода startThreads().

BJS2-49873: Асинхронность и Future

---

src/main/java/school/faang/bjs_49883/MasterCardService.java
src/main/java/school/faang/bjs_49883/ServiceRunner.java
src/test/java/school/faang/bjs_49883/ServiceRunnerTest.java

Решение задачи "Асинхронность и Future"

Anton graf bjs2 49883

---

src/main/java/school/faang/sprint_4/task_bjs249894/Main.java
src/main/java/school/faang/sprint_4/task_bjs249894/MasterCardService.java

BJS2-49894
Асинхронность и Future

BJS2-49894

---

src/main/java/school/faang/task_50026/Main.java
src/main/java/school/faang/task_50026/Player.java
src/main/java/school/faang/task_50026/Quest.java
src/main/java/school/faang/task_50026/QuestSystem.java

- Добавил систему повышения уровней у игроков при достежении определенного опыта

BJS2-50026 WOW

---

src/main/java/school/faang/sprint_4/task_bjs250027/Main.java
src/main/java/school/faang/sprint_4/task_bjs250027/Player.java
src/main/java/school/faang/sprint_4/task_bjs250027/Quest.java
src/main/java/school/faang/sprint_4/task_bjs250027/QuestSystem.java

BJS2-50027

---

src/main/java/beloved_hogwarts/Main.java
src/main/java/beloved_hogwarts/SpellAction.java
src/main/java/beloved_hogwarts/SpellCaster.java

теперь лучше понятно удобство лямбд  (джинерики классная штука)

White fox beloved hogwarts

---

src/main/java/school/faang/bjs248999/Food.java
src/main/java/school/faang/bjs248999/House.java
src/main/java/school/faang/bjs248999/Main.java
src/main/java/school/faang/bjs248999/Officiant.java
src/main/java/school/faang/bjs248999/Room.java

BJS2-48999, Mice are very nice - alpha release

BJS2-48999, Mice are very nice

---

src/main/java/school/faang/bjs249133/GooglePhotosAutoUploader.java
src/main/java/school/faang/bjs249133/Main.java

BJS2-49133, Google Photo sync - alpha release

BJS2-49133, Google Photo sync

---

src/main/java/school/faang/bjs249266/Main.java
src/main/java/school/faang/bjs249266/VideoManager.java

BJS2-49266, YouTube View Counter - alpha release

BJS2-49266, YouTube View Counter

---

src/main/java/derschrank/sprint03/task09/bjstwo_49207/Main.java
src/main/java/derschrank/sprint03/task09/bjstwo_49207/VideoManager.java
src/main/java/derschrank/sprint03/task09/bjstwo_49207/VideoManagerInterface.java
src/main/java/derschrank/sprint03/task09/bjstwo_49207/info.txt

Условия задачи
Вам нужно разработать многопоточный класс VideoManager, который управляет просмотрами видео на YouTube. Ваша задача заключается в том, чтобы корректно подсчитывать количество просмотров для каждого видео, несмотря на большое количество параллельных запросов. Для этого нужно синхронизировать доступ к просмотрам, чтобы избежать состояния гонки
Требования:
1️⃣ Создайте класс VideoManager, который будет содержать приватное поле viewsMap для хранения количества просмотров каждого видео (можно использовать Map<String, Integer>).
2️⃣ Реализуйте метод addView(String videoId), который:
Добавляет один просмотр для видео с данным videoId.
Этот метод должен быть потокобезопасным.
3️⃣ Реализуйте метод getViewCount(String videoId), который:
Возвращает текущее количество просмотров для …

BJS2-49207 Sprint03. Task09. Synchro. View counter

---

src/main/java/school/faang/bjs_50017/Player.java
src/main/java/school/faang/bjs_50017/Quest.java
src/main/java/school/faang/bjs_50017/QuestSystem.java
src/test/java/school/faang/bjs_50017/QuestSystemTest.java

Anton graf bjs2 50017

---

src/main/java/derschrank/sprint03/task05/bjstwo_49183/Music.java
src/main/java/derschrank/sprint03/task05/bjstwo_49183/Player.java
src/main/java/derschrank/sprint03/task05/bjstwo_49183/PlayerInterface.java

Условия задачи
В Spotify есть интересная функция под названием "Group Session". Она позволяет нескольким пользователям управлять воспроизведением музыки одновременно, синхронизируя их действия на разных устройствах в реальном времени. Это значит, что несколько человек могут, например, вместе слушать один и тот же плейлист, даже если они находятся далеко друг от друга.
Давайте реализуем упрощённую версию этой функции! Мы хотим, чтобы несколько пользователей могли управлять воспроизведением музыки на разных устройствах, но при этом не мешали друг другу и не могли одновременно нажать и play и pause, а только по очереди.
Требования:
1️⃣ Создайте класс Player, который будет управлять воспроизведением музыки. У этого класса должны быть методы для выполнения следующих действий:
play() — начать …

BJS2-49183 Sprint03. Task05. Synchro. Spotify

---

src/main/java/school/faang/task_48723/MailSender.java
src/main/java/school/faang/task_48723/SenderRunnable.java

BJS2-48723 - задача "Вы работаете в Microsoft!"

BJS2-48723 - the task "You work at Microsoft!"

---

src/main/java/school/faang/task_48209/Archer.java
src/main/java/school/faang/task_48209/Army.java
src/main/java/school/faang/task_48209/CalculatePower.java
src/main/java/school/faang/task_48209/Mage.java
src/main/java/school/faang/task_48209/Main.java
src/main/java/school/faang/task_48209/Swordsman.java
src/main/java/school/faang/task_48209/Unit.java

BJS2-48209 - задача "Распределенная армия героев меча и магии"

BJS2-48209 - the task "A distributed army of heroes of might and magic"

---

src/main/java/school/faang/task_48732/Chore.java
src/main/java/school/faang/task_48732/Main.java
src/main/java/school/faang/task_48732/WeasleyFamily.java

BJS2-48732 - задача "They were very nice but extremely poor"

BJS2-48732 - the task "They were very nice but extremely poor"

---

src/main/java/school/faang/sprint_3/task_48341/Archer.java
src/main/java/school/faang/sprint_3/task_48341/Army.java
src/main/java/school/faang/sprint_3/task_48341/Mage.java
src/main/java/school/faang/sprint_3/task_48341/Main.java
src/main/java/school/faang/sprint_3/task_48341/PowerCalculator.java
src/main/java/school/faang/sprint_3/task_48341/Swordsman.java
src/main/java/school/faang/sprint_3/task_48341/Unit.java

Решил задачу "Распределенная армия героев меча и магии". Проверьте пожалуйста.

BJS2-48341

---

src/main/java/derschrank/sprint03/task11/bjstwo_49559/Main.java
src/main/java/derschrank/sprint03/task11/bjstwo_49559/TamagotchiInterface.java
src/main/java/derschrank/sprint03/task11/bjstwo_49559/TamagotchiVlad.java
src/main/java/derschrank/sprint03/task11/bjstwo_49559/VladController.java
src/main/java/derschrank/sprint03/task11/bjstwo_49559/info.txt

Тамагочи Влад
👩‍💻 🧠 (Дополнительная задача)
Условия задачи
Задач становится так много, что удовлетворение базовых потребностей Влада приходится программировать и запускать в нескольких потоках. Вы должны помочь Владу наладить режим сна и питания. Ну ещё и поиграть с ним немного нужно, а то у него стресс.
Требования:
1️⃣ Создайте класс TamagotchiVlad, который будет представлять Влада и иметь следующие методы:
feed() — чтобы покормить Влада.
play() — чтобы поиграть с Владом.
clean() — чтобы почистить Влада.
sleep() — чтобы переводить Влада в режим сна.
Каждый метод должен выводить сообщение в консоль, описывая текущее действие (например, "Влад ест", "Влад играет").
Все методы должны быть синхронизированы (с использованием ключевого слова synchronized), чтобы предотвратить одновременный …

BJS2-49559 Sprint03. Task11. Synchro. TamagotchiVlad

---

src/main/java/meta_universe/Main.java
src/main/java/meta_universe/Notification.java
src/main/java/meta_universe/NotificationManager.java
src/main/java/meta_universe/TypNotification.java

добавил от себя фильтрацию на ругань
но проблема в том что надо еще сделать проверку на символы которые могут подставлять заместо каких то букв и оставить тот же смысл сообщения
с базовыми случаем справляется

мета вселенная

---

src/main/java/school/faang/task_48922/Food.java
src/main/java/school/faang/task_48922/House.java
src/main/java/school/faang/task_48922/Main.java
src/main/java/school/faang/task_48922/Room.java

Немного отошел от условий:
уменьшил интервал запуска задач с 30 до 5 секунд для наглядности работы.
метод main() перенес в из класса House в класс Main.

task_48922 solution

---

src/main/java/school/faang/googlephotosyncbjs49037/GooglePhotosAutoUploader.java
src/main/java/school/faang/googlephotosyncbjs49037/Main.java

Реализовал многопоточную загрузку фотографий в Google Photos

BJS2-49037 - Google Photo sync

---

src/main/java/school/faang/blockingsptifybjs49377/Music.java
src/main/java/school/faang/blockingsptifybjs49377/Player.java

- создал класс Player и реализовал в нем залоченные методы для выполн……ения действий
- в классе Music создал несколько потоков, которые имитирует действия разных пользователей

BJS2-49377 - Блокировка Spotify

---

src/main/java/school/faang/bjs247750/CashierThread.java
src/main/java/school/faang/bjs247750/Main.java

bjs2-47750 queue walmart

---

src/main/java/school/faang/sprint_3/task_48846/Chore.java
src/main/java/school/faang/sprint_3/task_48846/WeasleyFamily.java

Решил задачу "They were very nice but extremely poor", проверьте пожалуйста.

BJS2-48846

---

src/main/java/school/faang/bjs248205/City.java
src/main/java/school/faang/bjs248205/CityWorker.java
src/main/java/school/faang/bjs248205/Location.java
src/main/java/school/faang/bjs248205/Monster.java
src/main/java/school/faang/bjs248205/Witcher.java

bjs2-48205 pave the way with your finger

---

src/main/java/school/faang/task_48704/Food.java
src/main/java/school/faang/task_48704/House.java
src/main/java/school/faang/task_48704/Main.java
src/main/java/school/faang/task_48704/Room.java

BJS2-48704 - задача "Mice are very nice!"

BJS2-48704 - the task "Mice are very nice!"

---

src/main/java/school/faang/sprint_4/task_50260/Factorial.java
src/main/java/school/faang/sprint_4/task_50260/Main.java

Создана программа для асинхронного вычисления факториалов списка чисел

BJS2-50260: Великий и ужасный факториал!

---

src/main/java/ru/maks1979/task_48134/Archer.java
src/main/java/ru/maks1979/task_48134/Army.java
src/main/java/ru/maks1979/task_48134/Fighter.java
src/main/java/ru/maks1979/task_48134/Mage.java
src/main/java/ru/maks1979/task_48134/Main.java
src/main/java/ru/maks1979/task_48134/Swordsman.java

AtomicInteger среда подсказала использовать.

Stream api2

---

src/main/java/school/faang/task_48968/GooglePhotosAutoUploader.java
src/main/java/school/faang/task_48968/Main.java

BJS2-48968 - задача"Google Photo sync"

BJS2-48968 - the task "Google Photo sync"

---

src/main/java/school/faang/broforcebjs49421/Game.java

Реализовал классы Game, при котором игрок набирает очки, у него отнимаются жизни и по результату выводится набранное кол-во очков

BJS2-49421 - Be Force!

---

src/main/java/school/faang/task_49704/Boss.java
src/main/java/school/faang/task_49704/Main.java
src/main/java/school/faang/task_49704/Player.java

BJS2-49704 - the task "Supercow!"

BJS2-49704 - the task "Supercow!"

---

src/main/java/school/faang/task_50111/Main.java
src/main/java/school/faang/task_50111/Order.java
src/main/java/school/faang/task_50111/OrderProcessor.java
src/main/java/school/faang/task_50111/OrderStatus.java

- Реализовал доп. валидацию перехода статуса заказа

BJS2-50111 Собираем заказы в Amazon

---

src/main/java/school/faang/bjs249600/Boss.java
src/main/java/school/faang/bjs249600/Main.java
src/main/java/school/faang/bjs249600/Player.java

bjs2-49600 supercow

---

src/main/java/school/faang/bjs249230/Game.java
src/main/java/school/faang/bjs249230/Main.java

bjs2-49230 bro force

---

src/main/java/school/faang/bjs_50846/School.java
src/main/java/school/faang/bjs_50846/Student.java
src/main/java/school/faang/bjs_50846/Task.java
src/main/java/school/faang/bjs_50846/Tournament.java
src/test/java/school/faang/bjs_50846/TournamentTest.java

Решение задачи "Турнир трех волшебников"

AntonGraf-BJS2-50846

---

src/main/java/school/faang/bjs249891/Main.java
src/main/java/school/faang/bjs249891/MasterCardService.java

* Асинхронность и Future is done

bjs2-49891

---

src/main/java/school/faang/bjs250832/Inventory.java
src/main/java/school/faang/bjs250832/Item.java
src/main/java/school/faang/bjs250832/Main.java

bjs2-50832

---

src/main/java/school/faang/bjs249926/Main.java
src/main/java/school/faang/bjs249926/ResultConsumer.java
src/main/java/school/faang/bjs249926/SquareRequest.java

bjs2-49926

---

src/main/java/school/faang/bjs250772/Main.java
src/main/java/school/faang/bjs250772/TwitterAccount.java
src/main/java/school/faang/bjs250772/TwitterSubscriptionSystem.java

* Становимся celebrity в Twitter is done

bjs2-50772

---

src/main/java/school/faang/bjs251814/Main.java
src/main/java/school/faang/bjs251814/School.java
src/main/java/school/faang/bjs251814/Student.java
src/main/java/school/faang/bjs251814/Task.java
src/main/java/school/faang/bjs251814/Tournament.java

* Турнир трех волшебников is done

bjs2-51814

---

src/main/java/school/faang/bjs251851/Main.java
src/main/java/school/faang/bjs251851/Potion.java

bjs2-51851

---

src/main/java/school/faang/sprint_4/task_bjs250922/Main.java
src/main/java/school/faang/sprint_4/task_bjs250922/Potion.java
src/main/java/school/faang/sprint_4/task_bjs250922/PotionService.java
src/main/java/school/faang/sprint_4/task_bjs250922/TestDataGenerator.java

BJS2-50922
Качаем алхимию
для потокобезопасности тестовые данные генерируются в CopyOnWriteArrayList (как раз по задаче много операций чтения, нет операций записи)

BJS2-50922

---

src/main/java/school/faang/sprint_4/task_bjs250903/Main.java
src/main/java/school/faang/sprint_4/task_bjs250903/TwitterAccount.java
src/main/java/school/faang/sprint_4/task_bjs250903/TwitterSubscriptionSystem.java

BJS2-50903
Становимся celebrity в Twitter
main output:

BJS2-50903

---

src/main/java/school/faang/bjs_50741/TwitterAccount.java
src/main/java/school/faang/bjs_50741/TwitterSubscriptionSystem.java
src/test/java/school/faang/bjs_50741/TwitterSubscriptionSystemTest.java

Решение "Становимся celebrity в Twitter"

AntonGraf-BJS2-50741

---

src/main/java/school/faang/sprint_4/task_bjs250382/Main.java
src/main/java/school/faang/sprint_4/task_bjs250382/Order.java
src/main/java/school/faang/sprint_4/task_bjs250382/OrderProcessor.java
src/main/java/school/faang/sprint_4/task_bjs250382/OrderType.java
src/main/java/school/faang/sprint_4/task_bjs250382/TestDataGenerator.java

BJS2-50382
Собираем заказы в Amazon

BJS2-50382

---

src/main/java/school/faang/bjs_50055/Order.java
src/main/java/school/faang/bjs_50055/OrderProcessor.java
src/main/java/school/faang/bjs_50055/OrderStatus.java
src/test/java/school/faang/bjs_50055/OrderProcessorTest.java

Решение задачи "Собираем заказы в Amazon"

AntonGraf-BJS2-50055

---

src/main/java/school/faang/bjs250369/Main.java
src/main/java/school/faang/bjs250369/Player.java
src/main/java/school/faang/bjs250369/Quest.java
src/main/java/school/faang/bjs250369/QuestSystem.java

bjs2-50369

---

src/main/java/school/faang/bjs250275/Battle.java
src/main/java/school/faang/bjs250275/Main.java
src/main/java/school/faang/bjs250275/Robot.java

bjs2-50275

---

src/main/java/school/faang/bjs_50843/Potion.java
src/main/java/school/faang/bjs_50843/PotionGathering.java
src/test/java/school/faang/bjs_50843/PotionGatheringTest.java

Решение задачи "Качаем алхимию"

AntonGraf-BJS2-50843

---

src/main/java/school/faang/sprint_4/task_51112/DeliveryService.java
src/main/java/school/faang/sprint_4/task_51112/Main.java
src/main/java/school/faang/sprint_4/task_51112/Order.java
src/main/java/school/faang/sprint_4/task_51112/Product.java
src/main/java/school/faang/sprint_4/task_51112/PromoCode.java
src/main/java/school/faang/sprint_4/task_51112/ValidationUtils.java

Разработан сервис применения скидок к заказу с учетом асинхронного использования промокодов

BJS2-51112: Купоны на доставку

---

src/main/java/school/faang/bjs247736/GriffinsFoodDelivery.java

bjs2-47736 feed peter griffin

---

src/main/java/school/faang/bjs249906/Main.java
src/main/java/school/faang/bjs249906/MasterCardService.java

bjs2-49906 async and futur

---

src/main/java/derschrank/sprint04/task01/bjstwo_49942/CardServiceInterface.java
src/main/java/derschrank/sprint04/task01/bjstwo_49942/Main.java
src/main/java/derschrank/sprint04/task01/bjstwo_49942/MasterCardService.java

Асинхронность и Future
👩‍💻 🧠
Представьте, что вы работаете в компании Stripe и вам нужно интегрировать свою систему с сервисом обработки платежей MasterCard. Ваша задача — создать программу, которая обрабатывает платежи и отправляет аналитику одновременно, но выполняет их параллельно.
Цель:
Создайте программу, которая выполняет асинхронные операции оплаты и отправки аналитики, используя классы Future и CompletableFuture.
Требования:
1️⃣ Создайте класс MasterCardService, который содержит два метода:
collectPayment(): имитирует процесс оплаты и возвращает результат через 10 секунд.
sendAnalytics(): имитирует процесс отправки аналитики и возвращает результат через 1 секунду.
2️⃣ Реализуйте метод doAll в вашем классе:
Запустите метод collectPayment() в отдельном потоке и …

BJS2-49942 Sprint04. Task01. Future, CompletableFuture

---

src/main/java/school/faang/task_49961/Main.java
src/main/java/school/faang/task_49961/MasterCardService.java

BJS2-49961 - задача "Асинхронность и Future"

BJS2-49961 - the task "Asynchrony and Future"

---

src/main/java/school/faang/asyncandfuturebjs49984/MasterCardService.java

Создал программу, которая выполняет асинхронные операции оплаты и отправки аналитики, используя классы Future и CompletableFuture

BJS2-49984 - Асинхронность и Future

---

src/main/java/school/faang/bjs250199/Main.java
src/main/java/school/faang/bjs250199/MasterCardService.java

BJS2-50199, Asynchrony and Future - alpha release

BJS2-50199, Asynchrony and Future

---

src/main/java/school/faang/task_50006/Main.java
src/main/java/school/faang/task_50006/Player.java
src/main/java/school/faang/task_50006/Quest.java
src/main/java/school/faang/task_50006/QuestSystem.java

У меня возникла проблема. Вроде все работает правильно, но в консоль не выводятся логи. Пробывал main проверить через дебаг - все выводиться в консоль нормально. Не могу даже вопрос сформулировать, что бы спросить в Дескорде.

JS2-50006: WOW

---

src/main/java/school/faang/sprint_4/task_50011/Main.java
src/main/java/school/faang/sprint_4/task_50011/MasterCardService.java

Выполнил задачу "Асинхронность и Future". Проверьте пожалуйста.

BJS2-50011

---

src/main/java/school/faang/wowbjs501146/Main.java
src/main/java/school/faang/wowbjs501146/Player.java
src/main/java/school/faang/wowbjs501146/Quest.java
src/main/java/school/faang/wowbjs501146/QuestSystem.java

Создал класс QuestSystem, который использует CompletableFuture для acинхронного выполнения заданий

BJS2-50146 - WOW

---

src/main/java/school/faang/bjs250377/Main.java
src/main/java/school/faang/bjs250377/Player.java
src/main/java/school/faang/bjs250377/Quest.java
src/main/java/school/faang/bjs250377/QuestSystem.java

BJS2-50377, WOW - alpha release

BJS2-50377, WOW

---

src/main/java/school/faang/bjs251575/Donation.java
src/main/java/school/faang/bjs251575/Main.java
src/main/java/school/faang/bjs251575/Organization.java

bjs2-51575

---

src/main/java/school/faang/task_51580/Donation.java
src/main/java/school/faang/task_51580/Main.java
src/main/java/school/faang/task_51580/Organization.java

- использовал DecimalFormat для более точного вывода суммы
- добавил отчет по всем донатам  donationsReport

BJS2-51580 Поддержим животных

---

src/main/java/faang/school/godbless/FourthSprint/bjs2_50002/MasterCardService.java
src/main/resources/logback.xml

Reverts CorporationX/god_bless#16879

Revert "Revert "Асинхронность и Future""

---

src/main/java/school/faang/task_50154/Main.java
src/main/java/school/faang/task_50154/Player.java
src/main/java/school/faang/task_50154/Quest.java
src/main/java/school/faang/task_50154/QuestSystem.java

BJS2-50154 - the task "WOW"

---

src/main/java/school/faang/collectordersamazonbjs50169/Order.java
src/main/java/school/faang/collectordersamazonbjs50169/OrderProcessingApp.java
src/main/java/school/faang/collectordersamazonbjs50169/OrderProcessor.java
src/main/java/school/faang/collectordersamazonbjs50169/OrderStatus.java

Создал программу, которая асинхронно обрабатывает заказы и корректно считает их количество с помощью AtomicInteger

BJS2-50169 - Собираем заказы в Amazon

---

src/main/java/school/faang/bjs250332/Factorial.java
src/main/java/school/faang/bjs250332/Main.java

* Великий и ужасный факториал! is done

bjs2-50332

---

src/main/java/school/faang/sprint3/task49350broforce/Game.java
src/main/java/school/faang/sprint3/task49350broforce/Main.java
src/main/java/school/faang/sprint3/task49350broforce/Player.java

В выводе почему-то иногда пишет два раза какой игрок победил, а ещё бывает после завершения игры некоторые игроки делают ходы, не понимаю почему так

Я решил не по условию немного)

---

src/main/java/school/faang/sprint_4/task_51080/App.java
src/main/java/school/faang/sprint_4/task_51080/EncryptionUtils.java
src/main/java/school/faang/sprint_4/task_51080/MilitaryBase.java

Разработан сервис отправки и приема зашифрованных сообщений

BJS2-51080: База, прием!

---

src/main/java/school/faang/sprint_4/task_51010/DataCollector.java
src/main/java/school/faang/sprint_4/task_51010/Main.java
src/main/java/school/faang/sprint_4/task_51010/ReportGenerator.java
src/main/java/school/faang/sprint_4/task_51010/Sales.java
src/main/java/school/faang/sprint_4/task_51010/SalesData.java

Разработан сервис для сбора данных о продажах из нескольких магазинов

BJS2-51010: Сбор данных для отчета

---

src/main/java/school/faang/bjs250080/AmazonOrderProcessing.java
src/main/java/school/faang/bjs250080/Order.java
src/main/java/school/faang/bjs250080/OrderProcessor.java
src/main/java/school/faang/bjs250080/Status.java

bjs2-50080 we collect orders from amazon

---

src/main/java/school/faang/bjs249922/Main.java
src/main/java/school/faang/bjs249922/ResultConsumer.java
src/main/java/school/faang/bjs249922/SquareRequest.java

bjs2-49922 fan out fan in

---

src/main/java/school/faang/bjs250801/Main.java
src/main/java/school/faang/bjs250801/TwitterAccount.java
src/main/java/school/faang/bjs250801/TwitterSubscriptionSystem.java

bjs2-50801 becoming a celebrity on twitter

---

src/main/java/school/faang/bjs250622/Kingdom.java
src/main/java/school/faang/bjs250622/Main.java

bjs2-50622 send a raven

---

src/main/java/school/faang/bjs250265/Battle.java
src/main/java/school/faang/bjs250265/Robot.java
src/main/java/school/faang/bjs250265/StarWarsArena.java

bjs2-50265 star wars arena

---

src/main/java/school/faang/bjs250569/FacebookNotificationSystem.java
src/main/java/school/faang/bjs250569/Notification.java
src/main/java/school/faang/bjs250569/NotificationManager.java

bjs2-50569 sending notifications on facebook

---

src/main/java/derschrank/sprint04/task11/bjstwo_50572/Main.java
src/main/java/derschrank/sprint04/task11/bjstwo_50572/Notification.java
src/main/java/derschrank/sprint04/task11/bjstwo_50572/NotificationManager.java
src/main/java/derschrank/sprint04/task11/bjstwo_50572/NotificationManagerInterface.java
src/main/java/derschrank/sprint04/task11/bjstwo_50572/NotificatonService.java
src/main/java/derschrank/sprint04/task11/bjstwo_50572/info.txt

Рассылаем уведомления в Facebook
derschrank2000-S04-T11-BJS2-50572
derschrank.sprint04.task11.bjstwo_50572
Sprint04. Task11. CompletableFuture. Notification Facebook
-----------------------------------
Рассылаем уведомления в Facebook
👩‍💻 🧠🧠 (Дополнительная задача)
Условия задачи
Вам нужно создать систему уведомлений для Facebook, которая будет асинхронно получать уведомления и добавлять их в общий список. Необходимо использовать CompletableFuture для асинхронного добавления уведомлений и synchronized для контроля доступа к общему списку уведомлений.
Цель:
Создайте программу, которая будет асинхронно добавлять уведомления в общий список и корректно синхронизировать доступ к этому списку с помощью synchronized.
Требования:
1️⃣ Создайте класс Notification, который представляет собой …

BJS2-50572 Sprint04. Task11. CompletableFuture. Notification Facebook

---

src/main/java/school/faang/sprint_4/task_51901/Comment.java
src/main/java/school/faang/sprint_4/task_51901/Main.java
src/main/java/school/faang/sprint_4/task_51901/Post.java
src/main/java/school/faang/sprint_4/task_51901/PostService.java

Реализована система комментариев, которая позволяет пользователям одновременно оставлять комментарии под постами

BJS2-51901: Оставляем комментарий

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/task_49337/Music.java
src/main/java/school/faang/task_49337/Player.java

BJS2-49337 - the task "Blocking Spotify"

BJS2-49337 - the task "Blocking Spotify"

---

.gitignore
src/main/java/school/faang/task_50179/Main.java
src/main/java/school/faang/task_50179/Order.java
src/main/java/school/faang/task_50179/OrderProcessor.java
src/main/java/school/faang/task_50179/Status.java

BJS2-50179 - задача "Собираем заказы в Amazon"

BJS2-50179 - the task "We collect orders on Amazon"

---

src/main/java/school/faang/task_50894/Main.java
src/main/java/school/faang/task_50894/TwitterAccount.java
src/main/java/school/faang/task_50894/TwitterSubscriptionSystem.java

BJS2-50894 - задачи "Становимся celebrity в Twitter"

BJS2-50894 - the task "Becoming a celebrity on Twitter"

---

src/main/java/school/faang/task_51160/Main.java
src/main/java/school/faang/task_51160/School.java
src/main/java/school/faang/task_51160/Student.java
src/main/java/school/faang/task_51160/Task.java
src/main/java/school/faang/task_51160/Tournament.java

BJS2-51160 - задача "Турнир трех волшебников"

BJS2-51160 - the task "The Triwizard Tournament"

---

src/main/java/school/faang/task_51146/Main.java
src/main/java/school/faang/task_51146/Potion.java

BJS2-51146 - задача "Качаем алхимию"

BJS2-51146 - the task "Pumping alchemy"

---

src/main/java/school/faang/bjs250591/Main.java
src/main/java/school/faang/bjs250591/Pair.java
src/main/java/school/faang/bjs250591/Superhero.java
src/main/java/school/faang/bjs250591/SuperheroBattle.java

bjs2-50591

---

src/main/java/school/faang/bjs250615/Kingdom.java
src/main/java/school/faang/bjs250615/Main.java
src/main/java/school/faang/bjs250615/RavenService.java

bjs2-50615

---

src/main/java/school/faang/bjs250404/Factorial.java
src/main/java/school/faang/bjs250404/Main.java

bjs2-50404 the great and terrible factorial

---

src/main/java/school/faang/bjs251600/Donation.java
src/main/java/school/faang/bjs251600/Main.java
src/main/java/school/faang/bjs251600/Organization.java

bjs2-51600 support animals

---

src/main/java/school/faang/task_51253/Comment.java
src/main/java/school/faang/task_51253/Main.java
src/main/java/school/faang/task_51253/Post.java
src/main/java/school/faang/task_51253/PostService.java

BJS2-51253 - задача "Оставляем комментарий"

BJS2-51253 - the task "Writing a comment"

---

src/main/java/derschrank/sprint04/task07/bjstwo_50256/Battle.java
src/main/java/derschrank/sprint04/task07/bjstwo_50256/BattleInterface.java
src/main/java/derschrank/sprint04/task07/bjstwo_50256/BattleService.java
src/main/java/derschrank/sprint04/task07/bjstwo_50256/Fighting.java
src/main/java/derschrank/sprint04/task07/bjstwo_50256/Main.java
src/main/java/derschrank/sprint04/task07/bjstwo_50256/Robot.java
src/main/java/derschrank/sprint04/task07/bjstwo_50256/info.txt

Star Wars Arena
derschrank2000-S04-T07-BJS2-50256
derschrank.sprint04.task07.bjstwo_50256
Sprint04. Task07. Future. Star Wars Arena
---------------------
Star Wars Arena
👩‍💻 🧠 (Дополнительная задача)
Условия задачи
Вы являетесь разработчиком системы для арены Звёздных войн, на которой роботы сражаются друг с другом. Вам необходимо разработать систему, которая будет определять победителя в каждой битве между двумя роботами. Используйте Future в Java для асинхронного определения победителя.
Цель:
Создайте систему, которая будет асинхронно запускать битвы между роботами с использованием ExecutorService и возвращать результат битвы через Future.
Требования:
1️⃣ Создайте класс Robot, который представляет робота, с полями:
name — имя робота,
attackPower — сила атаки робота,
defensePower — сила …

BJS2-50256 Sprint04. Task07. Future. Star Wars Arena

---

src/main/java/derschrank/sprint04/task03/bjstwo_51033/Main.java
src/main/java/derschrank/sprint04/task03/bjstwo_51033/School.java
src/main/java/derschrank/sprint04/task03/bjstwo_51033/Student.java
src/main/java/derschrank/sprint04/task03/bjstwo_51033/Task.java
src/main/java/derschrank/sprint04/task03/bjstwo_51033/Tournament.java
src/main/java/derschrank/sprint04/task03/bjstwo_51033/info.txt

Представьте, что вам поручено разработать систему для магического турнира в мире Гарри Поттера. В этом турнире соревнуются команды из разных волшебных школ. Ваша задача — реализовать систему, которая моделирует выполнение заданий командами из разных школ и определяет победителя турнира. Используйте CompletableFuture в Java для асинхронного выполнения заданий и метода allOf для объединения результатов.
Цель:
Создайте класс Tournament, который использует CompletableFuture для асинхронного запуска заданий команд и объединяет результаты с помощью метода allOf для определения победителя турнира.
Требования:
1. Создайте класс School, который будет представлять волшебную школу. В нем должны быть следующие поля:
name (название школы),
team (список студентов этой школы),
getTotalPoints (метод для …

BJS2-51033 Sprint04. Task03. CompletableFuture. Tournament of three

---

src/main/java/derschrank/sprint04/task06/bjstwo_50791/Main.java
src/main/java/derschrank/sprint04/task06/bjstwo_50791/TwitterAccount.java
src/main/java/derschrank/sprint04/task06/bjstwo_50791/TwitterSubscriptionSystem.java
src/main/java/derschrank/sprint04/task06/bjstwo_50791/info.txt

derschrank2000-S04-T06-BJS2-50791
derschrank.sprint04.task06.bjstwo_50791
Sprint04. Task06. CompletableFuture. TwitterSubscriptionSystem
------------
Становимся celebrity в Twitter
👩‍💻 🧠🧠
Условия задачи
Представьте, что вам нужно разработать простую модель системы подписок для Twitter. Ваша задача — создать программу на Java, которая будет использовать CompletableFuture для асинхронного добавления подписчиков в учетные записи Twitter, и синхронизировать доступ к общему ресурсу — количеству подписчиков.
Цель:
Создайте программу, которая асинхронно добавляет подписчиков в учетную запись Twitter и корректно синхронизирует доступ к общему ресурсу.
Требования:
1️⃣ Создайте класс TwitterAccount, который представляет учетную запись Twitter. Поля:
username — уникальное имя учетной записи, …

BJS2-50791 Sprint04. Task06. CompletableFuture. TwitterSubscriptionSystem

---

src/main/java/derschrank/sprint04/task08/bjstwo_50617/Kingdom.java
src/main/java/derschrank/sprint04/task08/bjstwo_50617/Main.java
src/main/java/derschrank/sprint04/task08/bjstwo_50617/Raven.java
src/main/java/derschrank/sprint04/task08/bjstwo_50617/Service.java
src/main/java/derschrank/sprint04/task08/bjstwo_50617/TypeMsg.java
src/main/java/derschrank/sprint04/task08/bjstwo_50617/Utils.java
src/main/java/derschrank/sprint04/task08/bjstwo_50617/info.txt

Пошлите ворона!
derschrank2000-S04-T08-BJS2-50617
derschrank.sprint04.task08.bjstwo_50617
Sprint04. Task08.  CompletableFuture. Handle. Send Raven.
---------------------------
Пошлите ворона!
👩‍💻 🧠 (Дополнительная задача)
Условия задачи
В сеттинге «Игры престолов», семь королевств сражаются за железный трон. Ваша задача — написать программу на Java, используя CompletableFuture, которая асинхронно отправляет разведывательных воронов с сообщениями между королевствами. Если ворон не смог доставить сообщение, программа должна обрабатывать ошибку с помощью метода handle у CompletableFuture.
Требования:
1️⃣ Создайте класс Kingdom, который представляет королевство. Поля:
name — название королевства;
и метод sendMessage(Kingdom receiver) — метод, который отправляет сообщение из одного королевства …

BJS2-50617 Sprint04. Task08.  CompletableFuture. Handle. Send Raven

---

src/main/java/derschrank/sprint04/task12/bjstwo_50778/Inventory.java
src/main/java/derschrank/sprint04/task12/bjstwo_50778/Item.java
src/main/java/derschrank/sprint04/task12/bjstwo_50778/Main.java
src/main/java/derschrank/sprint04/task12/bjstwo_50778/ProviderItemsInterface.java
src/main/java/derschrank/sprint04/task12/bjstwo_50778/Service.java
src/main/java/derschrank/sprint04/task12/bjstwo_50778/Shop.java
src/main/java/derschrank/sprint04/task12/bjstwo_50778/WorkshopInterface.java
src/main/java/derschrank/sprint04/task12/bjstwo_50778/info.txt

Carry отожрался
derschrank2000-S04-T12-BJS2-50778
derschrank.sprint04.task12.bjstwo_50778
Sprint04. Task12. CompletableFuture. Carry. f.thenCombine() и f.thenCompose()
------------------------
Carry отожрался
👩‍💻 🧠🧠🧠 (Дополнительная задача)
Условия задачи
В мире Dota 2, игроки собирают предметы, которые могут быть скомбинированы для создания более мощных предметов. Вам нужно написать программу, которая асинхронно собирает предметы и комбинирует их в более сильные предметы.
Используйте методы thenCombine и thenCompose у CompletableFuture для асинхронного получения предметов и их объединения.
Требования:
1️⃣ Создайте класс Item — он описывает предметы и их характеристики. Поля:
name — название предмета;
power — сила предмета.
2️⃣ Создайте класс Inventory — он описывает инвентарь игрока. У …

BJS2-50778 Sprint04. Task12. CompletableFuture. Carry. f.thenCombine() и f.thenCompose()

---

src/main/java/school/faang/celebritytwitbjs50953/Main.java
src/main/java/school/faang/celebritytwitbjs50953/TwitterAccount.java
src/main/java/school/faang/celebritytwitbjs50953/TwitterSubscriptionSystem.java

Создал программу, которая асинхронно добавляет подписчиков в учетную запись Twitter и корректно синхронизирует доступ к общему ресурсу

BJS2-50953 - Становимся celebrity в Twitter

---

src/main/java/school/faang/triwizardtournamentbjs51148/MagicalTournament.java
src/main/java/school/faang/triwizardtournamentbjs51148/School.java
src/main/java/school/faang/triwizardtournamentbjs51148/Student.java
src/main/java/school/faang/triwizardtournamentbjs51148/Task.java
src/main/java/school/faang/triwizardtournamentbjs51148/Tournament.java

Создал класс Tournament, который использует CompletableFuture для асинхронного запуска заданий команд и объединяет результаты с помощью метода allOf для определения победителя турнира

BJS2-51148 - Турнир трех волшебников

---

src/main/java/school/faang/pumpingalchemybjs51125/Potion.java
src/main/java/school/faang/pumpingalchemybjs51125/PotionGathering.java

Создал программу, которая будет асинхронно собирать ингредиенты для каждого зелья в списке и вычислять общее количество собранных ингредиентов

BJS2-51125 - Качаем алхимию

---

src/main/java/school/faang/bjs250440/AmazonOrderProcessing.java
src/main/java/school/faang/bjs250440/Order.java
src/main/java/school/faang/bjs250440/OrderProcessor.java
src/main/java/school/faang/bjs250440/OrderStatus.java

BJS2-50440, We collect orders on Amazon - alpha release

BJS2-50440, We collect orders on Amazon

---

src/main/java/derschrank/sprint04/task02/bjstwo_50097/Main.java
src/main/java/derschrank/sprint04/task02/bjstwo_50097/Player.java
src/main/java/derschrank/sprint04/task02/bjstwo_50097/Quest.java
src/main/java/derschrank/sprint04/task02/bjstwo_50097/QuestSystem.java
src/main/java/derschrank/sprint04/task02/bjstwo_50097/QuestSystemInterface.java
src/main/java/derschrank/sprint04/task02/bjstwo_50097/info.txt

WOW
👩‍💻 🧠
Представьте, что вы являетесь разработчиком системы для MMORPG World of Warcraft. Ваша задача — создать систему, которая моделирует выполнение заданий игроками и получение результатов с использованием CompletableFuture в Java. Вам нужно реализовать асинхронную модель выполнения квестов, где игроки выполняют задания параллельно, а результаты обрабатываются после завершения каждого задания.
Цель:
Создайте класс QuestSystem, который использует CompletableFuture для асинхронного выполнения заданий и возвращает результаты с использованием методов thenApply, thenAccept и других методов CompletableFuture.
Требования:
1️⃣ Создайте класс Player с полями:
name (имя игрока),
level (уровень игрока),
experience (опыт игрока).
2️⃣ Создайте класс Quest с полями:
name (название …

BJS2-50097 Sprint04. Task02. WOW CompletableFuture.thenAccept()

---

src/main/java/school/faang/bjs251771/Main.java
src/main/java/school/faang/bjs251771/TwitterAccount.java
src/main/java/school/faang/bjs251771/TwitterSubscriptionSystem.java

BJS2-51771, Becoming a celebrity on Twitter  - alpha release

BJS2-51771, Becoming a celebrity on Twitter

---

src/main/java/school/faang/bjs251881/MagicalTournament.java
src/main/java/school/faang/bjs251881/School.java
src/main/java/school/faang/bjs251881/Student.java
src/main/java/school/faang/bjs251881/Task.java
src/main/java/school/faang/bjs251881/Tournament.java

BJS2-51881, The Triwizard Tournament - alpha release

BJS2-51881, The Triwizard Tournament

---

src/main/java/school/faang/bjs251911/Potion.java
src/main/java/school/faang/bjs251911/PotionGathering.java

BJS2-51911, Pumping alchemy - alpha release

BJS2-51911, Pumping alchemy

---

src/main/java/school/faang/task_51642/Main.java
src/main/java/school/faang/task_51642/School.java
src/main/java/school/faang/task_51642/Student.java
src/main/java/school/faang/task_51642/Task.java
src/main/java/school/faang/task_51642/Tournament.java

Создан класс School, представляющий школу;
Создан класс Student, представляющий студента;
Создан класс Task, представляющий задание;
Реализован класс Tournament с методом startTask, принимающий School и Task и возвращающий - CompletableFuture<School>, который обновляет очки студентов школы после выполнения задания.

BJS2-51642: Турнир трех волшебников

---

src/main/java/school/faang/bjs251335/with_deadlock/DesignDepartment.java
src/main/java/school/faang/bjs251335/with_deadlock/DesignResources.java
src/main/java/school/faang/bjs251335/with_deadlock/Main.java
src/main/java/school/faang/bjs251335/with_deadlock/MarketingDepartment.java
src/main/java/school/faang/bjs251335/with_deadlock/MarketingResources.java
src/main/java/school/faang/bjs251335/without_deadlock/DesignDepartment.java
src/main/java/school/faang/bjs251335/without_deadlock/DesignResources.java
src/main/java/school/faang/bjs251335/without_deadlock/Main.java
src/main/java/school/faang/bjs251335/without_deadlock/MarketingDepartment.java
src/main/java/school/faang/bjs251335/without_deadlock/MarketingResources.java

bjs2-51335 the work is standing

---

src/main/java/school/faang/bjs251235/Location.java
src/main/java/school/faang/bjs251235/LocationGenerator.java
src/main/java/school/faang/bjs251235/Main.java
src/main/java/school/faang/bjs251235/Status.java
src/main/java/school/faang/bjs251235/TransportManagementSystem.java
src/main/java/school/faang/bjs251235/Vehicle.java
src/main/java/school/faang/bjs251235/VehicleTracker.java

bjs2-51235 tracking system

---

src/main/java/school/faang/bjs251188/App.java
src/main/java/school/faang/bjs251188/CollaborativeDocument.java
src/main/java/school/faang/bjs251188/DocumentSection.java
src/main/java/school/faang/bjs251188/DocumentSectionProcessor.java

bjs2-51188  google docs

---

src/main/java/derschrank/sprint04/task21/bjstwo_50984/Conference.java
src/main/java/derschrank/sprint04/task21/bjstwo_50984/Main.java
src/main/java/derschrank/sprint04/task21/bjstwo_50984/Participant.java
src/main/java/derschrank/sprint04/task21/bjstwo_50984/info.txt

Мини Zoom
derschrank2000-S04-T21-BJS2-50984
derschrank.sprint04.task21.bjstwo_50984
Sprint04. Task21/7. CyclicBarrier. Conference
--------------------------
Мини Zoom
👩‍💻 🧠🧠🧠 (Дополнительная задача)
Условия задачи
Вы разрабатываете приложение для трансляции онлайн-конференций, где каждый участник должен подключиться к приложению по сети и начать трансляцию своего видео и звука. Трансляция может быть запущена только после того, как определённое количество участников присоединится к конференции. Ваше задание — написать механизм, который будет ожидать прибытия всех участников перед запуском трансляции.
Требования:
1️⃣ Создайте класс Conference, который хранит информацию о конференции. Добавьте поле requiredParticipants — количество участников, необходимых для начала трансляции.
2️⃣ В классе …

BJS2-50984 Sprint04. Task21/7. CyclicBarrier. Conference

---

src/main/java/derschrank/sprint04/task23/bjstwo_51054/Base.java
src/main/java/derschrank/sprint04/task23/bjstwo_51054/EncryptionUtils.java
src/main/java/derschrank/sprint04/task23/bjstwo_51054/Main.java
src/main/java/derschrank/sprint04/task23/bjstwo_51054/MilitaryBase.java
src/main/java/derschrank/sprint04/task23/bjstwo_51054/info.txt

База, прием!
derschrank2000-S04-T23-BJS2-51054
derschrank.sprint04.task23.bjstwo_51054
Sprint04. Task23/9. LinkedBlockingQueue. EncryptionUtils
-------------------------------------------
База, прием!
👩‍💻 🧠🧠🧠 (Дополнительная задача)
Условия задачи
Пентагон разрабатывает систему обмена сообщениями между военными базами. Ваша задача — разработать приложение на Java, которое обеспечивает безопасный и быстрый обмен информацией между военными базами. Обмен сообщениями осуществляется с использованием симметричного шифрования AES, многопоточности и потокобезопасной очереди LinkedBlockingQueue.
Требования:
1️⃣ Создайте класс EncryptionUtils, который будет содержать методы для шифрования и расшифровывания сообщений с использованием алгоритма AES.
AES-шифрование — алгоритм симметричного шифрования, …

BJS2-51054 Sprint04. Task23/9. LinkedBlockingQueue. EncryptionUtils

---

src/main/java/school/faang/bjs250902/Gathering.java
src/main/java/school/faang/bjs250902/Main.java
src/main/java/school/faang/bjs250902/Potion.java

bjs2-50902 downloading alchemy

---

src/main/java/school/faang/task_50209/AmazonOrderProcessing.java
src/main/java/school/faang/task_50209/Order.java
src/main/java/school/faang/task_50209/OrderProcessor.java
src/main/java/school/faang/task_50209/OrderStatus.java

Создан класс Order, представляющий заказ;
Создан enum OrderStatus;
Создан класс OrderProcessor с методами processAllOrders, processOrder, который управляет обработкой заказов

BJS2-50209: Собираем заказы в Amazon

---

src/main/java/school/faang/task_50976/Main.java
src/main/java/school/faang/task_50976/School.java
src/main/java/school/faang/task_50976/Student.java
src/main/java/school/faang/task_50976/Task.java
src/main/java/school/faang/task_50976/Tournament.java

Помогите найти ошибку. Не выводиться в консоль информация.

BJS2-50976: Турнир трех волшебников

---

src/main/java/derschrank/sprint04/task10/bjstwo_50592/Main.java
src/main/java/derschrank/sprint04/task10/bjstwo_50592/PairToFight.java
src/main/java/derschrank/sprint04/task10/bjstwo_50592/Superhero.java
src/main/java/derschrank/sprint04/task10/bjstwo_50592/SuperheroBattle.java
src/main/java/derschrank/sprint04/task10/bjstwo_50592/SuperheroBattleService.java
src/main/java/derschrank/sprint04/task10/bjstwo_50592/info.txt

Superheroes battle
derschrank2000-S04-T10-BJS2-50592
derschrank.sprint04.task10.bjstwo_50592
Sprint04. Task10. Future. Superheroes battle
--------------------
Superheroes battle
👩‍💻 🧠🧠 (Дополнительная задача)
Условия задачи
Вы являетесь разработчиком системы для анализа силы супергероев Marvel. Вам нужно создать систему, которая будет асинхронно проводить сражения между супергероями в парах и определять победителей. Для этого необходимо использовать ExecutorService и Future для асинхронного выполнения и сбора результатов соревнований.
Требования:
1️⃣ Создайте класс Superhero, который представляет супергероя. Поля:
name — имя супергероя,
strength — сила супергероя,
agility — ловкость супергероя.
2️⃣ Создайте класс SuperheroBattle с методом runCompetitions, который:
Принимает список пар …

BJS2-50592 Sprint04. Task10. Future. Superheroes battle

---

src/main/java/school/faang/Main.java
src/main/java/task_BJS2_56298/Main.java
src/main/java/task_BJS2_56298/User.java

Привет! 
Выполнил задачу:
https://faang-school.atlassian.net/browse/BJS2-56298
Просьба провести ревью
Спасибо!

BJS2-56298: Группировка пользователей по возрасту

---

src/main/java/school/faang/User.java

BJS2-56335

---

src/main/java/school/faang/User.java
src/test/java/school/faang/UserTest.java
src/test/java/shcool/faang/UserTest.java

Task:
https://faang-school.atlassian.net/browse/BJS2-56292
What was done:
- completed solution according to full requirements 
- unit tests
- improvements

Lexx117-BJS2-56292 Collections of users

---

src/main/java/task_BJS2_56332/Main.java
src/main/java/task_BJS2_56332/User.java

Привет!
Выполнил задачу:
https://faang-school.atlassian.net/browse/BJS2-56332
Просьба провести ревью
Спасибо!

BJS2-56332: Регистрация пользователей

---

src/main/java/school/faang/usercollection/Main.java
src/main/java/school/faang/usercollection/User.java
src/test/java/UserTest.java

subtask BJS2-56299:
Коллекционируем пользователей

subtask BJS2-56299

---

src/main/java/school/faang/Main.java
src/main/java/users/groups/Main.java
src/main/java/users/groups/User.java

lauralomberg-BJS2-56302

---

src/main/java/school/faang/User.java

*Change field name
*Add getters
*Add JavaDoc
*Replace String on StringBuilder

1ilyaaaaa1-BJS2-56335

---

src/main/java/school/faang/groupusers/Main.java
src/main/java/school/faang/groupusers/User.java

subtask BJS2-56343

---

src/main/java/toska27_BJS2_56980/Book.java
src/main/java/toska27_BJS2_56980/LibrarySystem.java
src/main/java/toska27_BJS2_56980/Main.java

Привет!
Выполнил задачу: https://faang-school.atlassian.net/browse/BJS2-56980
прошу проверить
спасибо!

BJS2-56980: Библиотека Вестеросса

---

src/main/java/task_BJS2_56366/Archer.java
src/main/java/task_BJS2_56366/Character.java
src/main/java/task_BJS2_56366/Main.java
src/main/java/task_BJS2_56366/Warrior.java

Привет!
Выполнил задачу: https://faang-school.atlassian.net/browse/BJS2-56366
Спасибо!

BJS2_56366: Абстракция, абстракция!

---

src/main/java/abstraction/Archer.java
src/main/java/abstraction/Character.java
src/main/java/abstraction/Main.java
src/main/java/abstraction/Warrior.java

lauralomberg-BJS2-56316

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/abstraction/Archer.java
src/main/java/school/faang/abstraction/Character.java
src/main/java/school/faang/abstraction/Main.java
src/main/java/school/faang/abstraction/Warrior.java

Выполнил свою первую задачу из спринта "Абстракция".

Implemented task about abstractions

---

src/main/java/school/faang/user/registration/User.java

Регистрация пользователей - BJS2-56466

Amanzhol.tanat bjs2 56466

---

src/main/java/school/faang/usergrouping/User.java

Группировка пользователей по возрасту - BJS2-56403

Группировка пользователей по возрасту - BJS2-56403

---

src/main/java/school/faang/agegrouping/Main.java
src/main/java/school/faang/agegrouping/User.java

BJS2-56347

---

src/main/java/school/faang/sprint/first/character/Main.java
src/main/java/school/faang/sprint/first/character/model/Archer.java
src/main/java/school/faang/sprint/first/character/model/Character.java
src/main/java/school/faang/sprint/first/character/model/Warrior.java
src/main/java/school/faang/sprint/first/collectingusers/Main.java
src/main/java/school/faang/sprint/first/collectingusers/model/User.java
src/main/java/school/faang/sprint/first/groupbyage/model/User.java
src/main/java/school/faang/sprint/first/model/User.java

Я перепутал ключи задач и поэтому одна задача делается в рамках другой... Этот ПР для таски https://faang-school.atlassian.net/browse/BJS2-56330.

Takewqa bjs2 56394

---

src/main/java/bjs256438/Main.java
src/main/java/bjs256438/User.java

Создан класс User, в котором статический метод groupUsers. Метод принимает List из объектов User и возвращает Map, где ключом является возраст пользователя, а значением — список из всех пользователей в оригинальном списке, которые имеют соответствующий возраст.

BJS2-56438

---

src/main/java/task_BJS2_57002/HogwartsSpells.java
src/main/java/task_BJS2_57002/Main.java
src/main/java/task_BJS2_57002/SpellEvent.java

Привет!
Выполнил задачу https://faang-school.atlassian.net/browse/BJS2-57002
прошу проверить
спасибо!

BJS2-57002: Ловим события

---

src/main/java/school/faang/BJS2_56482/Main.java
src/main/java/school/faang/BJS2_56482/User.java
src/main/java/school/faang/Main.java

Artur30052009 bjs2 56482

---

src/main/java/school/faang/spring1/basicjava/userregistration/Main.java
src/main/java/school/faang/spring1/basicjava/userregistration/User.java

task: user registration

---

src/main/java/school/faang/Book.java
src/main/java/school/faang/LibrarySystem.java
src/main/java/school/faang/Main.java

Не знаю есть ли смысл добавлять try\catch в findBook , вроде и getOrDefault подходит в этом методе

BJS2-57032

---

build.gradle
src/main/java/school/faang/sprint/first/cachecache/Main.java
src/main/java/school/faang/sprint/first/cachecache/db/StudentDatabase.java
src/main/java/school/faang/sprint/first/cachecache/model/Student.java
src/main/java/school/faang/sprint/first/cachecache/model/Subject.java
src/test/java/scool/faang/sprint/first/cachecache/db/StudentDatabaseTest.java

Я никогда не понимал как тестировать void методы, поэтому не написал для них тесты(

BJS2-56919 Двойной кэш-кэш

---

src/main/java/bjs256504/User.java
src/main/java/bjs256504/UserConstructorValidator.java

Создан класс User с конструктором, который принимает значения для всех полей и выполняет валидацию входных данных.

BJS2-56504

---

src/main/java/library/Book.java
src/main/java/library/LibrarySystem.java
src/main/java/library/Main.java

lauralomberg-BJS2-57009

---

src/main/java/school/faang/groupUsers/Main.java
src/main/java/school/faang/groupUsers/User.java

Идея ругает на название пакета groupUsers, но в инструкциях просили под каждую задачу свой пакет создавать.  Может их называть маленькими буквами, а не верблюжьей нотацией?

create class User and method groupUsers by age

---

src/main/java/bjs257097/Book.java
src/main/java/bjs257097/LibrarySystem.java
src/main/java/bjs257097/Main.java

Созданы классы Book, LibrarySystem, проверена правильность работы методов в LibrarySystem. Класс Book дополнительно аннотирован @ToString, чтобы в консоль выводилась информация о книгах в читабельном виде

BJS2-57097

---

src/main/java/game/Archer.java
src/main/java/game/Character.java
src/main/java/game/Game.java
src/main/java/game/Warrior.java
src/test/java/game/GameTest.java

task:
https://faang-school.atlassian.net/browse/BJS2-56376

Game prototype has been completed

---

src/main/java/school/faang/BJS2_58634/Archer.java
src/main/java/school/faang/BJS2_58634/Character.java
src/main/java/school/faang/BJS2_58634/Main.java
src/main/java/school/faang/BJS2_58634/Warrior.java
src/main/java/school/faang/Main.java

я сделал простенкую игру с добавлением Random (просто было скучно наблюдать как они оба умерали из за того что они наносили одинаковый урон друг другу... (надеюсь зацените :)

задача "Абстракция абстракция !"

---

src/main/java/school/faang/westeroslibrary/Book.java
src/main/java/school/faang/westeroslibrary/LibrarySystem.java
src/main/java/school/faang/westeroslibrary/Main.java

BJS2-57112

---

src/main/java/school/faang/BJS2_57129/Book.java
src/main/java/school/faang/BJS2_57129/LibrarySystem.java
src/main/java/school/faang/BJS2_57129/Main.java

bjs2 57129

---

src/main/java/marketplace/Category.java
src/main/java/marketplace/Main.java
src/main/java/marketplace/Product.java
src/main/java/marketplace/ProductManager.java

lauralomberg-BJS2-57013

---

src/main/java/school/faang/sorting_out_amazons_warehouse/BJS2_56958/Category.java
src/main/java/school/faang/sorting_out_amazons_warehouse/BJS2_56958/Main.java
src/main/java/school/faang/sorting_out_amazons_warehouse/BJS2_56958/Product.java
src/main/java/school/faang/sorting_out_amazons_warehouse/BJS2_56958/ProductManager.java

1. Создан класс Product
2. Создан класс Category
3. Создан класс ProductManager с методами addProduct, removeProduct, findProductsByCategory, groupProductsByCategory, printAllProducts
4. Тестирование сделанно в main

BJS2-56958

---

src/main/java/school/faang/model/Booking.java
src/main/java/school/faang/model/Room.java
src/main/java/school/faang/observer/BookingNotifier.java
src/main/java/school/faang/observer/BookingObserver.java
src/main/java/school/faang/service/Admin.java
src/main/java/school/faang/service/BookingSystem.java
src/test/java/school/faang/service/BookingSystemTest.java

Task:
https://faang-school.atlassian.net/browse/BJS2-57008

completed booking service

---

src/main/java/task_BJS2_56972/Category.java
src/main/java/task_BJS2_56972/Main.java
src/main/java/task_BJS2_56972/Product.java
src/main/java/task_BJS2_56972/ProductManager.java

Привет!
Выполнил задачу: https://faang-school.atlassian.net/browse/BJS2-56972
Просьба проверить
Спасибо!

BJS2-56972: Разбираем склад Amazon

---

src/main/java/school/faang/task56471/Main.java
src/main/java/school/faang/task56471/User.java

https://faang-school.atlassian.net/browse/BJS2-56471

BJS2-56471 Группировка пользователей по возрасту

---

src/main/java/school/faang/library/Book.java
src/main/java/school/faang/library/LibrarySystem.java
src/main/java/school/faang/library/Main.java

Задача BJS2-57174 выполнена

---

src/main/java/school/faang/BJS2_56433/Main.java
src/main/java/school/faang/BJS2_56433/User.java
src/main/java/school/faang/Main.java

Tibareal17 bjs2 56433

---

src/main/java/school/faang/catchingEvents/HogwartsSpells.java
src/main/java/school/faang/catchingEvents/Main.java
src/main/java/school/faang/catchingEvents/SpellEvent.java

Задача BJS2-57169 выполнена

---

src/main/java/school/faang/amazon/Category.java
src/main/java/school/faang/amazon/Mai.java
src/main/java/school/faang/amazon/Main.java
src/main/java/school/faang/amazon/Product.java
src/main/java/school/faang/amazon/ProductManager.java

Задача BJS2-57054 выполнена

---

src/main/java/school/faang/caching/FrequentUpdateWeatherCache.java
src/main/java/school/faang/caching/StandardWeatherCache.java
src/main/java/school/faang/caching/WeatherCacheTemplate.java
src/main/java/school/faang/caching/WeatherData.java
src/main/java/school/faang/caching/WeatherProvider.java
src/main/java/school/faang/caching/WeatherService.java
src/test/java/school/faang/caching/FrequentUpdateWeatherCacheTest.java
src/test/java/school/faang/caching/StandardWeatherCacheTest.java
src/test/java/school/faang/caching/WeatherCashTemplateTest.java
src/test/java/school/faang/caching/WeatherServiceTest.java

test have been written and passed

cache system for the weather has been done

---

src/main/java/school/faang/task_56505/Main.java
src/main/java/school/faang/task_56505/User.java

BJS2-56505

---

src/main/java/school/faang/horwarts/Main.java
src/main/java/school/faang/horwarts/SpellAction.java
src/main/java/school/faang/horwarts/SpellCaster.java

cast gets the string with the name of the spell and lambda-expression describing the action

SpellCaster has been made

---

src/main/java/school/faang/task_57021/Category.java
src/main/java/school/faang/task_57021/Main.java
src/main/java/school/faang/task_57021/Product.java
src/main/java/school/faang/task_57021/ProductManager.java

Разбираем склад Amazon

---

src/main/java/translator/DictionaryProcessingException.java
src/main/java/translator/DictionaryProcessor.java
src/test/java/translator/DictionaryProcessorTest.java

Task:
https://faang-school.atlassian.net/browse/BJS2-57082

Completed Sprint-2 Google translator task

---

src/main/java/school/faang/abstraction/Archer.java
src/main/java/school/faang/abstraction/Character.java
src/main/java/school/faang/abstraction/Main.java
src/main/java/school/faang/abstraction/Warrior.java

BJS2-56468

---

src/main/java/school/faang/catchingevents/HogwartsSpells.java
src/main/java/school/faang/catchingevents/Main.java
src/main/java/school/faang/catchingevents/SpellEvent.java

BJS2-57179

---

src/main/java/school/faang/task_57280/Book.java
src/main/java/school/faang/task_57280/LibraryMap.java
src/main/java/school/faang/task_57280/Main.java

Библиотека вестероса
Использовал аннотации ломбок, однако тем не менее запустил compile.java и в папке build изучил как выглядят используемые hashCode и equals, проверил работу всех методов.

BJS2-57280

---

src/main/java/task_BJS2_57276/Main.java
src/main/java/task_BJS2_57276/SpellAction.java
src/main/java/task_BJS2_57276/SpellCaster.java

Привет!
Выполнил задачу: https://faang-school.atlassian.net/browse/BJS2-57276
прошу проверить
Спасибо!

BJS2-57276: Хогвартс, Хогвартс, наш любимый Хогвартс

---

src/main/java/school/faang/hogwarts/Main.java
src/main/java/school/faang/hogwarts/SpellAction.java
src/main/java/school/faang/hogwarts/SpellCaster.java
src/main/java/school/faang/hogwarts/Spells.java

Решение Задачи

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/task_56528/Archer.java
src/main/java/school/faang/task_56528/Character.java
src/main/java/school/faang/task_56528/Main.java
src/main/java/school/faang/task_56528/Warrior.java

Абстракция, абстракция!
Настроил конструкторы для всех классов, учёл факт, что здоровье не может быть меньше нуля, провёл проверку на созданных в мэйне экземплярах классов.

BJS2-56528

---

src/main/java/school/faang/BJS2_58448/Main.java
src/main/java/school/faang/BJS2_58448/User.java
src/main/java/school/faang/Main.java

Коллекционируем пользователей 58448

---

src/main/java/school/faang/task57219/Main.java
src/main/java/school/faang/task57219/library/Book.java
src/main/java/school/faang/task57219/library/LibrarySystem.java

https://faang-school.atlassian.net/browse/BJS2-57219

BJS2-57219 Библиотека Вестеросса

---

src/main/java/university/Main.java
src/main/java/university/Student.java
src/main/java/university/StudentDatabase.java
src/main/java/university/Subject.java

lauralomberg-BJS2-57012

---

src/main/java/spell/Main.java
src/main/java/spell/SpellAction.java
src/main/java/spell/SpellCaster.java

lauralomberg-BJS2-57305

---

src/main/java/task_BJS2_57679/FilterProcessor.java
src/main/java/task_BJS2_57679/Image.java
src/main/java/task_BJS2_57679/Main.java

Привет!
Выполнил задачу: https://faang-school.atlassian.net/browse/BJS2-57679
Спасибо!

BJS2-57679: Фильтры Instagram

---

src/main/java/instagram/FilterProcessor.java
src/main/java/instagram/Image.java
src/main/java/instagram/Main.java

lauralomberg-BJS2-57890

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/task_56587/Main.java
src/main/java/school/faang/task_56587/User.java

BJS2-56587
Регистрация пользователей

BJS2-56587

---

src/main/java/school/faang/task_BJS2_56323/Main.java
src/main/java/school/faang/task_BJS2_56323/User.java

Уфф, первый PR на буткемпе, поехали)!
Выполнение задачи BJS2-56323 (Коллекционируем пользователей).

Выполнение задачи BJS2-56323 (Коллекционируем пользователей)

---

META-INF/MANIFEST.MF
src/main/java/bjs256991/Main.java
src/main/java/bjs256991/Student.java
src/main/java/bjs256991/StudentDatabase.java
src/main/java/bjs256991/Subject.java
src/main/resources/META-INF/MANIFEST.MF
src/test/java/bjs256991test/StudentDatabaseTest.java

Добавлены тестовые классы, класс Main и файл MANIFEST.MF 
Создан модуль для тестирования, добавлена Test Source директория java.
Main нужен для того, чтобы указать его главным классом при добавлении файла jar в артефакты 
( File -> Project Structure -> Artifacts -> + -> JAR -> From modules with dependencies). 
Файл jar нужен, чтобы связать тестовые классы с проектом: при сборке в директории build будет создана директория libs c соответствующим jar файлом. 
Протестированы специальные методы StudentDatabase, кроме вывода в консоль printAllStudents и printAllSubjects, там вывод из логгера, который протестировать проблемно

BJS2-56991

---

src/main/java/bjs256951/Category.java
src/main/java/bjs256951/Main.java
src/main/java/bjs256951/Product.java
src/main/java/bjs256951/ProductManager.java

В классе ProductManager
реализованы методы:
addProduct(Category category, String name);
removeProduct(Category category, String name);
findProductsByCategory(Category category);
groupProductsByCategory();
printAllProducts();

BJS2-56951

---

src/main/java/bjs257119/HogwartsSpells.java
src/main/java/bjs257119/Main.java
src/main/java/bjs257119/SpellEvent.java

Реализваны методы в классе HogwartsSpells:
addSpellEvent(String eventType, 
String actionDescription);
getSpellEventById(int id);
getSpellEventsByType(String eventType);
deleteSpellEvent(int id);
printAllSpellEvents();

BJS2-57119

---

src/main/java/bjs256450/Archer.java
src/main/java/bjs256450/Character.java
src/main/java/bjs256450/Main.java
src/main/java/bjs256450/Warrior.java

Создан базовый класс Character и классы-наследники Warrior, Archer. В переопределённых методах attack применяется метод isHealthNotLessThanZero, который проверяет, чтобы значение поля health было неотрицательной величиной

BJS2-56450

---

src/main/java/listoperations/ListOperations.java
src/main/java/listoperations/Main.java
src/test/java/listoperations/ListOperationsTest.java

task:
https://faang-school.atlassian.net/browse/BJS2-58149

BJS2-58149 Completed ListOperations task 

---

.gitignore
src/main/java/school/faang/gmail/Email.java
src/main/java/school/faang/gmail/EmailProcessor.java
src/main/java/school/faang/gmail/Main.java

Used Predicate<Email> to filter, Funcltion<Email, String> to convert, Consumer<Email> to handle

EmailProcessor created

---

src/main/java/school/faang/metauniverse/Main.java
src/main/java/school/faang/metauniverse/Notification.java
src/main/java/school/faang/metauniverse/NotificationManager.java
src/main/java/school/faang/metauniverse/NotificationType.java

filtration added
corrector added
В целом сделал по заданию, но дополнительных расширений придумать не смог
Пока не хватает насмотренности
Думал об отложенной отправке сообщений, но будто там хочется использовать многопоточность, а пока в ней плаваю

NotificationManager created

---

src/main/java/notifications/Main.java
src/main/java/notifications/Notification.java
src/main/java/notifications/NotificationManager.java
src/main/java/notifications/NotificationType.java

lauralomberg-BJS2-57802

---

src/main/java/task_BJS2_56980/Book.java
src/main/java/task_BJS2_56980/LibrarySystem.java
src/main/java/task_BJS2_56980/Main.java
src/main/java/task_BJS2_57435/Character.java
src/main/java/task_BJS2_57435/InventoryManager.java
src/main/java/task_BJS2_57435/Item.java
src/main/java/task_BJS2_57435/Main.java

Привет!
Выполнил задачу: https://faang-school.atlassian.net/browse/BJS2-57435
Спасибо!

BJS2-57435: Lord of the Rings RPG

---

src/main/java/school/faang/Archer.java
src/main/java/school/faang/Character.java
src/main/java/school/faang/Main.java
src/main/java/school/faang/Warrior.java

Вопрос важно ли расставлять классы по порядку в идее? (чтобы сначала шёл main, затем character и тд)  Если да, то как это сделать?

Выполнение задачи "Абстракция, абстракция!"

---

src/main/java/school/faang/BJS2_56484/Archer.java
src/main/java/school/faang/BJS2_56484/Character.java
src/main/java/school/faang/BJS2_56484/Main.java
src/main/java/school/faang/BJS2_56484/Warrior.java
src/main/java/school/faang/Main.java

Version 3
Персонаж атакует оппонента, у оппонента уменьшается HP, когда здоровье будет 0 программа сообщает о том что оппонент повержен.

Tibareal17 bjs2 56484

---

src/main/java/bjs257422/Alphabet.java
src/main/java/bjs257422/Droid.java
src/main/java/bjs257422/DroidMessageEncryptor.java
src/main/java/bjs257422/Main.java

Для удобства итерации, сообщения
переведены из String в char[].
Проводится сверка каждого символа,
является ли буквой, если да,
то строчной или заглавной.
В процессе шифрования и дешифрования
определяется индекс в Enum и буква,
которым будет соответствовать каждый символ сообщения

BJS2-57422

---

src/main/java/school/faang/caching_caching/BJS2_56894/FrequentUpdateWeatherCache.java
src/main/java/school/faang/caching_caching/BJS2_56894/StandardWeatherCache.java
src/main/java/school/faang/caching_caching/BJS2_56894/WeatherCacheTemplate.java
src/main/java/school/faang/caching_caching/BJS2_56894/WeatherData.java
src/main/java/school/faang/caching_caching/BJS2_56894/WeatherProvider.java
src/main/java/school/faang/caching_caching/BJS2_56894/WeatherService.java
src/test/java/school/faang/caching_caching/BJS2_56894/FrequentUpdateWeatherCacheTest.java
src/test/java/school/faang/caching_caching/BJS2_56894/StandardWeatherCacheTest.java
src/test/java/school/faang/caching_caching/BJS2_56894/WeatherServiceTest.java

1. Создан класс WeatherData
2. Создан интерфейс WeatherProvider с методом fetchWeatherData
3. Создан класс WeatherService реализацией fetchWeatherData
4. Создан абстрактный класс WeatherCacheTemplate с методами getWeatherData, updateWeatherData, clearExpiredCache, абстрактный isCacheExpired
5. Созданы подклассы StandardWeatherCache, FrequentUpdateWeatherCache

BJS2-56894

---

src/main/java/school/faang/task56515/Main.java
src/main/java/school/faang/task56515/character/Archer.java
src/main/java/school/faang/task56515/character/Character.java
src/main/java/school/faang/task56515/character/Warrior.java

https://faang-school.atlassian.net/browse/BJS2-56515

BJS2-56515 Абстракция, абстракция!

---

src/main/java/school/faang/task57094/Main.java
src/main/java/school/faang/task57094/warehouse/Category.java
src/main/java/school/faang/task57094/warehouse/Product.java
src/main/java/school/faang/task57094/warehouse/ProductManager.java

https://faang-school.atlassian.net/browse/BJS2-57094

BJS2-57094 Разбираем склад Amazon

---

src/main/java/school/faang/task57079/Main.java
src/main/java/school/faang/task57079/student/Student.java
src/main/java/school/faang/task57079/student/StudentDatabase.java
src/main/java/school/faang/task57079/student/Subject.java

https://faang-school.atlassian.net/browse/BJS2-57079

BJS2-57079 Двойной кэш-кэш

---

src/main/java/school/faang/task57212/Main.java
src/main/java/school/faang/task57212/spells/HogwartsSpells.java
src/main/java/school/faang/task57212/spells/SpellEvent.java

https://faang-school.atlassian.net/browse/BJS2-57212

BJS2-57212 Ловим события

---

src/main/java/school/faang/task56921/Main.java
src/main/java/school/faang/task56921/weather/FrequentUpdateWeatherCache.java
src/main/java/school/faang/task56921/weather/StandardWeatherCache.java
src/main/java/school/faang/task56921/weather/WeatherCacheTemplate.java
src/main/java/school/faang/task56921/weather/WeatherData.java
src/main/java/school/faang/task56921/weather/WeatherProvider.java
src/main/java/school/faang/task56921/weather/WeatherService.java

https://faang-school.atlassian.net/browse/BJS2-56921

BJS2-56921 Кэшируем, кэшируем

---

src/main/java/school/faang/spring1/basicjava/collectingusers/Main.java
src/main/java/school/faang/spring1/basicjava/collectingusers/User.java

task: user hobbies

---

src/main/java/school/faang/khogvarts/Main.java
src/main/java/school/faang/khogvarts/SpellAction.java
src/main/java/school/faang/khogvarts/SpellCaster.java
src/main/java/school/faang/khogvarts/SpellConstants.java

Задача BJS2-57356 выполнена.

---

src/main/java/BJS257244/Email.java
src/main/java/BJS257244/EmailProcessor.java
src/main/java/BJS257244/Main.java

добавил условие в метод processEmails
вывод и изменение регистра происходят если письмо важное

1ilyaaaaa1-BJS2-57244

---

src/main/java/task_BJS2_57697/Main.java
src/main/java/task_BJS2_57697/Notification.java
src/main/java/task_BJS2_57697/NotificationManager.java
src/main/java/task_BJS2_57697/NotificationType.java

Привет!
Выполнил задачу: https://faang-school.atlassian.net/browse/BJS2-57697
Спасибо!

BJS2-57697: Meta-вселенная?

---

src/main/java/school/faang/firsttrainofstream/ListOperations.java
src/main/java/school/faang/firsttrainofstream/Main.java

Возникают пока у меня проблемы с проверкой на null в аргументах
Стараюсь контролировать за собой
В текущей таске будто все окей, но если в этом плане будут доп комментарии, буду рад услышать, чтобы искоренить проблему

List of operations created with NPE check

---

src/main/java/streamapi2/StreamOperations2.java
src/test/java/streamapi2/StreamOperations2Test.java

task:
https://faang-school.atlassian.net/browse/BJS2-57797

Task BJS2-57797 completed

---

src/main/java/streamapi3/Employee.java
src/main/java/streamapi3/StreamOperations3.java
src/test/java/streamapi3/StreamOperations3Test.java

task:
https://faang-school.atlassian.net/browse/BJS2-57841

BJS2-57841 Completed task

---

src/main/java/school/faang/doubleCash/Student.java
src/main/java/school/faang/doubleCash/StudentDatabase.java
src/main/java/school/faang/doubleCash/Subject.java
src/test/java/school/faang/doubleCash/StudentDatabaseTest.java

Задача BJS2-56913 выполнена.

---

src/main/java/school/faang/meta_universe/BJS2_57812/Notification.java
src/main/java/school/faang/meta_universe/BJS2_57812/NotificationManager.java
src/main/java/school/faang/meta_universe/BJS2_57812/NotificationType.java
src/test/java/school/faang/meta_universe/BJS2_57812/NotificationManagerTest.java
src/test/java/school/faang/meta_universe/BJS2_57812/NotificationTest.java

1. Создан класс Notification
2. Создан класс NotificationManager с методами registerHandler, sendNotification, filtering, addSender

BJS2-57812

---

src/main/java/gmail/Email.java
src/main/java/gmail/EmailProcessor.java
src/main/java/gmail/Main.java

lauralomberg-BJS2-57390

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/User.java

Выполнение задачи от kalenteenkovalexander2586

BJS2-58505-Группировка-пользователей-по-возрасту

---

src/main/java/instagram/FilterProcessor.java
src/main/java/instagram/Image.java
src/main/java/instagram/Main.java
src/test/java/instagram/FilterProcessorTest.java

task:
https://faang-school.atlassian.net/browse/BJS2-57783

Task BJS2-57783

---

.gitignore
src/main/java/school/faang/secondstreamtraining/Main.java
src/main/java/school/faang/secondstreamtraining/StreamOperations.java
src/main/resources/logback.xml

В целом вопросов не осталось
Если только совет потенциально нужен: есть ли какой-то более универсальный способ проверки NullPoinerException
Стараюсь следовать DRY, но как будто местами можно еще лучше оптимизировать, но не понимаю как

Methods with stream operations created

---

src/main/java/school/faang/lord_of_the_rings_rpg/BJS2_57552/Character.java
src/main/java/school/faang/lord_of_the_rings_rpg/BJS2_57552/InventoryManager.java
src/main/java/school/faang/lord_of_the_rings_rpg/BJS2_57552/Item.java
src/test/java/school/faang/lord_of_the_rings_rpg/BJS2_57552/InventoryManagerTest.java
src/test/java/school/faang/lord_of_the_rings_rpg/BJS2_57552/ItemTest.java

1. Создан класс Item и Character
2. Создан класс InventoryManager с методами addItem, removeItem, updateItem.

BJS2-57552

---

src/main/java/bjs257813/FilterProcessor.java
src/main/java/bjs257813/Image.java
src/main/java/bjs257813/Main.java

BJS2-57813

---

src/main/java/bjs257481/Main.java
src/main/java/bjs257481/SpellAction.java
src/main/java/bjs257481/SpellCaster.java

BJS2-57481

---

src/main/java/bjs258257/ListOperations.java
src/main/java/bjs258257/Main.java

BJS2-58257

---

src/main/java/task_BJS2_60546/ListOperations.java
src/main/java/task_BJS2_60546/Main.java

Привет!
Выполнил задачу: https://faang-school.atlassian.net/browse/BJS2-60546
Спасибо!

BJS2-60546: Потренируем StreamAPI 1

---

src/main/java/bjs257886/Main.java
src/main/java/bjs257886/TaskStreamApi.java

BJS2-57886

---

src/main/java/bjs257436/Email.java
src/main/java/bjs257436/EmailProcessor.java
src/main/java/bjs257436/Main.java

Сделан фильтр, обработчик, преобразователь писем

BJS2-57436

---

src/main/java/school/faang/task57453/Main.java
src/main/java/school/faang/task57453/filter/Email.java
src/main/java/school/faang/task57453/filter/EmailProcessor.java

https://faang-school.atlassian.net/browse/BJS2-57453

BJS2-57453 Gmail Rich Filters

---

src/main/java/bjs257936/Main.java
src/main/java/bjs257936/Notification.java
src/main/java/bjs257936/NotificationManager.java
src/main/java/bjs257936/NotificationType.java

BJS2-57936

---

src/main/java/school/faang/outlook/MailSender.java
src/main/java/school/faang/outlook/SenderRunnable.java

Так как создание new Thread - ресурсоемкая операция, немного отошел от ТЗ и сделал через ThreadPool

MailSender done

---

src/main/java/school/faang/bjs2_57888/Main.java
src/main/java/school/faang/bjs2_57888/Notification.java
src/main/java/school/faang/bjs2_57888/NotificationManager.java
src/main/java/school/faang/bjs2_57888/NotificationType.java

created classes Notification, NotificationManager, NotificationType. Add methods registerHandler and sendNotification

BJS2-57888 

---

src/main/java/school/faang/instagram_filters/BJS2_57744/FilterProcessor.java
src/main/java/school/faang/instagram_filters/BJS2_57744/Image.java
src/test/java/school/faang/instagram_filters/BJS2_57744/FilterProcessorTest.java
src/test/java/school/faang/instagram_filters/BJS2_57744/ImageTest.java

1. Создан класс Image
2. Создан класс FilterProcessor с методами applyFilter и combineFilters

BJS2-57744

---

src/main/java/school/faang/doublecash/Student.java
src/main/java/school/faang/doublecash/StudentDatabase.java
src/main/java/school/faang/doublecash/Subject.java
src/test/java/school/faang/doublecash/StudentDatabaseTest.java

tests have been written for all the methods

database has been created

---

src/main/java/school/faang/task57565/Main.java
src/main/java/school/faang/task57565/game/Character.java
src/main/java/school/faang/task57565/game/InventoryManager.java
src/main/java/school/faang/task57565/game/Item.java

https://faang-school.atlassian.net/browse/BJS2-57565

BJS2-57565 Lord of the Rings RPG

---

src/main/java/school/faang/task57532/Main.java
src/main/java/school/faang/task57532/spell/SpellAction.java
src/main/java/school/faang/task57532/spell/SpellCaster.java

https://faang-school.atlassian.net/browse/BJS2-57532

BJS2-57532 Хогвартс, Хогвартс, наш любимый Хогвартс

---

src/main/java/school/faang/task57954/Main.java
src/main/java/school/faang/task57954/notification/Notification.java
src/main/java/school/faang/task57954/notification/NotificationManager.java
src/main/java/school/faang/task57954/notification/NotificationType.java
src/main/java/school/faang/task57954/notification/WordFilter.java

https://faang-school.atlassian.net/browse/BJS2-57954

BJS2-57954 Meta-вселенная?

---

src/main/java/school/faang/task58319/ListOperations.java
src/main/java/school/faang/task58319/Main.java

https://faang-school.atlassian.net/browse/BJS2-58319

BJS2-58319 Потренируем StreamAPI 1

---

src/main/java/school/faang/ActionType.java
src/main/java/school/faang/UserAction.java
src/main/java/school/faang/UserActionAnalyzer.java

BJS2-58043

---

src/main/java/school/faang/task57829/Main.java
src/main/java/school/faang/task57829/instagram/FilterProcessor.java
src/main/java/school/faang/task57829/instagram/Image.java

https://faang-school.atlassian.net/browse/BJS2-57829

BJS2-57829 Фильтры Instagram

---

src/main/java/school/faang/bjs2_59715/Character.java
src/main/java/school/faang/bjs2_59715/InventoryManager.java
src/main/java/school/faang/bjs2_59715/Item.java
src/main/java/school/faang/bjs2_59715/Main.java

…ed methods addItems, removeItem, updateItem

bjs2 59715

---

src/main/java/school/faang/droid_secrets/BJS2_57606/Droid.java
src/main/java/school/faang/droid_secrets/BJS2_57606/DroidMessageDecoder.java
src/main/java/school/faang/droid_secrets/BJS2_57606/DroidMessageEncryptor.java
src/main/java/school/faang/droid_secrets/BJS2_57606/Main.java

1. Создан интерфейс DroidMessageEncryptor с методом encrypt.
2. Создан класс Droid с методами sendMessage, receiveMessage, encryptMessage, decryptMessage.

BJS2-57606

---

src/main/java/school/faang/handling_mistakes_beautifully/BJS2_57733/ErrorHandler.java
src/main/java/school/faang/handling_mistakes_beautifully/BJS2_57733/ExceptionHandler.java
src/main/java/school/faang/handling_mistakes_beautifully/BJS2_57733/Main.java

1. Создан класс ErrorHandler с методом withErrorHandling.
2. Создан функциональный интерфейс ExceptionHandler с методом handle

BJS2-57733

---

src/main/java/school/faang/task57988/Main.java
src/main/java/school/faang/task57988/Operations.java

https://faang-school.atlassian.net/browse/BJS2-57988

BJS2-57988 Потренируем StreamAPI 2

---

src/main/java/school/faang/lets_practice_streamAPI_1/BJS2_58330/ListOperations.java
src/main/java/school/faang/lets_practice_streamAPI_1/BJS2_58330/Main.java

Создан класс ListOperations с методами sumOfEvenNumbers, findMax, findAverage, countStringsStartingWith, filterStringsContainingSubstring, sortByLength, allMatchCondition, findMinGreaterThan, convertToLengths.

BJS2-58330

---

src/main/java/bjs260443/MailSender.java
src/main/java/bjs260443/SenderRunnable.java

Созданы Threads для обработки писем

BJS2-60443

---

src/main/java/BJS258102/ActionService.java
src/main/java/BJS258102/ActionType.java
src/main/java/BJS258102/Main.java
src/main/java/BJS258102/UserAction.java

как то немного усложнил сам себе ...

BJS2-58102 init

---

src/main/java/task_BJS2_60559/MailSender.java
src/main/java/task_BJS2_60559/SenderRunnable.java

Привет!
Выполнил задачу: https://faang-school.atlassian.net/browse/BJS2-60559
Спасибо!

BJS2-60559: Вы работаете в Microsoft!

---

src/main/java/bjs260693/Chore.java
src/main/java/bjs260693/Main.java
src/main/java/bjs260693/WeasleyFamily.java

Распределение задач в виде объектов Chore в Executors.newCachedThreadPool()

BJS2-60693

---

src/main/java/bjs261069/Archer.java
src/main/java/bjs261069/Army.java
src/main/java/bjs261069/Fighter.java
src/main/java/bjs261069/Mage.java
src/main/java/bjs261069/Main.java
src/main/java/bjs261069/PowerCalculator.java
src/main/java/bjs261069/Squad.java
src/main/java/bjs261069/Swordsman.java

Распараллелены потоки для вызова calculateSquadPower

BJS2-61069

---

src/main/java/school/faang/supercow/BJS2_61566/Boss.java
src/main/java/school/faang/supercow/BJS2_61566/Main.java
src/main/java/school/faang/supercow/BJS2_61566/Player.java

1. Создан класс Boss с методами joinBattle, leaveBattle.
2. Создан рекорд Player с методом doBattle.

BJS2-61566

---

src/main/java/school/faang/task58120/ActionType.java
src/main/java/school/faang/task58120/Main.java
src/main/java/school/faang/task58120/UserAction.java
src/main/java/school/faang/task58120/UserActionAnalyzer.java

https://faang-school.atlassian.net/browse/BJS2-58120

BJS2-58120 Анализ активности пользователей в социальной сети

---

build.gradle
src/main/java/school/faang/Coordinates.java
src/main/java/school/faang/FlipDirection.java
src/main/java/school/faang/Matrix.java
src/main/java/school/faang/MatrixTransformer.java
src/test/java/MatrixTest.java

Также провел unit тесты (в enum FlipDirection добавил HORIZONTAL для теста на неподходящую flipDirection)

Задача Повернём матрицу

---

src/main/java/school/faang/a_distributed_army_of_sword_and_magic_heroes/BJS2_61166/Archer.java
src/main/java/school/faang/a_distributed_army_of_sword_and_magic_heroes/BJS2_61166/Army.java
src/main/java/school/faang/a_distributed_army_of_sword_and_magic_heroes/BJS2_61166/Fighter.java
src/main/java/school/faang/a_distributed_army_of_sword_and_magic_heroes/BJS2_61166/Mage.java
src/main/java/school/faang/a_distributed_army_of_sword_and_magic_heroes/BJS2_61166/Main.java
src/main/java/school/faang/a_distributed_army_of_sword_and_magic_heroes/BJS2_61166/Squad.java
src/main/java/school/faang/a_distributed_army_of_sword_and_magic_heroes/BJS2_61166/Swordsman.java

1. Созданы классы Fighter, Archer, Mage, Swordsman.
2. Создан класс Squad с методом calculateSquadPower.
3. Создан класс Army с методами addSquad, calculateTotalPower.

BJS2-61166

---

src/main/java/school/faang/sprint3/multithreading/bjs2_60900/Chore.java
src/main/java/school/faang/sprint3/multithreading/bjs2_60900/Main.java
src/main/java/school/faang/sprint3/multithreading/bjs2_60900/WeasleyFamily.java

initial commit task BJS2-60900

---

src/main/java/school/faang/verynicebut/Chore.java
src/main/java/school/faang/verynicebut/WeasleyFamily.java

try {
if (!service.awaitTermination(second, TimeUnit.SECONDS)) {
service.shutdownNow();
System.out.printf("Задачи не успели выполнится за %s секунд", second);
}
} catch (InterruptedException e) {
throw new RuntimeException(e.getMessage());
}
В случае ошибки стоит ли останавливать остальные потоки?

BJS2-60701 They were very nice but extremely poor

---

src/main/java/school/faang/armyheroes/Archer.java
src/main/java/school/faang/armyheroes/Army.java
src/main/java/school/faang/armyheroes/Heroes.java
src/main/java/school/faang/armyheroes/Mage.java
src/main/java/school/faang/armyheroes/Main.java
src/main/java/school/faang/armyheroes/Squad.java
src/main/java/school/faang/armyheroes/Swordsman.java

Что-то немного сложновато, но интересно)

BJS2-61116 Распределенная армия героев меча и магии

---

src/main/java/school/faang/bjs2_60463/MailSender.java
src/main/java/school/faang/bjs2_60463/SenderRunnable.java

Я намерено отступил от ТЗ в части запуска потоков через Thread и завершения с помощью thread.join(), на данном уровне я немного понимаю как работает многопоточка, в своей короткой карьере я как раз и занимался тем что писал сервис парсинга файлов с асинхронной и многопоточной обработкой)

BJS2-60463 is done.

---

build.gradle
src/main/java/bjs2_60493/MailSender.java
src/main/java/bjs2_60493/SenderRunnable.java

kalenteenkovalexander2586-BJS2-60493-Вы-работаете-в-Microsoft

---

src/main/java/task_BJS2_61139/Chore.java
src/main/java/task_BJS2_61139/WeasleyFamily.java

Привет!
Выполнил задачу: https://faang-school.atlassian.net/browse/BJS2-61139
Прошу проверить 
Спасибо!

BJS2-61139: They were very nice but extremely poor

---

src/main/java/task_BJS2_61403/Archer.java
src/main/java/task_BJS2_61403/Army.java
src/main/java/task_BJS2_61403/Character.java
src/main/java/task_BJS2_61403/CharacterType.java
src/main/java/task_BJS2_61403/Magician.java
src/main/java/task_BJS2_61403/Main.java
src/main/java/task_BJS2_61403/Squad.java
src/main/java/task_BJS2_61403/Swordsman.java

Привет!
Выполнил задачу: https://faang-school.atlassian.net/browse/BJS2-61403
Спасибо!

BJS2-61403: Распределенная армия героев меча и магии

---

src/main/java/bjs2_56245/LaunchScheduler.java
src/main/java/bjs2_56245/Main.java
src/main/java/bjs2_56245/RocketLaunch.java

BJS2-56245 выполнение задачи

---

src/main/java/task_BJS2_63440/Boss.java
src/main/java/task_BJS2_63440/Main.java
src/main/java/task_BJS2_63440/Player.java

Привет!
Выполнил задачу: https://faang-school.atlassian.net/browse/BJS2-63440
Прошу проверить!
Спасибо

BJS2-63440: Supercow!

---

src/main/java/bjs261468/House.java
src/main/java/bjs261468/Main.java
src/main/java/bjs261468/Role.java
src/main/java/bjs261468/User.java

Многопоточные методы выбора домов и установления ролей

BJS2-61468

---

src/main/java/got/House.java
src/main/java/got/Main.java
src/main/java/got/User.java
src/test/java/got/HouseTest.java
src/test/java/got/UserTest.java

task:
https://faang-school.atlassian.net/browse/BJS2-61464

Task BJS2-61464 Games of thrones

---

src/main/java/bjs2_60571/Main.java
src/main/java/bjs2_60571/Person.java
src/main/java/bjs2_60571/PersonInfoPrinter.java

Kalenteenkovalexander2586 bjs2 60571 помогите коллеге

---

src/main/java/bjs2_60615/CashierThread.java
src/main/java/bjs2_60615/Main.java

Из описания я не понял, что нужно было сделать. Поэтому подсмотрел реализыцию, которая предложена в лекциях. Мне показалась она не логичной, поэтому я сделл так. Могу аргументировать своё решение и обсудить решение, предложеное в лекциях.

BJS2-60615 выполнение задачи.

---

src/main/java/bjs261657/Music.java
src/main/java/bjs261657/MusicException.java
src/main/java/bjs261657/Player.java

BJS2-61657

---

src/main/java/task_BJS2_63835/Music.java
src/main/java/task_BJS2_63835/Player.java

Привет!
Выполнил задачу: https://faang-school.atlassian.net/browse/BJS2-63835
Спасибо!

BJS2-63835: Блокировка Spotify

---

src/main/java/mailclient/MailSender.java
src/main/java/mailclient/SenderRunnable.java
src/test/java/mailclient/SenderRunnableTest.java

task:
https://faang-school.atlassian.net/browse/BJS2-60521

Task BJS2-60521 Mail client

---

src/main/java/bjs261606/ForceModifier.java
src/main/java/bjs261606/Game.java
src/main/java/bjs261606/Main.java
src/main/java/bjs261606/Player.java
src/main/java/bjs261606/PlayerModifier.java
src/main/java/bjs261606/Position.java
src/main/java/bjs261606/PositionModifier.java

BJS2-61606

---

src/main/java/bjs261487/Boss.java
src/main/java/bjs261487/Main.java
src/main/java/bjs261487/Player.java

Игра Supercow с лимитом игроков

BJS2-61487

---

src/main/java/bjs261587/Main.java
src/main/java/bjs261587/VideoManager.java

Разработан многопоточный класс VideoManager

BJS2-61587

---

src/main/java/BJS261220/Archer.java
src/main/java/BJS261220/Army.java
src/main/java/BJS261220/Mage.java
src/main/java/BJS261220/Main.java
src/main/java/BJS261220/Squad.java
src/main/java/BJS261220/Swordsman.java
src/main/java/BJS261220/Unit.java

делал по подсказкам, но вроде разобрался с темой

1ilyaaaaa1-BJS2-61220

---

src/main/java/school/faang/GooglePhotosAutoUploader.java
src/main/java/school/faang/PhotosSync.java

BJS2-61791

---

src/main/java/school/faang/lets_practice_streamAPI_2/BJS2_58055/ListOperations.java
src/main/java/school/faang/lets_practice_streamAPI_2/BJS2_58055/Main.java
src/main/java/school/faang/lets_practice_streamAPI_2/BJS2_58055/NumberPair.java

1. Не делал валидацию и логирование для ускорения решения задач.
2. Создан класс ListOperations с методами findPairsWithSum, sortingCapitals, filteringAndSortingOfStrings, convertingNumbersToBinary, filteringStringsAlphabeticallyAndSortingByLength
3. Создан класс NumberPair

BJS2-58055

---

src/main/java/school/faang/task60558/MailSender.java
src/main/java/school/faang/task60558/SenderRunnable.java

https://faang-school.atlassian.net/browse/BJS2-60558

BJS2-60558 Вы работаете в Microsoft!

---

src/main/java/bigbang/BigBangTheory.java
src/main/java/bigbang/Task.java
src/test/java/bigbang/TaskTest.java

task:
https://faang-school.atlassian.net/browse/BJS2-61210

Task BJS2-61210 Big bang theory

---

src/main/java/school/faang/youtube_view_counter/BJS2_61656/Main.java
src/main/java/school/faang/youtube_view_counter/BJS2_61656/VideoManager.java

1. Создан класс VideoManager с методами addView и getViewCount.

BJS2-61656

---

src/main/java/school/faang/they_were_very_nice_but_extremely_poor/BJS2_60770/Chore.java
src/main/java/school/faang/they_were_very_nice_but_extremely_poor/BJS2_60770/Main.java
src/main/java/school/faang/they_were_very_nice_but_extremely_poor/BJS2_60770/WeasleyFamily.java

1. Создан класс Chore, который реализовывает интерфейс Runnable.
2. Создан класс WeasleyFamily с методом doHouseholdChores.

BJS2-60770

---

src/main/java/school/faang/House.java
src/main/java/school/faang/User.java

BJS2-61507

---

src/main/java/school/faang/Music.java
src/main/java/school/faang/Player.java

BJS2-62056

---

src/main/java/space/LaunchPlanner.java
src/main/java/space/RocketLaunch.java
src/main/java/space/SpaceProgram.java

task:
https://faang-school.atlassian.net/browse/BJS2-60785

Task BJS2-60785 SpaceX 

---

src/main/java/school/faang/you_work_at_microsoft/BJS2_60544/MailSender.java
src/main/java/school/faang/you_work_at_microsoft/BJS2_60544/SenderRunnable.java

1. Создан класс SenderRunnable, который реализует интерфейс Runnable.
2. Создан класс MailSender с методом main

BJS2-60544

---

src/main/java/bjs2_61466/House.java
src/main/java/bjs2_61466/Main.java
src/main/java/bjs2_61466/Role.java
src/main/java/bjs2_61466/User.java

bjs2_61466 Железный трон любой ценой

bjs2_61466 Железный трон любой ценой

---

src/main/java/tinder/Chat.java
src/main/java/tinder/ChatManager.java
src/main/java/tinder/Main.java
src/main/java/tinder/User.java
src/main/java/tinder/UserList.java

task:
https://faang-school.atlassian.net/browse/BJS2-61534

Task  BJS2-61534 Tinder

---

src/main/java/school/faang/task60791/Chore.java
src/main/java/school/faang/task60791/WeasleyFamily.java

https://faang-school.atlassian.net/browse/BJS2-60791

BJS2-60791 They were very nice but extremely poor

---

src/main/java/school/faang/task_61904/Music.java
src/main/java/school/faang/task_61904/Player.java

Выполнил задание: Блокировка Spotify

Выполнил задание: Блокировка Spotify

---

src/main/java/asyncfactorial/Factorial.java
src/main/java/asyncfactorial/FactorialComputationException.java
src/main/java/asyncfactorial/FactorialMain.java
src/test/java/asyncfactorial/FactorialTest.java

task:
https://faang-school.atlassian.net/browse/BJS2-61995

Task BJS2-61995 Factorial

---

src/main/java/school/faang/VideoManager.java
src/main/java/school/faang/ViewManager.java

я правильно понимаю, что использование ConcurrentHashMap<>() и viewsMap.merge уже делает программу потокозащищенной? если я оставляю значение synchronized у методов addView и getViewCount, то для video0 значения получаются некорректными, а без него все работает как нужно

Задача Счетчик просмотров на YouTube

---

src/main/java/school/faang/triwizard_tournament/BJS2_62446/Main.java
src/main/java/school/faang/triwizard_tournament/BJS2_62446/School.java
src/main/java/school/faang/triwizard_tournament/BJS2_62446/Student.java
src/main/java/school/faang/triwizard_tournament/BJS2_62446/Task.java
src/main/java/school/faang/triwizard_tournament/BJS2_62446/Tournament.java

1. Создан класс Tournament с методом startTask.
2. Создан record Task, класс Student и класс School с методом getTotalPoints.

BJS2-62446

---

src/main/java/school/faang/google_photo_sync/BJS2_61771/GooglePhotosAutoUploader.java
src/main/java/school/faang/google_photo_sync/BJS2_61771/Main.java

1. Создан класс GooglePhotosAutoUploader с методами startAutoUpload, onNewPhotoAdded, uploadPhotos.

BJS2-61771

---

src/main/java/school/faang/task61897/GooglePhotosAutoUploader.java
src/main/java/school/faang/task61897/Main.java

https://faang-school.atlassian.net/browse/BJS2-61713

BJS2-61713 Google Photo sync

---

src/main/java/school/faang/task61643/Boss.java
src/main/java/school/faang/task61643/Main.java
src/main/java/school/faang/task61643/Player.java

https://faang-school.atlassian.net/browse/BJS2-61643

BJS2-61643 Supercow!

---

src/main/java/school/faang/task61852/Game.java
src/main/java/school/faang/task61852/Main.java

https://faang-school.atlassian.net/browse/BJS2-61852

BJS2-61852 Bro Force!

---

src/main/java/school/faang/bro_force/BJS2_61630/Bro.java
src/main/java/school/faang/bro_force/BJS2_61630/Game.java
src/main/java/school/faang/bro_force/BJS2_61630/Main.java

1. Создал класс Game с методами addBro, update, gameOver.
2. Создал класс Bro.

BJS2-61630

---

src/main/java/school/faang/tournament_wizzards/Difficulty.java
src/main/java/school/faang/tournament_wizzards/School.java
src/main/java/school/faang/tournament_wizzards/Student.java
src/main/java/school/faang/tournament_wizzards/Task.java
src/main/java/school/faang/tournament_wizzards/Tournament.java

BJS2-62357

---

src/main/java/school/faang/MasterCardService.java

решение задачи
я долго не понимал почему задачи у меня не выполняются асинхронно пока мне чатгпт не подсказал что на обработку самого Future можно повесить новый Thread, для меня стало открытие. Вероятно в реальных задачах бред, но сейчас у меня такие

BJS2-61851

---

src/main/java/bjs2_61741/Music.java
src/main/java/bjs2_61741/Player.java

BJS2-61741-Блокировка-Spotify

---

src/main/java/school/faang/task61218/Main.java
src/main/java/school/faang/task61218/army/Archer.java
src/main/java/school/faang/task61218/army/Army.java
src/main/java/school/faang/task61218/army/Character.java
src/main/java/school/faang/task61218/army/Mage.java
src/main/java/school/faang/task61218/army/Squad.java
src/main/java/school/faang/task61218/army/Swordsman.java

https://faang-school.atlassian.net/browse/BJS2-61218

BJS2-61218 Распределенная армия героев меча и магии

---

src/main/java/bjs2_61879/Main.java
src/main/java/bjs2_61879/MasterCardService.java

BJS2-61879-Асинхронность-и-Future

---

src/main/java/school/faang/wow/Player.java
src/main/java/school/faang/wow/Quest.java
src/main/java/school/faang/wow/QuestSystem.java

BJS2-62044

---

src/main/java/school/faang/task61578/House.java
src/main/java/school/faang/task61578/Main.java
src/main/java/school/faang/task61578/User.java

https://faang-school.atlassian.net/browse/BJS2-61578

BJS2-61578 Железный трон любой ценой

---

src/main/java/school/faang/task61768/Main.java
src/main/java/school/faang/task61768/VideoManager.java

https://faang-school.atlassian.net/browse/BJS2-61768

BJS2-61768 Счетчик просмотров на YouTube

---

src/main/java/school/faang/blocking_spotify/BJS2_61770/Main.java
src/main/java/school/faang/blocking_spotify/BJS2_61770/Music.java
src/main/java/school/faang/blocking_spotify/BJS2_61770/Player.java

1. Создан класс Player с методами play, pause, skip, previous.
2. Создан класс Music с методом multiUserSimulation.

BJS2-61770

---

src/main/java/school/faang/lets_calculate_the_number_of_pIs/BJS2_62125/Main.java
src/main/java/school/faang/lets_calculate_the_number_of_pIs/BJS2_62125/PiCalculator.java
src/main/java/school/faang/lets_calculate_the_number_of_pIs/BJS2_62125/Point.java

1. Создан рекорд Point.
2. Создан класс PiCalculator с методом calculatePi.

BJS2-62125

---

src/main/java/bjs2_61828/FacebookNotificationSystem.java
src/main/java/bjs2_61828/Notification.java
src/main/java/bjs2_61828/NotificationManager.java

bjs2-61828 рассылаем уведомления в facebook

---

src/main/java/school/faang/BJS2_61694/Bro.java
src/main/java/school/faang/BJS2_61694/ConstAndMessages.java
src/main/java/school/faang/BJS2_61694/Game.java
src/main/java/school/faang/BJS2_61694/Main.java

В рамках разделения lock на два объекта не удается сделать так, чтобы больше никто не умирал после объявления победителя. Прошу помочь

BJS2-61694 Bro Force!

---

src/main/java/school/faang/superherobattle/Battle.java
src/main/java/school/faang/superherobattle/Pair.java
src/main/java/school/faang/superherobattle/Superhero.java
src/main/java/school/faang/superherobattle/SuperheroBattle.java

BJS2-61895

---

src/main/java/bjs2_62563/Comment.java
src/main/java/bjs2_62563/Main.java
src/main/java/bjs2_62563/Post.java
src/main/java/bjs2_62563/PostService.java

BJS2-62563-Оставляем-комментарий

---

src/main/java/fooddelivery/DeliveryService.java
src/main/java/fooddelivery/DeliveryServiceMain.java
src/main/java/fooddelivery/Order.java
src/main/java/fooddelivery/Product.java
src/main/java/fooddelivery/PromoCode.java
src/test/java/fooddelivery/DeliveryServiceTest.java
src/test/java/fooddelivery/OrderTest.java
src/test/java/fooddelivery/ProductTest.java
src/test/java/fooddelivery/PromoCodeTest.java

task:
https://faang-school.atlassian.net/browse/BJS2-63064

Task BJS2 63064 Food delivery

---

src/main/java/bjs2_61491/Main.java
src/main/java/bjs2_61491/TelegramBot.java

BJS2-61491-Telegram-бот

---

src/main/java/bjs2_62337/MagicalTournament.java
src/main/java/bjs2_62337/School.java
src/main/java/bjs2_62337/Student.java
src/main/java/bjs2_62337/Task.java
src/main/java/bjs2_62337/Tournament.java

BJS2-62337-Турнир-трех-волшебников

---

src/main/java/school/faang/alchemy/Potion.java
src/main/java/school/faang/alchemy/PotionGathering.java

BJS2-62429

---

src/main/java/school/faang/amazon_orders/AmazonProcessing.java
src/main/java/school/faang/amazon_orders/Order.java
src/main/java/school/faang/amazon_orders/OrderProcessor.java
src/main/java/school/faang/amazon_orders/OrderStatus.java

BJS2-61930

---

src/main/java/bjs2_62812/App.java
src/main/java/bjs2_62812/CollaborativeDocument.java
src/main/java/bjs2_62812/DocumentSection.java
src/main/java/bjs2_62812/DocumentSectionProcessor.java
src/main/java/bjs2_62812/SectionNotFoundException.java

BJS2-62812-GoogleDocs

---

src/main/java/school/faang/twitter_celebrity/FollowersDashboard.java
src/main/java/school/faang/twitter_celebrity/TwitterAccount.java
src/main/java/school/faang/twitter_celebrity/TwitterSubscriptionSystem.java

BJS2-62361

---

src/main/java/school/faang/asynchrony_and_future/BJS2_61988/Main.java
src/main/java/school/faang/asynchrony_and_future/BJS2_61988/MasterCardService.java

1. Создан класс MasterCardService с методами: collectPayment, sendAnalytics, doAll.

BJS2-61988

---

src/main/java/school/faang/wow/BJS2_62226/Main.java
src/main/java/school/faang/wow/BJS2_62226/Player.java
src/main/java/school/faang/wow/BJS2_62226/Quest.java
src/main/java/school/faang/wow/BJS2_62226/QuestSystem.java

1. Создан класс Player с методом addExperience.
2. Создан рекорд Quest.
3. Создан класс QuestSystem с методом startQuest.

BJS2-62226

---

src/main/java/school/faang/task62119/Main.java
src/main/java/school/faang/task62119/MasterCardService.java

https://faang-school.atlassian.net/browse/BJS2-62119

BJS2-62119 Асинхронность и Future

---

src/main/java/school/faang/collecting_orders_at_amazon/BJS2_62344/AmazonOrderProcessing.java
src/main/java/school/faang/collecting_orders_at_amazon/BJS2_62344/Order.java
src/main/java/school/faang/collecting_orders_at_amazon/BJS2_62344/OrderProcessor.java
src/main/java/school/faang/collecting_orders_at_amazon/BJS2_62344/Status.java

1. Создал классы Order и AmazonOrderProcessing.
2. Создал класс OrderProcessor с методами processAllOrders и processOrder.

BJS2-62344

---

src/main/java/bjs2_62067/Main.java
src/main/java/bjs2_62067/PiValueCalculator.java
src/main/java/bjs2_62067/Point.java

BJS2-62067-Вычислим-число-ПИ

---

src/main/java/bjs2_62545/ForeverOperationStopper.java
src/main/java/bjs2_62545/Main.java
src/main/java/bjs2_62545/MonitoringSystem.java
src/main/java/bjs2_62545/Sensor.java
src/main/java/bjs2_62545/SensorData.java
src/main/java/bjs2_62545/Substation.java

Задачу выполнил, как понял, но скорее всего предполагалось, что не нужно делать копию объектов SensorData, но я не понял, как это сделать без блокировки конкурентной мапы. А тогда теряется смысл её потокобезопасности, т.е. можно было обычную мапу использовать.

bjs2 62545 мониторинг электроподстанций

---

src/main/java/school/faang/task62302/Main.java
src/main/java/school/faang/task62302/Player.java
src/main/java/school/faang/task62302/Quest.java
src/main/java/school/faang/task62302/QuestSystem.java

https://faang-school.atlassian.net/browse/BJS2-62302

BJS2-62302 WOW

---

src/main/java/bjs2_62865/DataCollector.java
src/main/java/bjs2_62865/Main.java
src/main/java/bjs2_62865/ReportGenerator.java
src/main/java/bjs2_62865/Sales.java
src/main/java/bjs2_62865/SalesData.java

BJS2-62865-Сбор-данных-для-отчета

---

src/main/java/bjs2_63072/DeliveryService.java
src/main/java/bjs2_63072/Main.java
src/main/java/bjs2_63072/Order.java
src/main/java/bjs2_63072/Product.java
src/main/java/bjs2_63072/PromoCode.java

BJS2-63072-Купоны-на-доставку

---

build.gradle
src/main/java/school/faang/BJS2_68100/Main.java
src/main/java/school/faang/BJS2_68100/User.java
src/main/java/school/faang/Main.java

Блок 1.2 Java Core и Основы SQL
Задача: 

BJS2-68100 

---

src/main/java/school/faang/Group_Users_By_Age/User.java
src/main/java/school/faang/Main.java

Группировка пользователей по возрасту BJS2-68109

Группировка пользователей по возрасту BJS2-68109

---

src/main/java/school/faang/Group_Users_By_Age/User.java
src/main/java/school/faang/Main.java

Группировка пользователей по возрасту BJS2-68109
Изменил содание юзеров в main, переписал тело for с методом computeIfAbsent

Vladimirekgardt bjs2 68109

---

src/main/java/school/faang/library_westeros/Book.java
src/main/java/school/faang/library_westeros/LibrarySystem.java
src/main/java/school/faang/library_westeros/Main.java

BJS2-68650: create class Book and LibrarySystem

BJS2-68650: create class Book and LibrarySystem

---

src/main/java/school/faang/BJS2_68131/Main.java
src/main/java/school/faang/BJS2_68131/User.java
src/main/java/school/faang/Main.java

Блок: 1.2 Java Core и Основы SQL
Здача: Регистрация пользователя

BJS2-68100 Done

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/User.java
src/main/java/school/faang/groupingusersbyage/Main.java
src/main/java/school/faang/groupingusersbyage/User.java

Задача "Группировка пользователей по возрасту" решена

BJS2-68119 Grouping users by age

---

src/main/java/school/faang/BJS2_68051/Main.java
src/main/java/school/faang/BJS2_68051/User.java
src/main/java/school/faang/Main.java

1.2 Java Core и Основы SQL 
Коллекционируем пользователей

BJS2-68051 Initial commit

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/bjs2_68188/Main.java
src/main/java/school/faang/bjs2_68188/User.java

Создал два класса Main и User.
idea выдает предупреждение:  Call to 'printStackTrace()' should probably be replaced with more robust logging, нужно ли его убирать, по хорошему хочется без ворнингов.

Создан класс User и Main для запуска.

---

src/main/java/school/faang/reverse_example/Example.java
src/main/java/school/faang/reverse_example/Main.java

Реализация класса Example с методом reverse для разворота элементов массива

Класс с методом для разворота массива

---

src/main/java/school/faang/bjs2_68665/HogwartsSpells.java
src/main/java/school/faang/bjs2_68665/Main.java
src/main/java/school/faang/bjs2_68665/SpellEvent.java
src/main/java/school/faang/bjs_68653/Book.java
src/main/java/school/faang/bjs_68653/LibrarySystem.java
src/main/java/school/faang/bjs_68653/Main.java

Задача по Библиотеке Вестероса

BJS2-68653 Initial commit

---

src/main/java/school/faang/userregistr/Main.java
src/main/java/school/faang/userregistr/User.java

Решение задачи "Регистрация пользователя"

BJS2-68168 creat "User Registration" task

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/bjs2_68088/Main.java
src/main/java/school/faang/bjs2_68088/User.java

Добавлено предлагаемое решение задачи.

BJS2-68088 Коллекционируем пользователей.

---

src/main/java/school/faang/bjs2_68089/Example.java
src/main/java/school/faang/bjs2_68089/Main.java

На всякий случай сделал несколько вариантов реверса массива

task BJS2-68089

---

src/main/java/group/user/by/age/Main.java
src/main/java/group/user/by/age/User.java

Task Group user by age task BJS2-68114 is done !

Group user by age task BJS2-68114

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/User.java

loved hobbies

---

src/main/java/school/faang/bjs2_69188/Example.java
src/main/java/school/faang/bjs2_69188/Main.java

Kashkademan bjs2 69188 Развернитесь.

---

src/main/java/user/validation/Main.java
src/main/java/user/validation/User.java

Надеюсь так лучше чем через if в конструкторе :)

User Validation task BJS2-68196

---

src/main/java/school/faang/User.java

Задача BJS2-68059 "Коллекционируем пользователей"

BJS2-68059

---

src/main/java/school/faang/bjs2_69388/Main.java
src/main/java/school/faang/bjs2_69388/User.java

Решение для задачи Группировка пользователей по возрасту.

kashkademan bjs2 69388 Группировка пользователей по возрасту.

---

src/main/java/school/faang/collectionuser/Main.java
src/main/java/school/faang/collectionuser/User.java

Задача "Коллекционируем пользователей"

BJS2-68067-Collecting users

---

src/main/java/school/faang/hogwarts/spell/management/HogwartsSpells.java
src/main/java/school/faang/hogwarts/spell/management/Main.java
src/main/java/school/faang/hogwarts/spell/management/SpellEvent.java

BJS2-68663: add class HogwartsSpells, SpellEvent and test in Main

BJS2-68663: add class HogwartsSpells, SpellEvent and test in Main

---

src/main/java/school/faang/bjs2_68400/Main.java
src/main/java/school/faang/bjs2_68400/characters/Archer.java
src/main/java/school/faang/bjs2_68400/characters/Character.java
src/main/java/school/faang/bjs2_68400/characters/Warrior.java

решение в пакете school.faang.bjs2_68400

решение задачи BJS2-68400

---

config/checkstyle/checkstyle.xml
src/main/java/school/faang/university/student/management/Main.java
src/main/java/school/faang/university/student/management/Student.java
src/main/java/school/faang/university/student/management/StudentDatabase.java
src/main/java/school/faang/university/student/management/Subject.java
src/test/java/school/faang/university/student/management/StudentDatabaseTest.java

BJS2-68716: add class Student, StudentDatabase, Subject, Unit-test, main with test

BJS2-68716: add class Student, StudentDatabase, Subject, Unit-test, main with test 

---

src/main/java/school/faang/bjs2_68215/Main.java
src/main/java/school/faang/bjs2_68215/User.java

Решил сделать валидацию в конструкторе через методы (не знаю, верно это или нет)

Task BJS2-68215

---

src/main/java/school/faang/collect_users/Main.java
src/main/java/school/faang/collect_users/User.java

- Реализован класс User с методом для поиска увлечений по пользовотелям

Added class User, added method findHobbyLovers

---

src/main/java/librarywesteros/Book.java
src/main/java/librarywesteros/LibertySystem.java
src/main/java/librarywesteros/Main.java

The Library of Westeros

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/abstraction/Archer.java
src/main/java/school/faang/abstraction/Character.java
src/main/java/school/faang/abstraction/GameProperties.java
src/main/java/school/faang/abstraction/Main.java
src/main/java/school/faang/abstraction/Warrior.java

Создан абстрактный класс Character и классы-наследники Warrior и Archer. В классах-наследниках переопределен метод attack. В родительском классе определен метод checkHealth для проверки здоровья.

Создание абстрактного класса и его наследников

---

src/main/java/school/faang/abstraction/Archer.java
src/main/java/school/faang/abstraction/Character.java
src/main/java/school/faang/abstraction/HeroSettings.java
src/main/java/school/faang/abstraction/Main.java
src/main/java/school/faang/abstraction/StartHero.java
src/main/java/school/faang/abstraction/Warrior.java

Задания "Абстракция, абстракция!" решена

BJS2-68108 abstraction

---

src/main/java/school/faang/userregistration/Main.java
src/main/java/school/faang/userregistration/User.java

возможно стримы и Optional еще рано использовать, но все же хочу их потренировать - очень надо для работы.
заранее спасибо за понимание )

kenig8649: BJS2-68263 Регистрация пользователя

---

src/main/java/school/faang/bjs2_68700/Book.java
src/main/java/school/faang/bjs2_68700/LibrarySystem.java
src/main/java/school/faang/bjs2_68700/Main.java

решение в пакете school.faang.bjs2_68700

решение задачи BJS2-68700

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/User.java

Выполнение задания Группировка пользователей по возрасту "На проверку"

---

src/main/java/school/faang/bjs2_68750/HogwartsSpells.java
src/main/java/school/faang/bjs2_68750/Main.java
src/main/java/school/faang/bjs2_68750/SpellEvent.java

решение задачи в пакете school.faang.bjs2_68750

Werv666 bjs2 68750

---

src/main/java/school/faang/bjs2_69199/Archer.java
src/main/java/school/faang/bjs2_69199/Character.java
src/main/java/school/faang/bjs2_69199/Main.java
src/main/java/school/faang/bjs2_69199/Warrior.java

Kashkademan bjs2 69199 Абстракция, абстракция.

---

src/main/java/abstraction/abstraction/Archer.java
src/main/java/abstraction/abstraction/Character.java
src/main/java/abstraction/abstraction/CharacterConfiguration.java
src/main/java/abstraction/abstraction/Warrior.java

Abstraction, abstraction task BJS2-68172.

Abstraction, abstraction task BJS2-68172.

---

src/main/java/school/faang/bookingmanagement/AdminBookingObserver.java
src/main/java/school/faang/bookingmanagement/Booking.java
src/main/java/school/faang/bookingmanagement/BookingNotifier.java
src/main/java/school/faang/bookingmanagement/BookingObserver.java
src/main/java/school/faang/bookingmanagement/BookingSystem.java
src/main/java/school/faang/bookingmanagement/Main.java
src/main/java/school/faang/bookingmanagement/Room.java
src/main/java/school/faang/bookingmanagement/TimeSlot.java
src/main/java/school/faang/bookingmanagement/UserBookingObserver.java

Методы equals и hashcode переопределены используя только roomNumber или bookingId соответственно. Предполагаю, что они уникальны.
BookingSystem: 
Использую две доп. hashmap-ы для быстрого удаления, сравнения и поиска элементов.
В методе findAvailableRooms()
Использую DateTimeFormatter для преобразования строки в нужный тип и LocalTime, LocalDate для определения доступности комнат в промежутках времени. 
Для тестов созданы классы реализующие "Наблюдателя" AdminBookingObserver и UserBookingObserver.
Main тестирует все методы за исключением выброса ошибок. Тесты используют только валидные данные для даты и времени.

BJS2-68742 booking management solution
