CorporationX/god_bless

- src/main/java/faang/school/godbless/google_engine/Main.java
- src/main/java/faang/school/godbless/google_engine/WebPage.java
- src/main/java/faang/school/godbless/google_engine/WebPageService.java
Task: https://faang-school.atlassian.net/browse/BJS2-4445
> BJS2-4445: Google engine

- src/main/java/faang/school/godbless/registration/Main.java
- src/main/java/faang/school/godbless/registration/User.java
В классе User закомментировал ещё один вариант реализации
> Регистрация пользователей

- src/main/java/faang/school/godbless/index_requests/Main.java
- src/main/java/faang/school/godbless/index_requests/Query.java
- src/main/java/faang/school/godbless/index_requests/User.java
Task: https://faang-school.atlassian.net/browse/BJS2-4469
> BJS2-4469: Index requests

- src/main/java/faang/school/godbless/double_cache/Main.java
- src/main/java/faang/school/godbless/double_cache/Student.java
- src/main/java/faang/school/godbless/double_cache/Subject.java
Task: https://faang-school.atlassian.net/browse/BJS2-4475
> BJS2-4475: Double cache

- src/main/java/faang/school/godbless/reverse/Example.java
- src/main/java/faang/school/godbless/reverse/Main.java
> Nikolaianokhin 85207 bjs2 4522

- src/main/java/reverseArray/Example.java
решил задачу Развернитесь! - BJS2-4546
> решил задачу Развернитесь! - BJS2-4546

- src/main/java/faang/school/godbless/users/Main.java
- src/main/java/faang/school/godbless/users/User.java
Перепутал ветки. Вроде смог поправить самостоятельно.
Ошибаться можно, чтобы учиться на своих ошибках :).
> Added new logic for registration of users

- src/main/java/faang/school/godbless/javaHashMap/heroes/Battlefield.java
- src/main/java/faang/school/godbless/javaHashMap/heroes/Hero.java
- src/main/java/faang/school/godbless/javaHashMap/heroes/Main.java
- src/main/java/faang/school/godbless/javaHashMap/heroes/creatures/Angel.java
- src/main/java/faang/school/godbless/javaHashMap/heroes/creatures/Creature.java
- src/main/java/faang/school/godbless/javaHashMap/heroes/creatures/Griffin.java
- src/main/java/faang/school/godbless/javaHashMap/heroes/creatures/Pikeman.java
- src/main/java/faang/school/godbless/javaHashMap/heroes/creatures/Swordsman.java
В героев меча и магии не играл, поэтому сделал отсылку на WoW)
> BJS2-4399 (Герои меча и магии)

- src/main/java/users_registartion/Main.java
- src/main/java/users_registartion/User.java
решил задачу Регистрация пользователей- BJS2-4554
> решил задачу Регистрация пользователей- BJS2-4554

- src/main/java/abstraction/Archer.java
- src/main/java/abstraction/Character.java
- src/main/java/abstraction/Main.java
- src/main/java/abstraction/Warrior.java
решил задачу "Абстракция, абстракция!" - BJS2-4570
> решил задачу "Абстракция, абстракция!" - BJS2-4570

- src/main/java/collectUsers/Main.java
- src/main/java/collectUsers/User.java
решил задачу "Коллекционируем пользователей" - BJS2-4555
> решил задачу "Коллекционируем пользователей" - BJS2-4555

- src/main/java/faang/school/godbless/Main.java
- src/main/java/faang/school/godbless/User.java
Условия задачи
Создать класс 
User со следующими полями:
имя;
возраст;
место работы;
адрес.
В этом же классе создать статический метод 
groupUsers, который принимает List из объектов User и возвращает Map, где ключом является возраст пользователя, а значением — список из всех пользователей в оригинальном списке, которые имеют соответствующий возраст.
> добавлены 2 класса: юзер и мейн

- src/main/java/faang/school/godbless/bjs2_4467/DataCenter.java
- src/main/java/faang/school/godbless/bjs2_4467/DataCenterService.java
- src/main/java/faang/school/godbless/bjs2_4467/EnergyEfficencyOptimizationStrategy.java
- src/main/java/faang/school/godbless/bjs2_4467/LoadBalancingOptimizationStrategy.java
- src/main/java/faang/school/godbless/bjs2_4467/Main.java
- src/main/java/faang/school/godbless/bjs2_4467/OptimizationStrategy.java
- src/main/java/faang/school/godbless/bjs2_4467/ResourceRequest.java
- src/main/java/faang/school/godbless/bjs2_4467/Server.java
Task: https://faang-school.atlassian.net/browse/BJS2-4467
> BJS2-4467: Java HashMap: Оптимизируем работу дата-центра

- src/main/java/faang/school/godbless/BJS2_4622/ActionOnStudents.java
- src/main/java/faang/school/godbless/BJS2_4622/Main.java
- src/main/java/faang/school/godbless/BJS2_4622/Student.java
Создан алгоритм для создания, удаления, поиска и вывода информации о студентах на различных курсах
> Задание: Считаем прогулы BJS2-4622

- src/main/java/faang/school/godbless/BJS2_4561/ActionOnBook.java
- src/main/java/faang/school/godbless/BJS2_4561/Book.java
- src/main/java/faang/school/godbless/BJS2_4561/Main.java
Создан алгоритм для создания, удаления, поиска и вывода информации о книгах в библиотеке
> Задание: Библиотека Вестеросса BJS2-4561

- src/main/java/faang/school/godbless/BJS2_4341/Main.java
- src/main/java/faang/school/godbless/BJS2_4341/User.java
Создано:
Main: Объявление набора активностей, пользователей, вывод найденых пользователе
User: метод findHobbyLovers
> Задание: Коллекционируем пользователей BJS2-4341

- src/main/java/faang/school/godbless/Example.java
> Add solution for task BJS2-4506.

- src/main/java/faang/school/godbless/core/task_5/Main.java
- src/main/java/faang/school/godbless/core/task_5/util/Example.java
В описании, наверное, стоит уточнить, что задача на построение алгоритма и что нельзя использовать механизмы разворота из существующих классов.
> Развернитесь!

- src/main/java/faang/school/godbless/core/task_2/Main.java
- src/main/java/faang/school/godbless/core/task_2/model/User.java
Сюда бы очень хорошо пошло unit-тестирование, чтобы продемонстрировать каждый случай
> Регистрация пользователя

- src/main/java/usersGrouping/Main.java
- src/main/java/usersGrouping/User.java
решил задачу Группировка пользователей по возрасту - BJS2-4556
> решил задачу Группировка пользователей по возрасту - BJS2-4556

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/abstractionAbstraction/Character.java
Add solution for task BJS2-4509.
> Solution for task BJS2-4509.

- src/main/java/faang/school/godbless/core/task_3/Main.java
- src/main/java/faang/school/godbless/core/task_3/model/Archer.java
- src/main/java/faang/school/godbless/core/task_3/model/Character.java
- src/main/java/faang/school/godbless/core/task_3/model/Warrior.java
Скорее всего это задание на тренировку доступа к полям абстрактного класса и повторение мод-ров доступа.
Но я бы избегал обращения к полям класса напрямую.
> Абстракция, абстракция!

- src/main/java/faang/school/godbless/BJS2_4588/Example.java
- src/main/java/faang/school/godbless/BJS2_4588/Main.java
https://faang-school.atlassian.net/browse/BJS2-4588
> BJS2-4588: Reversed numbers.

- src/main/java/faang/school/godbless/BJS2_4127/Main.java
- src/main/java/faang/school/godbless/BJS2_4127/Product.java
Task: https://faang-school.atlassian.net/browse/BJS2-4127
> BJS2-4127: add product class & some group method

- src/main/java/faang/school/godbless/BJS2_4131/House.java
- src/main/java/faang/school/godbless/BJS2_4131/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-4131
> BJS2-4131: add house class & some houses from games of thrones

- src/main/java/faang/school/godbless/bjs2_4481/Main.java
- src/main/java/faang/school/godbless/bjs2_4481/Query.java
- src/main/java/faang/school/godbless/bjs2_4481/User.java
Task: https://faang-school.atlassian.net/browse/BJS2-4481
> BJS2-4481: Java HashMap: Индекс запросов ELK

- src/main/java/faang/school/godbless/bjs2_4526/Data.java
- src/main/java/faang/school/godbless/bjs2_4526/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-4526
> BJS2-4526: Java HashMap: LRU Cache

- src/main/java/faang/school/godbless/bjs2_4476/Main.java
- src/main/java/faang/school/godbless/bjs2_4476/WebPage.java
Task: https://faang-school.atlassian.net/browse/BJS2-4476
> Java HashMap: Поисковый мини-движок Google

- src/main/java/faang/school/godbless/BJS2_4134/Main.java
- src/main/java/faang/school/godbless/BJS2_4134/WeatherData.java
- src/main/java/faang/school/godbless/BJS2_4134/WeatherService.java
Task: https://faang-school.atlassian.net/browse/BJS2-4134
> BJS2-4134: add weatherData class & weatherService with cache

- src/main/java/faang/school/godbless/BJS2_4136/Main.java
- src/main/java/faang/school/godbless/BJS2_4136/StreamEvent.java
Task: https://faang-school.atlassian.net/browse/BJS2-4136
> BJS2-4136: add StreamEvent class & some methods

- src/main/java/countingAbsenteeism/Main.java
- src/main/java/countingAbsenteeism/Student.java
Созданы два класса Student и Main
В Main реазилованы методы:
добавления, удаления студентов из списка
Сортировка студентов по факультету-курсу
Поиск студентов по факультету-курсу
Вывод всех студентов
> BJS2-4386 : Считаем прогулы

- src/main/java/faang/school/godbless/BJS2_4126/Book.java
- src/main/java/faang/school/godbless/BJS2_4126/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-4126
> BJS2-4126: add book class & some books for library

- src/main/java/faang/school/godbless/BJS2_4614/Main.java
- src/main/java/faang/school/godbless/BJS2_4614/User.java
Task BJS2-4614 (Группировка пользователей по возрасту)
> Solution to task BJS2-4614

- src/main/java/faang/school/godbless/sprint1/javacore/groupuserbyage/Main.java
- src/main/java/faang/school/godbless/sprint1/javacore/groupuserbyage/User.java
BJS2-4705: Added: Grouping users by age task
> BJS2-4705: Added: Grouping users by age task

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/countingAbsenteeism/Main.java
- src/main/java/faang/school/godbless/countingAbsenteeism/Student.java
Add solution for task BJS2-4639.
> Solution for task BJS2-4639.

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/collectUsers/User.java
Add solution for task BJS2-4508.
> Solution for task BJS2-4508.

- src/main/java/faang/school/godbless/BJS2_4123/Main.java
- src/main/java/faang/school/godbless/BJS2_4123/User.java
https://faang-school.atlassian.net/browse/BJS2-4584
> BJS2-4584: collect the users.

- src/main/java/faang/school/godbless/BJS2_4582/Archer.java
- src/main/java/faang/school/godbless/BJS2_4582/Character.java
- src/main/java/faang/school/godbless/BJS2_4582/Main.java
- src/main/java/faang/school/godbless/BJS2_4582/Warrior.java
https://faang-school.atlassian.net/browse/BJS2-4582
> BJS2-4582: Abstraction, my friend!

- src/main/java/faang/school/godbless/bjs2_4441/Angel.java
- src/main/java/faang/school/godbless/bjs2_4441/Battlefield.java
- src/main/java/faang/school/godbless/bjs2_4441/Creature.java
- src/main/java/faang/school/godbless/bjs2_4441/Griffin.java
- src/main/java/faang/school/godbless/bjs2_4441/Hero.java
- src/main/java/faang/school/godbless/bjs2_4441/Main.java
- src/main/java/faang/school/godbless/bjs2_4441/Pikeman.java
- src/main/java/faang/school/godbless/bjs2_4441/Swordman.java
Task: https://faang-school.atlassian.net/browse/BJS2-4441
> BJS2-4441: Java HashMap: Герои Меча и Магии

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/libraryOfWesteros/Book.java
- src/main/java/faang/school/godbless/libraryOfWesteros/Main.java
Add solution for task BJS2-4632.
> Solution for task BJS2-4632.

- src/main/java/faang/school/godbless/LRU_cache/CustomDataStorage.java
- src/main/java/faang/school/godbless/LRU_cache/Data.java
- src/main/java/faang/school/godbless/LRU_cache/Main.java
- src/main/java/faang/school/godbless/LRU_cache/Node.java
Task: https://faang-school.atlassian.net/browse/BJS2-4483
> BJS2-4483: LRU Cache

- src/main/java/faang/school/godbless/optimization_data_center/DataCenter.java
- src/main/java/faang/school/godbless/optimization_data_center/DataCenterService.java
- src/main/java/faang/school/godbless/optimization_data_center/Main.java
- src/main/java/faang/school/godbless/optimization_data_center/Server.java
- src/main/java/faang/school/godbless/optimization_data_center/dto/ResourceRequest.java
- src/main/java/faang/school/godbless/optimization_data_center/optimization/LoadBalancingOptimizationStrategy.java
- src/main/java/faang/school/godbless/optimization_data_center/optimization/OptimizationStrategy.java
- src/test/java/faang/school/godbless/optimization_data_center/DataCenterServiceTest.java
Task: https://faang-school.atlassian.net/browse/BJS2-4387
> BJS2-4387: Optimization data center

- src/main/java/faang/school/godbless/BJS2_4560/EventsForHouses.java
- src/main/java/faang/school/godbless/BJS2_4560/House.java
- src/main/java/faang/school/godbless/BJS2_4560/Main.java
Создан алгоритм для создания, удаления, поиска и вывода информации о домах
> Задание: Игра престолов BJS2-4560

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/amazon/Main.java
- src/main/java/faang/school/godbless/amazon/Product.java
Created package amazon. Add Main and Product.
> Java HashMap: Разбираем склад Amazon

- src/main/java/faang/school/godbless/bjs2_4523/Main.java
- src/main/java/faang/school/godbless/bjs2_4523/Student.java
- src/main/java/faang/school/godbless/bjs2_4523/Subject.java
Task: https://faang-school.atlassian.net/browse/BJS2-4523
> BJS2-4523: Java HashMap: Двойной кэш-кэш

- src/main/java/CountingAbsenteeism/Main.java
- src/main/java/CountingAbsenteeism/Student.java
Java HashMap: Считаем прогулы- BJS2-4859
> Выполнил задание, отправляю на PR

- src/main/java/cache/Main.java
- src/main/java/cache/MockService.java
- src/main/java/cache/WeatherData.java
Созданы два класса WeatherData и Main
В Main реазилованы методы:
метод, который возвращает информацию о погоде в переданном городе, если его нет в кэше то получает через MockService
Методы обновления, удаления и вывода информации о погоде на экран
> BJS2-4465 : Кэшируем

- src/main/java/amazon/Main.java
- src/main/java/amazon/Product.java
Созданы 2 класса StreamEvent и Main
В Main реализованы методы добавления нового события, поиска события по ID, поиск списка событий по типу, удаления события и метод вывода информации о всех событиях
> BJS2-4495 : Склад Amazon

- src/main/java/heroesOfMightAndMagic/Angel.java
- src/main/java/heroesOfMightAndMagic/Battlefield.java
- src/main/java/heroesOfMightAndMagic/Creature.java
- src/main/java/heroesOfMightAndMagic/Griffin.java
- src/main/java/heroesOfMightAndMagic/Hero.java
- src/main/java/heroesOfMightAndMagic/Pikeman.java
- src/main/java/heroesOfMightAndMagic/Swordman.java
Добавил поле health и hpAfterAttack для абстрактного класса Creature.
Суть моего класса Hero в том, что все существа группируются по названию их класса, изменяется в процессе добавления только их количество. 
Суть моего метода battle в том, что существа героя наносят урон первому существу противника по очереди, затем ход меняется и второй герой по тому же принципу наносит урон существу противника. Если после атаки кончается кол-во существ, то атака будет переключена на следующее существо противника.
В battle дописан дополнительный метод countQuantityAfterAttack, который возвращает количество существ, которые остались после нападения, так же с записью остаточного здоровья у раненого существа (если такая ситуация происходит), чтобы следующая атака начиналась с раненого существа.
> BJS2-4529 : Герои Меча и Магии

- src/main/java/faang/school/godbless/hashMap/task_1/Main.java
- src/main/java/faang/school/godbless/hashMap/task_1/model/House.java
В методе printAll() в конце добавил вывод пустой строки, чтобы в демонстрации работы несколько раз не писать команду вывода пустой строки.
> Java HashMap: Игра престолов

- src/main/java/faang/school/godbless/hogwarts_hogwarts/Main.java
- src/main/java/faang/school/godbless/hogwarts_hogwarts/SpellAction.java
- src/main/java/faang/school/godbless/hogwarts_hogwarts/SpellCaster.java
Task: https://faang-school.atlassian.net/browse/BJS2-4957
> BJS2-4957: Hogwarts, Hogwarts

- src/main/java/faang/school/godbless/instagram_filters/FilterProcessor.java
- src/main/java/faang/school/godbless/instagram_filters/Image.java
- src/main/java/faang/school/godbless/instagram_filters/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-5006
> BJS2-5006: Instagram filters

- src/main/java/faang/school/godbless/meta_universe/BadWordsManager.java
- src/main/java/faang/school/godbless/meta_universe/Main.java
- src/main/java/faang/school/godbless/meta_universe/Notification.java
- src/main/java/faang/school/godbless/meta_universe/NotificationManager.java
Task: https://faang-school.atlassian.net/browse/BJS2-4988
> BJS2-4988: Meta universe

- src/main/java/faang/school/godbless/grouped/Main.java
- src/main/java/faang/school/godbless/grouped/User.java
Сгруппировали пользователей по возрасту
> grouping users by age

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/gameOfThrones/House.java
- src/main/java/faang/school/godbless/gameOfThrones/Main.java
Add solution for task BJS2-4637.
> Solution for task BJS2-4637.

- src/main/java/faang/school/godbless/gmail_rich_filters/Email.java
- src/main/java/faang/school/godbless/gmail_rich_filters/EmailProcessor.java
- src/main/java/faang/school/godbless/gmail_rich_filters/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-5009
> BJS2-5009: Gmail rich filters

- src/main/java/faang/school/godbless/library_of_westeros/Book.java
- src/main/java/faang/school/godbless/library_of_westeros/Main.java
BJS2-4583 library_of_westeros complete
> BJS2-4583 library_of_westeros complete

- src/main/java/faang/school/godbless/module/hashmap/library/Book.java
- src/main/java/faang/school/godbless/module/hashmap/library/Main.java
Ссылка на задачу
https://faang-school.atlassian.net/jira/software/c/projects/BJS2/boards/42?assignee=5fa6735d71ab9e006a2b7749&selectedIssue=BJS2-4914
> Решение задачи BJS2-4914 - Java HashMap: Библиотека Вестеросса

- src/main/java/faang/school/godbless/google_translate/DictionaryProcessor.java
- src/main/java/faang/school/godbless/google_translate/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-5008
> BJS2-5008: Google translate

- src/main/java/faang/school/godbless/bjs2_5007/Main.java
- src/main/java/faang/school/godbless/bjs2_5007/Notification.java
- src/main/java/faang/school/godbless/bjs2_5007/NotificationManager.java
Task: https://faang-school.atlassian.net/browse/BJS2-5007
> BJS2-5007: Meta-вселенная?

- src/main/java/faang/school/godbless/abstraction_abstraction/Archer.java
- src/main/java/faang/school/godbless/abstraction_abstraction/Character.java
- src/main/java/faang/school/godbless/abstraction_abstraction/Main.java
- src/main/java/faang/school/godbless/abstraction_abstraction/Warrior.java
Я не особо понял прикола с двумя конструкторами, где есть имя отдельно и всеми полями, кроме здоровья. Я использовал либо один, либо другой. Либо можно было для арчера один, на воина другой может. Если есть полезный способ использования, покажите, пожалуйста
> Абстракция-абстракция!

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/registrationOfUser/Main.java
- src/main/java/faang/school/godbless/registrationOfUser/User.java
Add 4 constants and IllegalArgumetException in User class. Removed Application class.
> Регистрация пользователя.

- src/main/java/faang/school/godbless/BJS2_4585/Example.java
- src/main/java/faang/school/godbless/BJS2_4585/Main.java
Task BJS2-4585 (Развернитесь!)
> Solution to task BJS2-4585

- src/main/java/faang/school/godbless/bjs2_5014/Email.java
- src/main/java/faang/school/godbless/bjs2_5014/EmailProcessor.java
- src/main/java/faang/school/godbless/bjs2_5014/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-5014
> BJS2-5014: Gmail Rich Filters

- src/main/java/faang/school/godbless/bjs2_4918/Main.java
- src/main/java/faang/school/godbless/bjs2_4918/SpellAction.java
- src/main/java/faang/school/godbless/bjs2_4918/SpellCaster.java
Task: https://faang-school.atlassian.net/browse/BJS2-4918
> BJS2-4918: Хогвартс, Хогвартс, наш любимый Хогвартс

- src/main/java/faang/school/godbless/bjs2_5041/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-5041
> BJS2-5041: Вспомним школу

- src/main/java/faang/school/godbless/bjs2_5063/Location.java
- src/main/java/faang/school/godbless/bjs2_5063/LocationSearchEngine.java
- src/main/java/faang/school/godbless/bjs2_5063/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-5063
> BJS2-5063: Google Maps

- src/main/java/faang/school/godbless/lambdas/task_1/Main.java
- src/main/java/faang/school/godbless/lambdas/task_1/model/SpellAction.java
- src/main/java/faang/school/godbless/lambdas/task_1/model/SpellCaster.java
Тут можно было бы Function<String, String> использовать, но в задании сказано создать пользовательский ФИ.
> Хогвартс, Хогвартс, наш любимый Хогвартс

- src/main/java/faang/school/godbless/WebPagesIndexing/Main.java
- src/main/java/faang/school/godbless/WebPagesIndexing/WebPage.java
> Moved to package Page indexing task files

- src/main/java/AmazonWarehouse/Main.java
- src/main/java/AmazonWarehouse/Product.java
Java HashMap: Разбираем склад Amazon - BJS2-4928
> Выполнил задание, отправляю PR

- src/main/java/faang/school/godbless/hogwards/Main.java
- src/main/java/faang/school/godbless/hogwards/SpellAction.java
- src/main/java/faang/school/godbless/hogwards/SpellCaster.java
Хогвартс, Хогвартс, наш любимый Хогвартс
> Added functional interface Spell and class SpellCaster

- src/main/java/faang/school/godbless/BJS2_5082/Main.java
- src/main/java/faang/school/godbless/BJS2_5082/SpellAction.java
- src/main/java/faang/school/godbless/BJS2_5082/SpellCaster.java
Реализована работа лямбды для вывода сообщений
> Задание: Хогвартс, Хогвартс, наш любимый Хогвартс BJS2-5082

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/collecting_users/Main.java
- src/main/java/faang/school/godbless/collecting_users/User.java
Created new folder collecting_users, add Main and User classes. In User class created method findHobbyLovers. Deleted Application class.
> Коллекционируем пользователей.

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/groupAgeOfUsers/Main.java
- src/main/java/faang/school/godbless/groupAgeOfUsers/User.java
Add Main and User classes. Removed Application class.
> Группировка пользователей по возрасту.

- src/main/java/faang/school/godbless/weather_forecast/Main.java
- src/main/java/faang/school/godbless/weather_forecast/WeatherData.java
- src/main/java/faang/school/godbless/weather_forecast/WeatherService.java
Created package weather_forecast. Add Main, WeatherData and WeatherService(имитация стороннего сервиса).
> Java HashMap: Кэшируем, кэшируем.

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/stream_event/Main.java
- src/main/java/faang/school/godbless/stream_event/StreamEvent.java
Created package stream_event. Add Main and StreamEvent.
> Java HashMap: Ловим события

- src/main/java/faang/school/godbless/bjs2_5059/Droid.java
- src/main/java/faang/school/godbless/bjs2_5059/DroidMessageEncryptor.java
- src/main/java/faang/school/godbless/bjs2_5059/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-5059
> BJS2-5059: Секреты дроидов

- src/main/java/faang/school/godbless/InstagramFilters/FilterProcessor.java
- src/main/java/faang/school/godbless/InstagramFilters/Image.java
- src/main/java/faang/school/godbless/InstagramFilters/Main.java
BJS2-5052 Java 8: Функциональные интерфейсы, Лямбды: Фильтры Instagram
> BJS2-5052 Java 8: Функциональные интерфейсы, Лямбды: Фильтры Instagram

- src/main/java/faang/school/godbless/Example.java
> BJS2-4607-reverse

- src/main/java/theLordOfTheRings/Character.java
- src/main/java/theLordOfTheRings/InventoryManager.java
- src/main/java/theLordOfTheRings/Item.java
- src/main/java/theLordOfTheRings/Main.java
добавил еще один метод printInfoAboutCharacter, для вывода информации об объекте
> BJS2-5095 : The Lord Of The Rings

- src/main/java/faang/school/godbless/gameOfThrones/House.java
- src/main/java/faang/school/godbless/gameOfThrones/Main.java
> BJS2-4955-GoT

- src/main/java/faang/school/godbless/BJS2_5099/House.java
- src/main/java/faang/school/godbless/BJS2_5099/Main.java
Task BJS2-5099 (Java HashMap: Игра престолов)
> Solution to task BJS2-5099

- src/main/java/faang/school/godbless/Insta/FilterProcessor.java
- src/main/java/faang/school/godbless/Insta/Image.java
- src/main/java/faang/school/godbless/Insta/Main.java
Instagram filter task for review.
> BJS2-5119-Instagram

- src/main/java/faang/school/godbless/library/Book.java
- src/main/java/faang/school/godbless/library/Main.java
> BJS2-4960-library

- src/main/java/faang/school/godbless/calculator/Calculator.java
- src/main/java/faang/school/godbless/calculator/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-5019
> BJS2-5019: Calculator

- src/main/java/faang/school/godbless/handle_exceptions/ExceptionHandler.java
- src/main/java/faang/school/godbless/handle_exceptions/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-5097
> BJS2-5097: Handle exceptions

- src/main/java/faang/school/godbless/module/hashmap/keshiruem/Main.java
- src/main/java/faang/school/godbless/module/hashmap/keshiruem/WeatherData.java
- src/main/java/faang/school/godbless/module/hashmap/keshiruem/WeatherDataService.java
https://faang-school.atlassian.net/browse/BJS2-5079?atlOrigin=eyJpIjoiYjNkOGQ1ZjIyMTdjNDVjYjg2ZjUxNzE4M2NmMGQ2ZTkiLCJwIjoiaiJ9
> Решение задачи BJS2-5079 Java HashMap: Кэшируем, кэшируем

- src/main/java/faang/school/godbless/module/hashmap/event/Main.java
- src/main/java/faang/school/godbless/module/hashmap/event/StreamEvent.java
https://faang-school.atlassian.net/browse/BJS2-5098?atlOrigin=eyJpIjoiMGQ3OTU2NWUzMTNmNGEzYWIwMGYyMzgwZTVkOWFlNzUiLCJwIjoiaiJ9
> Решение задачи BJS2-5098 Java HashMap: Ловим события

- src/main/java/faang/school/godbless/module/hashmap/sklad/Main.java
- src/main/java/faang/school/godbless/module/hashmap/sklad/Product.java
https://faang-school.atlassian.net/browse/BJS2-5142?atlOrigin=eyJpIjoiZDY2NzQ0N2RlYTY5NDRiOTg3MDg5YzRlN2I4OWUxMzgiLCJwIjoiaiJ9
> Решение задачи BJS2-5142 Java HashMap: Разбираем склад Amazon

- src/main/java/faang/school/godbless/bjs2_5016/Main.java
- src/main/java/faang/school/godbless/bjs2_5016/MessageFilter.java
- src/main/java/faang/school/godbless/bjs2_5016/MessageProcessor.java
Task: https://faang-school.atlassian.net/browse/BJS2-5016
> BJS2-5016: Фильтруем спам

- src/main/java/faang/school/godbless/droid_secrets/Droid.java
- src/main/java/faang/school/godbless/droid_secrets/DroidMessageEncryptor.java
- src/main/java/faang/school/godbless/droid_secrets/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-5111
> BJS2-5111: Droid secrets

- src/main/java/faang/school/godbless/module/hashmap/heroes/Battlefield.java
- src/main/java/faang/school/godbless/module/hashmap/heroes/Main.java
- src/main/java/faang/school/godbless/module/hashmap/heroes/creature/Angel.java
- src/main/java/faang/school/godbless/module/hashmap/heroes/creature/Creature.java
- src/main/java/faang/school/godbless/module/hashmap/heroes/creature/Griffin.java
- src/main/java/faang/school/godbless/module/hashmap/heroes/creature/Pikeman.java
- src/main/java/faang/school/godbless/module/hashmap/heroes/creature/Swordman.java
- src/main/java/faang/school/godbless/module/hashmap/heroes/hero/FirstPlayer.java
- src/main/java/faang/school/godbless/module/hashmap/heroes/hero/Hero.java
- src/main/java/faang/school/godbless/module/hashmap/heroes/hero/SecondPlayer.java
https://faang-school.atlassian.net/browse/BJS2-5145?atlOrigin=eyJpIjoiMDYwZTY3YmRjZTYwNGUxY2E4NzM3N2ZhZGRmYTAwM2IiLCJwIjoiaiJ9
> Решение задачи BJS2-5145 Java HashMap: Герои меча и магии

- src/main/java/faang/school/godbless/bjs2_5020/Character.java
- src/main/java/faang/school/godbless/bjs2_5020/InventoryManager.java
- src/main/java/faang/school/godbless/bjs2_5020/Item.java
- src/main/java/faang/school/godbless/bjs2_5020/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-5020
> BJS2-5020: Lord of the Rings RPG

- src/main/java/faang/school/godbless/bjs2_5025/ExceptionHandler.java
- src/main/java/faang/school/godbless/bjs2_5025/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-5025
> BJS2-5025: Обрабатываем ошибки красиво

- src/main/java/faang/school/godbless/lord_of_the_rings/Character.java
- src/main/java/faang/school/godbless/lord_of_the_rings/InventoryManager.java
- src/main/java/faang/school/godbless/lord_of_the_rings/Item.java
- src/main/java/faang/school/godbless/lord_of_the_rings/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-5067
> BJS2-5067: Lord of the rings

- src/main/java/faang/school/godbless/BJS2_5154/Example.java
- src/main/java/faang/school/godbless/BJS2_5154/Main.java
> Task BJS2-5154

- src/main/java/faang/school/godbless/goolgeTransale/DictionaryProcessor.java
- src/main/java/faang/school/godbless/goolgeTransale/Main.java
BJS2-5124-google translate for check
> BJS2-5124-google translate

- src/main/java/faang/school/godbless/MetaUniverse/Main.java
- src/main/java/faang/school/godbless/MetaUniverse/Notification.java
- src/main/java/faang/school/godbless/MetaUniverse/NotificationManager.java
BJS2-5056 Java 8: Функциональные интерфейсы, Лямбды: Meta-вселенная?
> BJS2-5056 Java 8: Функциональные интерфейсы, Лямбды: Meta-вселенная?

- src/main/java/faang/school/godbless/Calculator/Calculator.java
- src/main/java/faang/school/godbless/Calculator/Main.java
BJS2-5049 Java 8: Функциональные интерфейсы, Лямбды: Калькулятор
> ethiqque-BJS2-5049 Java 8: Функциональные интерфейсы, Лямбды: Калькулятор

- src/main/java/faang/school/godbless/BJS2_5157/Main.java
- src/main/java/faang/school/godbless/BJS2_5157/SpellAction.java
- src/main/java/faang/school/godbless/BJS2_5157/SpellCaster.java
Task BJS2-5157 (Хогвартс, Хогвартс, наш любимый Хогвартс)
> Solution to task BJS2-5157

- src/main/java/faang/school/godbless/practice_stream_1/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-5194
> BJS2-5194: Practice stream 1

- src/main/java/faang/school/godbless/game_of_thrones/House.java
- src/main/java/faang/school/godbless/game_of_thrones/Main.java
BJS2-4567 game_of_thrones complete
> BJS2-4567 game_of_thrones complete

- src/main/java/faang/school/godbless/caching_caching/Main.java
- src/main/java/faang/school/godbless/caching_caching/WeatherData.java
BJS2-4644 caching_caching complete
> BJS2-4644 caching_caching complete

- src/main/java/faang/school/godbless/counting_absenteeism/Main.java
BJS2-4592 counting_absenteeism complete(solution 3)
> BJS2-4592 counting_absenteeism complete(solution 3)

- src/main/java/faang/school/godbless/catching_events/Main.java
- src/main/java/faang/school/godbless/catching_events/StreamEvent.java
BJS2-4677 catching_events complete
> BJS2-4677 catching_events complete

- src/main/java/faang/school/godbless/BJS2_5187/Main.java
- src/main/java/faang/school/godbless/BJS2_5187/Notification.java
- src/main/java/faang/school/godbless/BJS2_5187/NotificationManager.java
Task BJS2-5187 (Meta-вселенная?)
> Solution to task BJS2-5187

- src/main/java/faang/school/godbless/BJS2_5214/House.java
- src/main/java/faang/school/godbless/BJS2_5214/Main.java
> Task BJS2-5214

- src/main/java/faang/school/godbless/meta/Main.java
- src/main/java/faang/school/godbless/meta/Notification.java
- src/main/java/faang/school/godbless/meta/NotificationManager.java
Created Main, Notification and NotificationManager classes.
> Meta-вселенная?

- src/main/java/catchingEvents/Main.java
- src/main/java/catchingEvents/StreamEvent.java
Созданы 2 класса StreamEvent и Main
В Main реализованы методы добавления нового события, поиска события по ID, поиск списка событий по типу, удаления события и метод вывода информации о всех событиях
> BJS2-4477 : Ловим события

- src/main/java/faang/school/godbless/bjs2_5123/Employee.java
- src/main/java/faang/school/godbless/bjs2_5123/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-5123
> BJS2-5123: Потренируем StreamAPI 2

- src/main/java/faang/school/godbless/bjs2_5069/Main.java
- src/main/java/faang/school/godbless/bjs2_5069/MatrixJoiner.java
- src/main/java/faang/school/godbless/bjs2_5069/VectorJoiner.java
Task: https://faang-school.atlassian.net/browse/BJS2-5069
> BJS2-5069: Построим CSV

- src/main/java/faang/school/godbless/gmail_rich_filters/Email.java
- src/main/java/faang/school/godbless/gmail_rich_filters/EmailProcessor.java
- src/main/java/faang/school/godbless/gmail_rich_filters/Test.java
BJS2-5196 gmail_rich_filters complete
> BJS2-5196 gmail_rich_filters complete

- src/main/java/faang/school/godbless/hogwarts_hogwarts/SpellAction.java
- src/main/java/faang/school/godbless/hogwarts_hogwarts/SpellCaster.java
- src/main/java/faang/school/godbless/hogwarts_hogwarts/Test.java
BJS2-5084 hogwarts_hogwarts complete
> BJS2-5084 hogwarts_hogwarts complete

- src/main/java/faang/school/godbless/instagram_filters/FilterProcessor.java
- src/main/java/faang/school/godbless/instagram_filters/Image.java
- src/main/java/faang/school/godbless/instagram_filters/Test.java
BJS2-5189 instagram_filters complete
> BJS2-5189 instagram_filters complete

- src/main/java/faang/school/godbless/google_translator/DictionaryProcessor.java
- src/main/java/faang/school/godbless/google_translator/Test.java
BJS2-5195 google_translation complete
> BJS2-5195 google_translation complete

- src/main/java/faang/school/godbless/meta_universe/Notification.java
- src/main/java/faang/school/godbless/meta_universe/NotificationManager.java
- src/main/java/faang/school/godbless/meta_universe/Test.java
BJS2-5143 meta_universe complete
> BJS2-5143 meta_universe complete

- src/main/java/faang/school/godbless/module/second/lambda/hogwarts/Main.java
- src/main/java/faang/school/godbless/module/second/lambda/hogwarts/SpellAction.java
- src/main/java/faang/school/godbless/module/second/lambda/hogwarts/SpellCaster.java
https://faang-school.atlassian.net/browse/BJS2-5290?atlOrigin=eyJpIjoiYTIwNzBkNGMyMDkyNDU2MGI4ZmY1OGZiY2NkOWQ0ZmYiLCJwIjoiaiJ9
> Решение задачи BJS2-5290 Хогвартс, Хогвартс, наш любимый Хогвартс

- src/main/java/faang/school/godbless/gmail/Email.java
- src/main/java/faang/school/godbless/gmail/EmailProcessor.java
- src/main/java/faang/school/godbless/gmail/Main.java
Add Main, Email and EmailProcessor classes.
> Gmail Rich Filters

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/mUniverse/Main.java
- src/main/java/faang/school/godbless/mUniverse/Notification.java
- src/main/java/faang/school/godbless/mUniverse/NotificationManager.java
https://faang-school.atlassian.net/browse/BJS2-5292
> Add solution for task BJS2-5292.

- src/main/java/faang/school/godbless/filter_spam/MessageFilter.java
- src/main/java/faang/school/godbless/filter_spam/MessageProcessor.java
- src/main/java/faang/school/godbless/filter_spam/Test.java
BJS2-5274 filter_spam complete
> BJS2-5274 filter_spam complete

- src/main/java/faang/school/godbless/test/TestExample.java
- src/main/java/faang/school/godbless/turnaround/Example.java
Iterating through half of our array
and while iterating swapping ints
> Turn around

- src/main/java/faang/school/godbless/groupusers/User.java
- src/main/java/faang/school/godbless/test/TestUser.java
For indexing of User objects
We use utility method getListOUsersByAge.
That why we decided getListOUsersByAge
to use on it private modifier.
> Group users by age:

- src/main/java/faang/school/godbless/bjs2_5177/ActionType.java
- src/main/java/faang/school/godbless/bjs2_5177/Main.java
- src/main/java/faang/school/godbless/bjs2_5177/UserAction.java
Task: https://faang-school.atlassian.net/browse/BJS2-5177
> BJS2-5177: Анализ активности пользователей в социальной сети

- src/main/java/faang/school/godbless/module/second/lambda/spam/Main.java
- src/main/java/faang/school/godbless/module/second/lambda/spam/MessageFilter.java
- src/main/java/faang/school/godbless/module/second/lambda/spam/MessageProcessor.java
https://faang-school.atlassian.net/browse/BJS2-5347?atlOrigin=eyJpIjoiZDY5ZDI0ZTU1ZTI0NGE3YjlmMzc0ZjFlMmNiM2QyMjEiLCJwIjoiaiJ9
> Решение задачи BJS2-5347 Фильтруем спам

- src/main/java/faang/school/godbless/BJS2_4919/House.java
- src/main/java/faang/school/godbless/BJS2_4919/Main.java
https://faang-school.atlassian.net/browse/BJS2-4919
> BJS2-4919: Java HashMap. Hame of thrones.

- src/main/java/faang/school/godbless/calculator/Calculator.java
- src/main/java/faang/school/godbless/calculator/Test.java
> BJS2-5281 calculator complete

- src/main/java/faang/school/godbless/lord_of_the_rings_rpg/Character.java
- src/main/java/faang/school/godbless/lord_of_the_rings_rpg/InventoryManager.java
- src/main/java/faang/school/godbless/lord_of_the_rings_rpg/Item.java
- src/main/java/faang/school/godbless/lord_of_the_rings_rpg/Test.java
BJS2-5325 lord_of_the_rings_rpg complete
> BJS2-5325 lord_of_the_rings_rpg complete

- src/main/java/faang/school/godbless/bjs2_5319/Gender.java
- src/main/java/faang/school/godbless/bjs2_5319/Main.java
- src/main/java/faang/school/godbless/bjs2_5319/Product.java
- src/main/java/faang/school/godbless/bjs2_5319/ProductOrder.java
- src/main/java/faang/school/godbless/bjs2_5319/RecommendationService.java
- src/main/java/faang/school/godbless/bjs2_5319/UserProfile.java
Task: https://faang-school.atlassian.net/browse/BJS2-5319
> BJS2-5319: Рекомендательная система

- src/main/java/faang/school/godbless/ReversedArrray/Example.java
- src/main/java/faang/school/godbless/ReversedArrray/Main.java
> BJS2-5299 Развернитесь!

- src/main/java/faang/school/godbless/library/Book.java
- src/main/java/faang/school/godbless/library/Main.java
Java HashMap: Библиотека Вестеросса
> Added class Book with overrided method equals() and hashCode().

- src/main/java/faang/school/godbless/game_of_throne/House.java
- src/main/java/faang/school/godbless/game_of_throne/Main.java
Возможно для поиска у меня слишком громоздкая махина получилась, если есть возможность лаконичнее написать, буду рад подсказке)
> Play this hashmap(Game of Thrones)

- src/main/java/faang/school/godbless/BJS2_4132/Main.java
- src/main/java/faang/school/godbless/BJS2_4132/WebPage.java
TASK: https://faang-school.atlassian.net/browse/BJS2-4132
> BJS2-4132: add web page index search

- src/main/java/faang/school/godbless/module/second/lambda/calculator/Calculator.java
- src/main/java/faang/school/godbless/module/second/lambda/calculator/CalculatorService.java
- src/main/java/faang/school/godbless/module/second/lambda/calculator/Main.java
https://faang-school.atlassian.net/browse/BJS2-5349?atlOrigin=eyJpIjoiMjA3ZDg5YjFhZGJjNGNhZmExY2NiNWQ1ZWUyNTg0YmMiLCJwIjoiaiJ9
> Решение задачи BJS2-5349 Калькулятор

- src/main/java/matrix/Coordinates.java
- src/main/java/matrix/FlipDirection.java
- src/main/java/matrix/Main.java
- src/main/java/matrix/MatrixTransformer.java
Сделал немного по-другому, крутил исходную матрицу и transformMatrix у меня принимает еще один параметр FlipDirection, в зависимости от того, как разворачивается матрица меняется проход  по ней
> BJS2-5215 : Повернем матрицу

- src/main/java/faang/school/godbless/BJS2_5192/Main.java
- src/main/java/faang/school/godbless/BJS2_5192/User.java
Task BJS2-5192 (Регистрация пользователя)
> Solution to task BJS2-5192

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/cacheCache/Main.java
- src/main/java/faang/school/godbless/cacheCache/MockWeather.java
- src/main/java/faang/school/godbless/cacheCache/WeatherData.java
https://faang-school.atlassian.net/browse/BJS2-4640
> Add solution for task BJS2-4640.

- src/main/java/faang/school/godbless/BJS2_5382/Main.java
- src/main/java/faang/school/godbless/BJS2_5382/SpellAction.java
- src/main/java/faang/school/godbless/BJS2_5382/SpellCaster.java
> Task BJS2-5382

- src/main/java/faang/school/godbless/BJS2_5391/Main.java
- src/main/java/faang/school/godbless/BJS2_5391/SpellAction.java
- src/main/java/faang/school/godbless/BJS2_5391/SpellCaster.java
TASK: https://faang-school.atlassian.net/browse/BJS2-5391
> BJS2-5391: add spell caster

- src/main/java/faang/school/godbless/lord/Character.java
- src/main/java/faang/school/godbless/lord/InventoryManager.java
- src/main/java/faang/school/godbless/lord/Item.java
- src/main/java/faang/school/godbless/lord/Main.java
Add Item, InventoryManager, Character, Main.
> Lord of the Rings RPG

- src/main/java/faang/school/godbless/school_math/Main.java
> Вспомним школу

- src/main/java/faang/school/godbless/stream/stream_api/Main.java
> Потренируем StreamAPI 1.

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/googleTranslator/DictionaryProcessor.java
- src/main/java/faang/school/godbless/googleTranslator/Main.java
https://faang-school.atlassian.net/browse/BJS2-5220
> Add solution for task BJS2-5220.

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/rememberSchool/Main.java
https://faang-school.atlassian.net/browse/BJS2-5370
> Add solution for task BJS2-5370.

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/Main.java
- src/main/java/faang/school/godbless/MessageFilter.java
- src/main/java/faang/school/godbless/MessageProcessor.java
https://faang-school.atlassian.net/browse/BJS2-5354
> Add solution for task BJS2-5354.

- src/main/java/faang/school/godbless/BJS2_5384/Main.java
- src/main/java/faang/school/godbless/BJS2_5384/MessageFilter.java
- src/main/java/faang/school/godbless/BJS2_5384/MessageProcessor.java
> Task BJS2-5384

- src/main/java/faang/school/godbless/bjs2_5296/Main.java
- src/main/java/faang/school/godbless/bjs2_5296/Student.java
- src/main/java/faang/school/godbless/bjs2_5296/StudentService.java
Task: https://faang-school.atlassian.net/browse/BJS2-5296
> BJS2-5296: Электронный дневник

- src/main/java/faang/school/godbless/amazon/Main.java
- src/main/java/faang/school/godbless/amazon/Product.java
> BJS2-5316-AmazonWarehouse

- src/main/java/faang/school/godbless/registration/RegistrationMain.java
- src/main/java/faang/school/godbless/registration/User.java
> User's registration

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/gmailRichFilters/Email.java
- src/main/java/faang/school/godbless/gmailRichFilters/EmailProcessor.java
- src/main/java/faang/school/godbless/gmailRichFilters/Main.java
https://faang-school.atlassian.net/browse/BJS2-5217
> Add solution for task BJS2-5217.

- src/main/java/faang/school/godbless/collecting/CollectingMain.java
- src/main/java/faang/school/godbless/collecting/User.java
> Collecting people by their hobbies

- src/main/java/faang/school/godbless/heroesOfMigthAndMagic/Angel.java
- src/main/java/faang/school/godbless/heroesOfMigthAndMagic/Battlefield.java
- src/main/java/faang/school/godbless/heroesOfMigthAndMagic/Creature.java
- src/main/java/faang/school/godbless/heroesOfMigthAndMagic/Griffin.java
- src/main/java/faang/school/godbless/heroesOfMigthAndMagic/Hero.java
- src/main/java/faang/school/godbless/heroesOfMigthAndMagic/Pikeman.java
- src/main/java/faang/school/godbless/heroesOfMigthAndMagic/Swordsman.java
Нужна подсказка. Почему у меня не работает removeCreature,
> BJS2-5316-Amazon Warehouse for check

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/handleErrorsGracefuly/ErrorHandling.java
- src/main/java/faang/school/godbless/handleErrorsGracefuly/ExceptionHandler.java
https://faang-school.atlassian.net/browse/BJS2-5218
> Add solution for task BJS2-5218.

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/calculator/Calculator.java
- src/main/java/faang/school/godbless/calculator/Main.java
https://faang-school.atlassian.net/browse/BJS2-5356
> Add solution for task BJS2-5356.

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/lordOfTheRings/Character.java
- src/main/java/faang/school/godbless/lordOfTheRings/InventoryManager.java
- src/main/java/faang/school/godbless/lordOfTheRings/Item.java
- src/main/java/faang/school/godbless/lordOfTheRings/Main.java
https://faang-school.atlassian.net/browse/BJS2-5361
> Add solution for task BJS2-5361.

- src/main/java/faang/school/godbless/registerusers/User.java
- src/main/java/faang/school/godbless/registerusers/constants/UserConstants.java
- src/main/java/faang/school/godbless/registerusers/validation/UserValidator.java
used custom validate class to validate
arguments in a constructor
Also chose to place constants VALID_JOBS and VALID_ADDRESSES in a separate class UserConstants because intuitively passing them to the validateParametersOfUser method as arguments doesn't sit well with me
> Register users:

- src/main/java/faang/school/godbless/BJS2_4128/Angel.java
- src/main/java/faang/school/godbless/BJS2_4128/Battlefield.java
- src/main/java/faang/school/godbless/BJS2_4128/Creature.java
- src/main/java/faang/school/godbless/BJS2_4128/Griffin.java
- src/main/java/faang/school/godbless/BJS2_4128/Hero.java
- src/main/java/faang/school/godbless/BJS2_4128/Main.java
- src/main/java/faang/school/godbless/BJS2_4128/Pikeman.java
- src/main/java/faang/school/godbless/BJS2_4128/Swordman.java
TASK: https://faang-school.atlassian.net/browse/BJS2-4128
> BJS2-4128: add battlefield for heroes & magics

- src/main/java/faang/school/godbless/user_activity_analysis/ActionType.java
- src/main/java/faang/school/godbless/user_activity_analysis/Main.java
- src/main/java/faang/school/godbless/user_activity_analysis/UserAction.java
- src/test/java/faang/school/godbless/user_activity_analysis/MainTest.java
Task: https://faang-school.atlassian.net/browse/BJS2-5256
> BJS2-5256: User activity analysis

- src/main/java/faang/school/godbless/collectingusers/User.java
in User set of hobbies and hobbies which come
from argument in "findHobbyLovers"
would be force worst case to run through
all hobbies of each User
At least contain method would not
take more than O(1)
> Collecting users

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/filtersInst/FilterProcessor.java
- src/main/java/faang/school/godbless/filtersInst/Image.java
- src/main/java/faang/school/godbless/filtersInst/Main.java
https://faang-school.atlassian.net/browse/BJS2-5351
> Add solution for task BJS2-5351.

- src/main/java/faang/school/godbless/BJS2_5400/Main.java
- src/main/java/faang/school/godbless/BJS2_5400/Notification.java
- src/main/java/faang/school/godbless/BJS2_5400/NotificationManager.java
TASK: https://faang-school.atlassian.net/browse/BJS2-5400
> BJS2-5400: add notification manager

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/amazonWarehouse/Main.java
- src/main/java/faang/school/godbless/amazonWarehouse/Product.java
https://faang-school.atlassian.net/browse/BJS2-4633
> Add solution for task BJS2-4633.

- src/main/java/faang/school/godbless/BJS2_4129/Main.java
- src/main/java/faang/school/godbless/BJS2_4129/Query.java
- src/main/java/faang/school/godbless/BJS2_4129/User.java
TASK: https://faang-school.atlassian.net/browse/BJS2-4129
> BJS2-4129: add ELK index

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/indexELK/Main.java
- src/main/java/faang/school/godbless/indexELK/Query.java
- src/main/java/faang/school/godbless/indexELK/QueryComparator.java
- src/main/java/faang/school/godbless/indexELK/User.java
https://faang-school.atlassian.net/browse/BJS2-4635
> Add solution for task BJS2-4635.

- src/main/java/faang/school/godbless/handle_errors_beautiful/ExceptionHandler.java
- src/main/java/faang/school/godbless/handle_errors_beautiful/Main.java
BJS2-5418 handle_errors_beautiful complete(solution 1)
> BJS2-5418 handle_errors_beautiful complete(solution 1)

- src/main/java/faang/school/godbless/practise_stream_API_1/StreamPractise.java
BJS2-5358 practise_stream_API_1 complete(solution 1)
> BJS2-5358 practise_stream_API_1 complete(solution 1)

- src/main/java/faang/school/godbless/module/second/lambda/meta/Main.java
- src/main/java/faang/school/godbless/module/second/lambda/meta/Notification.java
- src/main/java/faang/school/godbless/module/second/lambda/meta/NotificationManager.java
https://faang-school.atlassian.net/browse/BJS2-5301?atlOrigin=eyJpIjoiYWJjY2M4MTg2MjY3NDQwZDgwYjg3MTgxZDRiZjA4N2QiLCJwIjoiaiJ9
> Решение задачи BJS2-5301 Meta-вселенная?

- src/main/java/faang/school/godbless/BJS2_5479/MailSender.java
- src/main/java/faang/school/godbless/BJS2_5479/SenderRunnable.java
Задание: Вы работаете в Microsoft! BJS2-5479
> Kayfral BJS2-5479

- src/main/java/faang/school/godbless/module/second/lambda/instagram/FilterProcessor.java
- src/main/java/faang/school/godbless/module/second/lambda/instagram/Image.java
- src/main/java/faang/school/godbless/module/second/lambda/instagram/Main.java
https://faang-school.atlassian.net/browse/BJS2-5313?atlOrigin=eyJpIjoiMzE0NmVmNWIwMjIyNDNjMDk0ZDgxMmJlNDY1YTUxNWUiLCJwIjoiaiJ9
> Решение задачи BJS2-5313 Фильтры Instagram

- src/main/java/faang/school/godbless/module/second/lambda/gmail/Email.java
- src/main/java/faang/school/godbless/module/second/lambda/gmail/EmailProcessor.java
- src/main/java/faang/school/godbless/module/second/lambda/gmail/Main.java
https://faang-school.atlassian.net/browse/BJS2-5329?atlOrigin=eyJpIjoiOTRmMjcyZjI1ODQyNGQzMGFlNjFkMDljYmFhNzg2ZGUiLCJwIjoiaiJ9
> Решение задачи BJS2-5329 Gmail Rich Filters

- src/main/java/faang/school/godbless/you_work_for_microsoft/MailSender.java
- src/main/java/faang/school/godbless/you_work_for_microsoft/SenderRunnable.java
Task: https://faang-school.atlassian.net/browse/BJS2-5441
> BJS2-5441: You work for Microsoft

- src/main/java/faang/school/godbless/CacheLRU/Data.java
- src/main/java/faang/school/godbless/CacheLRU/DataNotFoundException.java
- src/main/java/faang/school/godbless/CacheLRU/Main.java
- src/main/java/faang/school/godbless/CacheLRU/data.java
BJS2-4320 Java HashMap: LRU Cache
> BJS2-4320 Java HashMap: LRU Cache

- src/main/java/faang/school/godbless/catchingEvents/Main.java
- src/main/java/faang/school/godbless/catchingEvents/StreamEvent.java
Catching events- не работает удаления
> Egorp bjs2 5263 catching events

- src/main/java/faang/school/godbless/backToSchool/Main.java
> BJS2-5558-back to school for review

- src/main/java/faang/school/godbless/distributed_army/Main.java
- src/main/java/faang/school/godbless/distributed_army/model/Archer.java
- src/main/java/faang/school/godbless/distributed_army/model/Army.java
- src/main/java/faang/school/godbless/distributed_army/model/Counter.java
- src/main/java/faang/school/godbless/distributed_army/model/Creature.java
- src/main/java/faang/school/godbless/distributed_army/model/Mage.java
- src/main/java/faang/school/godbless/distributed_army/model/Swordsman.java
Task: https://faang-school.atlassian.net/browse/BJS2-5454
> BJS2-5454: Distributed army

- src/main/java/faang/school/godbless/BJS2_5408/Droid.java
- src/main/java/faang/school/godbless/BJS2_5408/DroidMessageEncryptor.java
- src/main/java/faang/school/godbless/BJS2_5408/Main.java
У меня есть два вопроса. В классе Droid находится два метода. Оба имеют алгоритм, в который нужно вникать. Первый вопрос, Будет ли хорошо в таком случае написать краткое описание данного алгоритма перед методом или не нужно? (Я хочу сделать описание, чтобы легче было понимать как работает данный алгоритм). Второй вопрос, если всё же описывать алгоритмы, то стоит ли описывать работу алгоритмов шифровки данных или их оставлять без комментариев?
> Задание: Секреты дроидов BJS2-5408

- src/main/java/faang/school/godbless/filters/FilterProcessor.java
- src/main/java/faang/school/godbless/filters/Image.java
> BJS2-5551 filters Instagram

- src/main/java/faang/school/godbless/BJS2_4130/Main.java
- src/main/java/faang/school/godbless/BJS2_4130/Student.java
- src/main/java/faang/school/godbless/BJS2_4130/Subject.java
TASK: https://faang-school.atlassian.net/browse/BJS2-4130
> BJS2-4130: add double cache task

- src/main/java/faang/school/godbless/sprint2/BJS2_5399/Main.java
- src/main/java/faang/school/godbless/sprint2/BJS2_5399/MessageFilter.java
- src/main/java/faang/school/godbless/sprint2/BJS2_5399/MessageProcessor.java
TASK: https://faang-school.atlassian.net/browse/BJS2-5399
> BJS2-5399: add MessageFilter

- src/main/java/faang/school/godbless/multithreading/task_1/MailSender.java
- src/main/java/faang/school/godbless/multithreading/task_1/sender/SenderRunnable.java
Я понимаю, что тут очень сильно напрашиваются циклы, но очень уж хотелось join-ы руками поменять, чтобы получше понять, как это работает
> Вы работаете в Microsoft!

- src/main/java/faang/school/godbless/BJS2_5618/MailSender.java
- src/main/java/faang/school/godbless/BJS2_5618/SenderRunnable.java
> Task BJS2-5618

- src/main/java/faang/school/godbless/errorHandling/ErrorHandler.java
- src/main/java/faang/school/godbless/errorHandling/ExceptionHandler.java
- src/main/java/faang/school/godbless/errorHandling/Main.java
- src/main/java/faang/school/godbless/errorHandling/RemoteService.java
> BJS2-5542-ErrorHandler -for review

- src/main/java/faang/school/godbless/sprint2/BJS2_5387/ExceptionHandler.java
- src/main/java/faang/school/godbless/sprint2/BJS2_5387/Main.java
TASK: https://faang-school.atlassian.net/browse/BJS2-5387
> BJS2-5387: add withErrorHandling

- src/main/java/faang/school/godbless/filtersinstagram/FilterProcessor.java
- src/main/java/faang/school/godbless/filtersinstagram/Image.java
- src/main/java/faang/school/godbless/filtersinstagram/test/TestFilterProcessor.java
Был реализован класс с
методами высочайшего порядка
Методы были протестированы
> Фильтры Instagram

- src/main/java/faang/school/godbless/sprint2/BJS2_5386/Email.java
- src/main/java/faang/school/godbless/sprint2/BJS2_5386/EmailProcessor.java
- src/main/java/faang/school/godbless/sprint2/BJS2_5386/Main.java
TASK: https://faang-school.atlassian.net/browse/BJS2-5386
> BJS2-5386: add EmailProcessor

- src/main/java/faang/school/godbless/sprint2/BJS2_5389/DictionaryProcessor.java
- src/main/java/faang/school/godbless/sprint2/BJS2_5389/Main.java
TASK: https://faang-school.atlassian.net/browse/BJS2-5389
> BJS2-5389: add DictionaryProcessor

- src/main/java/faang/school/godbless/sprint2/BJS2_5392/Calculator.java
- src/main/java/faang/school/godbless/sprint2/BJS2_5392/Main.java
TASK: https://faang-school.atlassian.net/browse/BJS2-5392
> BJS2-5392: add Calculator

- src/main/java/faang/school/godbless/sprint2/BJS2_5394/Character.java
- src/main/java/faang/school/godbless/sprint2/BJS2_5394/InventoryManager.java
- src/main/java/faang/school/godbless/sprint2/BJS2_5394/Item.java
- src/main/java/faang/school/godbless/sprint2/BJS2_5394/Main.java
TASK: https://faang-school.atlassian.net/browse/BJS2-5394
> BJS2-5394: add InventoryManager

- src/main/java/faang/school/godbless/BJS2_5634/Main.java
- src/main/java/faang/school/godbless/BJS2_5634/WeatherData.java
- src/main/java/faang/school/godbless/BJS2_5634/WeatherService.java
https://faang-school.atlassian.net/browse/BJS2-5634
> BJS2-5634: Java HashMap: Кэшируем, кэшируем

- src/main/java/faang/school/godbless/javahashmap/westeroslibrary/Book.java
- src/main/java/faang/school/godbless/javahashmap/westeroslibrary/Main.java
- src/main/java/faang/school/godbless/javahashmap/westeroslibrary/test/TestMain.java
- Был ркализованы классы Book и Main
- В класск Book были переопределены методы equals и hashCode
- В класск Main была реализована логика
- В класса TestMain протестрированы публичные методы класса Main
> Java HashMap: Библиотека Вестеросса

- src/main/java/faang/school/godbless/you_work_for_microsoft/MailSender.java
- src/main/java/faang/school/godbless/you_work_for_microsoft/SenderRunnable.java
BJS2-5539 you_work_for_microsoft complete(solution 1)
> BJS2-5539 you_work_for_microsoft complete(solution 1)

- src/main/java/faang/school/godbless/bjs2_5523/Food.java
- src/main/java/faang/school/godbless/bjs2_5523/House.java
- src/main/java/faang/school/godbless/bjs2_5523/Room.java
Task: https://faang-school.atlassian.net/browse/BJS2-5523
> BJS2-5523: Mice are very nice!

- src/main/java/faang/school/godbless/bjs2_5439/Archer.java
- src/main/java/faang/school/godbless/bjs2_5439/Army.java
- src/main/java/faang/school/godbless/bjs2_5439/Mage.java
- src/main/java/faang/school/godbless/bjs2_5439/Main.java
- src/main/java/faang/school/godbless/bjs2_5439/Swordsman.java
- src/main/java/faang/school/godbless/bjs2_5439/Unit.java
Task: https://faang-school.atlassian.net/browse/BJS2-5439
> BJS2-5439: Распределенная армия героев меча и магии

- src/main/java/faang/school/godbless/bjs2_5448/BigBangTheory.java
- src/main/java/faang/school/godbless/bjs2_5448/Task.java
Task: https://faang-school.atlassian.net/browse/BJS2-5448
> BJS2-5448: The Big Bang Theory

- src/main/java/faang/school/godbless/the_big_bang_theory/BigBangTheory.java
- src/main/java/faang/school/godbless/the_big_bang_theory/Task.java
BJS2-5597 the_big_bang_theory complete(solution 1)
> BJS2-5597 the_big_bang_theory complete(solution 1)

- src/main/java/faang/school/godbless/bjs2_5451/Chore.java
- src/main/java/faang/school/godbless/bjs2_5451/WeasleyFamily.java
Task: https://faang-school.atlassian.net/browse/BJS2-5451
> BJS2-5451: They were very nice but extremely poor

- src/main/java/faang/school/godbless/they_were_very_nice_but_extremely_poor/Chore.java
- src/main/java/faang/school/godbless/they_were_very_nice_but_extremely_poor/WeasleyFamily.java
BJS2-5608 they_were_very_nice_but_extremely_poor complete(solution 1)
> BJS2-5608 they_were_very_nice_but_extremely_poor complete(solution 1)

- src/main/java/faang/school/godbless/distributed_army_of_heroes_of_might_and_magic/Archer.java
- src/main/java/faang/school/godbless/distributed_army_of_heroes_of_might_and_magic/Army.java
- src/main/java/faang/school/godbless/distributed_army_of_heroes_of_might_and_magic/Division.java
- src/main/java/faang/school/godbless/distributed_army_of_heroes_of_might_and_magic/Mage.java
- src/main/java/faang/school/godbless/distributed_army_of_heroes_of_might_and_magic/Main.java
- src/main/java/faang/school/godbless/distributed_army_of_heroes_of_might_and_magic/Swordsman.java
BJS2-5545 distributed_army_of_heroes_of_might_and_magic complete(solution 1)
> BJS2-5545 distributed_army_of_heroes_of_might_and_magic complete(solution 1)

- src/main/java/faang/school/godbless/module/third/parallelism/microsoft/MailSender.java
- src/main/java/faang/school/godbless/module/third/parallelism/microsoft/SenderRunnable.java
https://faang-school.atlassian.net/browse/BJS2-5672?atlOrigin=eyJpIjoiYzdmNTI0OGU4N2QxNDA1ZGE4MDhkZTFiZTQxNmQxYzQiLCJwIjoiaiJ9
> Решение задачи BJS2-5672 Вы работаете в Microsoft!

- src/main/java/BJS2_5670/FoodDeliveryTask.java
- src/main/java/BJS2_5670/GriffinsFoodDelivery.java
Вопрос, ожидание доставки клиенту это была имитацией обычной доставки, только у них вместо Thread.Sleep() какой-то код?
> BJS2-5670: Накормите Питера Гриффина

- src/main/java/faang/school/godbless/the_big_bang_theory/BigBangTheory.java
- src/main/java/faang/school/godbless/the_big_bang_theory/Task.java
Task: https://faang-school.atlassian.net/browse/BJS2-5459
> BJS2-5459: The Big Bang theory

- src/main/java/faang/school/godbless/they_were_nice/Chore.java
- src/main/java/faang/school/godbless/they_were_nice/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-5503
> JS2-5503: They were nice but extremely poor

- src/main/java/faang/school/godbless/module/second/stream/one/Main.java
https://faang-school.atlassian.net/browse/BJS2-5504?atlOrigin=eyJpIjoiODJjNWJhNGYyYTM1NGNmYzg4ZjFmMGU1NDIyNmZmODciLCJwIjoiaiJ9
> Решение задачи BJS2-5504 Потренируем StreamAPI 1

- src/main/java/faang/school/godbless/workInMicrosoft/MailSender.java
- src/main/java/faang/school/godbless/workInMicrosoft/SenderRunnable.java
> BJS2-5651-workInMicrosoft

- src/main/java/faang/school/godbless/YouAreWorkingInMicrosoft/MailSender.java
- src/main/java/faang/school/godbless/YouAreWorkingInMicrosoft/SenderRunnable.java
Поставил создание нового потока в цикл fori, потому, что как я понял, это в условии задачи (В подсказках) это требуется. Но из лекции Влада, понял, что так лучше не делать, так как съедает много памяти и лучше заключать в thread pool
> BJS2-5482 Multithreading: Parallelism: Вы работаете в Microsoft!

- src/main/java/faang/school/godbless/droidSecrets/Droid.java
- src/main/java/faang/school/godbless/droidSecrets/DroidMessageEncryptor.java
- src/main/java/faang/school/godbless/droidSecrets/Main.java
> BJS2-5559-Droid secrets for review

- src/main/java/streamAPI_1/Main.java
Ссылки на методы решил не использовать и не обращал внимания на подсказки IDE, мне пока что так более понятнее)))
Пока что стримы тяжелее всего заходят, а еще многопоточка...RIP...
> Потренируем StreamAPI 1 - BJS2-5306, решил задание отправляю PR

- src/main/java/faang/school/godbless/practicestreamapi1/Practice.java
Были реализованы все методы из задания
> Потренируем StreamAPI 1

- build.gradle
- src/main/java/faang/school/godbless/JobAnalyzer/DataAnalyzer.java
- src/main/java/faang/school/godbless/JobAnalyzer/Job.java
- src/main/java/faang/school/godbless/JobAnalyzer/JobScraper.java
- src/main/java/faang/school/godbless/JobAnalyzer/JobStreamProcessor.java
- src/main/java/faang/school/godbless/JobAnalyzer/Main.java
- src/main/java/faang/school/godbless/JobAnalyzer/TrendGranularity.java
BJS2-5171 Java 8: Коллекции, Stream API, Optional: Анализатор вакансий
> BJS2-5171 Java 8: Коллекции, Stream API, Optional: Анализатор вакансий

- src/main/java/faang/school/godbless/electronicDiary/Main.java
- src/main/java/faang/school/godbless/electronicDiary/Service.java
- src/main/java/faang/school/godbless/electronicDiary/Student.java
> BJS2-5583-ElectronicDairy for review

- src/main/java/Multithreading_youAreWorkingMicrosoft/MailSender.java
- src/main/java/Multithreading_youAreWorkingMicrosoft/SenderRunnable.java
Выполнил задание отправляю PR.
+ решил время выполнения замерить, хотел ещё обычным перебором организовать поиск и сравнить, но не стал заморачиваться, тк задачек ещё много!
> Вы работаете в Microsoft! - BJS2-5640

- src/main/java/faang/school/godbless/foods/FoodDeliveryTask.java
- src/main/java/faang/school/godbless/foods/GriffinsFoodDelivery.java
> bjs2 5549 feed peter griffen

- src/main/java/faang/school/godbless/bjs2_5562/Main.java
- src/main/java/faang/school/godbless/bjs2_5562/Person.java
- src/main/java/faang/school/godbless/bjs2_5562/PersonNamePrinter.java
Task: https://faang-school.atlassian.net/browse/BJS2-5562
> BJS2-5562: Помогите коллеге

- build.gradle
- src/main/java/faang/school/godbless/bjs_5436/MailSender.java
- src/main/java/faang/school/godbless/bjs_5436/SenderRunnable.java
Task: https://faang-school.atlassian.net/browse/BJS2-5436
> BJS2-5436: Вы работаете в Microsoft!

- src/main/java/faang/school/godbless/bjs2_5437/FoodDeliveryTask.java
- src/main/java/faang/school/godbless/bjs2_5437/GriffinsFoodDelivery.java
Task: https://faang-school.atlassian.net/browse/BJS2-5437
> BJS2-5437: Накормите Питера Гриффина

- src/main/java/faang/school/godbless/bjs2_5580/CashierThread.java
- src/main/java/faang/school/godbless/bjs2_5580/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-5580
> BJS2-5580: Очередь в Walmart

- src/main/java/faang/school/godbless/bjs2_5555/Main.java
- src/main/java/faang/school/godbless/bjs2_5555/RocketLaunch.java
Task: https://faang-school.atlassian.net/browse/BJS2-5555
> BJS2-5555: Космическая программа SpaceX

- src/main/java/faang/school/godbless/bjs2_5582/Pig1Thread.java
- src/main/java/faang/school/godbless/bjs2_5582/Pig2Thread.java
- src/main/java/faang/school/godbless/bjs2_5582/Pig3Thread.java
- src/main/java/faang/school/godbless/bjs2_5582/PigThread.java
- src/main/java/faang/school/godbless/bjs2_5582/ThreeLittlePigs.java
Task: https://faang-school.atlassian.net/browse/BJS2-5582
> BJS2-5582: Наконец-то нормальная игра

- src/main/java/Multithreading_FeedPeteGriffin/FoodDeliveryTask.java
- src/main/java/Multithreading_FeedPeteGriffin/GriffinsFoodDelivery.java
> Накормите Питера Гриффина - BJS2-5644

- src/main/java/faang/school/godbless/practice/streamapi2/Employee.java
- src/main/java/faang/school/godbless/practice/streamapi2/Practice.java
- src/main/java/faang/school/godbless/practice/streamapi2/test/TestPractice.java
Реализованы и протестированы
все методы из задания
> Потренируем StreamAPI 2

- src/main/java/faang/school/godbless/BJS2_5532/GooglePhotosAutoUploader.java
- src/main/java/faang/school/godbless/BJS2_5532/Main.java
> Задание: Google Photo sync BJS2-5532

- src/main/java/TheBigBangTheory/BigBangTheory.java
- src/main/java/TheBigBangTheory/Task.java
> The Big Bang Theory - BJS2-5647

- src/main/java/faang/school/godbless/tournament/Knight.java
- src/main/java/faang/school/godbless/tournament/Main.java
- src/main/java/faang/school/godbless/tournament/Trial.java
Task: https://faang-school.atlassian.net/browse/BJS2-5512
> BJS2-5512: Tournament

- src/main/java/faang/school/godbless/BJS25688/BigBangTheory.java
- src/main/java/faang/school/godbless/BJS25688/Task.java
> BJS2-5688 The Big Bang Theory - Реализация задачи

- src/main/java/faang/school/godbless/way_with_finger/City.java
- src/main/java/faang/school/godbless/way_with_finger/CityWorker.java
- src/main/java/faang/school/godbless/way_with_finger/Location.java
- src/main/java/faang/school/godbless/way_with_finger/Main.java
- src/main/java/faang/school/godbless/way_with_finger/Monster.java
Task: https://faang-school.atlassian.net/browse/BJS2-5527
> BJS2-5527: Way with finger

- src/main/java/faang/school/godbless/BJS25683/MailSender.java
- src/main/java/faang/school/godbless/BJS25683/SenderRunnable.java
BJS2-5683 Вы работаете в Microsoft!
> BJS2-5683 Вы работаете в Microsoft! - Реализация задачи

- src/main/java/faang/school/godbless/module/third/parallelism/peter/FoodDeliveryTask.java
- src/main/java/faang/school/godbless/module/third/parallelism/peter/GriffinsFoodDelivery.java
https://faang-school.atlassian.net/browse/BJS2-5677?atlOrigin=eyJpIjoiNzg5Yjc3ZDlhNTU4NGM4OWI1Yzg4M2RhNTcxMmJhZmQiLCJwIjoiaiJ9
> Решение задачи BJS2-5677 Накормите Питера Гриффина

- src/main/java/faang/school/godbless/BJS25686/FoodDeliveryTask.java
- src/main/java/faang/school/godbless/BJS25686/GriffinsFoodDelivery.java
BJS2-5686 Накормите Питера Гриффина
> BJS2-5686 Накормите Питера Гриффина - Реализация задачи

- src/main/java/faang/school/godbless/millions_uber/FareCalculator.java
- src/main/java/faang/school/godbless/millions_uber/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-5120
> BJS2-5120: Millions Uber

- src/main/java/Multithreading_ArmyOfTheHeroes/Archer.java
- src/main/java/Multithreading_ArmyOfTheHeroes/Army.java
- src/main/java/Multithreading_ArmyOfTheHeroes/Character.java
- src/main/java/Multithreading_ArmyOfTheHeroes/CharacterPowerThread.java
- src/main/java/Multithreading_ArmyOfTheHeroes/Mage.java
- src/main/java/Multithreading_ArmyOfTheHeroes/Main.java
- src/main/java/Multithreading_ArmyOfTheHeroes/Swordsman.java
> Распределенная армия героев меча и магии - BJS2-5646

- src/main/java/LockingSpotify/Music.java
- src/main/java/LockingSpotify/Player.java
выполнил задание отправляю на PR
> Блокировка Spotify - BJS2-5771

- src/main/java/faang/school/godbless/lambda/BJS2_5701/FilterProcessor.java
- src/main/java/faang/school/godbless/lambda/BJS2_5701/Image.java
- src/main/java/faang/school/godbless/lambda/BJS2_5701/Main.java
https://faang-school.atlassian.net/browse/BJS2-5701
> BJS2-5701: Фильтры Instagram

- src/main/java/faang/school/godbless/microsoft/MailSender.java
- src/main/java/faang/school/godbless/microsoft/SenderRunnable.java
> Microsoft Outlook

- src/main/java/faang/school/godbless/bjs2_5598/GooglePhotosAutoUploader.java
- src/main/java/faang/school/godbless/bjs2_5598/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-5598
> BJS2-5598: Google Photo sync

- src/main/java/faang/school/godbless/bjs2_5628/Main.java
- src/main/java/faang/school/godbless/bjs2_5628/VideoManager.java
Task: https://faang-school.atlassian.net/browse/BJS2-5628
> BJS2-5628: Счетчик просмотров на YouTube

- src/main/java/faang/school/godbless/bjs2_5619/Boss.java
- src/main/java/faang/school/godbless/bjs2_5619/Main.java
- src/main/java/faang/school/godbless/bjs2_5619/Player.java
Task: https://faang-school.atlassian.net/browse/BJS2-5619
> BJS2-5619: Supercow!

- src/main/java/faang/school/godbless/bjs2_5621/Game.java
- src/main/java/faang/school/godbless/bjs2_5621/Main.java
- src/main/java/faang/school/godbless/bjs2_5621/Player.java
Task: https://faang-school.atlassian.net/browse/BJS2-5621
> BJS2-5621: Bro Force!

- src/main/java/faang/school/godbless/bjs2_5706/Main.java
- src/main/java/faang/school/godbless/bjs2_5706/TelegramBot.java
Task: https://faang-school.atlassian.net/browse/BJS2-5706
> BJS2-5706: Telegram-бот

- src/main/java/faang/school/godbless/bjs2_5705/Main.java
- src/main/java/faang/school/godbless/bjs2_5705/TamagotchiVlad.java
- src/main/java/faang/school/godbless/bjs2_5705/VladController.java
Task: https://faang-school.atlassian.net/browse/BJS2-5705
> BJS2-5705: Тамагочи Влад

- src/main/java/faang/school/godbless/BJS2_5750/FoodDeliveryTask.java
- src/main/java/faang/school/godbless/BJS2_5750/GriffinsFoodDelivery.java
> Task BJS2-5750

- src/main/java/faang/school/godbless/synchronization/task_1/Music.java
- src/main/java/faang/school/godbless/synchronization/task_1/model/Player.java
Я никогда не пользовался Spotify, и не знаю, насколько это верно, но на моем плеере можно переключать музыку, когда она не играет, поэтому в методах методах skip() и previous() я не стал делать блоки с синхронизацией.
> Блокировка Spotify

- src/main/java/faang/school/godbless/KingLandingTournament/King.java
- src/main/java/faang/school/godbless/KingLandingTournament/Knight.java
- src/main/java/faang/school/godbless/KingLandingTournament/Trial.java
Я создал по 3 испытания для каждого рыцаря, думаю не проблема)
> BJS2-5487 Multithreading: Parallelism: Турнир в Королевской гавани

- src/main/java/faang/school/godbless/SpamFilter/Main.java
- src/main/java/faang/school/godbless/SpamFilter/MessageFilter.java
- src/main/java/faang/school/godbless/SpamFilter/MessageProcessor.java
BJS2-5055 Java 8: Функциональные интерфейсы, Лямбды: Фильтруем спам
> BJS2-5055 Java 8: Функциональные интерфейсы, Лямбды: Фильтруем спам

- src/main/java/faang/school/godbless/rpg/Character.java
- src/main/java/faang/school/godbless/rpg/InventoryManager.java
- src/main/java/faang/school/godbless/rpg/Item.java
> BJS2-5620 Lord of the Rings RPG

- src/main/java/faang/school/godbless/LordOfTheRingsRPG/Character.java
- src/main/java/faang/school/godbless/LordOfTheRingsRPG/InventoryManager.java
- src/main/java/faang/school/godbless/LordOfTheRingsRPG/Item.java
- src/main/java/faang/school/godbless/LordOfTheRingsRPG/Main.java
BJS2-5050 Java 8: Функциональные интерфейсы, Лямбды: Lord of the Rings RPG
Идея подсказала, решил в первый раз воспользоваться record, правильное решение?
> BJS2-5050 Java 8: Функциональные интерфейсы, Лямбды: Lord of the Rings RPG

- src/main/java/faang/school/godbless/module/third/parallelism/bang/BigBangTheory.java
- src/main/java/faang/school/godbless/module/third/parallelism/bang/Task.java
https://faang-school.atlassian.net/browse/BJS2-5724?atlOrigin=eyJpIjoiOWE1NzhiYjczODA4NGQ3OWFiYmE2MGU3ZTUwZGFkYjciLCJwIjoiaiJ9
> Решение задачи BJS2-5724 The Big Bang Theory

- src/main/java/faang/school/godbless/BJS25689/Chore.java
- src/main/java/faang/school/godbless/BJS25689/WeasleyFamily.java
BJS2-5689 They were very nice but extremely poor
> BJS2-5689 They were very nice but extremely poor - Реализация задачи

- src/main/java/faang/school/godbless/module/third/parallelism/heroes/Army.java
- src/main/java/faang/school/godbless/module/third/parallelism/heroes/Main.java
- src/main/java/faang/school/godbless/module/third/parallelism/heroes/creature/Archer.java
- src/main/java/faang/school/godbless/module/third/parallelism/heroes/creature/Creature.java
- src/main/java/faang/school/godbless/module/third/parallelism/heroes/creature/Mage.java
- src/main/java/faang/school/godbless/module/third/parallelism/heroes/creature/Swordsman.java
https://faang-school.atlassian.net/browse/BJS2-5679?atlOrigin=eyJpIjoiNTU0Zjc4YWYwMTk3NDhiYzk2ZWI3ZDA4OTRhZmE4ZDEiLCJwIjoiaiJ9
> Решение задачи BJS2-5679 Распределенная армия героев меча и магии

- src/main/java/faang/school/godbless/BJS25693/Food.java
- src/main/java/faang/school/godbless/BJS25693/House.java
- src/main/java/faang/school/godbless/BJS25693/Room.java
- src/main/java/faang/school/godbless/BJS25693/TomAndJerryHouse.java
> BJS2-5693 Mice are very nice! - Реализация задачи

- src/main/java/faang/school/godbless/module/third/parallelism/turnir/King.java
- src/main/java/faang/school/godbless/module/third/parallelism/turnir/Knight.java
- src/main/java/faang/school/godbless/module/third/parallelism/turnir/Trial.java
https://faang-school.atlassian.net/browse/BJS2-5729?atlOrigin=eyJpIjoiYjI5Yzc4MjY3NmEwNDRjYjk5ZGU2MjUwNzlkNTMwYWQiLCJwIjoiaiJ9
> Решение задачи BJS2-5729 Турнир в Королевской гавани

- src/main/java/faang/school/godbless/mice_are_very_nice/Food.java
- src/main/java/faang/school/godbless/mice_are_very_nice/House.java
- src/main/java/faang/school/godbless/mice_are_very_nice/Room.java
Task: https://faang-school.atlassian.net/browse/BJS2-5557
> BJS2-5557: Mice are very nice

- src/main/java/faang/school/godbless/spotify_blocking/Music.java
- src/main/java/faang/school/godbless/spotify_blocking/Player.java
Task: https://faang-school.atlassian.net/browse/BJS2-5694
> BJS2-5694: Spotify blocking

- src/main/java/faang/school/godbless/module/third/synchronization/spotify/Music.java
- src/main/java/faang/school/godbless/module/third/synchronization/spotify/Player.java
https://faang-school.atlassian.net/browse/BJS2-5802?atlOrigin=eyJpIjoiOWU4YWYwYWY1MjNkNDBkYWI3MWZmZWU5MjEzMjgyNjQiLCJwIjoiaiJ9
> Решение задачи BJS2-5802 Блокировка Spotify

- src/main/java/faang/school/godbless/analysisofuseractivityonasocialnetwork/FastBigDecimalPercentage.java
- src/main/java/faang/school/godbless/analysisofuseractivityonasocialnetwork/UserAction.java
- src/main/java/faang/school/godbless/analysisofuseractivityonasocialnetwork/UserActionType.java
- src/main/java/faang/school/godbless/analysisofuseractivityonasocialnetwork/UsersDataAnalyzer.java
Реализованы все методы из задания
> Анализ активности пользователей в социальной сети

- src/main/java/faang/school/godbless/GmailRichFilters/Email.java
- src/main/java/faang/school/godbless/GmailRichFilters/EmailProcessor.java
- src/main/java/faang/school/godbless/GmailRichFilters/Main.java
BJS2-5043 Java 8: Функциональные интерфейсы, Лямбды: Gmail Rich Filters
> ethiqque-BJS2-5043

- src/main/java/calculator/Calculator.java
- src/main/java/calculator/Main.java
Не могу найти способ корректно получать результат больше, чем максимальное значение int. Добавила промежуточную переменную `intermediateResult` сначала с типом long, чтобы преобразовывать в int только промежуточную переменную(предполагая, что тип переменной result менялся из-за `(int) result` или `Long.valueOf(result).intValue()`), но даже в таком случае переменная `result `некорректна(
> BJS2-5755 - Калькулятор

- src/main/java/TheWitcher/City.java
- src/main/java/TheWitcher/CityWorker.java
- src/main/java/TheWitcher/Location.java
- src/main/java/TheWitcher/Monster.java
- src/main/java/TheWitcher/Witcher.java
При первом решении что-то пошло не так, получилось "навалить кринжа" в данном методе(findNearestMonster), пришлось воспользоваться разбором... Но принцип я понял!:) 
+ благодаря разбору получилось некоторые строчки сократить, а то я там изобрел велосипед...
> Путь пальцем проложи… - BJS2-5718

- src/main/java/Supercow/Boss.java
- src/main/java/Supercow/Main.java
- src/main/java/Supercow/Player.java
выполнил задание отправляю на PR
> Supercow! - BJS2-5775

- src/main/java/faang/school/godbless/optimizingDataCenter/DataCenter.java
- src/main/java/faang/school/godbless/optimizingDataCenter/DataCenterService.java
- src/main/java/faang/school/godbless/optimizingDataCenter/EnergyEfficencyOptimizationStrategy.java
- src/main/java/faang/school/godbless/optimizingDataCenter/LoadBalancingOptimizationStrategy.java
- src/main/java/faang/school/godbless/optimizingDataCenter/Main.java
- src/main/java/faang/school/godbless/optimizingDataCenter/OptimizationStrategy.java
- src/main/java/faang/school/godbless/optimizingDataCenter/ResourceRequest.java
- src/main/java/faang/school/godbless/optimizingDataCenter/Server.java
Optimizing data center - for check
> BJS2-5353-Optimizing data center - for check

- src/main/java/faang/school/godbless/lordOfTheRings/Character.java
- src/main/java/faang/school/godbless/lordOfTheRings/InventoryManager.java
- src/main/java/faang/school/godbless/lordOfTheRings/Item.java
- src/main/java/faang/school/godbless/lordOfTheRings/Main.java
Lord Of The Rings RPS - for check
> BJS2-5541-LordOfTheRingsRPS - for check

- src/main/java/faang/school/godbless/big_bang_theory/BigBangTheory.java
- src/main/java/faang/school/godbless/big_bang_theory/Task.java
> BJS2-5745 The Big Bang Theory

- src/main/java/faang/school/godbless/module/third/parallelism/poor/Chore.java
- src/main/java/faang/school/godbless/module/third/parallelism/poor/WeasleyFamily.java
https://faang-school.atlassian.net/browse/BJS2-5726?atlOrigin=eyJpIjoiM2ZlYmQzZmNmNWRhNDNjZDg3MjQxOWNkYTlhZTc3NmIiLCJwIjoiaiJ9
> Решение задачи BJS2-5726 They were very nice but extremely poor

- src/main/java/faang/school/godbless/youtube_view_counter/Main.java
- src/main/java/faang/school/godbless/youtube_view_counter/VideoManager.java
Task: https://faang-school.atlassian.net/browse/BJS2-5788
> BJS2-5788: Youtube views counter

- src/main/java/faang/school/godbless/supercow/Boss.java
- src/main/java/faang/school/godbless/supercow/Main.java
- src/main/java/faang/school/godbless/supercow/Player.java
Task: https://faang-school.atlassian.net/browse/BJS2-5710
> BJS2-5710: Supercow!

- src/main/java/faang/school/godbless/google_photo_sync/GooglePhotosAutoUploader.java
- src/main/java/faang/school/godbless/google_photo_sync/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-5704
> BJS2-5704: Google photo sync

- src/main/java/faang/school/godbless/bro_force/Game.java
- src/main/java/faang/school/godbless/bro_force/Main.java
- src/main/java/faang/school/godbless/bro_force/Person.java
- src/main/java/faang/school/godbless/bro_force/UpdateType.java
Task: https://faang-school.atlassian.net/browse/BJS2-5721
> BJS2-5721: Bro force

- src/main/java/faang/school/godbless/BJS2_5366/FilterProcessor.java
- src/main/java/faang/school/godbless/BJS2_5366/Image.java
- src/main/java/faang/school/godbless/BJS2_5366/Main.java
Task BJS2-5366 (Фильтры Instagram)
> Solution to task BJS2-5366

- src/main/java/faang/school/godbless/streamApi1/StreamAPI.java
> Egorp bjs2 5599 stream api one

- src/main/java/faang/school/godbless/BJS2_5653/Main.java
- src/main/java/faang/school/godbless/BJS2_5653/Stream.java
Task BJS2-5653 (Потренируем StreamAPI 1)
> Solution to task BJS2-5653

- src/main/java/faang/school/godbless/BJS2_5831/Music.java
- src/main/java/faang/school/godbless/BJS2_5831/Player.java
> Task BJS2-5831

- src/main/java/faang/school/godbless/bjs2_5684/Chat.java
- src/main/java/faang/school/godbless/bjs2_5684/ChatManager.java
- src/main/java/faang/school/godbless/bjs2_5684/Main.java
- src/main/java/faang/school/godbless/bjs2_5684/User.java
- src/main/java/faang/school/godbless/bjs2_5684/UserList.java
Task: https://faang-school.atlassian.net/browse/BJS2-5684
> BJS2-5684: Matters of the heart

- src/main/java/faang/school/godbless/lambda/BJS2_5696/Main.java
- src/main/java/faang/school/godbless/lambda/BJS2_5696/SpellAction.java
- src/main/java/faang/school/godbless/lambda/BJS2_5696/SpellCaster.java
- src/main/java/faang/school/godbless/lambda/BJS2_5790/Email.java
- src/main/java/faang/school/godbless/lambda/BJS2_5790/EmailProcessor.java
- src/main/java/faang/school/godbless/lambda/BJS2_5790/Main.java
- src/main/java/faang/school/godbless/lambda/BJS2_5798/Main.java
- src/main/java/faang/school/godbless/lambda/BJS2_5798/MessageFilter.java
- src/main/java/faang/school/godbless/lambda/BJS2_5798/MessageProcessor.java
https://faang-school.atlassian.net/browse/BJS2-5790
> BJS2-5790: Gmail Rich Filters.

- src/main/java/faang/school/godbless/lambda/BJS2_5812/ExceptionHandler.java
- src/main/java/faang/school/godbless/lambda/BJS2_5812/Main.java
https://faang-school.atlassian.net/browse/BJS2-5812
> BJS2-5812: Fancy error handler

- src/main/java/faang/school/godbless/lambda/BJS2_5798/Main.java
- src/main/java/faang/school/godbless/lambda/BJS2_5798/MessageFilter.java
- src/main/java/faang/school/godbless/lambda/BJS2_5798/MessageProcessor.java
https://faang-school.atlassian.net/browse/BJS2-5798
> BJS2-5798: Spam filter.

- src/main/java/faang/school/godbless/wow/Main.java
- src/main/java/faang/school/godbless/wow/Player.java
- src/main/java/faang/school/godbless/wow/Quest.java
- src/main/java/faang/school/godbless/wow/QuestSystem.java
Task: https://faang-school.atlassian.net/browse/BJS2-5885
> BJS2-5885: WOW

- src/main/java/faang/school/godbless/async_and_future/Main.java
- src/main/java/faang/school/godbless/async_and_future/MasterCardService.java
Task: https://faang-school.atlassian.net/browse/BJS2-5884
> BJS2-5884: Async and Future

- src/main/java/faang/school/godbless/module/second/stream/two/Employee.java
- src/main/java/faang/school/godbless/module/second/stream/two/Main.java
https://faang-school.atlassian.net/browse/BJS2-5517?atlOrigin=eyJpIjoiMmZlNjMxOWNjZTE1NDBmNjg1ZDBjY2NhNjQwZGRjZjIiLCJwIjoiaiJ9
> Решение задачи BJS2-5517 Потренируем StreamAPI 2

- src/main/java/faang/school/godbless/army_of_heroes/Archer.java
- src/main/java/faang/school/godbless/army_of_heroes/Army.java
- src/main/java/faang/school/godbless/army_of_heroes/Hero.java
- src/main/java/faang/school/godbless/army_of_heroes/Mage.java
- src/main/java/faang/school/godbless/army_of_heroes/Main.java
- src/main/java/faang/school/godbless/army_of_heroes/PowerThread.java
- src/main/java/faang/school/godbless/army_of_heroes/Swordsman.java
> BJS2-5735 Распределенная армия героев меча и магии

- src/main/java/faang/school/godbless/IronThrone/House.java
- src/main/java/faang/school/godbless/IronThrone/Main.java
- src/main/java/faang/school/godbless/IronThrone/User.java
Надеюсь правильно понял проблематику задачи, очень запутанное и странное описание ;(
> Железный трон любой ценой BJS2-5703

- src/main/java/faang/school/godbless/MattersOfTheHeart/Chat.java
- src/main/java/faang/school/godbless/MattersOfTheHeart/ChatManager.java
- src/main/java/faang/school/godbless/MattersOfTheHeart/ChatService.java
- src/main/java/faang/school/godbless/MattersOfTheHeart/Main.java
- src/main/java/faang/school/godbless/MattersOfTheHeart/User.java
- src/main/java/faang/school/godbless/MattersOfTheHeart/UserList.java
Ну задача очень творческая, поэтому хотел бы расписать свою логику:
1. Добавил в класс User поля с теми кого он лайкнул и теми, кто лайкнул его. описал логику это действия в методах like и dislike.
2. Сделал UserList польностью синхронизированной коллекцией. Также метод addUser вызывает метод notify(), чтобы другие потоки, которые хотят обработать этот лист, узнали о добавлении нового юзера.
3. В методе begin() класса Chat решил сделать небольшую интрижку итога диалога с классом Random.
4. В ChatManager не нашел применения методу endChat в моей реализации, не решил как его использовать в Main и опустил. 
5. Вынес логику работы с чатами в отдельный класс ChatService.
> Matters of the heart BJS2-5741

- src/main/java/faang/school/godbless/lambda/BJS2_5811/Character.java
- src/main/java/faang/school/godbless/lambda/BJS2_5811/InventoryManager.java
- src/main/java/faang/school/godbless/lambda/BJS2_5811/Item.java
- src/main/java/faang/school/godbless/lambda/BJS2_5811/Main.java
https://faang-school.atlassian.net/browse/BJS2-5811
> BJS2-5811: Lord of the Rings RPG

- src/main/java/faang/school/godbless/bjs2_5889/Main.java
- src/main/java/faang/school/godbless/bjs2_5889/MasterCardService.java
Task: https://faang-school.atlassian.net/browse/BJS2-5889
> BJS2-5889: Асинхронность и Future

- src/main/java/faang/school/godbless/instagram/FilterProcessor.java
- src/main/java/faang/school/godbless/instagram/Image.java
- src/main/java/faang/school/godbless/instagram/InstagramMain.java
> Instagram filters

- build.gradle
- src/main/java/faang/school/godbless/vacancyAnalyzer/DataAnalyzer.java
- src/main/java/faang/school/godbless/vacancyAnalyzer/Job.java
- src/main/java/faang/school/godbless/vacancyAnalyzer/JobScraper.java
- src/main/java/faang/school/godbless/vacancyAnalyzer/JobStreamProcessor.java
- src/main/java/faang/school/godbless/vacancyAnalyzer/Main.java
- src/main/java/faang/school/godbless/vacancyAnalyzer/TrendGranularity.java
> BJS2-5765-Vacancy-analyzer

- src/main/java/TheyWereVeryNiceButExtremelyPoor/Chore.java
- src/main/java/TheyWereVeryNiceButExtremelyPoor/WeasleyFamily.java
> They were very nice but extremely poor - BJS2-5648

- src/main/java/faang/school/godbless/lambda/BJS2_5814/Main.java
https://faang-school.atlassian.net/browse/BJS2-5814
> BJS2-5814: Triangle area

- src/main/java/faang/school/godbless/blocking_spotify/Music.java
- src/main/java/faang/school/godbless/blocking_spotify/Player.java
BJS2-5820 blocking_spotify complete(solution 1)
> BJS2-5820 blocking_spotify complete(solution 1)

- src/main/java/faang/school/godbless/matters_of_the_heart/Chat.java
- src/main/java/faang/school/godbless/matters_of_the_heart/ChatManager.java
- src/main/java/faang/school/godbless/matters_of_the_heart/Main.java
- src/main/java/faang/school/godbless/matters_of_the_heart/User.java
- src/main/java/faang/school/godbless/matters_of_the_heart/UserList.java
Task: https://faang-school.atlassian.net/browse/BJS2-5800
> BJS2-5800: Matters of the heart

- src/main/java/faang/school/godbless/module/fourth/async/stripe/Main.java
- src/main/java/faang/school/godbless/module/fourth/async/stripe/MasterCardService.java
https://faang-school.atlassian.net/browse/BJS2-5937?atlOrigin=eyJpIjoiNTZhNTY4ODgzOTI0NDA0MTk2ZTQ0ZmY3YjFlMjk2YTAiLCJwIjoiaiJ9
> Решение задачи BJS2-5937 Асинхронность и Future

- src/main/java/faang/school/godbless/spotify/Music.java
- src/main/java/faang/school/godbless/spotify/Player.java
- src/main/java/faang/school/godbless/spotify/PlayerStatic.java
> egorp bjs2 5973 spotify

- src/main/java/faang/school/godbless/lambda/BJS2_5816/Droid.java
- src/main/java/faang/school/godbless/lambda/BJS2_5816/DroidMessageEncryptor.java
- src/main/java/faang/school/godbless/lambda/BJS2_5816/Main.java
https://faang-school.atlassian.net/browse/BJS2-5816
Пытался вынести логику `getEncryptorDecryptor` в default метод интерфейса, но ничего хорошего не получилось
> BJS2-5816: Droid secrets

- src/main/java/faang/school/godbless/griffin/FoodDeliveryTask.java
- src/main/java/faang/school/godbless/griffin/GriffinsFoodDelivery.java
> Food Delivery

- src/main/java/faang/school/godbless/stream/BJS2_5836/Main.java
https://faang-school.atlassian.net/browse/BJS2-5836
> BJS2-5836: Stream API 1

- src/main/java/faang/school/godbless/feedPeterGriffin/FoodDeliveryTask.java
- src/main/java/faang/school/godbless/feedPeterGriffin/GriffinsFoodDelivery.java
> BJS2-5904-Feed Peter Griffin for review

- src/main/java/faang/school/godbless/theTournament/King.java
- src/main/java/faang/school/godbless/theTournament/Knight.java
- src/main/java/faang/school/godbless/theTournament/Trial.java
> egorp bjs2 5921 the tournament

- src/main/java/faang/school/godbless/multithreading/task_4/BigBangTheory.java
- src/main/java/faang/school/godbless/multithreading/task_4/model/Task.java
Я не уверен, что справился с этим заданием. Участок кода на картинке меня очень смущает. 
Правильно ли я понимаю, что по сути при таком коде  метод shutdown может вызваться потоком main вообще в любое время и все, что написано ниже не имеет  никакого смысла?
Я сначала написал вариант с очередью и передавал в Executor элементы из очереди до тех пор, пока в очереди что-то есть. 
Что-то по типу: 
_EXECUTORS.execute(poll)._
Затем проверял, что очередь пустая и уже при пустой очереди вызывал EXECUTOR.shutdown() и печатал на консоль сообщение о том, что задачи выполнены (еще можно вариант с ArrayList через индексы рассмотреть и проверку по индексу и размеру листа осуществлять).
Я переделал вариант на тот, который сейчас, так как начало казаться, что я сильно усложняю.
Подскажите пожалуйста, как …
> The Big Bang Theory

- src/main/java/faang/school/godbless/recommendation_system/Main.java
- src/main/java/faang/school/godbless/recommendation_system/RecommendationService.java
- src/main/java/faang/school/godbless/recommendation_system/model/Gender.java
- src/main/java/faang/school/godbless/recommendation_system/model/Product.java
- src/main/java/faang/school/godbless/recommendation_system/model/ProductOrder.java
- src/main/java/faang/school/godbless/recommendation_system/model/UserProfile.java
- src/main/java/faang/school/godbless/recommendation_system/repository/ProductOrderRepository.java
- src/main/java/faang/school/godbless/recommendation_system/repository/ProductRepository.java
- src/main/java/faang/school/godbless/recommendation_system/repository/UserProfileRepository.java
- src/test/java/faang/school/godbless/recommendation_system/RecommendationServiceTest.java
Task: https://faang-school.atlassian.net/browse/BJS2-5426
> BJS2-5426: Recommendation system

- src/main/java/faang/school/godbless/stream/BJS2_5841/Employee.java
- src/main/java/faang/school/godbless/stream/BJS2_5841/Main.java
https://faang-school.atlassian.net/browse/BJS2-5841
> BJS2-5841: Stream API 2

- src/main/java/faang/school/godbless/synchronization/task_6/Main.java
- src/main/java/faang/school/godbless/synchronization/task_6/model/House.java
- src/main/java/faang/school/godbless/synchronization/task_6/model/Role.java
- src/main/java/faang/school/godbless/synchronization/task_6/model/User.java
Решил отойти от рандомайзеров и в классе House сделал вот такую конструкцию:
Программа работает, но подскажите пожалуйста, насколько адекватно кидать исключения в подобных ситуациях?
> Железный трон любой ценой

- src/main/java/faang/school/godbless/miceAreVeryNice/Food.java
- src/main/java/faang/school/godbless/miceAreVeryNice/House.java
- src/main/java/faang/school/godbless/miceAreVeryNice/Main.java
- src/main/java/faang/school/godbless/miceAreVeryNice/Room.java
Mice are very nice! на проверку.
> egorp bjs2 5923 mice are very nice

- src/main/java/faang/school/godbless/build_csv/Main.java
- src/main/java/faang/school/godbless/build_csv/MatrixJoiner.java
- src/main/java/faang/school/godbless/build_csv/VectorJoiner.java
Task: https://faang-school.atlassian.net/browse/BJS2-5135
> BJS2-5135: Build CSV

- src/main/java/faang/school/godbless/help_a_colleague/Main.java
- src/main/java/faang/school/godbless/help_a_colleague/Person.java
- src/main/java/faang/school/godbless/help_a_colleague/PersonWorkPlacePrinter.java
Task: https://faang-school.atlassian.net/browse/BJS2-5642
> BJS2-5642: Help a colleague

- src/main/java/faang/school/godbless/queue_in_walmart/CashierThread.java
- src/main/java/faang/school/godbless/queue_in_walmart/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-5650
> BJS2-5650: Queue in Walmart

- src/main/java/faang/school/godbless/finally_good_game/Pig1Thread.java
- src/main/java/faang/school/godbless/finally_good_game/Pig2Thread.java
- src/main/java/faang/school/godbless/finally_good_game/Pig3Thread.java
- src/main/java/faang/school/godbless/finally_good_game/PigThread.java
- src/main/java/faang/school/godbless/finally_good_game/ThreeLittlePigs.java
Task: https://faang-school.atlassian.net/browse/BJS2-5652
> BJS2-5652: Finally a good game!

- src/main/java/faang/school/godbless/sprint2/lambda/instagram/filters/FilterProcessor.java
- src/main/java/faang/school/godbless/sprint2/lambda/instagram/filters/Image.java
- src/main/java/faang/school/godbless/sprint2/lambda/instagram/filters/Runner.java
BJS2-5574: Added: Instagram filters task was added.
> BJS2-5574: Added: Instagram filters task was added.

- src/main/java/faang/school/godbless/sprint2/lambda/school/Runner.java
- src/main/java/faang/school/godbless/sprint2/lambda/school/TriangleCalculator.java
BJS2-5573: Added: School task was added.
> BJS2-5573: Added: School task was added.

- src/main/java/faang/school/godbless/sprint2/lambda/calculator/Calculator.java
- src/main/java/faang/school/godbless/sprint2/lambda/calculator/Operations.java
- src/main/java/faang/school/godbless/sprint2/lambda/calculator/Runner.java
BJS2-5570: Added: Calculator task was added.
> BJS2-5570: Added: Calculator task was added.

- src/main/java/faang/school/godbless/stream/BJS2_5912/ActionType.java
- src/main/java/faang/school/godbless/stream/BJS2_5912/Main.java
- src/main/java/faang/school/godbless/stream/BJS2_5912/UserAction.java
https://faang-school.atlassian.net/browse/BJS2-5912
> BJS2-5912: Анализ активности пользователей в социальной сети

- src/main/java/faang/school/godbless/stream/streamapi2/Employee.java
- src/main/java/faang/school/godbless/stream/streamapi2/ExtendedStreamUtilOperations.java
- src/main/java/faang/school/godbless/stream/streamapi2/Pair.java
- src/main/java/faang/school/godbless/stream/streamapi2/Runner.java
BJS2-5826: Added: Stream API 2 task was added.
> BJS2-5826: Added: Stream API 2 task was added.

- src/main/java/faang/school/godbless/homm/Archer.java
- src/main/java/faang/school/godbless/homm/Army.java
- src/main/java/faang/school/godbless/homm/HeroesMain.java
- src/main/java/faang/school/godbless/homm/Mage.java
- src/main/java/faang/school/godbless/homm/PowerThread.java
- src/main/java/faang/school/godbless/homm/Swordsman.java
- src/main/java/faang/school/godbless/homm/Unit.java
> Heroes of Might and Magic

- src/main/java/faang/school/godbless/googlePhoto/GooglePhotosAutoUploader.java
- src/main/java/faang/school/godbless/googlePhoto/Main.java
> BJS2-5974-Google photo for review

- src/main/java/faang/school/godbless/bjs2_5896/Main.java
- src/main/java/faang/school/godbless/bjs2_5896/Player.java
- src/main/java/faang/school/godbless/bjs2_5896/Quest.java
- src/main/java/faang/school/godbless/bjs2_5896/QuestSystem.java
Task: https://faang-school.atlassian.net/browse/BJS2-5896
> BJS2-5896: WOW

- src/main/java/faang/school/godbless/bjs2_5890/Battle.java
- src/main/java/faang/school/godbless/bjs2_5890/Robot.java
Task: https://faang-school.atlassian.net/browse/BJS2-5890
> BJS2-5890: Star Wars Arena

- src/main/java/faang/school/godbless/bjs2_6012/Pair.java
- src/main/java/faang/school/godbless/bjs2_6012/Superhero.java
- src/main/java/faang/school/godbless/bjs2_6012/SuperheroBattle.java
Task: https://faang-school.atlassian.net/browse/BJS2-6012
> BJS2-6012: Superheroes battle

- src/main/java/faang/school/godbless/youtube_view_counter/Test.java
- src/main/java/faang/school/godbless/youtube_view_counter/VideoManager.java
BJS2-5869 youtube_view_counter complete(solution 1)
> BJS2-5869 youtube_view_counter complete(solution 1)

- src/main/java/faang/school/godbless/google_photo_sync/GooglePhotosAutoUploader.java
BJS2-5834 google_photo_sync complete(solution 1)
> BJS2-5834 google_photo_sync complete(solution 1)

- src/main/java/faang/school/godbless/wow/Main.java
- src/main/java/faang/school/godbless/wow/Player.java
- src/main/java/faang/school/godbless/wow/Quest.java
- src/main/java/faang/school/godbless/wow/QuestSystem.java
BJS2-6043 wow complete(solution 1)
> BJS2-6043 wow complete(solution 1)

- src/main/java/faang/school/godbless/bjs2_5900/Main.java
- src/main/java/faang/school/godbless/bjs2_5900/ResultConsumer.java
- src/main/java/faang/school/godbless/bjs2_5900/SquareRequest.java
Task: https://faang-school.atlassian.net/browse/BJS2-5900
> BJS2-5900: Fan out – Fan In

- src/main/java/faang/school/godbless/bjs2_5908/MagicalTournament.java
- src/main/java/faang/school/godbless/bjs2_5908/School.java
- src/main/java/faang/school/godbless/bjs2_5908/Student.java
- src/main/java/faang/school/godbless/bjs2_5908/Task.java
- src/main/java/faang/school/godbless/bjs2_5908/Tournament.java
Task: https://faang-school.atlassian.net/browse/BJS2-5908
> BJS2-5908: Турнир трех волшебников

- src/main/java/faang/school/godbless/module/third/synchronization/youtube/Main.java
- src/main/java/faang/school/godbless/module/third/synchronization/youtube/VideoManager.java
https://faang-school.atlassian.net/browse/BJS2-5936?atlOrigin=eyJpIjoiZWYwZjc4ZjYxODFhNDM4MjkyMDZlNjc5MTIwMWQ3ZTUiLCJwIjoiaiJ9
> Решение задачи BJS2-5936 Счетчик просмотров на YouTube

- src/main/java/faang/school/godbless/module/fourth/async/wow/Player.java
- src/main/java/faang/school/godbless/module/fourth/async/wow/Quest.java
- src/main/java/faang/school/godbless/module/fourth/async/wow/QuestSystem.java
https://faang-school.atlassian.net/browse/BJS2-6022?atlOrigin=eyJpIjoiMWIzMGVkYTNjM2Y4NGExZTk0OTUyZjU5MTJiMjE3ZDYiLCJwIjoiaiJ9
> Решение задачи BJS2-6022 WOW

- src/main/java/faang/school/godbless/star_wars_arena/Battle.java
- src/main/java/faang/school/godbless/star_wars_arena/Main.java
- src/main/java/faang/school/godbless/star_wars_arena/Robot.java
Task: https://faang-school.atlassian.net/browse/BJS2-5895
> BJS2-5895: Star Wars arena

- src/main/java/faang/school/godbless/fan_out_fan_in/Main.java
- src/main/java/faang/school/godbless/fan_out_fan_in/ResultConsumer.java
- src/main/java/faang/school/godbless/fan_out_fan_in/SquareRequest.java
Task: https://faang-school.atlassian.net/browse/BJS2-5887
> BJS2-5887: Fan out fan in

- src/main/java/faang/school/godbless/module/fourth/async/fan/Main.java
- src/main/java/faang/school/godbless/module/fourth/async/fan/ResultConsumer.java
- src/main/java/faang/school/godbless/module/fourth/async/fan/SquareRequest.java
https://faang-school.atlassian.net/browse/BJS2-6026?atlOrigin=eyJpIjoiZWE1MGVlOWQ3N2U0NDc0Nzk4ZThiMGU3N2VmZWEyMWUiLCJwIjoiaiJ9
> Решение задачи BJS2-6026 Fan out – Fan In

- src/main/java/collect_orders_from_amazon/Main.java
- src/main/java/collect_orders_from_amazon/Order.java
- src/main/java/collect_orders_from_amazon/OrderProcessor.java
Выполнил задание, отправляю PR
> Собираем заказы в Amazon - BJS2-6132

- src/main/java/faang/school/godbless/BJS2_4919/Main.java
- src/main/java/faang/school/godbless/multithreading_parallelism/BJS2_6153/MailSender.java
- src/main/java/faang/school/godbless/multithreading_parallelism/BJS2_6153/SenderRunnable.java
https://faang-school.atlassian.net/browse/BJS2-6153
> BJS2-6153: Microsoft

- src/main/java/faang/school/godbless/BJS2_5966/MailSender.java
- src/main/java/faang/school/godbless/BJS2_5966/SenderRunnable.java
Task BJS2-5966 (Вы работаете в Microsoft!)
> Solution to task BJS2-5966

- src/main/java/faang/school/godbless/theIronThrone/House.java
- src/main/java/faang/school/godbless/theIronThrone/Main.java
- src/main/java/faang/school/godbless/theIronThrone/User.java
The iron throne in any price for review.
> bjs2 6040 the iron throne in any price

- src/main/java/faang/school/godbless/async/task_1/Main.java
- src/main/java/faang/school/godbless/async/task_1/service/MasterCardService.java
Я не совсем в этом уверен, но исходя из условий задачи (выделил красным), у CompletableFuture по-хорошему нужно вызвать join, чтобы гарантировать, что результат его работы точно выведется первым.
Поправьте меня пожалуйста, если я не прав.
> Асинхронность и Future

- src/main/java/TheIronThrone/House.java
- src/main/java/TheIronThrone/Main.java
- src/main/java/TheIronThrone/Role.java
- src/main/java/TheIronThrone/User.java
> Железный трон любой ценой - BJS2-5960

- src/main/java/faang/school/godbless/bjs2_5940/Main.java
- src/main/java/faang/school/godbless/bjs2_5940/Order.java
- src/main/java/faang/school/godbless/bjs2_5940/OrderProcessor.java
- src/main/java/faang/school/godbless/bjs2_5940/StatusOrder.java
Task: https://faang-school.atlassian.net/browse/BJS2-5940
> BJS2-5940: Собираем заказы в Amazon

- src/main/java/faang/school/godbless/bjs2_5942/Main.java
- src/main/java/faang/school/godbless/bjs2_5942/TwitterAccount.java
- src/main/java/faang/school/godbless/bjs2_5942/TwitterSubscriptionSystem.java
Task: https://faang-school.atlassian.net/browse/BJS2-5942
> BJS2-5942: Становимся celebrity в Twitter

- src/main/java/faang/school/godbless/bjs2_5939/Main.java
- src/main/java/faang/school/godbless/bjs2_5939/Potion.java
Task: https://faang-school.atlassian.net/browse/BJS2-5939
> BJS2-5939: Качаем алхимию

- src/main/java/faang/school/godbless/async/alchemy/Main.java
- src/main/java/faang/school/godbless/async/alchemy/Potion.java
Есть ли смысл здесь использовать AtomicInteger, если можно просуммировать все после выполнения всех заданий?
Или нужно использовать Atomic, чтобы можно было получить результат даже , если не все задания выполнятся?
И почему лучше использовать allOf(), а не stream().map(future -> future.join()) ... ?
> BJS2-5964 (Качаем алхимию)

- src/main/java/faang/school/godbless/bjs2_5938/Inventory.java
- src/main/java/faang/school/godbless/bjs2_5938/Item.java
- src/main/java/faang/school/godbless/bjs2_5938/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-5938
> BJS2-5938: Carry отожрался

- src/main/java/faang/school/godbless/bjs2_5957/Kingdom.java
- src/main/java/faang/school/godbless/bjs2_5957/Main.java
- src/main/java/faang/school/godbless/bjs2_5957/RavenException.java
Task: https://faang-school.atlassian.net/browse/BJS2-5957
> BJS2-5957: Пошлите ворона!

- src/main/java/faang/school/godbless/multithreading_parallelism/BJS2_6154/FoodDeliveryTask.java
- src/main/java/faang/school/godbless/multithreading_parallelism/BJS2_6154/GriffinsFoodDelivery.java
https://faang-school.atlassian.net/browse/BJS2-6154
> BJS2-6154: Накормите Питера Гриффина.

- src/main/java/faang/school/godbless/multithreading_parallelism/BJS2_6155/Archer.java
- src/main/java/faang/school/godbless/multithreading_parallelism/BJS2_6155/Army.java
- src/main/java/faang/school/godbless/multithreading_parallelism/BJS2_6155/Character.java
- src/main/java/faang/school/godbless/multithreading_parallelism/BJS2_6155/Mage.java
- src/main/java/faang/school/godbless/multithreading_parallelism/BJS2_6155/Main.java
- src/main/java/faang/school/godbless/multithreading_parallelism/BJS2_6155/Swordsman.java
- src/main/java/faang/school/godbless/multithreading_parallelism/BJS2_6155/UnitThread.java
https://faang-school.atlassian.net/browse/BJS2-6155
> BJS2-6155: Распределенная армия героев меча и магии

- src/main/java/faang/school/godbless/bjs2_5949/Main.java
- src/main/java/faang/school/godbless/bjs2_5949/Point.java
Task: https://faang-school.atlassian.net/browse/BJS2-5949
> BJS2-5949: Вычислим число ПИ

- src/main/java/faang/school/godbless/bjs2_6018/Main.java
- src/main/java/faang/school/godbless/bjs2_6018/Notification.java
- src/main/java/faang/school/godbless/bjs2_6018/NotificationManager.java
Task: https://faang-school.atlassian.net/browse/BJS2-6018
> BJS2-6018: Рассылаем уведомления в Facebook

- src/main/java/faang/school/godbless/module/fourth/async/wars/Battle.java
- src/main/java/faang/school/godbless/module/fourth/async/wars/Robot.java
https://faang-school.atlassian.net/browse/BJS2-5971?atlOrigin=eyJpIjoiOGEwYjQ2N2NmMTcwNDM2NmI3MGU3Nzc3YTI1NjAzZTIiLCJwIjoiaiJ9
> Решение задачи BJS2-5971 Star Wars Arena

- src/main/java/TriwizardTournament/Main.java
- src/main/java/TriwizardTournament/School.java
- src/main/java/TriwizardTournament/Student.java
- src/main/java/TriwizardTournament/Task.java
- src/main/java/TriwizardTournament/Tournament.java
> Турнир трех волшебников - BJS2-6030

- src/main/java/faang/school/godbless/module/third/synchronization/supercow/Boss.java
- src/main/java/faang/school/godbless/module/third/synchronization/supercow/Main.java
- src/main/java/faang/school/godbless/module/third/synchronization/supercow/Player.java
https://faang-school.atlassian.net/browse/BJS2-5881?atlOrigin=eyJpIjoiYTNiNDZmMzMyMTMxNDUxMTk0ZmExMWYyNjMxNjJiMjYiLCJwIjoiaiJ9
> Решение задачи BJS2-5655 Supercow!

- src/main/java/faang/school/godbless/support_animals/Donation.java
- src/main/java/faang/school/godbless/support_animals/Main.java
- src/main/java/faang/school/godbless/support_animals/Organization.java
Task: https://faang-school.atlassian.net/browse/BJS2-6053
> BJS2-6053: Support animals

- src/main/java/faang/school/godbless/module/fourth/async/alchemy/Main.java
- src/main/java/faang/school/godbless/module/fourth/async/alchemy/Potion.java
https://faang-school.atlassian.net/browse/BJS2-6055?atlOrigin=eyJpIjoiYTYyZjdlZjUxNTkzNDYwOWIxY2NhMjVlNTg1MzkzZDIiLCJwIjoiaiJ9
> Решение задачи BJS2-6055 Качаем алхимию

- src/main/java/faang/school/godbless/upgrade_alchemy/Main.java
- src/main/java/faang/school/godbless/upgrade_alchemy/Potion.java
Task: https://faang-school.atlassian.net/browse/BJS2-5911
> BJS2-5911: Upgrade alchemy

- src/main/java/faang/school/godbless/iron_throne/House.java
- src/main/java/faang/school/godbless/iron_throne/HouseRole.java
- src/main/java/faang/school/godbless/iron_throne/Main.java
- src/main/java/faang/school/godbless/iron_throne/User.java
Task: https://faang-school.atlassian.net/browse/BJS2-5791
> BJS2-5791: Iron throne

- src/main/java/faang/school/godbless/collect_orders_on_amazon/Main.java
- src/main/java/faang/school/godbless/collect_orders_on_amazon/Order.java
- src/main/java/faang/school/godbless/collect_orders_on_amazon/OrderProcessor.java
- src/main/java/faang/school/godbless/collect_orders_on_amazon/Status.java
Task: https://faang-school.atlassian.net/browse/BJS2-5916
> BJS2-5916: Collect orders on Amazon

- src/main/java/faang/school/godbless/module/fourth/async/amazon/Main.java
- src/main/java/faang/school/godbless/module/fourth/async/amazon/Order.java
- src/main/java/faang/school/godbless/module/fourth/async/amazon/OrderProcessor.java
- src/main/java/faang/school/godbless/module/fourth/async/amazon/Status.java
https://faang-school.atlassian.net/browse/BJS2-6059?atlOrigin=eyJpIjoiNzhjNGUwZDhlYWExNDM1OWE1OTc4OTI3NzZhMTQ5MmQiLCJwIjoiaiJ9
> Решение задачи BJS2-6059 Собираем заказы в Amazon

- src/main/java/faang/school/godbless/triwizard_tournament/MagicalTournament.java
- src/main/java/faang/school/godbless/triwizard_tournament/School.java
- src/main/java/faang/school/godbless/triwizard_tournament/Student.java
- src/main/java/faang/school/godbless/triwizard_tournament/Task.java
- src/main/java/faang/school/godbless/triwizard_tournament/Tournament.java
Task: https://faang-school.atlassian.net/browse/BJS2-5892
> BJS2-5892: Triwizard tournament

- src/main/java/faang/school/godbless/module/fourth/async/wizards/School.java
- src/main/java/faang/school/godbless/module/fourth/async/wizards/Student.java
- src/main/java/faang/school/godbless/module/fourth/async/wizards/Task.java
- src/main/java/faang/school/godbless/module/fourth/async/wizards/Tournament.java
https://faang-school.atlassian.net/browse/BJS2-6036?atlOrigin=eyJpIjoiZmEzYWE1NGY0ODJiNDI2Yzg2Y2Q1NzRiNmViMTZjYzEiLCJwIjoiaiJ9
> Решение задачи BJS2-6036 Турнир трех волшебников

- src/main/java/faang/school/godbless/leave_a_comment/Comment.java
- src/main/java/faang/school/godbless/leave_a_comment/Main.java
- src/main/java/faang/school/godbless/leave_a_comment/Post.java
- src/main/java/faang/school/godbless/leave_a_comment/PostService.java
- src/main/java/faang/school/godbless/leave_a_comment/User.java
Task: https://faang-school.atlassian.net/browse/BJS2-6019
> BJS2-6019: Leave a comment

- src/main/java/faang/school/godbless/become_celebrity_in_twitter/Main.java
- src/main/java/faang/school/godbless/become_celebrity_in_twitter/TwitterAccount.java
- src/main/java/faang/school/godbless/become_celebrity_in_twitter/TwitterSubscriptionSystem.java
Task: https://faang-school.atlassian.net/browse/BJS2-5917 
В классе TwitterSubscriptionSystem есть комменты
> BJS2-5917: Become celebrity in Twitter

- src/main/java/faang/school/godbless/tamagotchi/Main.java
- src/main/java/faang/school/godbless/tamagotchi/TamagotchiVlad.java
- src/main/java/faang/school/godbless/tamagotchi/VladController.java
Task: https://faang-school.atlassian.net/browse/BJS2-5815
> BJS2-5815: Tamagotchi

- src/main/java/faang/school/godbless/armyOfHeroesOfMightAndMagic/Archer.java
- src/main/java/faang/school/godbless/armyOfHeroesOfMightAndMagic/Army.java
- src/main/java/faang/school/godbless/armyOfHeroesOfMightAndMagic/Creature.java
- src/main/java/faang/school/godbless/armyOfHeroesOfMightAndMagic/Mage.java
- src/main/java/faang/school/godbless/armyOfHeroesOfMightAndMagic/Main.java
- src/main/java/faang/school/godbless/armyOfHeroesOfMightAndMagic/SquadCalculate.java
- src/main/java/faang/school/godbless/armyOfHeroesOfMightAndMagic/Swordsman.java
Army of Heroes Of Might And Magic for review (without synchronization)
> BJS2-5905-Army of Heroes Of Might And Magic for review (no sync)

- src/main/java/faang/school/godbless/supercow/Boss.java
- src/main/java/faang/school/godbless/supercow/Main.java
- src/main/java/faang/school/godbless/supercow/Player.java
> egorp bjs2 5976 supercow!

- src/main/java/faang/school/godbless/mattersOfTheheart/Chat.java
- src/main/java/faang/school/godbless/mattersOfTheheart/ChatManager.java
- src/main/java/faang/school/godbless/mattersOfTheheart/Main.java
- src/main/java/faang/school/godbless/mattersOfTheheart/User.java
- src/main/java/faang/school/godbless/mattersOfTheheart/UserChatStatus.java
- src/main/java/faang/school/godbless/mattersOfTheheart/UserList.java
Matters Of The Heart for review
> bjs2 6041 matters of the heart

- src/main/java/faang/school/godbless/BJS2_6210/Email.java
- src/main/java/faang/school/godbless/BJS2_6210/EmailProcessor.java
- src/main/java/faang/school/godbless/BJS2_6210/Main.java
> Task BJS2-6210

- src/main/java/faang/school/godbless/BJS2_6208/FilterProcessor.java
- src/main/java/faang/school/godbless/BJS2_6208/Image.java
- src/main/java/faang/school/godbless/BJS2_6208/Main.java
> Task BJS2-6208

- src/main/java/faang/school/godbless/BJS2_6206/Main.java
- src/main/java/faang/school/godbless/BJS2_6206/Notification.java
- src/main/java/faang/school/godbless/BJS2_6206/NotificationManager.java
> Task BJS2-6206

- src/main/java/faang/school/godbless/wow/Main.java
- src/main/java/faang/school/godbless/wow/Player.java
- src/main/java/faang/school/godbless/wow/Quest.java
- src/main/java/faang/school/godbless/wow/QuestSystem.java
> BJS2-6164-WOW for review

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/asyncAndFuture/Main.java
- src/main/java/faang/school/godbless/asyncAndFuture/MasterCardService.java
https://faang-school.atlassian.net/browse/BJS2-6080
> Add solution for task BJS2-6080.

- src/main/java/faang/school/godbless/asycnAndFuture/Main.java
- src/main/java/faang/school/godbless/asycnAndFuture/MasterCardService.java
> BJS2-6159-Async and future fore review

- src/main/java/faang/school/godbless/fanOutFanIn/Main.java
- src/main/java/faang/school/godbless/fanOutFanIn/ResultConsumer.java
- src/main/java/faang/school/godbless/fanOutFanIn/SquareRequest.java
> Egorp bjs2 6166 fan out fan in

- src/main/java/faang/school/godbless/bjs2_6032/Donation.java
- src/main/java/faang/school/godbless/bjs2_6032/Main.java
- src/main/java/faang/school/godbless/bjs2_6032/Organization.java
Task: https://faang-school.atlassian.net/browse/BJS2-6032
> BJS2-6032: Поддержим животных

- src/main/java/faang/school/godbless/bjs2_6033/Conference.java
- src/main/java/faang/school/godbless/bjs2_6033/Main.java
- src/main/java/faang/school/godbless/bjs2_6033/Participant.java
Task: https://faang-school.atlassian.net/browse/BJS2-6033
> BJS2-6033: Мини Zoom

- src/main/java/faang/school/godbless/bjs2_6104/DesignDepartment.java
- src/main/java/faang/school/godbless/bjs2_6104/DesignResources.java
- src/main/java/faang/school/godbless/bjs2_6104/Main.java
- src/main/java/faang/school/godbless/bjs2_6104/MarketingDepartment.java
- src/main/java/faang/school/godbless/bjs2_6104/MarketingResources.java
Task: https://faang-school.atlassian.net/browse/BJS2-6104
> BJS2-6104: Работа стоит

- src/main/java/faang/school/godbless/bjs2_6110/Location.java
- src/main/java/faang/school/godbless/bjs2_6110/StatusVehicle.java
- src/main/java/faang/school/godbless/bjs2_6110/TransportManagementSystem.java
- src/main/java/faang/school/godbless/bjs2_6110/Vehicle.java
- src/main/java/faang/school/godbless/bjs2_6110/VehicleTracker.java
Task: https://faang-school.atlassian.net/browse/BJS2-6110
> BJS2-6110: Система трекинга

- src/main/java/faang/school/godbless/star_wars_arena/Battle.java
- src/main/java/faang/school/godbless/star_wars_arena/Main.java
- src/main/java/faang/school/godbless/star_wars_arena/Robot.java
BJS2-6134 star_wars_arena complete(solution 1)
> BJS2-6134 star_wars_arena complete(solution 1)

- src/main/java/faang/school/godbless/triwizard_tournament/Main.java
- src/main/java/faang/school/godbless/triwizard_tournament/School.java
- src/main/java/faang/school/godbless/triwizard_tournament/Student.java
- src/main/java/faang/school/godbless/triwizard_tournament/Task.java
- src/main/java/faang/school/godbless/triwizard_tournament/Tournament.java
BJS2-6140 triwizard_tournament complete(solution 1)
> BJS2-6140 triwizard_tournament complete(solution 1)

- src/main/java/faang/school/godbless/asynchrone_and_future/Main.java
- src/main/java/faang/school/godbless/asynchrone_and_future/MasterCardService.java
BJS2-5982 asynchrone_and_future complete(solution 1)
> BJS2-5982 asynchrone_and_future complete(solution 1)

- src/main/java/faang/school/godbless/notifications_on_facebook/Main.java
- src/main/java/faang/school/godbless/notifications_on_facebook/Notification.java
- src/main/java/faang/school/godbless/notifications_on_facebook/NotificationManager.java
BJS2-6192 notifications_on_facebook complete(solution 1)
> BJS2-6192 notifications_on_facebook complete(solution 1)

- src/main/java/faang/school/godbless/bjs2_6130/Account.java
- src/main/java/faang/school/godbless/bjs2_6130/Bank.java
- src/main/java/faang/school/godbless/bjs2_6130/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-6130
> BJS2-6130: Поиграем в банк

- src/main/java/faang/school/godbless/bjs2_6157/DeliveryService.java
- src/main/java/faang/school/godbless/bjs2_6157/Main.java
- src/main/java/faang/school/godbless/bjs2_6157/Order.java
- src/main/java/faang/school/godbless/bjs2_6157/Product.java
- src/main/java/faang/school/godbless/bjs2_6157/PromoCode.java
Task: https://faang-school.atlassian.net/browse/BJS2-6157
> BJS2-6157: Купоны на доставку 

- src/main/java/faang/school/godbless/sprint2/lambda/metauniverse/Notification.java
- src/main/java/faang/school/godbless/sprint2/lambda/metauniverse/NotificationManager.java
- src/main/java/faang/school/godbless/sprint2/lambda/metauniverse/Runner.java
BJS2-5578: Added: Meta universe task -- Support for multiple handlers per notification type was added.
> BJS2-5578: Added: Meta universe task -- Support for multiple handlers per notification type was added.

- src/main/java/faang/school/godbless/sprint2/lambda/hogwarts/Runner.java
- src/main/java/faang/school/godbless/sprint2/lambda/hogwarts/SpellAction.java
- src/main/java/faang/school/godbless/sprint2/lambda/hogwarts/SpellCaster.java
BJS2-5569: Hogwarts, Hogwarts, our beloved Hogwarts task was added.
> BJS2-5569: Hogwarts, Hogwarts, our beloved Hogwarts task was added.

- src/main/java/faang/school/godbless/multithreading_parallelism/BJS2_6220/City.java
- src/main/java/faang/school/godbless/multithreading_parallelism/BJS2_6220/CityWorker.java
- src/main/java/faang/school/godbless/multithreading_parallelism/BJS2_6220/Location.java
- src/main/java/faang/school/godbless/multithreading_parallelism/BJS2_6220/Monster.java
- src/main/java/faang/school/godbless/multithreading_parallelism/BJS2_6220/Witcher.java
https://faang-school.atlassian.net/browse/BJS2-6220
> BJS2-6220: Путь пальцем проложи

- src/main/java/faang/school/godbless/multithreading_parallelism/BJS2_6217/Chore.java
- src/main/java/faang/school/godbless/multithreading_parallelism/BJS2_6217/WeasleyFamily.java
https://faang-school.atlassian.net/browse/BJS2-6217
> BJS2-6214: newCachedThreadPool

- src/main/java/faang/school/godbless/multithreading_parallelism/BJS2_6214/BigBangTheory.java
- src/main/java/faang/school/godbless/multithreading_parallelism/BJS2_6214/Task.java
https://faang-school.atlassian.net/browse/BJS2-6214
> BJS2-6214: The Big Bang Theory.

- src/main/java/faang/school/godbless/multithreading_parallelism/BJS2_6218/King.java
- src/main/java/faang/school/godbless/multithreading_parallelism/BJS2_6218/Knight.java
- src/main/java/faang/school/godbless/multithreading_parallelism/BJS2_6218/Trial.java
https://faang-school.atlassian.net/browse/BJS2-6218
> BJS2-6218: Турнир в Королевской гавани

- src/main/java/faang/school/godbless/module/fourth/async/twitter/TwitterAccount.java
- src/main/java/faang/school/godbless/module/fourth/async/twitter/TwitterSubscriptionSystem.java
https://faang-school.atlassian.net/browse/BJS2-6133?atlOrigin=eyJpIjoiMmQ4OGYwYThmNmEwNGMyYWFlOWNlMjFiZjVjNjQ4Y2MiLCJwIjoiaiJ9
> Решение задачи BJS2-6133 Становимся celebrity в Twitter

- src/main/java/faang/school/godbless/carry_overfed/Inventory.java
- src/main/java/faang/school/godbless/carry_overfed/Item.java
- src/main/java/faang/school/godbless/carry_overfed/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-5955
> BJS2-5955: Carry overfed

- src/main/java/faang/school/godbless/sprint3/BJS2_6312/City.java
- src/main/java/faang/school/godbless/sprint3/BJS2_6312/CityWorker.java
- src/main/java/faang/school/godbless/sprint3/BJS2_6312/Location.java
- src/main/java/faang/school/godbless/sprint3/BJS2_6312/Monster.java
- src/main/java/faang/school/godbless/sprint3/BJS2_6312/Witcher.java
Task: https://faang-school.atlassian.net/browse/BJS2-6312
> BJS2-6312: add the witcher

- src/main/java/faang/school/godbless/calculate_pi/Main.java
- src/main/java/faang/school/godbless/calculate_pi/Point.java
- src/test/java/faang/school/godbless/vacancy_analyzer/DataAnalyzerTest.java
Task: https://faang-school.atlassian.net/browse/BJS2-5928
> BJS2-5928: Calculate PI

- src/main/java/faang/school/godbless/work_stopped/DesignDepartment.java
- src/main/java/faang/school/godbless/work_stopped/DesignResources.java
- src/main/java/faang/school/godbless/work_stopped/Main.java
- src/main/java/faang/school/godbless/work_stopped/MarketingDepartment.java
- src/main/java/faang/school/godbless/work_stopped/MarketingResources.java
Task: https://faang-school.atlassian.net/browse/BJS2-6148
> BJS2-6148: Work stopped

- src/main/java/faang/school/godbless/space_x/Main.java
- src/main/java/faang/school/godbless/space_x/RocketLaunch.java
Task: https://faang-school.atlassian.net/browse/BJS2-5585
> BJS2-5585: SpaceX

- src/main/java/faang/school/godbless/BJS25695/RocketLaunch.java
- src/main/java/faang/school/godbless/BJS25695/SpaceXRocketPlanner.java
BJS2-5695 Космическая программа SpaceX
> BJS2-5695 Космическая программа SpaceX - Реализация задачи

- src/main/java/faang/school/godbless/turn_matrix/Coordinates.java
- src/main/java/faang/school/godbless/turn_matrix/FlipDirection.java
- src/main/java/faang/school/godbless/turn_matrix/Main.java
- src/main/java/faang/school/godbless/turn_matrix/MatrixTransformer.java
Task: https://faang-school.atlassian.net/browse/BJS2-5140
> BJS2-5140: Turn matrix

- src/main/java/faang/school/godbless/sprint2/stream/streamapi1/Constants.java
- src/main/java/faang/school/godbless/sprint2/stream/streamapi1/Runner.java
- src/main/java/faang/school/godbless/sprint2/stream/streamapi1/StreamUtilOperations.java
- src/main/java/faang/school/godbless/sprint2/stream/streamapi1/Utility.java
BJS2-5827: Added: Stream API 1 task was added.
> BJS2-5827: Added: Stream API 1 task was added.

- src/main/java/faang/school/godbless/sprint3/BJS2_6306/MailSender.java
- src/main/java/faang/school/godbless/sprint3/BJS2_6306/SenderRunnable.java
Task: https://faang-school.atlassian.net/browse/BJS2-6306
> BJS2-6306: add mail sender

- src/main/java/faang/school/godbless/sprint3/BJS2_6307/FoodDeliveryTask.java
- src/main/java/faang/school/godbless/sprint3/BJS2_6307/GriffinsFoodDelivery.java
TASK: https://faang-school.atlassian.net/browse/BJS2-6307
> BJS2-6307: add food delivery

- src/main/java/faang/school/godbless/broForce/Game.java
- src/main/java/faang/school/godbless/broForce/Main.java
> egorp bjs2 5977 bro force

- src/main/java/faang/school/godbless/sprint3/BJS2_6324/GooglePhotosAutoUploader.java
- src/main/java/faang/school/godbless/sprint3/BJS2_6324/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-6324
> BJS2-6324: add google photo uploader

- src/main/java/faang/school/godbless/BJS2_6209/DictionaryProcessor.java
- src/main/java/faang/school/godbless/BJS2_6209/Main.java
> Task BJS2-6209

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/starWarsArena/Battle.java
- src/main/java/faang/school/godbless/starWarsArena/Main.java
- src/main/java/faang/school/godbless/starWarsArena/Robot.java
https://faang-school.atlassian.net/browse/BJS2-6079
> Add solution for task BJS2-6079.

- src/main/java/faang/school/godbless/async/task_5/MagicalTournament.java
- src/main/java/faang/school/godbless/async/task_5/model/School.java
- src/main/java/faang/school/godbless/async/task_5/model/Student.java
- src/main/java/faang/school/godbless/async/task_5/model/Task.java
- src/main/java/faang/school/godbless/async/task_5/model/Tournament.java
Не знаю, верно ли я понял задачу.
Постарался сделать так, чтобы каждый студент из школы прошел испытание, но при этом, чтобы он не мог проходить 2 испытания одновременно.
Пришлось посидеть, до сих пор не уверен в решении.
> Турнир трех волшебников

- src/main/java/faang/school/godbless/sprint3/BJS2_6310/Chore.java
- src/main/java/faang/school/godbless/sprint3/BJS2_6310/WeasleyFamily.java
Task: https://faang-school.atlassian.net/browse/BJS2-6310
> BJS2-6310: weasley family tasks

- src/main/java/faang/school/godbless/sprint3/BJS2_6309/BigBangTheory.java
- src/main/java/faang/school/godbless/sprint3/BJS2_6309/Task.java
Task: https://faang-school.atlassian.net/browse/BJS2-6309
> BJS2-6309: add big bang theory tasks

- src/main/java/faang/school/godbless/sprint3/BJS2_6322/Music.java
- src/main/java/faang/school/godbless/sprint3/BJS2_6322/Player.java
Task: https://faang-school.atlassian.net/browse/BJS2-6322
> BJS2-6322: add player

- src/main/java/faang/school/godbless/feedpitergriffen/FoodDeliveryTask.java
- src/main/java/faang/school/godbless/feedpitergriffen/GriffinsFoodDelivery.java
Задание выполнено
реализован пример кода
> Накормите Питера Гриффина

- src/main/java/faang/school/godbless/sprint3/BJS2_6311/King.java
- src/main/java/faang/school/godbless/sprint3/BJS2_6311/Knight.java
- src/main/java/faang/school/godbless/sprint3/BJS2_6311/Trial.java
Task: https://faang-school.atlassian.net/browse/BJS2-6311
> BJS2-6311: king tournament

- src/main/java/faang/school/godbless/sprint3/BJS2_6320/Game.java
- src/main/java/faang/school/godbless/sprint3/BJS2_6320/Main.java
- src/main/java/faang/school/godbless/sprint3/BJS2_6320/Player.java
Task: https://faang-school.atlassian.net/browse/BJS2-6320
> BJS2-6320: add player & game

- src/main/java/faang/school/godbless/carryGotOverFed/Inventory.java
- src/main/java/faang/school/godbless/carryGotOverFed/Item.java
CarryGotOverfed according to Vlad
> Egorp bjs2 6042 carry got overfed

- src/main/java/faang/school/godbless/tracking_system/Location.java
- src/main/java/faang/school/godbless/tracking_system/TransportManagementSystem.java
- src/main/java/faang/school/godbless/tracking_system/Vehicle.java
- src/main/java/faang/school/godbless/tracking_system/VehicleTracker.java
Task: https://faang-school.atlassian.net/browse/BJS2-6173
> BJS2-6173: Tracking system

- src/main/java/faang/school/godbless/banks/Account.java
- src/main/java/faang/school/godbless/banks/Bank.java
- src/main/java/faang/school/godbless/banks/Main.java
Task: https://faang-school.atlassian.net/browse/BJS2-6185
> BJS2-6185: Banks

- src/main/java/faang/school/godbless/delivery_coupons/DeliveryService.java
- src/main/java/faang/school/godbless/delivery_coupons/Main.java
- src/main/java/faang/school/godbless/delivery_coupons/Order.java
- src/main/java/faang/school/godbless/delivery_coupons/Product.java
- src/main/java/faang/school/godbless/delivery_coupons/Promocode.java
Task: https://faang-school.atlassian.net/browse/BJS2-6256
> BJS2-6256: Delivery coupons

- src/main/java/faang/school/godbless/electronic_diary/CourseType.java
- src/main/java/faang/school/godbless/electronic_diary/Main.java
- src/main/java/faang/school/godbless/electronic_diary/Student.java
- src/main/java/faang/school/godbless/electronic_diary/StudentCollector.java
- src/main/java/faang/school/godbless/electronic_diary/StudentPerformanceService.java
- src/test/java/faang/school/godbless/electronic_diary/StudentPerformanceServiceTest.java
Task: https://faang-school.atlassian.net/browse/BJS2-5355
> BJS2-5355: Electronic diary

- src/main/java/leave_a_comment/Comment.java
- src/main/java/leave_a_comment/Main.java
- src/main/java/leave_a_comment/Post.java
- src/main/java/leave_a_comment/PostService.java
- src/main/java/leave_a_comment/User.java
Выполнил задание, отправляю PR
> Оставляем комментарий - BJS2-6117

- src/main/java/faang/school/godbless/triWizardTournament/MagicalTournament.java
- src/main/java/faang/school/godbless/triWizardTournament/School.java
- src/main/java/faang/school/godbless/triWizardTournament/Student.java
- src/main/java/faang/school/godbless/triWizardTournament/Task.java
- src/main/java/faang/school/godbless/triWizardTournament/Tournament.java
TriWizard tournament for review
> BJS2-6169- TriWizard tournament for review

- src/main/java/faang/school/godbless/async/task_6/Main.java
- src/main/java/faang/school/godbless/async/task_6/model/Potion.java
Я сначала написал вот такой вариант:
но потом у меня закрались сомнения о целесообразности вызова join в данном случае, поскольку мы используем allOf, который обеспечивает выполнение всех задач, которые мы в него передаем.
Правильно ли я понимаю, что при таком раскладе дополнительная блокировка с помощью join-ов избыточна?
Если это не так, то наведите меня пожалуйста на правильные мысли.
Документацию посмотрел, вроде как я мыслю верно.
> Качаем алхимию

- src/main/java/alchemy/Main.java
- src/main/java/alchemy/Potion.java
Выполнил задание, отправляю PR
> Качаем алхимию - BJS2-6111

- src/main/java/faang/school/godbless/multithreading_synchronization/BJS2_6505/GooglePhotosAutoUploader.java
- src/main/java/faang/school/godbless/multithreading_synchronization/BJS2_6505/Main.java
https://faang-school.atlassian.net/browse/BJS2-6505
> BJS2-6505: Google Photo sync

- src/main/java/faang/school/godbless/multithreading_synchronization/BJS2_6506/Boss.java
- src/main/java/faang/school/godbless/multithreading_synchronization/BJS2_6506/Main.java
- src/main/java/faang/school/godbless/multithreading_synchronization/BJS2_6506/Player.java
https://faang-school.atlassian.net/browse/BJS2-6506
> BJS2-6506: Wait notify the battle with boss

- src/main/java/faang/school/godbless/multithreading_synchronization/BJS2_6507/Game.java
- src/main/java/faang/school/godbless/multithreading_synchronization/BJS2_6507/Main.java
- src/main/java/faang/school/godbless/multithreading_synchronization/BJS2_6507/Player.java
https://faang-school.atlassian.net/browse/BJS2-6507
> BJS2-6507: multithread game with lives

- src/main/java/faang/school/godbless/multithreading_async/BJS2_6514/Main.java
- src/main/java/faang/school/godbless/multithreading_async/BJS2_6514/School.java
- src/main/java/faang/school/godbless/multithreading_async/BJS2_6514/Student.java
- src/main/java/faang/school/godbless/multithreading_async/BJS2_6514/Task.java
- src/main/java/faang/school/godbless/multithreading_async/BJS2_6514/Tournament.java
https://faang-school.atlassian.net/browse/BJS2-6514
> BJS2-6514: supplyAsync for 2 tasks and allOf

- src/main/java/faang/school/godbless/multithreading_async/BJS2_6513/Main.java
- src/main/java/faang/school/godbless/multithreading_async/BJS2_6513/ResultConsumer.java
- src/main/java/faang/school/godbless/multithreading_async/BJS2_6513/SquareRequest.java
https://faang-school.atlassian.net/browse/BJS2-6513
> BJS2-6513: Async Square calc

- src/main/java/faang/school/godbless/multithreading_async/BJS2_6511/Main.java
- src/main/java/faang/school/godbless/multithreading_async/BJS2_6511/Player.java
- src/main/java/faang/school/godbless/multithreading_async/BJS2_6511/Quest.java
- src/main/java/faang/school/godbless/multithreading_async/BJS2_6511/QuestSystem.java
https://faang-school.atlassian.net/browse/BJS2-6511
> BJS2-6511: players pass quests in CompletableFuture.

- .github/workflows/ci.yaml
- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/multithreading_async/BJS2_6510/Main.java
- src/main/java/faang/school/godbless/multithreading_async/BJS2_6510/MasterCardService.java
https://faang-school.atlassian.net/browse/BJS2-6510
> bjs2-6510: Асинхронность и Future

- src/main/java/faang/school/godbless/task1/Main.java
- src/main/java/faang/school/godbless/task1/User.java
Задание "Коллекционируем пользователей"
> Сделал задание 1 "Коллекционируем пользователей"

- src/main/java/faang/school/godbless/task1/Main.java
- src/main/java/faang/school/godbless/task1/User.java
Запушил по рекомендациям из лекций еще и класс Main для проверки работоспособности.
> Task_1 done

- src/main/java/faang/school/godbless/User.java
- src/test/java/faang/school/godbless/UserTest.java
Запрос на проверку задания  "Группировка пользователей по возрасту"
> добавил юзера и метод групировки по возрасту

- src/main/java/faang/school/godbless/Main.java
- src/main/java/faang/school/godbless/Product.java
Написал 2 метода. 1) группировка товаров по категории; 2) Вывод инфомации с помощью Entry
> Разбираем склад Амазон

- build.gradle
- src/main/java/faang/school/godbless/task1/User.java
- src/main/java/faang/school/godbless/task1/UserTest.java
Создан метод который проходит по списку пользователей. В цикле мы получаем возраст каждого пользователя и смотрим не является ли он уже ключом. Далее в зависимости от результата или просто добавляем пользователя в список по его возрасту или создаем сначала новый ключ, а потом добавляем пользователя в соответствующий список.
> Решение задачи "Группировка пользователей по возрасту".

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/User.java
> BJS2-7580 Группировка пользователей по возрасту

- .github/workflows/ci.yaml
- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/domain/User.java
> User class created

- build.gradle
- src/main/java/faang/school/godbless/usersGroupedByAge/User.java
- src/main/java/faang/school/godbless/usersGroupedByAge/UserTest.java
Решил написать код через TDD, но тесты сходу не завелись, пришлось добавить строку в `build.gradle`, но хз, насколько это правильно. Ошибка при запуске тестов была такая: `java: package org.junit does not exist `.
> Группировка пользователей по возрасту

- src/main/java/faang/school/godbless/Westeros/House.java
- src/main/java/faang/school/godbless/Westeros/Main.java
> Implemented a new class and created methods for interacting with HashMap : Java HashMap: Игра престолов

- src/main/java/faang/school/godbless/groupbyage/Main.java
- src/main/java/faang/school/godbless/groupbyage/User.java
- Created User class with necessary fields.
- Added groupUsers static method for grouping users by age.
- Verified the implementation with sample data in main method.
> Implemented user grouping by age

- src/main/java/faang/school/godbless/BJS27707/Example.java
- src/main/java/faang/school/godbless/BJS27707/Main.java
Implement Array reverse
Да, я понимаю, что для примитивов так не будет работать, но очень хотелось обойтись без перебора, не нарушив условия задачи :)
> Resolve task BJS2-7707.

- src/main/java/faang/school/godbless/BJS27788/Archer.java
- src/main/java/faang/school/godbless/BJS27788/Character.java
- src/main/java/faang/school/godbless/BJS27788/Main.java
- src/main/java/faang/school/godbless/BJS27788/Warrior.java
Create abstract class and use some plain patterns
> Resolve task BJS2-7788.

- src/main/java/faang/school/godbless/abstraction/Archer.java
- src/main/java/faang/school/godbless/abstraction/Character.java
- src/main/java/faang/school/godbless/abstraction/Main.java
- src/main/java/faang/school/godbless/abstraction/Warrior.java
- Created abstract class Character with fields: name, strength, agility, intelligence, and health (default 100).
- Added two constructors in Character: one accepting only name, another accepting all fields except health.
- Created subclasses Warrior and Archer with specific values for strength, agility, and intelligence.
- Implemented constructors for Warrior and Archer to set predefined attribute values and accept name from outside.
- Added abstract method attack in Character class which accepts another Character as a parameter.
- Implemented attack method in Warrior class to deal damage equal to the Warrior's strength.
- Implemented attack method in Archer class to deal damage equal to the Archer's agility.
> Add Character class with constructors and subclasses Warrior and Archer

- src/main/java/faang/school/godbless/Main.java
- src/main/java/faang/school/godbless/Student.java
- src/main/java/faang/school/godbless/Subject.java
https://faang-school.atlassian.net/browse/BJS2-7958
> Java HashMap: Двойной кэш-кэш

- src/main/java/faang/school/godbless/BJS2_7177/Test.java
- src/main/java/faang/school/godbless/BJS2_7177/User.java
> BJS2-7177 Коллекционируем пользователей

- src/main/java/faang/school/godbless/BJS27500/Main.java
- src/main/java/faang/school/godbless/BJS27500/User.java
Create map of Users with common Hobby
> Maksim don bjs2 7500

- src/main/java/faang/school/godbless/module1/sprint1/task13/DataCenter.java
- src/main/java/faang/school/godbless/module1/sprint1/task13/DataCenterService.java
- src/main/java/faang/school/godbless/module1/sprint1/task13/Main.java
- src/main/java/faang/school/godbless/module1/sprint1/task13/OptimizationStrategy.java
- src/main/java/faang/school/godbless/module1/sprint1/task13/ResourceRequest.java
- src/main/java/faang/school/godbless/module1/sprint1/task13/Server.java
https://faang-school.atlassian.net/browse/BJS2-8535
> Java HashMap: Оптимизируем работу дата-центра

- src/main/java/faang/school/godbless/module1/sprint1/task1/Main.java
- src/main/java/faang/school/godbless/module1/sprint1/task1/User.java
Группировка пользователей по возрасту  [BJS2-7563]
[BJS2-7563]: https://faang-school.atlassian.net/browse/BJS2-7563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Frai bjs2 7563

- src/main/java/faang/school/godbless/BJS27979/Battlefield.java
- src/main/java/faang/school/godbless/BJS27979/Creatures/Bandit.java
- src/main/java/faang/school/godbless/BJS27979/Creatures/BlackDragon.java
- src/main/java/faang/school/godbless/BJS27979/Creatures/Creature.java
- src/main/java/faang/school/godbless/BJS27979/Creatures/Dwarf.java
- src/main/java/faang/school/godbless/BJS27979/Creatures/Efreet.java
- src/main/java/faang/school/godbless/BJS27979/Creatures/GoldGolem.java
- src/main/java/faang/school/godbless/BJS27979/Creatures/Minotaur.java
- src/main/java/faang/school/godbless/BJS27979/Creatures/Naga.java
- src/main/java/faang/school/godbless/BJS27979/Creatures/Titan.java
- src/main/java/faang/school/godbless/BJS27979/Hero.java
- src/main/java/faang/school/godbless/BJS27979/Main.java
Implement Heroes of Might and Magic fight mechanic
> Maksim don bjs2 7979

- src/main/java/faang/school/godbless/BJS2_8241/Book.java
- src/main/java/faang/school/godbless/BJS2_8241/Main.java
> work build

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/library/of/westeros/Book.java
Продублирую комментарий: "Я проверил все методы, что написал - они работают. Просто я почему-то решил проверять каждый метод когда писал его по факту - потом стирать код - снова писать для след. метода."
> Задание: Java HashMap: Библиотека Вестероса.

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/User.java
> Max.shundrik bjs2 7174

- src/main/java/faang/school/godbless/revert/Example.java
- src/main/java/faang/school/godbless/revert/Main.java
- Created Example class.
- Added reverse method that accepts an array of integers as a parameter.
- Implemented logic in reverse method to reverse the given array.
- Example: {nums = [1,2,3,4,5]} → reverse(nums) → nums = [5,4,3,2,1]
> Add Example class with reverse method to reverse an array of integers

- src/main/java/faang/school/godbless/usercollection/Main.java
- src/main/java/faang/school/godbless/usercollection/User.java
- Created User class with fields: id, name, age, and activities.
- Added method findHobbyLovers to find users with matching activities from a given set.
- Implemented logic to return a map where the key is the user and the value is the first matching activity.
- Added a constructor to User class for easier instantiation.
- Included example usage in Main class to demonstrate the functionality of findHobbyLovers method.
> Add User class with findHobbyLovers method and example usage

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/Task4/Main.java
> Holymagic1997 bjs2 7729 Абстракция, абстракция!

- src/main/java/faang/school/godbless/BJS28024/House.java
- src/main/java/faang/school/godbless/BJS28024/Main.java
Create HouseLibrary of Westeros with simple methods.
> Resolve task BJS2-8024.

- src/main/java/faang/school/godbless/module1/spring1/task8/Angel.java
- src/main/java/faang/school/godbless/module1/spring1/task8/Battlefield.java
- src/main/java/faang/school/godbless/module1/spring1/task8/Creature.java
- src/main/java/faang/school/godbless/module1/spring1/task8/Griffin.java
- src/main/java/faang/school/godbless/module1/spring1/task8/Hero.java
- src/main/java/faang/school/godbless/module1/spring1/task8/Main.java
- src/main/java/faang/school/godbless/module1/spring1/task8/Pikeman.java
- src/main/java/faang/school/godbless/module1/spring1/task8/Swordman.java
https://faang-school.atlassian.net/browse/BJS2-7902
> Java HashMap: Герои меча и магии 

- src/main/java/faang/school/godbless/module1/sprint1/task5/Main.java
- src/main/java/faang/school/godbless/module1/sprint1/task5/User.java
Коллекционируем пользователей BJS2-7145
> Коллекционируем пользователей

- src/main/java/faang/school/godbless/hogwarts/Main.java
- src/main/java/faang/school/godbless/hogwarts/SpellAction.java
- src/main/java/faang/school/godbless/hogwarts/SpellCaster.java
…l management
- Created SpellAction functional interface with cast method.
- Implemented SpellCaster class with cast method to execute and print spell actions.
- Added Main class to demonstrate the usage of SpellCaster with various spells.
- Demonstrated spells: "Alohomora", "Lumos", and "Expelliarmus".
> Add SpellAction interface, SpellCaster class, and Main class for spell

- src/main/java/faang/school/godbless/reverse/Example.java
- src/main/java/faang/school/godbless/reverse/Main.java
> Task Развернитесь!

- src/main/java/faang/school/godbless/store/Main.java
- src/main/java/faang/school/godbless/store/Product.java
Java HashMap: Разбираем склад Amazon
> nulldeathh-BJS2-8273 : Java HashMap: Разбираем склад Amazon

- src/main/java/faang/school/godbless/prestol_game/House.java
- src/main/java/faang/school/godbless/prestol_game/Main.java
Задача Игра престолов
- добавил несколько домов в ХэшМапу
- создал методы добавления дома и вывода списка домов
> - создал класс Home

- src/main/java/faang/school/godbless/Library/Book.java
- src/main/java/faang/school/godbless/Library/Main.java
Java HashMap: Библиотека Вестероса
> nulldeathh-BJS2-8215 : Java HashMap: Библиотека Вестероса

- src/main/java/faang/school/godbless/aged777_BSJ2_collect_users/Main.java
- src/main/java/faang/school/godbless/aged777_BSJ2_collect_users/User.java
> выполнить задачу BSJ2-7758

- src/main/java/faang/school/godbless/module1/sprint1/task9/GroupStudentsByCourse.java
- src/main/java/faang/school/godbless/module1/sprint1/task9/Main.java
- src/main/java/faang/school/godbless/module1/sprint1/task9/Student.java
https://faang-school.atlassian.net/browse/BJS2-8173
> Java HashMap: Считаем прогулы

- src/main/java/faang/school/godbless/module1/sprint1/task10/Main.java
- src/main/java/faang/school/godbless/module1/sprint1/task10/WeatherData.java
https://faang-school.atlassian.net/browse/BJS2-8618
> Java HashMap: Кэшируем, кэшируем

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/User.java
- src/main/java/faang/school/godbless/groupingUsersByAge/Application.java
- src/main/java/faang/school/godbless/groupingUsersByAge/User.java
https://faang-school.atlassian.net/browse/BJS2-7548
> happyismile-BJS2-7548

- src/main/java/faang/school/godbless/googletranslator/DictionaryProcessor.java
- src/main/java/faang/school/godbless/googletranslator/Main.java
- Created DictionaryProcessor class with processWord method.
- Method processWord accepts a word, its translation, and a BiConsumer for dictionary processing.
- Defined BiConsumer lambda to add words and translations to a dictionary.
- Tested the system by adding multiple words and their translations to the dictionary.
- Verified the functionality by printing the dictionary content.
> Implement DictionaryProcessor for word processing using BiConsumer

- src/main/java/faang/school/godbless/instagramfilters/FilterProcessor.java
- src/main/java/faang/school/godbless/instagramfilters/Image.java
- src/main/java/faang/school/godbless/instagramfilters/Main.java
- Created Image class with name and description fields.
- Implemented FilterProcessor class with methods:
- applyFilter: accepts an Image object and a higher-order function (e.g., Function<Image, Image>) to apply a filter, returns a new Image object with the applied filter.
- combineFilters: accepts two higher-order functions and returns a new higher-order function that sequentially applies both functions.
- Defined several filters using lambda expressions and standard Java functional interfaces.
- Grayscale filter updates the image name and appends filter information to the description.
- Sepia filter updates the image name and appends filter information to the description.
- Vignette filter updates the image name and appends filter information to the description.
- Demonstrated the use …
> Add Image filtering functionality and combined filter handling

- src/main/java/faang/school/godbless/vesteros_library/Book.java
- src/main/java/faang/school/godbless/vesteros_library/Main.java
> Garikgarikas bjs2 8200

- src/main/java/faang/school/godbless/errorhandling/ErrorHandler.java
- src/main/java/faang/school/godbless/errorhandling/ExceptionHandler.java
- src/main/java/faang/school/godbless/errorhandling/Main.java
- Created ExceptionHandler functional interface with handle method to process exceptions.
- Implemented ErrorHandlingUtil class with static method withErrorHandling:
- Method withErrorHandling accepts a Supplier<T> for the main action and an ExceptionHandler for error handling.
- Executes the main action and handles exceptions using the provided ExceptionHandler.
- Added Main class to demonstrate the usage of withErrorHandling method:
- Example usage of withErrorHandling to wrap remote service calls with error handling.
- Included logging of exceptions and returning default value on error.
> Add error handling method with ExceptionHandler interface

- src/main/java/faang/school/godbless/spamfilter/Main.java
- src/main/java/faang/school/godbless/spamfilter/MessageFilter.java
- src/main/java/faang/school/godbless/spamfilter/MessageProcessor.java
- Created MessageFilter functional interface with filter method to apply filters on messages.
- Implemented MessageProcessor class with processMessage method to process messages using a list of MessageFilter objects.
- Method processMessage accepts a message and a list of filters, and returns true if the message passes all filters.
- Added example usage in Main class to demonstrate the functionality.
- Created spam, length, and emoji filters using lambda expressions.
- Processed multiple messages with different filters and printed the results.
> Implement Message filtering system using custom functional interface

- src/main/java/faang/school/godbless/Task9/Connection.java
- src/main/java/faang/school/godbless/Task9/Main.java
- src/main/java/faang/school/godbless/Task9/Test.java
- src/main/java/faang/school/godbless/Task9/WeatherData.java
> Holymagic1997 bjs2 8662 Кэшируем, кэшируем

- src/main/java/faang/school/godbless/stream_split/hogwarts/Main.java
- src/main/java/faang/school/godbless/stream_split/hogwarts/SpellAction.java
- src/main/java/faang/school/godbless/stream_split/hogwarts/SpellCaster.java
Хогвартс, Хогвартс, наш любимый Хогвартс
> nulldeathh-BJS2-9262 : Хогвартс

- src/main/java/faang/school/godbless/stream_split/instagram/FilterProcessor.java
- src/main/java/faang/school/godbless/stream_split/instagram/Image.java
- src/main/java/faang/school/godbless/stream_split/instagram/Main.java
> nulldeathh-BJS2-9848 : Фильтры Instagram

- src/main/java/faang/school/godbless/App.java
- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/House.java
BJS2-8068 Java HashMap: Игра престолов
> BJS2-8068 Java HashMap: Игра престолов

- src/main/java/faang/school/godbless/AppliedCalculator.java
- src/main/java/faang/school/godbless/Calculator.java
implemented AppliedCalculator class with methods: add and product
> Калькулятор

- src/main/java/faang/school/godbless/hogwards/Main.java
- src/main/java/faang/school/godbless/hogwards/SpellAction.java
- src/main/java/faang/school/godbless/hogwards/SpellCaster.java
> Хогвартс, Хогвартс

- src/main/java/faang/school/godbless/google_translator/DictionaryProcessor.java
- src/main/java/faang/school/godbless/google_translator/Main.java
> Google Translator

- src/main/java/faang/school/godbless/our_hogwards/Main.java
- src/main/java/faang/school/godbless/our_hogwards/SpellAction.java
- src/main/java/faang/school/godbless/our_hogwards/SpellCaster.java
Задача "Хогвартс, Хогвартс, наш любимый Хогвартс"
> Garikgarikas bjs2 9203

- src/main/java/faang/school/godbless/meta_universe/Main.java
- src/main/java/faang/school/godbless/meta_universe/Notification.java
- src/main/java/faang/school/godbless/meta_universe/NotificationManager.java
> Garikgarikas bjs2 10113

- src/main/java/faang/school/godbless/module1/sprint2/task10/Droid.java
- src/main/java/faang/school/godbless/module1/sprint2/task10/DroidMessageEncryptor.java
- src/main/java/faang/school/godbless/module1/sprint2/task10/DroidMessageReceiver.java
- src/main/java/faang/school/godbless/module1/sprint2/task10/Main.java
https://faang-school.atlassian.net/browse/BJS2-9005
> Секреты дроидов

- src/main/java/faang/school/godbless/module1/sprint2/task7/Main.java
- src/main/java/faang/school/godbless/module1/sprint2/task7/MessageFilter.java
- src/main/java/faang/school/godbless/module1/sprint2/task7/MessageProcessor.java
https://faang-school.atlassian.net/browse/BJS2-9969
> Фильтруем спам

- src/main/java/faang/school/godbless/BJS2_10059/Main.java
- src/main/java/faang/school/godbless/BJS2_10059/Notification.java
- src/main/java/faang/school/godbless/BJS2_10059/NotificationManager.java
- src/main/java/faang/school/godbless/BJS2_10059/ObscenityFilter.java
> BJS2-10059

- src/main/java/faang/school/godbless/Archer.java
- src/main/java/faang/school/godbless/Character.java
- src/main/java/faang/school/godbless/Warrior.java
Created an abstract class Character and two inherited classes from it
> Created abstract class Character and its subclasses Warrior and Archer

- src/main/java/faang/school/godbless/collectUsers/User.java
Created User class with findHobbyLovers method for users collecting
> Created User class with findHobbyLovers method

- src/main/java/faang/school/godbless/rotate_matrix/Coordinates.java
- src/main/java/faang/school/godbless/rotate_matrix/FlipDirection.java
- src/main/java/faang/school/godbless/rotate_matrix/Main.java
- src/main/java/faang/school/godbless/rotate_matrix/MatrixOperations.java
- src/main/java/faang/school/godbless/rotate_matrix/MatrixTransformer.java
> Повернём матрицу

- src/main/java/faang/school/godbless/uber_millions/FareCalculator.java
- src/main/java/faang/school/godbless/uber_millions/Main.java
> Миллиончики Uber

- src/main/java/faang/school/godbless/streamapi2/Employee.java
- src/main/java/faang/school/godbless/streamapi2/Main.java
- src/main/java/faang/school/godbless/streamapi2/SomeMethods.java
- Implement findPairsWithSum method: Finds all unique pairs of integers from a list whose sum equals a given target.
- Implement sortCapitalsByCountry method: Sorts a map of country names and capitals by country names in alphabetical order and returns a list of capitals.
- Implement filterAndSortStrings method: Filters a list of strings that start with a given character and sorts them by length in ascending order.
- Implement findNonFriendsWithCommonFriends method: Finds all pairs of people who are not friends but have common friends from a given map of people and their friends.
- Implement averageSalaryByDepartment method: Calculates the average salary for each department from a list of employees.
- Implement filterAndSortStringsByAlphabet method: Filters and sorts strings that only …
> Implement various utility methods for handling collections and maps

- src/main/java/faang/school/godbless/Pokemon.java
- src/main/java/faang/school/godbless/week1/Archer.java
- src/main/java/faang/school/godbless/week1/Character.java
- src/main/java/faang/school/godbless/week1/Example.java
- src/main/java/faang/school/godbless/week1/GameOfThrones/Book.java
- src/main/java/faang/school/godbless/week1/GameOfThrones/House.java
- src/main/java/faang/school/godbless/week1/GameOfThrones/Library.java
- src/main/java/faang/school/godbless/week1/GameOfThrones/Main.java
- src/main/java/faang/school/godbless/week1/Main.java
- src/main/java/faang/school/godbless/week1/Registration.java
- src/main/java/faang/school/godbless/week1/Students/Main.java
- src/main/java/faang/school/godbless/week1/Students/Students.java
- src/main/java/faang/school/godbless/week1/User.java
- src/main/java/faang/school/godbless/week1/User3.java
- src/main/java/faang/school/godbless/week1/Warrior.java
- src/main/java/faang/school/godbless/week1/Weather/WeatherData.java
- src/main/java/faang/school/godbless/week1/Weather/main.java
> Vovohka bjs2 8889

- src/main/java/faang/school/godbless/Pokemon.java
- src/main/java/faang/school/godbless/week1/User.java
> Mark bjs2 7562

- src/main/java/faang/school/godbless/Pokemon.java
- src/main/java/faang/school/godbless/week1/Archer.java
- src/main/java/faang/school/godbless/week1/Character.java
- src/main/java/faang/school/godbless/week1/Main.java
- src/main/java/faang/school/godbless/week1/Registration.java
- src/main/java/faang/school/godbless/week1/User.java
- src/main/java/faang/school/godbless/week1/Warrior.java
> Mark bjs2 7807

- src/main/java/faang/school/godbless/Pokemon.java
- src/main/java/faang/school/godbless/week1/Archer.java
- src/main/java/faang/school/godbless/week1/Character.java
- src/main/java/faang/school/godbless/week1/Example.java
- src/main/java/faang/school/godbless/week1/Main.java
- src/main/java/faang/school/godbless/week1/Registration.java
- src/main/java/faang/school/godbless/week1/User.java
- src/main/java/faang/school/godbless/week1/Warrior.java
> Mark bjs2 7652

- src/main/java/faang/school/godbless/Pokemon.java
- src/main/java/faang/school/godbless/week1/Archer.java
- src/main/java/faang/school/godbless/week1/Character.java
- src/main/java/faang/school/godbless/week1/Example.java
- src/main/java/faang/school/godbless/week1/GameOfThrones/Book.java
- src/main/java/faang/school/godbless/week1/GameOfThrones/House.java
- src/main/java/faang/school/godbless/week1/GameOfThrones/Library.java
- src/main/java/faang/school/godbless/week1/GameOfThrones/Main.java
- src/main/java/faang/school/godbless/week1/Main.java
- src/main/java/faang/school/godbless/week1/Registration.java
- src/main/java/faang/school/godbless/week1/User.java
- src/main/java/faang/school/godbless/week1/User3.java
- src/main/java/faang/school/godbless/week1/Warrior.java
git commit -m "BJS2-8289 <message>"
> Mark bjs2 8289

- src/main/java/faang/school/godbless/Pokemon.java
- src/main/java/faang/school/godbless/week1/Archer.java
- src/main/java/faang/school/godbless/week1/Character.java
- src/main/java/faang/school/godbless/week1/Example.java
- src/main/java/faang/school/godbless/week1/GameOfThrones/Book.java
- src/main/java/faang/school/godbless/week1/GameOfThrones/House.java
- src/main/java/faang/school/godbless/week1/GameOfThrones/Library.java
- src/main/java/faang/school/godbless/week1/GameOfThrones/Main.java
- src/main/java/faang/school/godbless/week1/Main.java
- src/main/java/faang/school/godbless/week1/Registration.java
- src/main/java/faang/school/godbless/week1/Students/Main.java
- src/main/java/faang/school/godbless/week1/Students/Students.java
- src/main/java/faang/school/godbless/week1/User.java
- src/main/java/faang/school/godbless/week1/User3.java
- src/main/java/faang/school/godbless/week1/Warrior.java
> Vovohka bjs2 8325

- src/main/java/faang/school/godbless/google_maps/Location.java
- src/main/java/faang/school/godbless/google_maps/LocationSearchEngine.java
- src/main/java/faang/school/godbless/google_maps/Main.java
> Google Maps

- src/main/java/faang/school/godbless/stream_api1/Main.java
- src/main/java/faang/school/godbless/stream_api1/StreamOperations.java
added static methods, processing integers and strings
> BJS2-10750 - Потренируем Stream API

- src/main/java/faang/school/godbless/BJS29555/Main.java
- src/main/java/faang/school/godbless/BJS29555/SpellAction.java
- src/main/java/faang/school/godbless/BJS29555/SpellCaster.java
Implement new Functional Interface
> Resolve task BJS2-9555

- src/main/java/faang/school/godbless/streamapi1/Main.java
- src/main/java/faang/school/godbless/streamapi1/MathMethods.java
- Added method to find the sum of even numbers in a list of integers.
- Added method to find the maximum element in a list of integers.
- Added method to find the average value of a list of integers.
- Added method to count the number of strings starting with a specific character in a list of strings.
- Added method to filter a list of strings, keeping only those containing a specific substring.
- Added method to sort a list of strings by their lengths.
- Added method to check if all elements in a list satisfy a specific condition.
- Added method to find the smallest element in a list that is greater than a given number.
- Added method to transform a list of strings into a list of their lengths.
> Implement utility class with static methods for various list operations

- src/main/java/faang/school/godbless/stream_split/calc/Calculator.java
- src/main/java/faang/school/godbless/stream_split/calc/Main.java
> nulldeathh-BJS2-8990 : Калькулятор

- src/main/java/faang/school/godbless/User.java
Created User class and GroupUsers method
> Group users by ages

- src/main/java/faang/school/godbless/build_csv/CsvFormatter.java
- src/main/java/faang/school/godbless/build_csv/Main.java
- src/main/java/faang/school/godbless/build_csv/MatrixJoiner.java
- src/main/java/faang/school/godbless/build_csv/VectorJoiner.java
> Построим CSV

- src/main/java/faang/school/godbless/activity_analysis/ActionType.java
- src/main/java/faang/school/godbless/activity_analysis/Main.java
- src/main/java/faang/school/godbless/activity_analysis/UserAction.java
- src/main/java/faang/school/godbless/activity_analysis/UserActionProcessor.java
Initial realization of 4 main methods of task
> BJS2-10355 - Анализ активности пользователей

- src/main/java/faang/school/godbless/Example.java
- src/main/java/faang/school/godbless/array_reverse/Example.java
Разворачивание массива через два указателя
> BJS2-7657-array_reverse

- src/main/java/faang/school/godbless/BJS210222/Main.java
- src/main/java/faang/school/godbless/BJS210222/Notification.java
- src/main/java/faang/school/godbless/BJS210222/NotificationManager.java
Implement Notification Manager and Notification filters
> Resolve task BJS2-10222

- src/main/java/faang/school/godbless/BJS2_10414/Main.java
BJS2-10414 Потренируем StreamAPI 1
> BJS2-10414

- src/main/java/faang/school/godbless/BJS2_10673/Employee.java
- src/main/java/faang/school/godbless/BJS2_10673/Main.java
BJS2-10673 Потренируем StreamAPI 2
> BJS2-10673

- src/main/java/faang/school/godbless/BJS29199/Character.java
- src/main/java/faang/school/godbless/BJS29199/InventoryManager.java
- src/main/java/faang/school/godbless/BJS29199/Item.java
- src/main/java/faang/school/godbless/BJS29199/Main.java
Implement simple functions with LOTR characters inventory
> Resolve task BJS2-9199

- src/main/java/faang/school/godbless/BJS28666/AverageLoadOptimizationStrategy.java
- src/main/java/faang/school/godbless/BJS28666/DataCenter.java
- src/main/java/faang/school/godbless/BJS28666/DataCenterService.java
- src/main/java/faang/school/godbless/BJS28666/EnergyEfficencyOptimizationStrategy.java
- src/main/java/faang/school/godbless/BJS28666/Main.java
- src/main/java/faang/school/godbless/BJS28666/OptimizationStrategy.java
- src/main/java/faang/school/godbless/BJS28666/ResourceRequest.java
- src/main/java/faang/school/godbless/BJS28666/Server.java
Implement DataCenter with optimizationStrategy and requestList
> Maksim don bjs2 8666

- src/main/java/faang/school/godbless/BJS28999/Calculator.java
- src/main/java/faang/school/godbless/BJS28999/Main.java
Implement FunctionalInterface Calculator
> Resolve task BJS2-8999

- src/main/java/faang/school/godbless/BJS28888/Data.java
- src/main/java/faang/school/godbless/BJS28888/DataBase.java
- src/main/java/faang/school/godbless/BJS28888/LRUCache.java
- src/main/java/faang/school/godbless/BJS28888/Main.java
> Resolve task BJS2-8888

- src/main/java/faang/school/godbless/User.java
Class User added to the project
> Class User added to the project

- src/main/java/faang/school/godbless/vesteros_library/Book.java
- src/main/java/faang/school/godbless/vesteros_library/Main.java
BJS2-8274 LibraryOfWesteros
create Class Book
implements methods : 
- addBook ( );
- removeBook( );
- findBook( );
- showAllBooks( );
> BJS2-8274 LibraryOfWesteros

- src/main/java/faang/school/godbless/user_group_by_id/Main.java
- src/main/java/faang/school/godbless/user_group_by_id/User.java
> done task group users by age for review

- src/main/java/faang/school/godbless/lambda/Calculator.java
- src/main/java/faang/school/godbless/lambda/Main.java
Создал класс калькулятор с методами для вычисления суммы и умножения на основе листа из чисел
> Создание калькулятора

- src/main/java/faang/school/godbless/calculate/Calculator.java
- src/main/java/faang/school/godbless/calculate/Main.java
create Interface Calculator
implemented method calculate();
realize method product();
realize method sum();
> BJS2-9032 Calculator 

- src/main/java/faang/school/godbless/lords_of_rings/Character.java
- src/main/java/faang/school/godbless/lords_of_rings/InventoryManager.java
- src/main/java/faang/school/godbless/lords_of_rings/Item.java
- src/main/java/faang/school/godbless/lords_of_rings/Main.java
implements methods:
addItem();
removeItem();
updateItem();
> BJS2-9136 Lords of the rings

- src/main/java/faang/school/godbless/lambdaEx/Main.java
- src/main/java/faang/school/godbless/lambdaEx/SpellAction.java
- src/main/java/faang/school/godbless/lambdaEx/SpellCaster.java
Создан класс SpellCaster с методом cast, который принимает строку с названием заклинания и лямбда-выражение, описывающее действие этого заклинания
> Создан функциональный интерфейс и класс SpellCaster 

- src/main/java/faang/school/godbless/registratuon_users/Main.java
- src/main/java/faang/school/godbless/registratuon_users/User.java
BJS2-7849 User Registration
Create class User
implements method groupUsers
> BJS2-7849  UsersRegistration

- src/main/java/faang/school/godbless/multithreading/microsoft/MailSender.java
- src/main/java/faang/school/godbless/multithreading/microsoft/SenderRunnable.java
> nulldeathh-BJS2-11807 : Вы работаете в Microsoft!

- src/main/java/faang/school/godbless/multithreading/family_guy/FoodDeliveryTask.java
- src/main/java/faang/school/godbless/multithreading/family_guy/GriffinsFoodDelivery.java
> nulldeathh-BJS2-12059 : Накормите Питера Гриффина

- src/main/java/faang/school/godbless/TheKingTournament/King.java
- src/main/java/faang/school/godbless/TheKingTournament/Knight.java
- src/main/java/faang/school/godbless/TheKingTournament/Trial.java
Не понял как реализовать эту подзадачу -  Реализуйте метод startTrials(), который будет запускать испытания в отдельных потоках, используя пул потоков.
> Kirill bjs2 10876

- src/main/java/faang/school/godbless/heroes/Archer.java
- src/main/java/faang/school/godbless/heroes/Army.java
- src/main/java/faang/school/godbless/heroes/Mage.java
- src/main/java/faang/school/godbless/heroes/Main.java
- src/main/java/faang/school/godbless/heroes/Swordsman.java
- src/main/java/faang/school/godbless/heroes/ThreadArmy.java
- src/main/java/faang/school/godbless/heroes/Warriors.java
> Heroes Multithreading

- src/main/java/faang/school/godbless/microsoft/MailSender.java
- src/main/java/faang/school/godbless/microsoft/SenderRunnable.java
- Added MailSender class to create and manage threads for sending emails.
- Added SenderRunnable class implementing Runnable to handle the logic of sending emails.
- Each thread sends a batch of 200 emails, ensuring no duplication.
- Implemented thread joining to wait for all threads to complete before signaling completion.
> Implemented multithreaded mail sending

- src/main/java/faang/school/godbless/module1/sprint3/task5/King.java
- src/main/java/faang/school/godbless/module1/sprint3/task5/Knight.java
- src/main/java/faang/school/godbless/module1/sprint3/task5/Trial.java
https://faang-school.atlassian.net/browse/BJS2-10883
> Турнир в Королевской гавани

- src/main/java/faang/school/godbless/BJS2_11893/MailSender.java
- src/main/java/faang/school/godbless/BJS2_11893/SenderRunnable.java
BJS2-11893 Вы работаете в Microsoft!
> BJS2-11893

- src/main/java/faang/school/godbless/BJS2_12098/FoodDeliveryTask.java
- src/main/java/faang/school/godbless/BJS2_12098/GriffinsFoodDelivery.java
BJS2-12098 Накормите Питера Гриффина
> BJS2-12098

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/Microsoft/MailSender.java
- src/main/java/faang/school/godbless/Microsoft/SenderRunnable.java
можно вопрос, а почему в ходе выполнения программы, System.out.println() не выводится?
> Решение задачи Microsoft

- src/main/java/faang/school/godbless/multithreading/army/Archer.java
- src/main/java/faang/school/godbless/multithreading/army/Army.java
- src/main/java/faang/school/godbless/multithreading/army/Character.java
- src/main/java/faang/school/godbless/multithreading/army/Mage.java
- src/main/java/faang/school/godbless/multithreading/army/Main.java
- src/main/java/faang/school/godbless/multithreading/army/Swordsman.java
- src/main/java/faang/school/godbless/multithreading/army/ThreadDistribution.java
> nulldeathh-BJS2-10988 : Распределенная армия героев меча и магии

- src/main/java/faang/school/godbless/meta/Main.java
- src/main/java/faang/school/godbless/meta/Notification.java
- src/main/java/faang/school/godbless/meta/NotificationManager.java
BJS2-10098: - Meta-Universe
implements method registerHandler( );
implements method sendNotification( );
> BJS2-10098: - Meta-Universe

- src/main/java/faang/school/godbless/module1/sprint3/task3/Archer.java
- src/main/java/faang/school/godbless/module1/sprint3/task3/Army.java
- src/main/java/faang/school/godbless/module1/sprint3/task3/ArmyThread.java
- src/main/java/faang/school/godbless/module1/sprint3/task3/Characters.java
- src/main/java/faang/school/godbless/module1/sprint3/task3/Mage.java
- src/main/java/faang/school/godbless/module1/sprint3/task3/Main.java
- src/main/java/faang/school/godbless/module1/sprint3/task3/Swordsman.java
- src/main/java/faang/school/godbless/module1/sprint3/task3/Warrior.java
https://faang-school.atlassian.net/browse/BJS2-10971
> Распределенная армия героев меча и магии

- src/main/java/faang/school/godbless/module1/sprint3/task4/Chore.java
- src/main/java/faang/school/godbless/module1/sprint3/task4/WeasleyFamily.java
https://faang-school.atlassian.net/browse/BJS2-12202
> They were very nice but extremely poor

- src/main/java/faang/school/godbless/BJS2_11033/Archer.java
- src/main/java/faang/school/godbless/BJS2_11033/Army.java
- src/main/java/faang/school/godbless/BJS2_11033/CalculateThread.java
- src/main/java/faang/school/godbless/BJS2_11033/Mage.java
- src/main/java/faang/school/godbless/BJS2_11033/Main.java
- src/main/java/faang/school/godbless/BJS2_11033/Swordsman.java
- src/main/java/faang/school/godbless/BJS2_11033/Warrior.java
BJS2-11033 Распределенная армия героев меча и магии
> BJS2-11033

- src/main/java/faang/school/godbless/BJS2_12211/Chore.java
- src/main/java/faang/school/godbless/BJS2_12211/WeasleyFamily.java
BJS2-12211 They were very nice but extremely poor
> BJS2-12211

- src/main/java/faang/school/godbless/BJS2_12301/BigBangTheory.java
- src/main/java/faang/school/godbless/BJS2_12301/Task.java
BJS2-12301 The Big Bang Theory
> BJS2-12301

- src/main/java/faang/school/godbless/feed_peter_griffin/FoodDeliveryTask.java
- src/main/java/faang/school/godbless/feed_peter_griffin/GriffinsFoodDelivery.java
Вроде все написала верно, а сообщения не выводятся((
Пожалуйста, подскажите, что не так
> Worked with ExecutorService and Thread.sleep()

- src/main/java/faang/school/godbless/griffin/FoodDeliveryTask.java
- src/main/java/faang/school/godbless/griffin/GriffinsFoodDelivery.java
- Added FoodDeliveryTask class implementing Runnable to simulate food delivery for characters.
- Each task waits for a random time (1-5 seconds) to simulate delivery time.
- Each task logs messages when the delivery starts and ends, showing the character and food type.
- Created GriffinsFoodDelivery class with main method to initiate the tasks.
- Utilized ExecutorService with a fixed thread pool of 3 threads to handle concurrent tasks.
- Randomly assigned food amount and type to each character.
- Ensured all threads are properly shut down after execution.
> Implemented Griffins food delivery simulation

- src/main/java/faang/school/godbless/tournament_in_kings_landing/King.java
- src/main/java/faang/school/godbless/tournament_in_kings_landing/Knight.java
- src/main/java/faang/school/godbless/tournament_in_kings_landing/Trial.java
У меня непонятная проблема: вылетает ошибка 
Process 'command 'C:/Users/olgak/.jdks/corretto-17.0.11/bin/java.exe'' finished with non-zero exit value 1.
Она уходит, если убрать метод для добавления испытания в список испытаний
public void addTrial(Trial trial){
trials.add(trial);
}
Первый раз столкнулась с таким...
> Worked with ExecutorService

- src/main/java/faang/school/godbless/Supercow/Boss.java
- src/main/java/faang/school/godbless/Supercow/Main.java
- src/main/java/faang/school/godbless/Supercow/Player.java
Сделал задание с помощью пула потоков, и синхронизировал блок. Только я синхронизировал по специально созданному объекту, а не по коллекции (тот же самый код, но синхроницация блока по коллекции имел неправильный результат, почему-то)
> Kirill bjs2 12542

- src/main/java/faang/school/godbless/recomend_sys/Gender.java
- src/main/java/faang/school/godbless/recomend_sys/Product.java
- src/main/java/faang/school/godbless/recomend_sys/ProductOrder.java
- src/main/java/faang/school/godbless/recomend_sys/RecommendationService.java
- src/main/java/faang/school/godbless/recomend_sys/UserProfile.java
+realized task required functions
> BJS2-10645 - Рекомендательная система

- src/main/java/faang/school/godbless/microsoft_work/MailSender.java
- src/main/java/faang/school/godbless/microsoft_work/SenderRunnable.java
> BJS2-12155 - Вы работаете в Microsoft!

- src/main/java/faang/school/godbless/feed_griffin/FoodDeliveryTask.java
- src/main/java/faang/school/godbless/feed_griffin/GriffinsFoodDelivery.java
> BJS2-12345 - Накормите Питера Гриффина

- src/main/java/faang/school/nice_but_poor/Chore.java
- src/main/java/faang/school/nice_but_poor/WeasleyFamily.java
> BJS2-12450 - They were very nice but extremely poor

- src/main/java/faang/school/godbless/big_bang_teory/BigBangTheory.java
- src/main/java/faang/school/godbless/big_bang_teory/Task.java
> BJS2-12500 The Big Bang Theory

- src/main/java/faang/school/godbless/BJS212189/FoodDeliveryTask.java
- src/main/java/faang/school/godbless/BJS212189/GriffinsFoodDelivery.java
1. создал 3 потока, перебрал персонажей, и каждого создал задачу покушать
> BJS2-12189-"Накормите Питера Гриффина"

- src/main/java/faang/school/godbless/paralelism/the_big_bang_theory/BigBangTheory.java
- src/main/java/faang/school/godbless/paralelism/the_big_bang_theory/Task.java
implementation of sequential execution of tasks using ExecutorService
> BJS2-12110 The Big Bang Theory

- src/main/java/faang/school/godbless/lambda/Droid.java
- src/main/java/faang/school/godbless/lambda/DroidMessageEncryptor.java
- src/main/java/faang/school/godbless/lambda/Main.java
- src/main/java/faang/school/godbless/lambda/MainDroid.java
Создал класс, который содержит методы на шифрование и дешифрование сообщения
> BJS2-9033 Создание шифровальщика

- src/main/java/faang/school/godbless/multithreading/MailSender.java
- src/main/java/faang/school/godbless/multithreading/SenderRunnable.java
- создал, в котором будет создаваться потоки для распараллеливания отправки сообщений
> BJS2-11811

- build.gradle
- src/main/java/faang/school/godbless/BJS210555/Main.java
- src/main/java/faang/school/godbless/BJS210555/StreamMethods.java
- src/test/java/faang/school/godbless/BJS210555/StreamMethodsTest.java
Practice simple methods with Stream API
> Resolve task BJS2-10555

- src/main/java/faang/school/godbless/Task_Working_in_Google/MailSender.java
- src/main/java/faang/school/godbless/Task_Working_in_Google/Main.java
- src/main/java/faang/school/godbless/Task_Working_in_Google/SenderRunnable.java
пришлось добавить exception, без него не работало
> Holymagic1997 bjs2 11880 Вы работаете в Microsoft!

- src/main/java/faang/school/godbless/BJS2_11942/City.java
- src/main/java/faang/school/godbless/BJS2_11942/CityWorker.java
- src/main/java/faang/school/godbless/BJS2_11942/Creature.java
- src/main/java/faang/school/godbless/BJS2_11942/Location.java
- src/main/java/faang/school/godbless/BJS2_11942/Main.java
- src/main/java/faang/school/godbless/BJS2_11942/Monster.java
- src/main/java/faang/school/godbless/BJS2_11942/Witcher.java
> BJS2-11942

- src/main/java/faang/school/godbless/BJS211809/Food.java
- src/main/java/faang/school/godbless/BJS211809/House.java
- src/main/java/faang/school/godbless/BJS211809/Room.java
Implemented all necessary classes using ScheduledExecutorService interface
> Mice are very nice!

- src/main/java/faang/school/godbless/synchronization/google_photo/GooglePhoto.java
- src/main/java/faang/school/godbless/synchronization/google_photo/GooglePhotosAutoUploader.java
implements method uploadPhoto();
implements method onNewPhotoAdded();
implements method startAutoUpload();
> BJS2-12642 Google Photo sync

- src/main/java/faang/school/godbless/parallelism/heroes_might_and_magic/Army.java
- src/main/java/faang/school/godbless/parallelism/heroes_might_and_magic/Main.java
- src/main/java/faang/school/godbless/parallelism/heroes_might_and_magic/PowerThread.java
- src/main/java/faang/school/godbless/parallelism/heroes_might_and_magic/entity/Archer.java
- src/main/java/faang/school/godbless/parallelism/heroes_might_and_magic/entity/Mage.java
- src/main/java/faang/school/godbless/parallelism/heroes_might_and_magic/entity/Swordsman.java
- src/main/java/faang/school/godbless/parallelism/heroes_might_and_magic/entity/Unit.java
Implementation of calculation of unit strength in different threads
> BJS2-11019 Distributed army of heroes of might and magic

- src/main/java/faang/school/godbless/tournament/King.java
- src/main/java/faang/school/godbless/tournament/Knight.java
- src/main/java/faang/school/godbless/tournament/Trial.java
> BJS2-11000 - Турнир в Королевской гавани

- src/main/java/faang/school/godbless/multithreading/mice/Food.java
- src/main/java/faang/school/godbless/multithreading/mice/House.java
- src/main/java/faang/school/godbless/multithreading/mice/Room.java
> тulldeathh-BJS2-11804 : Mice are very nice!

- src/main/java/faang/school/godbless/multithreading/supercow/Boss.java
- src/main/java/faang/school/godbless/multithreading/supercow/Main.java
- src/main/java/faang/school/godbless/multithreading/supercow/Player.java
> nulldeathh-BJS2-12545 : Supercow

- src/main/java/faang/school/godbless/multithreading/spotify/Music.java
- src/main/java/faang/school/godbless/multithreading/spotify/Player.java
> nulldeathh-BJS2-12707 : Блокировка Spotify

- src/main/java/hogwarts/MainHogwarts.java
- src/main/java/hogwarts/SpellAction.java
- src/main/java/hogwarts/SpellCaster.java
у меня вопрос . в условиях задачи : Создайте класс SpellCaster с методом cast, который принимает пример с названием типа заклинания и лямбда-выражения SpellAction . но мы же  указывает не лямбда-выражения SpellAction, а объект интерфейса . А лямбда-выражение указываем уже в main, например (spell) -> "The door is unlocked by ". я ошибаюсь или в условии задачи не корректно написано что указывать в параметре метода ?
> BJS2-9345 hogwarts

- src/main/java/faang/school/godbless/parallelism/tournament/King.java
- src/main/java/faang/school/godbless/parallelism/tournament/Knight.java
- src/main/java/faang/school/godbless/parallelism/tournament/Trial.java
implementation tasks using ExecutorService;
refactoring method startTrials;
> BJS2-10931 Tournament in King's Landing 

- src/main/java/faang/school/godbless/distributed_army/Archer.java
- src/main/java/faang/school/godbless/distributed_army/Army.java
- src/main/java/faang/school/godbless/distributed_army/Character.java
- src/main/java/faang/school/godbless/distributed_army/Mage.java
- src/main/java/faang/school/godbless/distributed_army/Swordsman.java
- src/test/java/faang/school/godbless/distributed_army/ArmyTest.java
> BJS2-11111 - Распределенная армия героев меча и магии

- src/main/java/faang/school/godbless/spacex/RocketLaunch.java
- src/main/java/faang/school/godbless/spacex/RocketLauncher.java
- src/main/java/faang/school/godbless/spacex/SpaceX.java
> BJS2-11100 - Космическая программа SpaceX

- src/main/java/faang/school/godbless/lambda/Character.java
- src/main/java/faang/school/godbless/lambda/InventoryManager.java
- src/main/java/faang/school/godbless/lambda/Item.java
- src/main/java/faang/school/godbless/lambda/Main.java
- src/main/java/faang/school/godbless/lambda/MainInventory.java
- создан класс персонажа и вещей для инвентаря
- добавлены методы для работы с инвентарем
> BJS2-9111 Создание системы для управления инвентарем персонажей

- src/main/java/faang/school/godbless/multithreading/tournament/King.java
- src/main/java/faang/school/godbless/multithreading/tournament/Knight.java
- src/main/java/faang/school/godbless/multithreading/tournament/Trial.java
- создал классы, в которых рыцарям назначаются испытания и с помощью ExecutorService возможно распараллелить выполнение этих испытаний
> BJS2-10896

- src/main/java/faang/school/godbless/lambdaEx/Main.java
- src/main/java/faang/school/godbless/lambdaEx/Notification.java
- src/main/java/faang/school/godbless/lambdaEx/NotificationManager.java
Реализована система, которая позволяет пользователям выбирать различные типы оповещений, но основе их типов
> Создание системы оповещения в зависимости от типа системы

- src/main/java/faang/school/godbless/stream/DataAnalyzer.java
- src/main/java/faang/school/godbless/stream/Job.java
- src/main/java/faang/school/godbless/stream/JobScraper.java
- src/main/java/faang/school/godbless/stream/JobStreamProcessor.java
- src/main/java/faang/school/godbless/stream/Main.java
- написал методы для сбора и анализа данных о вакансиях , чтобы выявить наиболее востребованные навыки, опыт работы
> BJS2-10810

- src/main/java/faang/school/godbless/BJS212002/MailSender.java
- src/main/java/faang/school/godbless/BJS212002/SenderRunnable.java
Implement 5 Threads with sending messages
> Resolving task BJS2-12002

- src/main/java/faang/school/godbless/Feed_Griffin/FoodDeliveryTask.java
- src/main/java/faang/school/godbless/Feed_Griffin/GriffinsFoodDelivery.java
> Holymagic1997 bjs2 12139 Накормите Питера Гриффина

- src/main/java/faang/school/godbless/BJS2_10219/ActionType.java
- src/main/java/faang/school/godbless/BJS2_10219/Main.java
- src/main/java/faang/school/godbless/BJS2_10219/UserAction.java
BJS2-10219 Анализ активности пользователей в социальной сети
> BJS2-10219

- src/main/java/faang/school/godbless/streamAPI_2/Employee.java
- src/main/java/faang/school/godbless/streamAPI_2/Main.java
Потренируем StreamAPI 2 - не смог выполнить 4-е задание.
> Garikgarikas bjs2 10723

- src/main/java/faang/school/godbless/BJS210900/Employee.java
- src/main/java/faang/school/godbless/BJS210900/Main.java
- src/main/java/faang/school/godbless/BJS210900/StreamMethods.java
- src/test/java/faang/school/godbless/BJS210900/StreamMethodsTest.java
Implement methods using Stream API
> Maksim don bjs2 10900

- src/main/java/faang/school/godbless/electronic_diary/Diary.java
- src/main/java/faang/school/godbless/electronic_diary/Main.java
- src/main/java/faang/school/godbless/electronic_diary/Student.java
Реализовал запрашиваемые функции
> BJS2 - 10800 - Электронный дневник

- build.gradle
- src/main/java/faang/school/godbless/BJS2_10757/DataAnalyzer.java
- src/main/java/faang/school/godbless/BJS2_10757/Job.java
- src/main/java/faang/school/godbless/BJS2_10757/JobNames.java
- src/main/java/faang/school/godbless/BJS2_10757/JobScrapper.java
- src/main/java/faang/school/godbless/BJS2_10757/JobStreamProcessor.java
- src/main/java/faang/school/godbless/BJS2_10757/JobsInJson.json
- src/main/java/faang/school/godbless/BJS2_10757/Locations.java
- src/main/java/faang/school/godbless/BJS2_10757/Main.java
- src/main/java/faang/school/godbless/BJS2_10757/Skills.java
BJS2-10757 Анализатор вакансий
> BJS2-10757

- src/main/java/faang/school/godbless/microsoft/MailSender.java
- src/main/java/faang/school/godbless/microsoft/SenderRunnable.java
Create class SenderRunnable
implemented task processing in five threads
> BJS2-11923 You work at microsoft

- src/main/java/faang/school/godbless/synchronization/googlePhoto/GooglePhotosAutoUploader.java
- src/main/java/faang/school/godbless/synchronization/googlePhoto/Main.java
- реализовал программу для автоматической загрузки фото путем создания потоков с использованием wait()/notify()
> BJS2-12630

- src/main/java/faang/school/godbless/synchronization/spotify/Music.java
- src/main/java/faang/school/godbless/synchronization/spotify/Player.java
- в классе Player в каждый метод добавлен блок synchronized для исключения неверных результатов при работе нескольких потоков
> BJS2-12695

- src/main/java/faang/school/godbless/multithreading/witcher/City.java
- src/main/java/faang/school/godbless/multithreading/witcher/CityWorker.java
- src/main/java/faang/school/godbless/multithreading/witcher/Location.java
- src/main/java/faang/school/godbless/multithreading/witcher/Monster.java
- src/main/java/faang/school/godbless/multithreading/witcher/Witcher.java
- реализовал задачу, в которой возможно распараллелить выполнение убийств монстров, находящихся вокруг городов. Монстры и города даны
- добавлена возможность изменять количество потоков для анализа времени выполнения программы
> BJS2-11951

- src/main/java/faang/school/godbless/multithreading/BigBangTheory.java
- src/main/java/faang/school/godbless/multithreading/Task.java
- реализовал класс, который создает пул из четырех потоков с помощью класса ExecutorService и распределяет выполнение задач между ними
> BJS2-12378

- src/main/java/faang/school/godbless/synchronozation/supercow/Boss.java
- src/main/java/faang/school/godbless/synchronozation/supercow/Main.java
- src/main/java/faang/school/godbless/synchronozation/supercow/Player.java
- реализовал игру, в которой игроки в многопоточной среде смогут присоединяться к сражению с боссом. Максимальное количество участников ограничено, ожидание и продолжение выполнения потоков организовано с помощью wait()/notify()
> BJS2-12540

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/King.java
- src/main/java/faang/school/godbless/Knight.java
- src/main/java/faang/school/godbless/Trial.java
Created and implemented classes King, Knight and Trial.
Implemented startTrial method in class King.
> BJS2-10912: Турнир в Королевской гавани

- src/main/java/faang/school/godbless/help_collegue/Main.java
- src/main/java/faang/school/godbless/help_collegue/Person.java
- src/main/java/faang/school/godbless/help_collegue/PersonNamePrinter.java
> BJS2-11900 - Помогите коллеге

- src/main/java/faang/school/godbless/normal_game/Main.java
- src/main/java/faang/school/godbless/normal_game/Pig1Thread.java
- src/main/java/faang/school/godbless/normal_game/Pig2Thread.java
- src/main/java/faang/school/godbless/normal_game/Pig3Thread.java
- src/main/java/faang/school/godbless/normal_game/PigThread.java
По задаче, думаю реализовывать отдельные классы для первого, второго и третьего поросят излишне.
Я бы лучше сделал instance variable material name в PigThread, и там реализовал бы все. Но все же решил сделать согласно задаче
> BJS2-12200 - Наконец-то нормальная игра

- src/main/java/faang/school/godbless/BJS212277/Chore.java
- src/main/java/faang/school/godbless/BJS212277/WeasleyFamily.java
1. попробовал динамически создавать потоки в зависимости от количества задач
> BJS2-12277 - "They were very nice but extremely poor"

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/BigBangTheory.java
- src/main/java/faang/school/godbless/Task.java
Created and implemented classes Task and BigBangTheory.
Used ExecutorService and its awaitTermination method.
> The Big Bang Theory - created and implemented classes Task and BigBangTheory

- src/main/java/faang/school/godbless/BJS212435/BigBangTheory.java
- src/main/java/faang/school/godbless/BJS212435/Task.java
Implement simple method with Threads
> Resolve task BJS2-12435

- src/main/java/faang/school/godbless/BJS211122/Archer.java
- src/main/java/faang/school/godbless/BJS211122/Army.java
- src/main/java/faang/school/godbless/BJS211122/Creature.java
- src/main/java/faang/school/godbless/BJS211122/Mage.java
- src/main/java/faang/school/godbless/BJS211122/Swordsman.java
- src/test/java/faang/school/godbless/BJS211122/ArmyTest.java
Implement simple method with Threads
> Resolve task BJS2-11122

- src/main/java/faang/school/godbless/BJS2_10889/King.java
- src/main/java/faang/school/godbless/BJS2_10889/Knight.java
- src/main/java/faang/school/godbless/BJS2_10889/Trial.java
BJS2-10889 Турнир в Королевской гавани
> BJS2-10889

- src/main/java/faang/school/godbless/module1/sprint3/task9/GooglePhotosAutoUploader.java
- src/main/java/faang/school/godbless/module1/sprint3/task9/Main.java
https://faang-school.atlassian.net/browse/BJS2-12653
> Google Photo sync

- src/main/java/faang/school/godbless/module1/sprint3/task11/Fighter.java
- src/main/java/faang/school/godbless/module1/sprint3/task11/Game.java
- src/main/java/faang/school/godbless/module1/sprint3/task11/Main.java
https://faang-school.atlassian.net/browse/BJS2-13093
> Bro Force!

- src/main/java/faang/school/godbless/BJS2_12557/Boss.java
- src/main/java/faang/school/godbless/BJS2_12557/Main.java
- src/main/java/faang/school/godbless/BJS2_12557/Player.java
> BJS2-12557

- src/main/java/faang/school/godbless/BJS2_12652/GooglePhotoAutoUploader.java
> BJS2-12652

- src/main/java/faang/school/godbless/BJS2_11785/Room.java
- src/main/java/faang/school/godbless/BJS2_12732/Music.java
- src/main/java/faang/school/godbless/BJS2_12732/Player.java
> BJS2-12732

- src/main/java/faang/school/godbless/BJS2_12779/House.java
- src/main/java/faang/school/godbless/BJS2_12779/Main.java
- src/main/java/faang/school/godbless/BJS2_12779/User.java
BJS2-12779 Железный трон любой ценой
> BJS2-12779

- src/main/java/faang/school/godbless/BJS2_12825/Main.java
- src/main/java/faang/school/godbless/BJS2_12825/VideoManager.java
BJS2-12825 Счетчик просмотров на YouTube
> BJS2-12825

- src/main/java/faang/school/godbless/BJS2_11785/Food.java
- src/main/java/faang/school/godbless/BJS2_11785/House.java
- src/main/java/faang/school/godbless/BJS2_11785/Room.java
BJS2-11785 Mice are very nice!
> BJS2-11785

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/BJS212723/Player.java
1.  синхронезировал управление плеером, используя монитор
> BJS2-12723 - "Блокировка Spotify"

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/Chore.java
- src/main/java/faang/school/godbless/WeasleyFamily.java
Created and implemented classes Chore and WeasleyFamily.
Created object of class ExecutorService using Executors.newCachedThreadPool() method.
> They were very nice but extremely poor - created and implemented classes Chore and WeasleyFamily

- src/main/java/faang/school/godbless/synchronization/youtube/Main.java
- src/main/java/faang/school/godbless/synchronization/youtube/Video.java
- src/main/java/faang/school/godbless/synchronization/youtube/VideoManager.java
- реализована задача по синхронному подсчету количества просмотров и вывода результата
> BJS2-12821

- src/main/java/faang/school/godbless/spotify/Music.java
- src/main/java/faang/school/godbless/spotify/Player.java
> BJS2-12750 - Блокировка Spotify

- src/main/java/faang/school/godbless/sychronithation/spotify/Music.java
- src/main/java/faang/school/godbless/sychronithation/spotify/Player.java
implementation of threads working with synchronized objects
> BJS2-12700 Spotify blocking

- src/main/java/faang/school/godbless/TheBigBangTheory/BigBangTheory.java
- src/main/java/faang/school/godbless/TheBigBangTheory/Task.java
Создание класса Task и BBT. Создание ExecutorService для распределения задач
> BJS2-12415-The Big Bang Theory

- src/main/java/faang/school/godbless/google_photo/GooglePhotosAutoUploader.java
- src/main/java/faang/school/godbless/google_photo/Main.java
+ Realized class GooglePhotosAutoUploader
> BJS2-12650 - Google Photo sync

- src/main/java/faang/school/godbless/BJS212777/Music.java
- src/main/java/faang/school/godbless/BJS212777/Player.java
Implemented thread methods wait and notify
> Resolved task BJS2-12777

- src/main/java/faang/school/godbless/fanoutfanin/Main.java
- src/main/java/faang/school/godbless/fanoutfanin/ResultConsumer.java
- src/main/java/faang/school/godbless/fanoutfanin/SquareRequest.java
- src/main/java/faang/school/godbless/fanoutfanin/SquareRequestManager.java
> Fan out fan in

- src/main/java/faang/school/godbless/Application.java
- src/main/java/faang/school/godbless/data/manager/NotificationManagerImpl.java
- src/main/java/faang/school/godbless/domain/manager/NotificationManager.java
- src/main/java/faang/school/godbless/domain/model/Notification.java
"оздайте метод synchronized addNotification(Notification), который добавляет уведомление в список. Подумайте, почему он должен быть synchronized? Какая у нас мотивация его делать таковым?"
Ответ:
В обычных коллекциях, как ArrayList, операции добавления не являются атомарными (они состоят из нескольких шагов: проверка размера, выделение памяти, добавление элемента). Если не используется синхронизация, возможны непредсказуемые результаты при конкурентном доступе.
> BJS2-14049 Completed

- src/main/java/faang/school/godbless/walmart_queue/CashierThread.java
- src/main/java/faang/school/godbless/walmart_queue/Item.java
- src/main/java/faang/school/godbless/walmart_queue/Main.java
- src/main/java/faang/school/godbless/walmart_queue/PaymentTaker.java
> BJS2-11755 Очередь в Walmart

- src/main/java/faang/school/godbless/youtube_views/Main.java
- src/main/java/faang/school/godbless/youtube_views/VideoManager.java
> BJS2-13050 - Счетчик просмотров на YouTube

- src/main/java/faang/school/godbless/iron_throne/House.java
- src/main/java/faang/school/godbless/iron_throne/Main.java
- src/main/java/faang/school/godbless/iron_throne/Role.java
- src/main/java/faang/school/godbless/iron_throne/User.java
> BJS2-12850 - Железный трон любой ценой

- src/main/java/faang/school/godbless/tamagotchi_vlad/Main.java
- src/main/java/faang/school/godbless/tamagotchi_vlad/TamagotchiVlad.java
- src/main/java/faang/school/godbless/tamagotchi_vlad/VladController.java
implemented functions required in task
> BJS2-13300 Тамагочи Влад

- src/main/java/faang/school/godbless/bro_force/Game.java
- src/main/java/faang/school/godbless/bro_force/Main.java
- src/main/java/faang/school/godbless/bro_force/Player.java
- src/main/java/faang/school/godbless/bro_force/UpdateResult.java
> BJS2-13100 - Bro Force!

- src/main/java/faang/school/godbless/MailSender.java
- src/main/java/faang/school/godbless/SenderRunnable.java
Вопрос:
Thread thread = null;
for (int i = 0; i < 5; i++) {
int startIndex = i * 200 + 1;
int endIndex = (i + 1) * 200;
SenderRunnable sender = new SenderRunnable(startIndex, endIndex);
thread = new Thread(sender);
thread.start();
}
тут мы получается создаем переменную потока, потом в цикле инициализируем её, запускаем поток, а потом ею можем снова пользоваться?
> Light bjs2 11908

- src/main/java/faang/school/godbless/module1/sprint3/task12/Main.java
- src/main/java/faang/school/godbless/module1/sprint3/task12/Message.java
- src/main/java/faang/school/godbless/module1/sprint3/task12/TelegramBot.java
https://faang-school.atlassian.net/browse/BJS2-13202
> TelegramBot

- src/main/java/faang/school/godbless/BJS212222/City.java
- src/main/java/faang/school/godbless/BJS212222/CityWorker.java
- src/main/java/faang/school/godbless/BJS212222/Location.java
- src/main/java/faang/school/godbless/BJS212222/Monster.java
- src/main/java/faang/school/godbless/BJS212222/Witcher.java
- src/test/java/faang/school/godbless/BJS212222/CityWorkerTest.java
Implements monsters map and practices using multithreading
> Maksim don bjs2 12222

- src/main/java/faang/school/godbless/BJS212424/FoodDeliveryTask.java
- src/main/java/faang/school/godbless/BJS212424/GriffinsFoodDelivery.java
Implement ThreadPool with 3 Threads
> Resolving task BJS2-12424

- src/main/java/faang/school/godbless/module1/sprint4/task2/Battle.java
- src/main/java/faang/school/godbless/module1/sprint4/task2/Main.java
- src/main/java/faang/school/godbless/module1/sprint4/task2/Robot.java
https://faang-school.atlassian.net/browse/BJS2-14125
> Star Wars Arena

- src/main/java/faang/school/godbless/BJS2_13381/MasterCardService.java
BJS2-13381 Асинхронность и Future
> BJS2-13381

- src/main/java/faang/school/godbless/BJS2_13469/Pi.java
- src/main/java/faang/school/godbless/BJS2_13469/Point.java
> BJS2-13469

- src/main/java/faang/school/godbless/BJS2_13089/Game.java
- src/main/java/faang/school/godbless/BJS2_13089/Main.java
- src/main/java/faang/school/godbless/BJS2_13089/Player.java
- src/main/java/faang/school/godbless/BJS2_13089/Randomizer.java
> BJS2-13089

- src/main/java/faang/school/godbless/BJS2_13571/Main.java
- src/main/java/faang/school/godbless/BJS2_13571/ResultConsumer.java
- src/main/java/faang/school/godbless/BJS2_13571/SquareRequest.java
> BJS2-13571

- src/main/java/faang/school/godbless/BJS2_13753/Main.java
- src/main/java/faang/school/godbless/BJS2_13753/Order.java
- src/main/java/faang/school/godbless/BJS2_13753/OrderProcessor.java
BJS2-13753 Собираем заказы в Amazon
> BJS2-13753

- src/main/java/faang/school/godbless/BJS2_13861/Player.java
- src/main/java/faang/school/godbless/BJS2_13861/Quest.java
- src/main/java/faang/school/godbless/BJS2_13861/QuestSystem.java
> BJS2-13861

- src/main/java/faang/school/godbless/BJS2_14161/Main.java
- src/main/java/faang/school/godbless/BJS2_14161/TwitterAccount.java
- src/main/java/faang/school/godbless/BJS2_14161/TwitterSubscriptionSystem.java
BJS2-14161 Становимся celebrity в Twitter
> BJS2-14161

- src/main/java/faang/school/godbless/BJS2_14384/School.java
- src/main/java/faang/school/godbless/BJS2_14384/Student.java
- src/main/java/faang/school/godbless/BJS2_14384/Task.java
- src/main/java/faang/school/godbless/BJS2_14384/Tournament.java
BJS2-14384 Турнир трех волшебников
> BJS2-14384

- src/main/java/faang/school/godbless/BJS2_12881/Chat.java
- src/main/java/faang/school/godbless/BJS2_12881/ChatList.java
- src/main/java/faang/school/godbless/BJS2_12881/ChatManager.java
- src/main/java/faang/school/godbless/BJS2_12881/Main.java
- src/main/java/faang/school/godbless/BJS2_12881/Rand.java
- src/main/java/faang/school/godbless/BJS2_12881/User.java
- src/main/java/faang/school/godbless/BJS2_12881/UserList.java
BJS2-12881 Matters of the heart
> BJS2-12881

- src/main/java/faang/school/godbless/asynchrony_concurrency/future/Main.java
- src/main/java/faang/school/godbless/asynchrony_concurrency/future/MasterCardService.java
> nulldeathh-BJS2-13380 : Асинхронность и Future

- src/main/java/faang/school/godbless/multithreading/matters_of_the_heart/Chat.java
- src/main/java/faang/school/godbless/multithreading/matters_of_the_heart/ChatManager.java
- src/main/java/faang/school/godbless/multithreading/matters_of_the_heart/Main.java
- src/main/java/faang/school/godbless/multithreading/matters_of_the_heart/User.java
- src/main/java/faang/school/godbless/multithreading/matters_of_the_heart/UserList.java
Код не до конца работает как надо, проблема в том, что у меня все потоки выполняются по очереди и chating происходит только с одним пользователем. Я понимаю в чем проблема, мне нужно как-то отдельно синхронизировать поиск первого онлайн пользователя и вызов chat.communication(). Но я не могу понять как это сделать, чтобы у меня блокались потоки когда я нахожу activeUsers и помечаю у него поля общения на false и разблокались когда я вызываю метод чата.
> nulldeathh-BJS2-12891 : Matters of the heart

- src/main/java/faang/school/godbless/telegram_bot/Main.java
- src/main/java/faang/school/godbless/telegram_bot/TelegramBot.java
+ implemented required functions
Паша, проверь пожалуйста правильно ли я сделал задание. Просто возникает ощущение, что я не до конца понял суть задачи
> BJS2-13250 - Telegram-бот

- src/main/java/faang/school/godbless/google_docks/App.java
- src/main/java/faang/school/godbless/google_docks/CollaborativeDocument.java
- src/main/java/faang/school/godbless/google_docks/DocumentSection.java
- src/main/java/faang/school/godbless/google_docks/DocumentSectionProcessor.java
+ сделал задачу согласно условию
> BJS2 - 15450

- src/main/java/faang/school/godbless/tournament_of_three/MagicalTournament.java
- src/main/java/faang/school/godbless/tournament_of_three/School.java
- src/main/java/faang/school/godbless/tournament_of_three/Student.java
- src/main/java/faang/school/godbless/tournament_of_three/Task.java
- src/main/java/faang/school/godbless/tournament_of_three/Tournament.java
Паша, можешь дать свое мнение по этому вопросу?
Одно из условий задачи: Создайте класс Tournament с методом startTask, который принимает объекты School и Task, и возвращает CompletableFuture < School > 
Это я реализую в классе Tournament.java с 14 по 36 строки, но нельзя ли просто написать...
```
public CompletableFuture<Void> startTask(School school, Task task) {
return CompletableFuture.runAsync(() -> {
...
studentList.forEach(student -> student.setPoints(student.getPoints() + rewardPoints));
...
});
} 
```
?
> BJS2-14500 - Турнир трех волшебников

- src/main/java/faang/school/godbless/pumping_alchemy/Main.java
- src/main/java/faang/school/godbless/pumping_alchemy/Potion.java
+ реализовал задачу по условию
> BJS2-14450 - Качаем алхимию

- src/main/java/faang/school/godbless/celebrity_twitter/Main.java
- src/main/java/faang/school/godbless/celebrity_twitter/TwitterAccount.java
- src/main/java/faang/school/godbless/celebrity_twitter/TwitterSubscriptionSystem.java
+ Реализовал задачу согласно условию
> BJS2-14155 Становимся celebrity в Twitter

- src/main/java/faang/school/godbless/BJS214119/ApplicationRunner.java
- src/main/java/faang/school/godbless/BJS214119/Battle.java
- src/main/java/faang/school/godbless/BJS214119/Robot.java
1. роботы не ждут друг друга, каждая пара сражается асинхронно на своей арене. Как только бой заканчивается, получаем результат сражения и объявляем победителя(объявляем любого победителя, не ждем всех)
> BJS2-14119 - "Star Wars Arena"

- src/main/java/faang/school/godbless/async_future/Main.java
- src/main/java/faang/school/godbless/async_future/MasterCardService.java
- src/main/java/faang/school/godbless/async_future/Stripe.java
+ implemented required functions
> BJS2-13400 - Асинхронность и Future

- src/main/java/faang/school/godbless/BJS213371/MasterCardService.java
1. осуществил платеж и паралельно собрал и отправил аналитику
> BJS2-13371 - "Асинхронность и Future"

- src/main/java/faang/school/godbless/BJS213572/Main.java
- src/main/java/faang/school/godbless/BJS213572/ResultConsumer.java
- src/main/java/faang/school/godbless/BJS213572/SquareRequest.java
Implemented methods: launch, fanOutFanIn
> Fan out – Fan In

- src/main/java/faang/school/godbless/fanout_fanin/Calculator.java
- src/main/java/faang/school/godbless/fanout_fanin/Main.java
- src/main/java/faang/school/godbless/fanout_fanin/ResultConsumer.java
- src/main/java/faang/school/godbless/fanout_fanin/SquareRequest.java
+ реализовал метод, который высчитывает сумму квадратов числа асинхронно, а затем собирает все в одно
> BJS2-13600 - Fan out - Fan In

- src/main/java/faang/school/godbless/collect_orders_amazon/Main.java
- src/main/java/faang/school/godbless/collect_orders_amazon/Order.java
- src/main/java/faang/school/godbless/collect_orders_amazon/OrderProcessor.java
+ реализовал задачу по условию
> BJS2-13800 - Собираем заказы в Amazon

- src/main/java/faang/school/godbless/wow/Main.java
- src/main/java/faang/school/godbless/wow/Player.java
- src/main/java/faang/school/godbless/wow/Quest.java
- src/main/java/faang/school/godbless/wow/QuestSystem.java
+ implemented required classes and methods
> BJS2-13850 - WOW

- src/main/java/faang/school/godbless/send_crow/Kingdom.java
- src/main/java/faang/school/godbless/send_crow/Main.java
+ имплементировал запрошенную функциональность
> BJS2-13950 - Пошлите ворона!

- src/main/java/faang/school/godbless/BJS212666/GooglePhotosAutoUploader.java
- src/main/java/faang/school/godbless/BJS212666/Main.java
Implemented simple method using 2 Threads to add and upload Photos with wait and notify
> Resolved task BJS2-12666

- src/main/java/faang/school/godbless/Task_FanOut_FanIn/Main.java
- src/main/java/faang/school/godbless/Task_FanOut_FanIn/ResultConsumer.java
- src/main/java/faang/school/godbless/Task_FanOut_FanIn/SquareRequest.java
не понял пока, как завершить через CompletableFuture.AllOf(). Я запускаю потоки в цикле, но как их потом остановить? Пришлось использовать AwaitTermination...
> Holymagic1997 bjs2 13583

- src/main/java/faang/school/godbless/BJS213434/Main.java
- src/main/java/faang/school/godbless/BJS213434/MasterCardService.java
Implemented simple method using Future and CompletableFuture
> Resolved task BJS2-13434

- src/main/java/faang/school/godbless/synchronization/throne/House.java
- src/main/java/faang/school/godbless/synchronization/throne/Main.java
- src/main/java/faang/school/godbless/synchronization/throne/Role.java
- src/main/java/faang/school/godbless/synchronization/throne/User.java
- реализована задача по синхронному подключению к дому в зависимости от роли пользователя и контроль наличия свободных ролей
> BJS2-12778

- src/main/java/faang/school/godbless/work_stands/DesignDepartment.java
- src/main/java/faang/school/godbless/work_stands/DesignResources.java
- src/main/java/faang/school/godbless/work_stands/Main.java
- src/main/java/faang/school/godbless/work_stands/MarketingDepartment.java
- src/main/java/faang/school/godbless/work_stands/MarketingResources.java
Сделал по задаче:
1 комит - первое задание: сделать DeadLock
2 комит - второе задание: разрешить DeadLock
> BJS2 - 15250 Работа стоит

- src/main/java/faang/school/godbless/delivery_coupons/DeliveryService.java
- src/main/java/faang/school/godbless/delivery_coupons/Main.java
- src/main/java/faang/school/godbless/delivery_coupons/Order.java
- src/main/java/faang/school/godbless/delivery_coupons/Product.java
- src/main/java/faang/school/godbless/delivery_coupons/PromoCode.java
+ имплементироавл согласно условию задачи
> BJS2-14850 - Купоны на доставку

- src/main/java/faang/school/godbless/carry_overate/Inventory.java
- src/main/java/faang/school/godbless/carry_overate/Item.java
- src/main/java/faang/school/godbless/carry_overate/Main.java
> BJS2-14350 Carry отожрался

- src/main/java/faang/school/godbless/future/pi/Main.java
- src/main/java/faang/school/godbless/future/pi/Point.java
- src/main/java/faang/school/godbless/future/pi/PointCounter.java
- src/main/java/faang/school/godbless/future/pi/PointGenerator.java
- реализовал метод, который путем создания точек с рандомными координатами и заданным радиусом высчитывает значение числа Pi
> BJS2-13482

- src/main/java/faang/school/godbless/play_bank/Account.java
- src/main/java/faang/school/godbless/play_bank/Bank.java
- src/main/java/faang/school/godbless/play_bank/Main.java
+ имплементировал функциональность согласно условию
> BJS2-14900 - Поиграем в банк

- src/main/java/faang/school/godbless/mini_zoom/Conference.java
- src/main/java/faang/school/godbless/mini_zoom/Main.java
- src/main/java/faang/school/godbless/mini_zoom/Participant.java
+ Сделал так, чтобы streaming не начинался, пока не присоединятся все участники.
+ Использовал CyclicBarrier
> BJS2 - 14650 Мини Zoom

- src/main/java/faang/school/godbless/starwars_arena/Battle.java
- src/main/java/faang/school/godbless/starwars_arena/Main.java
- src/main/java/faang/school/godbless/starwars_arena/Robot.java
+ Created Robot class: play role of fighters
+ Created Battle class: compares two robots and returns winner
+ Created Main class: tested functionality
> BJS2-14250 - Star Wars Arena

- src/main/java/faang/school/godbless/facebook_notifications/Main.java
- src/main/java/faang/school/godbless/facebook_notifications/Notification.java
- src/main/java/faang/school/godbless/facebook_notifications/NotificationManager.java
+ имплементировал запрошенную функциональность
> BJS2-14150 - Рассылаем уведомления в Facebook

- src/main/java/faang/school/godbless/tracking_system/Location.java
- src/main/java/faang/school/godbless/tracking_system/Main.java
- src/main/java/faang/school/godbless/tracking_system/TransportManagementSystem.java
- src/main/java/faang/school/godbless/tracking_system/Vehicle.java
- src/main/java/faang/school/godbless/tracking_system/VehicleStatus.java
- src/main/java/faang/school/godbless/tracking_system/VehicleTracker.java
+ Имплементировал функциональность согласно заданию
> BJS2-15115 - Система трекинга

- src/main/java/faang/school/godbless/leaving_comments/Comment.java
- src/main/java/faang/school/godbless/leaving_comments/Main.java
- src/main/java/faang/school/godbless/leaving_comments/Post.java
- src/main/java/faang/school/godbless/leaving_comments/PostService.java
+ имплементировал согласно условию задачи
> BJS2-15050 - Оставляем комментарий

- src/main/java/faang/school/godbless/factorial/Factorial.java
- src/main/java/faang/school/godbless/factorial/Main.java
+ имплементировал по условию задачи
> BJS2-13500 - Великий и ужасный факториал!

- src/main/java/faang/school/godbless/BJS29000/Droid.java
- src/main/java/faang/school/godbless/BJS29000/DroidMessageEncryptor.java
- src/main/java/faang/school/godbless/BJS29000/Main.java
> Resolve task BJS2-9000

- src/main/java/faang/school/godbless/BJS213131/Game.java
- src/main/java/faang/school/godbless/BJS213131/Gamer.java
- src/main/java/faang/school/godbless/BJS213131/Main.java
Implemented game Bro Force. All works and refactored
> Resolved task BJS2-13131

- src/main/java/faang/school/godbless/sendraven3256/Kingdom.java
- src/main/java/faang/school/godbless/sendraven3256/Main.java
BJS2-3256 - Черновик
Не понимаю как с этим работать((( честно пробовал разобраться
1. С вероятностью 20% выбрасываю исключение в методе sendRaven().
2. Вызываю метод sendRaven в main'е. Сразу же вызываю метод .handle(), в котором обрабатываю исключение.
3. Если исключение есть (exception != null) - возвращаю сообщение, хранящееся внутри исключения ("Raven was killed");
4. Когда вероятность срабатывает и исключение выбрасывается - программа крашится из-за RunTimeException...
Пробовал заменить RunTime на какое-нибудь checked исключение - не компилируется и заставляет меня дополнительно оборачивать всё в try/catch.
В чём тогда смысл обработки через handle, если программа всё равно крашится?
> BJS2-3256 - Пошлите ворона

- src/main/java/faang/school/godbless/vedmak_and_monsters/City.java
- src/main/java/faang/school/godbless/vedmak_and_monsters/CityWorker.java
- src/main/java/faang/school/godbless/vedmak_and_monsters/Monster.java
- src/main/java/faang/school/godbless/vedmak_and_monsters/TimeUtils.java
- src/main/java/faang/school/godbless/vedmak_and_monsters/Witcher.java
Привет.
Запушил то, что успел сделать. 
Акцент сделал на подсчете общего времени, затраченного на выполнение и времени, 
затраченного на выполнении в потоках.
Логику расчета пока не понимаю, как реализовать.
Понимаю, что с ToDo тоже пушить в ПР нельзя.
> BJS2-6174 Путь пальцем проложи

- src/main/java/faang/school/godbless/async_services/Main.java
- src/main/java/faang/school/godbless/async_services/MasterCardService.java
Пушу что успел сделать.
Завис и не понимаю как сделать: 
- Сначала ожидает завершения sendAnalytics и выводит результат. Кто ожидает? Поток, который и запустил задачу, т.е. основной поток, в котором и выполняется метод doAll, но никаких ожиданий через Thread.sleep! Нужно “присоединиться” к тому потоку, завершения которого ждём. Какой метод может помочь?
- 
- Потом дожидается collectPayment и выводит результат.
> BJS2-6081 Асинхронность и Future

- src/main/java/faang/school/godbless/multithreading_synchronization/BJS2_6503/Main.java
- src/main/java/faang/school/godbless/multithreading_synchronization/BJS2_6503/Player.java
https://faang-school.atlassian.net/browse/BJS2-6503
> BJS2-6503: Блокировка Spotify

- src/main/java/faang/school/godbless/delivery/DeliveryService.java
- src/main/java/faang/school/godbless/delivery/Main.java
- src/main/java/faang/school/godbless/delivery/Order.java
- src/main/java/faang/school/godbless/delivery/Product.java
- src/main/java/faang/school/godbless/delivery/PromoCode.java
Как я понимаю, смысл всей задачи реализовать метод processOrder без synchronized. Мне пока не удалось это сделать, пытался поискать решения у коллег, но и у них не получилось это сделать на данный момент. Буду думать дальше, как это можно исправить.
>  BJS2-6215-makakcuk-Купоны на доставку

- src/main/java/delivery_coupons/DeliveryService.java
- src/main/java/delivery_coupons/Main.java
- src/main/java/delivery_coupons/Order.java
- src/main/java/delivery_coupons/Product.java
- src/main/java/delivery_coupons/PromoCode.java
processOrder сделал synchronized, но это не оптимально, понимаю, до другого решения пока не додумался, надеюсь на выходных исправлю
> BJS2-6168 : Купоны на доставку
