src/main/java/faang/school/godbless/data_collection/DataCollector.java
src/main/java/faang/school/godbless/data_collection/Main.java
src/main/java/faang/school/godbless/data_collection/ReportGenerator.java
src/main/java/faang/school/godbless/data_collection/Sales.java
src/main/java/faang/school/godbless/data_collection/SalesData.java

+ Created Sales class: repersents sales(does not have any logic)
+ Created SalesDate class: collects Sales by id
+ Created DataCollector class: adds Sales to SalesDate
+ Created ReportGenerator class: get SalesData list and shows all Sales
+ Created Main class: tested functionality
+ Used CountDownLatch to wait untill all thread will be executed

BJS2 - 14905 Сбор данных для отчета

---

src/main/java/faang/school/godbless/substations/Main.java
src/main/java/faang/school/godbless/substations/MonitoringSystem.java
src/main/java/faang/school/godbless/substations/Sensor.java
src/main/java/faang/school/godbless/substations/SensorData.java
src/main/java/faang/school/godbless/substations/Substation.java

Implemented:
+ Sensor class - generates data and sends to Substation every 1 second
+ Substation class - contains data generated by Sensor and sends to Monitoring service every 60 seconds
+ MonitoringSystem class - contains average data sent by all Substations
+ SensorData class - represents data, collected by Substations
+ Main class - tested functionality

BJS2 - 15400 - Мониторинг электроподстанций

---

src/main/java/faang/school/godbless/App.java

Создано слияние двух веток для корректировки времени открытия магазина.

pespa_bjs2-17643

---

src/main/java/faang/school/godbless/basic/users/collect/App.java
src/main/java/faang/school/godbless/basic/users/collect/User.java

Class User and App (main) were created. App is main file and has to be executed to see result.

User collection

---

src/main/java/faang/school/godbless/Application.java
src/main/java/faang/school/godbless/Example.java
src/test/java/ExampleTest.java

Task "Развернитесь!" With 2 variants and 2 tests

Sleipnir fpv bjs2 18896

---

src/main/java/faang/school/godbless/BJS2_18440/Main.java
src/main/java/faang/school/godbless/BJS2_18440/User.java

Добавлено решение задачи BJS2_18440

Solution the task BJS2_18440

---

src/main/java/faang/school/godbless/Application.java
src/main/java/faang/school/godbless/User.java

Reverted code from the previous task, since it seems like a completely different project.

Created groupUsers method

---

src/main/java/faang/school/godbless/BJS2_18384/User.java
src/test/java/faang/school/godbless/BJS2_18384/UserTest.java

Не правильнее использовать Optional в методе findFirstCommonActivity?

BJS2-18384

---

src/main/java/faang/school/godbless/BJS2_18407/User.java
src/test/java/faang/school/godbless/BJS2_18407/UserTest.java

Не правильнее создать два Enum`а вместо того, чтобы иметь константы в виде сетов?

BJS2-18407

---

src/main/java/faang/school/godbless/reverseArray/Example.java

BJS2-18899 Развернитесь!

---

src/main/java/faang/school/godbless/task/user/grouping/User.java
src/test/java/faang/school/godbless/task/user/grouping/UserTest.java

**Ссылка на Jira:**
https://faang-school.atlassian.net/browse/BJS2-18468

Collecting users per age task resolve

---

src/main/java/faang/school/godbless/BJS2_18542/Archer.java
src/main/java/faang/school/godbless/BJS2_18542/Character.java
src/main/java/faang/school/godbless/BJS2_18542/Warrior.java
src/test/java/faang/school/godbless/BJS2_18542/ArcherTest.java
src/test/java/faang/school/godbless/BJS2_18542/WarriorTest.java

Abstract classes

---

src/main/java/faang/school/godbless/task/abstraction/abstraction/Archer.java
src/main/java/faang/school/godbless/task/abstraction/abstraction/Character.java
src/main/java/faang/school/godbless/task/abstraction/abstraction/Warrior.java
src/test/java/faang/school/godbless/task/abstraction/abstraction/CharacterTest.java

**Ссылка на таск в Jira:**
https://faang-school.atlassian.net/browse/BJS2-18547

Perform the task with abstract class

---

src/main/java/faang/school/godbless/task/reverse/Example.java
src/test/java/faang/school/godbless/task/reverse/ExampleTest.java

**Ссылка на таск в Jira:**
https://faang-school.atlassian.net/browse/BJS2-18833

Perform the task with reverse method

---

src/main/java/faang/school/godbless/BJS218658/Archer.java
src/main/java/faang/school/godbless/BJS218658/Character.java
src/main/java/faang/school/godbless/BJS218658/Main.java
src/main/java/faang/school/godbless/BJS218658/Warrior.java

BJS2-18658 Абстракция, абстракция!

BJS2-18658 Рик и Пиг

---

src/main/java/faang/school/godbless/Denalg/Main.java
src/main/java/faang/school/godbless/Denalg/User.java

Через ошибки, надеюсь получилось

Denalg-bjs2-18402

---

src/main/java/faang/school/godbless/BJS218870/Example.java

Main всегда отдельно нужно создавать?

BJS2-18870 reverse

---

src/main/java/user/collect/Main.java
src/main/java/user/collect/User.java
src/test/java/UserTest.java

Задача коллекционирование пользователей:
https://faang-school.atlassian.net/browse/BJS2-18383
Условия задачи
Создать класс 
User с полями:
id;
имя;
возраст;
множество активностей (строки).
Создать в этом классе метод findHobbyLovers, который принимает список пользователей и множество строк — активности. Возвращает мапу, где ключ пользователь, значение — строка.
Этот метод должен в переданном списке пользователей находить тех, у кого в ИХ множестве активностей есть хотя бы один элемент из переданного в метод множества активностей. Если так, то сохранить этого пользователя в виде ключа в результирующую мапу, а значением ему выставить первую совпавшую активность в двух множествах.

Sharkb6041 bjs2 18383

---

src/main/java/hasmap/library/Book.java
src/main/java/hasmap/library/Main.java
src/test/java/BookTest.java
src/test/java/HashMapTest.java

Задача Библиотека Вестероса
https://faang-school.atlassian.net/browse/BJS2-19271
Условия задачи
Создайте программу на Java, которая будет хранить информацию о библиотеке королевства, используя HashMap для хранения книг и их авторов. Вам нужно будет учесть особенности методов equals и hashCode.
Сюжет: В королевстве Вестероса хранится огромное количество книг, и король поручил вам создать систему учёта этих книг, чтобы обеспечить легкий доступ к ним для жителей королевства. Вы решаете создать программу на Java, используя HashMap для хранения книг и их авторов.
Требования:
Создайте класс Book, который будет содержать поля title (название книги), author (автор книги) и year (год издания).
Переопределите методы equals и hashCode в классе Book, чтобы учитывать название книги, автора и год …

Библиотека Вестероса

---

src/main/java/BJS218489/Main.java
src/main/java/BJS218489/User.java

Commiting "Users grouping" task

---

src/main/java/faang/school/godbless/Main.java
src/main/java/faang/school/godbless/User.java

add class user;

---

src/main/java/faang/school/godbless/Mathew/Archer.java
src/main/java/faang/school/godbless/Mathew/Character.java
src/main/java/faang/school/godbless/Mathew/Main.java
src/main/java/faang/school/godbless/Mathew/Warior.java

Commiting "Abstraction abstraction" task

---

src/main/java/BJS2_18472/User.java

Добавлена валидация для полей, протестировано локально

User registration

---

src/main/java/BJS218595/Example.java
src/main/java/BJS218595/Main.java

Mathew BJS2 18845

---

src/main/java/faang/school/godbless/BJS2_18414/Main.java
src/main/java/faang/school/godbless/BJS2_18414/User.java
src/test/java/UserTests.java

BJS2-18414

---

src/main/java/faang/school/godbless/BJS2_18648/Archer.java
src/main/java/faang/school/godbless/BJS2_18648/Character.java
src/main/java/faang/school/godbless/BJS2_18648/Main.java
src/main/java/faang/school/godbless/BJS2_18648/Warrior.java

BJS2-18648

---

src/main/java/faang/school/godbless/GameOfThrones/House.java
src/main/java/faang/school/godbless/GameOfThrones/Main.java

В классе Main сделал hashMap, которая хранит по названию дома объект класса house. Реализовал методы для работы с hashMap и выводом информации о всех домах\о гербе

Сделал класс House, содержащий в себе имя дома и герб.

---

.gitignore
src/main/java/faang/school/godbless/Application.java
src/main/java/ru/kraiush/model/BJS218540/Application.java
src/main/java/ru/kraiush/model/model/User.java

Creating class User with method findHobbyLovers();

Creating class User with method findHobbyLovers();

---

src/main/java/faang/school/godbless/BJS2_18459/User.java
src/test/java/faang/school/godbless/BJS2_18459/UserTest.java

Grouping by age done

---

src/main/java/faang/school/godbless/BJS2_18844/Example.java

BJS2-18844 - Развернитесь!

---

src/main/java/faang/school/godbless/BJS2_19000/Angel.java
src/main/java/faang/school/godbless/BJS2_19000/Battlefield.java
src/main/java/faang/school/godbless/BJS2_19000/Creature.java
src/main/java/faang/school/godbless/BJS2_19000/Griffin.java
src/main/java/faang/school/godbless/BJS2_19000/Hero.java
src/main/java/faang/school/godbless/BJS2_19000/Pikeman.java
src/main/java/faang/school/godbless/BJS2_19000/Swordman.java

… Battlefield c методом битвы и мэйн для тестирования

BJS2-19000 - Java HashMap: Герои меча и магии

---

src/main/java/faang/school/godbless/BJS2_18873/Main.java
src/main/java/faang/school/godbless/BJS2_18873/WeatherData.java
src/main/java/faang/school/godbless/BJS2_18873/WeatherExternalService.java
src/test/java/faang/school/godbless/BJS2_18873/MainTest.java

Cashing, cashing

---

src/main/java/faang/school/godbless/BJS2_18900/Main.java
src/main/java/faang/school/godbless/BJS2_18900/MockWeatherService.java
src/main/java/faang/school/godbless/BJS2_18900/WeatherData.java

…e - класс-заглушка для имитации сервиса погоды со случайной генерацией погоды, Main - класс с методами работы с кэшом и тестированием в мэйн.

BJS2-18900-Java HashMap: Кэшируем, кэшируем

---

src/main/java/faang/school/godbless/BJS2_19700/CompositeKeyFacultyYear.java
src/main/java/faang/school/godbless/BJS2_19700/Main.java
src/main/java/faang/school/godbless/BJS2_19700/Student.java

…пы CompositeKeyFacultyYear, и класс Main с методами работы программы и тестом работы в методе мэйн.

BJS2-19700-Java HashMap: Считаем прогулы

---

src/main/java/faang/school/godbless/BJS2_19746/House.java
src/main/java/faang/school/godbless/BJS2_19746/Main.java
src/test/java/faang/school/godbless/BJS2_19746/MainTest.java

Game of Thrones

---

src/main/java/faang/school/godbless/BJS2_18474/Main.java
src/main/java/faang/school/godbless/BJS2_18474/User.java
src/test/java/UserTest.java

BJS2-18474

---

src/main/java/faang/school/godbless/Main.java
src/main/java/faang/school/godbless/User.java

add class user

---

src/main/java/faang/school/godbless/Example.java
src/test/java/faang/school/godbless/ExampleTest.java

BJS2-18854 - Добавлен класс Example и реализован метод reverse

---

src/main/java/faang/school/godbless/grouping_persons_by_age/Main.java
src/main/java/faang/school/godbless/grouping_persons_by_age/User.java

BJS2-18545 - Группировка пользователей по возрасту

---

src/main/java/faang/school/godbless/BJS2_20323/Main.java
src/main/java/faang/school/godbless/BJS2_20323/StreamEvent.java
src/test/java/faang/school/godbless/BJS2_20323/MainTest.java

BJS2-20323 - Java HashMap: Ловим события

---

src/main/java/faang/school/godbless/BJS2_19400/Main.java
src/main/java/faang/school/godbless/BJS2_19400/Product.java

…аботы приложения и методом мэйн для проверки работы.

BJS2-19400-Java HashMap: Разбираем склад Amazon

---

src/main/java/faang/school/godbless/collecting_users/Main.java
src/main/java/faang/school/godbless/collecting_users/User.java

Коллекционируем пользователей: создала класс User с необходимыми полями и методом findHobbyLovers

BJS2-18403-collecting_users

---

src/main/java/faang/school/godbless/BJS2_19328/Group.java
src/main/java/faang/school/godbless/BJS2_19328/Main.java
src/main/java/faang/school/godbless/BJS2_19328/Student.java
src/test/java/faang/school/godbless/BJS2_19328/MainTest.java

Count misses

---

src/main/java/faang/school/godbless/BJS2_19300/Book.java
src/main/java/faang/school/godbless/BJS2_19300/Main.java

…и работы с библиотекой и тестом работы программы в методе мэйн.

BJS2-19300-Java HashMap: Библиотека Вестеросса

---

src/main/java/faang/school/godbless/grouping_users_by_age/Main.java
src/main/java/faang/school/godbless/grouping_users_by_age/User.java

BJS2-18451 - Группировка пользователей по возрасту

---

src/main/java/faang/school/godbless/BJS2_18418/Main.java
src/main/java/faang/school/godbless/BJS2_18418/User.java

Не знаю насколько уместно тут задавать вопрос, но как можно решить задачу, используя только стримы? Получилось только таким образом, но, по идее, это вариант хуже, чем в PR.
users.stream().filter(user -> user.activities.stream().anyMatch(activities::contains))
.forEach(userWithActivity -> {
matchedUsers.put(userWithActivity,
userWithActivity.activities.stream().filter(activities::contains).findFirst().get());
});

BJS2-18418 Коллекционируем пользователей

---

src/main/java/faang/school/godbless/User.java
src/main/java/user/group/User.java

Создал класс User и метод sortingUsersByAge, который сортирует юзеров по возрасту.

Создал класс User, выполнил таск BJS2-18448

---

src/main/java/faang/school/godbless/heroesofmightandmagic/Battlefield.java
src/main/java/faang/school/godbless/heroesofmightandmagic/Creature.java
src/main/java/faang/school/godbless/heroesofmightandmagic/Hero.java
src/main/java/faang/school/godbless/heroesofmightandmagic/creatures/Angel.java
src/main/java/faang/school/godbless/heroesofmightandmagic/creatures/Griffin.java
src/main/java/faang/school/godbless/heroesofmightandmagic/creatures/Pikeman.java
src/main/java/faang/school/godbless/heroesofmightandmagic/creatures/Swordman.java

Написал не до конца (только основную логику), так как могу очень увлечься и не успеть поделать другие задачи

BJS2-18882 Герои Меча и Магии

---

src/main/java/ru/kraiush/BJS2_19934/App_Counting_absenteeism.java
src/main/java/ru/kraiush/model/Student.java

BJS2-19934: Counting_absenteeism

---

src/main/java/faang/school/godbless/BJS2_19800/model/DataCenter.java
src/main/java/faang/school/godbless/BJS2_19800/model/ResourceRequest.java
src/main/java/faang/school/godbless/BJS2_19800/model/Server.java
src/main/java/faang/school/godbless/BJS2_19800/operationsOptimization/LoadBalancingOptimizationStrategy.java
src/main/java/faang/school/godbless/BJS2_19800/operationsOptimization/OptimizationStrategy.java
src/main/java/faang/school/godbless/BJS2_19800/service/DataCenterService.java
src/test/java/operationsOptimization/LoadBalancingOptimizationStrategyTest.java
src/test/java/service/DataCenterServiceTest.java

…-сервиса DataCenterService c логикой работы приложения, и класса с логикой оптимизации нагрузки на серверы LoadBalancingOptimizationStrategy, а так же юнит тесты на методы.

BJS2-19800-Java HashMap: Оптимизируем работу дата-центра

---

src/main/java/faang/school/godbless/BJS2_20020/Main.java
src/main/java/faang/school/godbless/BJS2_20020/Query.java
src/main/java/faang/school/godbless/BJS2_20020/User.java
src/test/java/faang/school/godbless/BJS2_20020/MainTest.java

…риложения, а так же юнит тесты на методы.

BJS2-20020-Java HashMap: Индекс запросов ELK

---

src/main/java/faang/school/godbless/turn_around/Example.java
src/main/java/faang/school/godbless/turn_around/Main.java

Развернитесь: создала класс Example с методом reverse

BJS2-18855-turn_around

---

src/main/java/faang/school/godbless/counting_absenteeism/Faculty.java
src/main/java/faang/school/godbless/counting_absenteeism/Main.java
src/main/java/faang/school/godbless/counting_absenteeism/Student.java

BJS2-19437

---

src/main/java/faang/school/godbless/library_of_westeros/Book.java
src/main/java/faang/school/godbless/library_of_westeros/Main.java

BJS2-19317

---

src/main/java/faang/school/godbless/caching/Main.java
src/main/java/faang/school/godbless/caching/WeatherData.java
src/main/java/faang/school/godbless/caching/api/Weather.java

BJS2-18961

---

src/main/java/faang/school/godbless/heroes_of_might_and_magic/Angel.java
src/main/java/faang/school/godbless/heroes_of_might_and_magic/Battlefield.java
src/main/java/faang/school/godbless/heroes_of_might_and_magic/Creature.java
src/main/java/faang/school/godbless/heroes_of_might_and_magic/Griffin.java
src/main/java/faang/school/godbless/heroes_of_might_and_magic/Hero.java
src/main/java/faang/school/godbless/heroes_of_might_and_magic/Pikeman.java
src/main/java/faang/school/godbless/heroes_of_might_and_magic/Swordman.java

BJS2-18958

---

src/main/java/faang/school/godbless/userRegistration/User.java
src/test/java/faang/school/godbless/userRegistration/UserTest.java

В сущности User добавил проверку на null для поля name, В UserTest добавил тест testCreateUserWithNullName().

Фикс согласно замечаниям.

---

build.gradle
src/main/java/faang/school/godbless/BJS2_18530/Application.java
src/main/java/faang/school/godbless/BJS2_18530/User.java
src/test/java/faang/school/godbless/BJS2_18530/UserTest.java

BJS2-18530

---

src/main/java/faang/school/godbless/javahashmap/task6/Main.java
src/main/java/faang/school/godbless/javahashmap/task6/Product.java

add class Product;

---

src/main/java/faang/school/godbless/BJS2_18587/Application.java
src/main/java/faang/school/godbless/BJS2_18587/User.java
src/test/java/faang/school/godbless/BJS2_18587/UserTest.java

Вывод в консоль не использовал. Написан тест!

BJS2-18587

---

src/main/java/user/group/Main.java
src/main/java/user/group/User.java
src/test/java/UserTest.java
src/test/java/user/group/test/UserTest.java

Задача Группировка пользователей по возрасту:
https://faang-school.atlassian.net/browse/BJS2-18469
Условия задачи
Создать класс 
User со следующими полями:
имя;
возраст;
место работы;
адрес.
В этом же классе создать статический метод 
groupUsers, который принимает List из объектов User и возвращает Map, где ключом является возраст пользователя, а значением — список из всех пользователей в оригинальном списке, которые имеют соответствующий возраст.

Added User class, added method for group users, added tests

---

src/main/java/faang/school/godbless/BJS2_19999/House.java
src/main/java/faang/school/godbless/BJS2_19999/Main.java

Добавил Класс-сущность House и класс Main с методами работы программы

BJS2-19999 Java HashMap: Игра престолов

---

src/main/java/faang/school/godbless/BJS2_20000/Main.java
src/main/java/faang/school/godbless/BJS2_20000/Student.java
src/main/java/faang/school/godbless/BJS2_20000/Subject.java
src/test/java/faang/school/godbless/BJS2_20000/MainTest.java

Добавил 2 класса сущности Subject и Student, и класс Main с методами работы программы, а так же MainTest для тестов методов

BJS2-20000 Java HashMap: Двойной кэш-кэш

---

build.gradle
src/main/java/user/registration/Main.java
src/main/java/user/registration/User.java
src/test/java/UserTest.java
src/test/java/user/registration/test/UserTest.java

Задача Регистрация пользователей
https://faang-school.atlassian.net/browse/BJS2-18421
Условия задачи
В том же классе пользователя создать конструктор, который принимает в качестве параметров значения для всех полей класса.
В качестве статических констант в классе объявить 2 сета:
{{VALID_JOBS}}— сразу инициализировать его, содержащим 3 строки: “Google”, “Uber”, “Amazon”;
{{VALID_ADDRESSES}}— сразу инициализировать его, содержащим 3 строки: “London”, “New York”, “Amsterdam”.
В конструкторе провести валидацию этих параметров по следующим правилам:
имя не может быть пустым;
возраст не может быть меньше 18;
место работы должно содержаться во множестве VALID_JOBS;
адрес должен содержаться во множестве VALID_ADDRESSES.
Если хотя бы одно из условий не выполняется, то выбросить исключение …

Added constructor in User with checking parameters, added tests

---

src/main/java/data/optimization/DataCenter.java
src/main/java/data/optimization/DataCenterService.java
src/main/java/data/optimization/ResourceRequest.java
src/main/java/data/optimization/Server.java
src/main/java/data/optimization/optim/strategy/EnergyEfficiencyOptimizationStrategy.java
src/main/java/data/optimization/optim/strategy/LoadBalancingOptimizationStrategy.java
src/main/java/data/optimization/optim/strategy/Main.java
src/main/java/data/optimization/optim/strategy/OptimizationStrategy.java
src/main/java/data/optimization/optim/strategy/SillyOptimizationStrategy.java
src/test/java/data/optimization/test/DataCenterTest.java
src/test/java/data/optimization/test/DataServiceTest.java
src/test/java/data/optimization/test/ServerTest.java
src/test/java/data/optimization/test/SillyOptimizationStrategyTest.java

Задача Оптимизируем работу дата-центра
https://faang-school.atlassian.net/browse/BJS2-19405
Условия задачи
Представьте, что Вы работаете в крупнейшей компании, с большим количеством дата-центров в разных уголках планеты. Вам нужно создать систему, которая позволит определить оптимальное распределение ресурсов и обеспечить эффективное использование серверов в дата-центре.
Выполнение этой задачи поможет лучше понять концепции ООП, реализовать паттерн Стратегия и в целом попрактиковать навыки проектирования и реализации систем с использованием различных компонентов.
Требования:
Создать класс Server, который будет содержать следующие характеристики: double load — отражает текущцю нагрузку на сервер; double maxLoad — отражает максимальную нагрузку на сервер; double energyConsumption — отражает …

Оптимизируем работу дата-центра

---

src/main/java/search/engine/Main.java
src/main/java/search/engine/WebPage.java
src/test/java/search/engine/test/EngineTest.java
src/test/java/search/engine/test/WebPageTest.java

Задача Поисковой мини-движок Google
https://faang-school.atlassian.net/browse/BJS2-20177
Условия задачи
Создайте программу на Java для реализации своего простого поискового движка с использованием HashMap.
Сюжет: Вы решили создать простой поисковой движок, который будет индексировать веб-страницы и позволять пользователям быстро находить страницы по ключевым словам. Ваша задача состоит в создании прототипа поискового движка, используя Java и HashMap для хранения и обработки данных.
Требования:
Создайте класс WebPage, который будет содержать поля url (URL веб-страницы), title (заголовок страницы) и content (содержание страницы).
В классе Main, создайте HashMap с ключом типа String (ключевое слово) и значением типа List<WebPage> (список веб-страниц, содержащих ключевое слово).
Реализуйте …

Поисковой мини-движок Google

---

src/main/java/faang/school/godbless/double_cache_cache/Main.java
src/main/java/faang/school/godbless/double_cache_cache/Student.java
src/main/java/faang/school/godbless/double_cache_cache/Subject.java

BJS2-19782

---

src/main/java/faang/school/godbless/dismantling_amazon_warehouse/Main.java
src/main/java/faang/school/godbless/dismantling_amazon_warehouse/Product.java

BJS2-19339

---

src/main/java/faang/school/godbless/catch_event/Main.java
src/main/java/faang/school/godbless/catch_event/StreamEvent.java

BJS2-20384

---

src/main/java/faang/school/godbless/turn_around/Example.java
src/main/java/faang/school/godbless/turn_around/Main.java

BJS2-18905

---

src/main/java/ru/kraiush/BJS2_20242/App_LRUCache.java
src/main/java/ru/kraiush/model/Student.java

BJS2-20242: "HashMap: LRU Cache" v.01

Bjs2 20242

---

src/main/java/faang/school/godbless/javahashmap/task7/Angel.java
src/main/java/faang/school/godbless/javahashmap/task7/BattleField.java
src/main/java/faang/school/godbless/javahashmap/task7/Creature.java
src/main/java/faang/school/godbless/javahashmap/task7/Griffin.java
src/main/java/faang/school/godbless/javahashmap/task7/Hero.java
src/main/java/faang/school/godbless/javahashmap/task7/Main.java
src/main/java/faang/school/godbless/javahashmap/task7/Pikeman.java
src/main/java/faang/school/godbless/javahashmap/task7/Swordman.java

add methods battle, add and remove Creature

add class Creature, Hero, Battlefield;

---

src/main/java/faang/school/godbless/javahashmap/task3/FacultyInfo.java
src/main/java/faang/school/godbless/javahashmap/task3/Main.java
src/main/java/faang/school/godbless/javahashmap/task3/Student.java

add methods add, remove, search Student

add class Student;

---

src/main/java/faang/school/godbless/lru_cache/Data.java
src/main/java/faang/school/godbless/lru_cache/Main.java

BJS2-20222

---

src/main/java/faang/school/godbless/javahashmap/task5/Main.java
src/main/java/faang/school/godbless/javahashmap/task5/StreamEvent.java

add class StreamEvent;

---

src/main/java/ru/kraiush/BJS2_18589/App_collecting_users_by_hobby.java
src/main/java/ru/kraiush/model/User.java

Coolecting users by hobbies
v.01

BJS2-18589 : Coolecting users by hobbies v.01

---

src/main/java/faang/school/godbless/javahashmap/task9/Main.java
src/main/java/faang/school/godbless/javahashmap/task9/WebPage.java

add methods remove, find, add webPage

add class WebPage;

---

src/main/java/faang/school/godbless/Application.java
src/main/java/faang/school/godbless/User.java
src/test/java/UserTest.java

PR второй задачи по группировке юзеров по возрасту

BJS2-18487 - Добавлен класс User и метод groupUsers

---

src/main/java/faang/school/godbless/Archer.java
src/main/java/faang/school/godbless/Character.java
src/main/java/faang/school/godbless/Warrior.java
src/test/java/faang/school/godbless/CharacterTest.java

PR задача 'Абстракция, абстракция!'

BJS2-18680 -Абстрактный класс Character, 2 персонажа

---

src/main/java/faang/school/godbless/User.java
src/main/java/faang/school/godbless/hobbyLovers/User.java
src/test/java/org/example/UserTest.java

PR для задачи 'Коллекционируем пользователей'

BJS2-18395 - Добавлен класс User и метод findHobbyLovers

---

src/main/java/faang/school/godbless/group_user_by_age/Main.java
src/main/java/faang/school/godbless/group_user_by_age/User.java

Группировка пользователей по возрасту: создала класс User с необходимыми полями и сделала метод groupUsers

BJS2-18473-group_user_by_age: added class User with method groupUsers

---

src/main/java/faang/school/godbless/game_of_thrones/House.java
src/main/java/faang/school/godbless/game_of_thrones/Main.java

created class House with all methods

BJS2-19818-game_of_thrones

---

src/main/java/faang/school/godbless/BJS2_20802/Main.java
src/main/java/faang/school/godbless/BJS2_20802/StreamEvent.java
src/test/java/faang/school/godbless/BJS2_20802/MainTest.java

Добавил класс-модель StreamEvent, класс Main с методами работы программы и тестовый класс

BJS2-20802  Java HashMap: Ловим события

---

src/main/java/faang/school/godbless/BJS2_20300/Main.java
src/main/java/faang/school/godbless/BJS2_20300/WebPage.java
src/test/java/faang/school/godbless/BJS2_20300/MainTest.java

Добавил класс-модель WebPage, класс Main c методами работы программы и класс с тестами методов.

BJS2-20300   Java HashMap: Поисковой мини-движок Google

---

src/main/java/faang/school/godbless/User.java
src/main/java/faang/school/godbless/user/User.java
src/test/java/UserTest.java

PR 3 задача по добавлению проверок в конструкторе

BJS2-18453 - В конструкторе класса User добавлены проверки

---

src/main/java/faang/school/godbless/BJS2_18484/Main.java
src/main/java/faang/school/godbless/BJS2_18484/User.java

- Создан конструктор в классе `User`, принимающий параметры для всех полей.
- В классе добавлены два статических сета `VALID_JOBS` и `VALID_ADDRESSES`, инициализированных значениями:
- `VALID_JOBS`: "Google", "Uber", "Amazon"
- `VALID_ADDRESSES`: "London", "New York", "Amsterdam"
- Реализована валидация параметров конструктора:
- Имя не может быть пустым и должно соответствовать паттерну.
- Возраст не может быть меньше 18 лет.
- Место работы должно быть одним из значений в `VALID_JOBS`.
- Адрес должен быть одним из значений в `VALID_ADDRESSES`.
- Если одно из условий не выполняется, выбрасывается исключение `IllegalArgumentException`.
- Поля класса инициализируются значениями, переданными в конструктор, если все проверки прошли успешно.

feat(user): добавлен конструктор с валидацией для класса User

---

src/main/java/homm/Battlefield.java
src/main/java/homm/Hero.java
src/main/java/homm/Main.java
src/main/java/homm/creatures/Angel.java
src/main/java/homm/creatures/Creature.java
src/main/java/homm/creatures/Griffin.java
src/main/java/homm/creatures/Pikeman.java
src/main/java/homm/creatures/Swordsman.java

Задача Герои Меча и Магии
https://faang-school.atlassian.net/browse/BJS2-18856
Условия задачи
Разработайте систему управления армией в сеттинге игры Heroes of Might and Magic III, используя основы ООП и коллекции. Ваша задача — создать иерархию классов для разных видов существ и героев, а также управление армией героя.
Требования:
Создайте абстрактный класс Creature с основными характеристиками, такими как имя, уровень, атака, защита, скорость и количество. Также добавьте метод getDamage(), который будет возвращать урон, наносимый существом.
Создайте несколько подклассов, таких как Pikeman, Griffin, Swordman, Angel, каждый из которых наследует от класса Creature. Установите соответствующие значения характеристик для каждого подкласса.
Создайте класс Hero с основными характеристиками, …

Герои Меча и Магии

---

src/main/java/faang/school/godbless/BJS2_18400/User.java

Добавлена валидация в конструкторе и множества в поля

BJS2-18400   Регистрация пользователей

---

src/main/java/faang/school/godbless/task19533/Main.java
src/main/java/faang/school/godbless/task19533/Student.java

Chibisovaanastasiia0318 bjs2 19533

---

src/main/java/faang/school/godbless/students/Main.java
src/main/java/faang/school/godbless/students/Student.java

Система учета студентов по факультетам и курсам

BJS2-19412 Java HashMap: Считаем прогулы 

---

src/main/java/faang/school/godbless/BJS220419/DictionaryProcessor.java
src/main/java/faang/school/godbless/BJS220419/Main.java

Google Переводчик под нашим контролем…
👩‍💻 🧠
Условия задачи
Описание: Вы являетесь разработчиком приложения Google Translator и работаете над функцией, которая позволяет пользователям добавлять слова и их переводы в словарь. Вам необходимо создать систему, которая будет принимать слово и его перевод, а затем сохранять их в словарь с использованием интерфейса BiConsumer.
Цель: Создайте класс DictionaryProcessor, который будет использовать BiConsumer для обработки словаря.
Требования:
Создайте класс DictionaryProcessor с методом processWord;
Метод processWord должен принимать слово, его перевод и BiConsumer для обработки словаря;
Создайте лямбда-выражение для сохранения слова и его перевода в словарь, используя интерфейс BiConsumer;
Протестируйте вашу систему, создав несколько примеров слов …

BJS2-20419

---

src/main/java/faang/school/godbless/BJS220724/Main.java
src/main/java/faang/school/godbless/BJS220724/SpellAction.java
src/main/java/faang/school/godbless/BJS220724/SpellCaster.java

Хогвартс, Хогвартс, наш любимый Хогвартс
👩‍💻 🧠
Условия задачи
Вы являетесь учеником школы чародейства и волшебства «Хогвартс», и вам поручено создать систему для управления заклинаниями. Ваша система должна быть способна выполнять различные магические действия, передавая функции в виде лямбда-выражений.
Цель: Создайте класс SpellCaster с методом cast, который принимает строку с названием заклинания и лямбда-выражение, описывающее действие этого заклинания. Используйте его для выполнения различных магических действий.
Требования:
Создайте функциональный интерфейс SpellAction, который принимает строку с названием заклинания и возвращает строку с результатом выполнения заклинания;
Создайте класс SpellCaster с методом cast, который принимает строку с названием заклинания и лямбда-выражение …

BJS2-20724

---

src/main/java/faang/school/godbless/BJS221095/ExceptionHandler.java
src/main/java/faang/school/godbless/BJS221095/Main.java

Обрабатываем ошибки красиво
👩‍💻 🧠🧠
Условия задачи
Представьте, что вы работаете в большой команде в Meta и строите систему на микросервисной архитектуре. При этом, вы заметили, что в коде часто повторяется одинаковый паттерн:
Есть вызов какого-то удалённого сервиса;
Он обёрнут в try/catch, и при ошибке возвращается какое-то дефолтное значение или null. Например, так:
try {
return remoteService.call(param);
} catch (Exception e) {
log.warn("Не удалось получить доступ к Remote Service. Вернем default значение");
return "DEFAULT";
}
И так повсюду в вашем коде, где вы обращаетесь в remoteService.
Вы захотели избавиться от этих повторений, и решили написать один метод withErrorHandling, который содержит в себе 2 перечисленных пункта.
Написать статический метод withErrorHandling, который …

Beksultan2005 bjs2 21095

---

src/main/java/faang/school/godbless/BJS221311/Email.java
src/main/java/faang/school/godbless/BJS221311/EmailProcessor.java
src/main/java/faang/school/godbless/BJS221311/Main.java

Gmail Rich Filters
👩‍💻 🧠
Условия задачи
Описание: Вы являетесь разработчиком приложения GMail и работаете над функцией, которая позволяет пользователям настраивать фильтры для обработки входящих писем. Вам необходимо создать систему, которая будет применять набор пользовательских фильтров к входящим письмам с использованием популярных функциональных интерфейсов Predicate, Consumer, и Function.
Цель: Создайте класс EmailProcessor, который будет использовать Predicate для фильтрации писем, Consumer для обработки писем и Function для преобразования писем.
Требования:
Создайте класс Email с полями subject, body и isImportant;
Создайте класс EmailProcessor с методом processEmails;
Метод processEmails должен принимать список входящих писем, Predicate для фильтрации, Consumer для обработки и …

BJS2-21311

---

src/main/java/faang/school/godbless/BJS221842/FilterProcessor.java
src/main/java/faang/school/godbless/BJS221842/Image.java
src/main/java/faang/school/godbless/BJS221842/Main.java

Фильтры Instagram
👩‍💻 🧠
Условия задачи
Описание: Вы являетесь разработчиком приложения Instagram и работаете над новой функцией, которая позволяет пользователям применять фильтры к своим фотографиям. Вам необходимо создать систему, которая позволяет пользователям выбирать различные фильтры и применять их к своим фотографиям. Для реализации этой системы вы должны использовать функции высокого порядка в Java.
Цель: Создайте класс FilterProcessor, который будет содержать функции высокого порядка для обработки изображений и применения фильтров.
Требования:
Создайте класс Image, который будет представлять фотографию пользователя. В рамках данной задачи, класс Image может иметь только имя файла и описание;
Создайте класс FilterProcessor с методами: applyFilter: принимает объект типа Image и …

BJS2-21842

---

src/main/java/faang/school/godbless/BJS2_18741/Archer.java
src/main/java/faang/school/godbless/BJS2_18741/Character.java
src/main/java/faang/school/godbless/BJS2_18741/Main.java
src/main/java/faang/school/godbless/BJS2_18741/Warrior.java

- Создан абстрактный класс `Character` с полями: имя, сила, ловкость, интеллект и здоровье (по умолчанию 100).
- Добавлены два конструктора в `Character`: один принимает только имя, другой — все параметры, кроме здоровья.
- Реализованы подклассы `Warrior` и `Archer` с переопределёнными конструкторами:
- `Warrior`: сила = 10, ловкость = 5, интеллект = 3.
- `Archer`: сила = 3, ловкость = 10, интеллект = 5.
- Определён абстрактный метод `attack` в классе `Character` и его реализация в классах `Warrior` и `Archer`:
- `Warrior` наносит урон, равный своей силе.
- `Archer` наносит урон, равный своей ловкости.

feat: реализованы классы Character, Warrior и Archer с логикой атаки

---

src/main/java/faang/school/godbless/BJS2_20220/Cache.java
src/main/java/faang/school/godbless/BJS2_20220/DaTa.java
src/main/java/faang/school/godbless/BJS2_20220/Main.java
src/test/java/faang/school/godbless/BJS2_20220/MainTest.java

Добавил класс-модель DaTa, класс-коллекцию Cache, класс Main с методами работы программы и Тестовый класс.

BJS2-20220   Java HashMap: LRU Cache

---

src/main/java/faang/school/godbless/register/user/User.java
src/test/java/faang/school/godbless/register/user/UserTest.java

Добавил валидации и сделал тесты

nf BJS2-18492 validation added

---

src/main/java/faang/school/godbless/abstraction/Archer.java
src/main/java/faang/school/godbless/abstraction/Character.java
src/main/java/faang/school/godbless/abstraction/Warrior.java
src/test/java/faang/school/godbless/abstraction/CharacterTest.java

Судя по последним строкам задания для поля нужно было делать protected, но хотелось сделать private + геттеры и сеттеры. Если надо переделаю

nf BJS2-18805 warrior and archer added

---

src/main/java/faang/school/godbless/gameofthrones/House.java
src/main/java/faang/school/godbless/gameofthrones/Main.java
src/test/java/faang/school/godbless/gameofthrones/TestMain.java

Houses of Westeros

---

src/main/java/faang/school/godbless/absent/Main.java
src/main/java/faang/school/godbless/absent/Student.java
src/test/java/faang/school/godbless/absent/TestMain.java

Absenteeism

---

build.gradle
src/main/java/faang/school/godbless/hogwarts_hogwarts_our_beloved_hogwarts/Main.java
src/main/java/faang/school/godbless/hogwarts_hogwarts_our_beloved_hogwarts/SpellAction.java
src/main/java/faang/school/godbless/hogwarts_hogwarts_our_beloved_hogwarts/SpellCaster.java
src/test/java/faang/school/godbless/hogwarts_hogwarts_our_beloved_hogwarts/SpellCasterTest.java

BJS2-20739

---

src/main/java/faang/school/godbless/BJS2_20880/SpellAction.java
src/main/java/faang/school/godbless/BJS2_20880/SpellCaster.java

Создал функциональный интерфейс и класс SpellCaster c логикой работы программы и проверкой в методе мэйн.

BJS2-20880   Хогвартс, Хогвартс, наш любимый Хогвартс

---

src/main/java/faang/school/godbless/filters_in_instagram/FilterProcessor.java
src/main/java/faang/school/godbless/filters_in_instagram/Image.java
src/main/java/faang/school/godbless/filters_in_instagram/Main.java

BJS2-21851

---

src/main/java/collect/Main.java
src/main/java/collect/User.java
src/main/java/collectUsers/Main.java
src/main/java/collectUsers/User.java

Поправил форматирование и переписал метод с помощью computeifabsent. У меня там, правда, лишний коммит залетел из другой ветки, но он не мешает задаче (в разных пакетах лежат).

Исправления по 18647

---

src/main/java/faang/school/godbless/BJS222070/Main.java
src/main/java/faang/school/godbless/BJS222070/MessageFilter.java
src/main/java/faang/school/godbless/BJS222070/MessageProcessor.java

Фильтруем спам
👩‍💻 🧠
Условия задачи
Описание: Вы являетесь разработчиком приложения Telegram и работаете над функцией, которая позволяет пользователям настраивать обработку входящих сообщений с помощью фильтров. Вам необходимо создать систему, которая будет применять набор пользовательских фильтров к входящим сообщениям с использованием собственного функционального интерфейса.
Цель: Создайте собственный функциональный интерфейс MessageFilter и класс MessageProcessor, который будет использовать список объектов MessageFilter для обработки сообщений.
Требования:
Создайте функциональный интерфейс MessageFilter с методом filter, который принимает строку (сообщение) и возвращает boolean (применяется фильтр или нет);
Создайте класс MessageProcessor с методом processMessage;
Метод processMessage …

Beksultan2005 bjs2 22070

---

src/main/java/faang/school/godbless/task20219/Main.java
src/main/java/faang/school/godbless/task20219/WebPage.java

BJS2-20219 - Поисковой мини-движок Google

BJS2-20219 - Поисковой мини-движок Google

---

src/main/java/faang/school/godbless/BJS221411/Calculator.java
src/main/java/faang/school/godbless/BJS221411/Main.java

Калькулятор
👩‍💻 🧠🧠
Условия задачи
Вы работаете разработчиком в дата центре Google и создаёте систему сбора аналитики использования ресурсов дата-центра. Вам нужно сделать её достаточно гибкой и масштабируемой для будущих новых сценариев, поэтому вы решаете использовать лямбды и функциональные интерфейсы.
1. Создать подходящий функциональный интерфейс Calculator, который должен иметь метод, принимающий два значения одного типа и возвращающий результат применения к ним какой-либо операции. Какого типа получится тогда результат?
2. Реализовать метод, который принимает список чисел, а также объект Calculator, который и будет операцией, которую нужно применить к элементам в списке.
public static int calculate(List<Integer> nums, Calculator calculator) throws IllegalArgumentException
3. …

BJS2-21411

---

src/main/java/BJS2_18987/Main.java
src/main/java/BJS2_18987/WeatherData.java
src/main/java/BJS2_18987/WeatherTestAPI.java

Sleipnir fpv bjs2 18987

---

src/main/java/BJS2_19344/Book.java
src/main/java/BJS2_19344/Main.java

Sleipnir fpv bjs2 19344

---

src/main/java/BJS2_19417/Main.java
src/main/java/BJS2_19417/Product.java

Amazon Warehouse can sleep well now!

Sleipnir fpv bjs2 19417

---

src/main/java/BJS2_20429/Main.java
src/main/java/BJS2_20429/StreamEvent.java

Ловим события

---

src/main/java/faang/school/godbless/BJS220937/Droid.java
src/main/java/faang/school/godbless/BJS220937/DroidMessageEncryptor.java
src/main/java/faang/school/godbless/BJS220937/Main.java

Секреты дроидов
👩‍💻 🧠🧠🧠
Условия задачи
Создание функционального интерфейса для передачи сообщений между дроидами во вселенной Звёздных Войн.
Описание: Вы являетесь разработчиком дроидов во вселенной Звёздных Войн, и вашей задачей является разработка функционального интерфейса для передачи зашифрованных сообщений между дроидами различных типов. Функциональный интерфейс должен быть способен принимать сообщение и ключ шифрования, а затем возвращать зашифрованное сообщение.
Цель: Создайте функциональный интерфейс DroidMessageEncryptor, и используйте его для передачи зашифрованных сообщений между дроидами.
Требования:
Создайте функциональный интерфейс DroidMessageEncryptor, который принимает сообщение (строку) и ключ шифрования (целое число), и возвращает зашифрованное сообщение (строку); …

BJS2-20937

---

src/main/java/faang/school/godbless/Maps/BJS2_18289/Main.java
src/main/java/faang/school/godbless/Maps/BJS2_18289/MockService.java
src/main/java/faang/school/godbless/Maps/BJS2_18289/WeatherData.java

Solution is in the BJS2_18289 folder

Java HashMap: Кэшируем, кэшируем : BJS2 19080

---

src/main/java/faang/school/godbless/task20901/Main.java
src/main/java/faang/school/godbless/task20901/SpellAction.java
src/main/java/faang/school/godbless/task20901/SpellCaster.java

BJS2 - 20901 - Хогвартс, Хогвартс, наш любимый Хогвартс

BJS2-20901 - Хогвартс, Хогвартс, наш любимый Хогвартс

---

src/main/java/handle/exceptions/ExceptionHandler.java
src/main/java/handle/exceptions/Main.java
src/main/java/handle/exceptions/Service.java

Задача Обрабатываем ошибки красиво
https://faang-school.atlassian.net/browse/BJS2-21103

Обрабатываем ошибки красиво

---

src/main/java/faang/school/godbless/Application.java
src/main/java/faang/school/godbless/SpellAction.java
src/main/java/faang/school/godbless/SpellCaster.java

implemented classes SpellAction and SpellCaster

almas4382d-BJS2-20923:Хогвартс, Хогвартс, наш любимый Хогвартс

---

src/main/java/faang/school/godbless/BJS2_21118/ExceptionHandler.java
src/main/java/faang/school/godbless/BJS2_21118/Main.java
src/main/java/faang/school/godbless/BJS2_21118/RemoteService.java
src/test/java/faang/school/godbless/BJS2_21118/MainTest.java

BJS2-21118 Exception handler

---

src/main/java/faang/school/godbless/BJS2_21251/Character.java
src/main/java/faang/school/godbless/BJS2_21251/InventoryManager.java
src/main/java/faang/school/godbless/BJS2_21251/Item.java
src/test/java/faang/school/godbless/BJS2_21251/InventoryManagerTest.java

BJS2-21251 Lord of the Rings RPG

---

src/main/java/faang/school/godbless/BJS2_21470/CalculatorService.java
src/main/java/faang/school/godbless/BJS2_21470/Main.java

Я не вижу необходимости создавать свой функ. интерфейс, ибо в джаве уже есть подходящий. Так же мне кажется лучше сразу в лямбде обработать весь лист нежели вызывать каждый раз лямбду для двух элементов листа

BJS2-21470

---

src/main/java/faang/school/godbless/InstagrammFilters/FilterProcessor.java
src/main/java/faang/school/godbless/InstagrammFilters/Image.java
src/main/java/faang/school/godbless/InstagrammFilters/Main.java

Сделал класс FilterProcessor, который накладывает фильтры на фотографии.

---

src/main/java/faang/school/godbless/meta_universe/Main.java
src/main/java/faang/school/godbless/meta_universe/Notification.java
src/main/java/faang/school/godbless/meta_universe/NotificationManager.java

Долго ломала голову как сделать и в итоге через accept() все получилось. Но пока осознать это не получается))

BJS2-22002-meta_universe

---

src/main/java/faang/school/godbless/BJS2_21451/Calculator.java
src/main/java/faang/school/godbless/BJS2_21451/Main.java
src/test/java/faang/school/godbless/BJS2_21451/MainTest.java

BJS2-21451 Калькулятор

---

src/main/java/transform/matrix/Coordinates.java
src/main/java/transform/matrix/Main.java
src/main/java/transform/matrix/MatrixTransformer.java

Задача Перевернем матрицу
https://faang-school.atlassian.net/browse/BJS2-20517

Перевернем матрицу

---

src/main/java/BJS2_18476/App.java
src/main/java/BJS2_18476/User.java

Взял за основу "Группировка пользователей по возрасту"

Task "Регистрация пользователя"

---

src/main/java/faang/school/godbless/BJS2_18929/Example.java
src/main/java/faang/school/godbless/BJS2_18929/Main.java

- Создан класс Example.
- Добавлен метод reverse, который принимает массив целых чисел и разворачивает его.
- Метод успешно разворачивает массив, изменяя порядок элементов на обратный.

feat: добавлен класс Example с методом reverse для разворота массива

---

src/main/java/faang/school/godbless/Application.java
src/main/java/faang/school/godbless/Battlefield.java
src/main/java/faang/school/godbless/Hero.java
src/main/java/faang/school/godbless/units/Angel.java
src/main/java/faang/school/godbless/units/Creature.java
src/main/java/faang/school/godbless/units/Griffin.java
src/main/java/faang/school/godbless/units/Pikeman.java
src/main/java/faang/school/godbless/units/Swordsman.java
src/test/java/faang/school/godbless/HeroTest.java

PR для задачи 'Java HashMap: Герои меча и магии'

BJS2-18903 - Разработана система управления армией для homm

---

src/main/java/faang/school/godbless/google_translator_is_under_our_control/DictionaryProcessor.java
src/main/java/faang/school/godbless/google_translator_is_under_our_control/Main.java

BJS2-20471

---

src/main/java/faang/school/godbless/Application.java
src/main/java/faang/school/godbless/elk/Main.java
src/main/java/faang/school/godbless/elk/models/Query.java
src/main/java/faang/school/godbless/elk/models/User.java
src/main/java/faang/school/godbless/elk/services/ELKService.java

Класс User и Query, сервис для работы с ELK.

BJS2-19751 - создан пробник запросов ELK

---

src/main/java/faang/school/godbless/BeautifulExceptionHandler/ExceptionHandler.java
src/main/java/faang/school/godbless/BeautifulExceptionHandler/Main.java

1) Действие
2) Действие в случае если первое действие не удалось.

Создал статический метод withErrorHandling, который принимает 2 лямбды:

---

src/main/java/faang/school/godbless/task20977/Droid.java
src/main/java/faang/school/godbless/task20977/DroidMassageReceiver.java
src/main/java/faang/school/godbless/task20977/DroidMessageEncryptor.java
src/main/java/faang/school/godbless/task20977/FunctionalDroidMessageEncryptor.java
src/main/java/faang/school/godbless/task20977/Main.java

BJS2 - 20977 - Секреты дроидов

BJS2-20977 - Секреты дроидов

---

src/main/java/ru/kraiush/BJS2_18571/AppUserRegistration.java
src/main/java/ru/kraiush/model/UserRegistration.java

BJS2-18571: user registration

---

src/main/java/faang/school/godbless/BJS2_18458/Main.java
src/main/java/faang/school/godbless/BJS2_18458/User.java

- Создан метод findHobbyLovers в классе User, который принимает список пользователей и множество активностей.
- Метод возвращает мапу, где ключом является пользователь, а значением — первая активность, совпавшая с переданными.
- Реализована логика фильтрации и поиска совпадающих активностей с использованием Stream API.
- Добавлен пример использования метода в классе Main с выводом результатов в консоль.

feat: добавлен метод findHobbyLovers для поиска пользователей по активностям

---

src/main/java/stream/training2/Employee.java
src/main/java/stream/training2/Main.java

Задача Тренируем StreamAPI 2
https://faang-school.atlassian.net/browse/BJS2-22435

Тренируем StreamAPI 2

---

src/main/java/BJS2_19829/Main.java
src/main/java/BJS2_19829/Student.java
src/main/java/BJS2_19829/Subject.java

Двойной кэш кэш, учел прошлые ошибки \ недоработки (с computeIfAbsent) в частности

Двойной Кэш Кэш

---

src/main/java/faang/school/godbless/handling_errors/ExceptionHandler.java
src/main/java/faang/school/godbless/handling_errors/Main.java

Добавил serviceCall для полноты картины (для себя), и пока его писал решил использовать Callable вместо Supplier (get кидает Exception - то, что нужно в задании).

BJS2-21143 - Обрабатываем ошибки красиво

---

src/main/java/faang/school/godbless/gmail/Email.java
src/main/java/faang/school/godbless/gmail/EmailProcessor.java
src/main/java/faang/school/godbless/gmail/Main.java

не стримом
```
for (Email e : emails) {
if (filter.test(e)) {
e.setBody(handler.apply(e));
consumer.accept(e);
}
}
```

BJS2-21329 - Фильтрация почты

---

src/main/java/faang/school/godbless/BJS2_22550/Employee.java
src/main/java/faang/school/godbless/BJS2_22550/Streams.java
src/test/java/faang/school/godbless/BJS2_22550/StreamsTest.java

Добавил класс-модель Employee, а так же класс Streams с методами работы программы, и тестовый класс.

BJS2-22550   Потренируем StreamAPI 2

---

src/main/java/faang/school/godbless/social_media/UserAction.java
src/main/java/faang/school/godbless/social_media/UserAnalyticsService.java
src/test/java/faang/school/godbless/social_media/UserAnalyticsServiceTest.java

- **prep & tests**
- **social media**

social media

---

src/main/java/faang/school/godbless/BJS2_22575/ActionType.java
src/main/java/faang/school/godbless/BJS2_22575/Social.java
src/main/java/faang/school/godbless/BJS2_22575/UserAction.java
src/test/java/faang/school/godbless/BJS2_22575/UserActionTest.java

Тесты добавил для наглядности вывода на экран. Нормальные тесты не писал

BJS2-22575 Social analysis

---

src/main/java/faang/school/godbless/user_activity/ActionType.java
src/main/java/faang/school/godbless/user_activity/StatsAnalyzer.java
src/main/java/faang/school/godbless/user_activity/UserAction.java
src/test/java/faang/school/godbless/user_activity/StatsAnalyzerTest.java

I have created a method for collecting stats (passing stream, filter, key function for grouping collector and limit for top entities), not sure whether it is most efficient - especially for finding top tags, please share insights on how to improve it.

BSJ2-22582 - User activity analysis

---

src/main/java/BJS2_19551/DataCenter.java
src/main/java/BJS2_19551/DataCenterService.java
src/main/java/BJS2_19551/LoadBalancingOptimizationStrategy.java
src/main/java/BJS2_19551/Main.java
src/main/java/BJS2_19551/Optimization.java
src/main/java/BJS2_19551/OptimizationStrategy.java
src/main/java/BJS2_19551/ResourceRequest.java
src/main/java/BJS2_19551/Server.java

Data Center Optimization v 1.0

Data Center Optimization

---

src/main/java/BJS2_20213/Main.java
src/main/java/BJS2_20213/WebPage.java

Поисковый движок Google

---

src/main/java/faang/school/godbless/meta/Main.java
src/main/java/faang/school/godbless/meta/Notification.java
src/main/java/faang/school/godbless/meta/NotificationManager.java

Хотел спросить совета по поводу случая с sms: не смог модерировать сообщение без изменения состояния уведомления (Notification.message), подскажите, как это можно было здесь провернуть.

BJS2-22013 - Meta Universe

---

src/main/java/faang/school/godbless/BJS2_22600/ActionType.java
src/main/java/faang/school/godbless/BJS2_22600/AnalyzeActionsUsers.java
src/main/java/faang/school/godbless/BJS2_22600/UserAction.java
src/test/java/faang/school/godbless/BJS2_22600/AnalyzeActionsUsersTest.java

Создал класс UserAction, enum ActionType, класс AnalyzeActionsUsers с методами работы программы и тестовый класс.

BJS2-22600   Анализ активности пользователей в социальной сети

---

src/main/java/ru/kraiush/BJS2_20267/AppDoubleCache.java
src/main/java/ru/kraiush/BJS2_20267/Student.java
src/main/java/ru/kraiush/BJS2_20267/StudentService.java
src/main/java/ru/kraiush/BJS2_20267/Subject.java

BJS2_20267: Double Cache
Problem with last method- delete Subject fro User,!

BJS2_20267: Double cache

---

src/main/java/faang/school/godbless/BJS220352/Main.java

Вспомним школу
👩‍💻 🧠🧠
Условия задачи
1. Дан код:
// Даны три стороны треугольника, вычислить его площадь
Double triangleArea(double a, double b, double c) throws IllegalArgumentException {
Function<Double, Function<Double, Double>> sum = (x) -> y -> x + y;
Function<Double, Function<Double, Double>> mul = (x) -> y -> x * y;
Function<Double, Function<Double, Double>> sub = (x) -> y -> x - y;
Function<Double, Function<Double, Double>> div = (x) -> y -> x / y;
Function<Double, Double> sqrt = (x) -> Math.sqrt(x);
}
2. Используя данные лямбды, вычислить площадь треугольника
3. Можно пользоваться только данными лямбдами. Нельзя использовать арифметические операторы + - * / и пакет Math, и др.
4. Добавить валидацию входных параметров.
Почему эта задача полезна?
В этой задаче мы знакомимся с …

BJS2-20352

---

src/main/java/hogwarts/Main.java
src/main/java/hogwarts/SpellAction.java
src/main/java/hogwarts/SpellCaster.java

…понял почему мой интерфейс вдруг решил возвращать то, что я в него передаю через лямбду без дополнительной логики...

Хогвартс, Хогвартс, наш любимый Хогвартс.

---

src/main/java/faang/school/godbless/meta_universe/Main.java
src/main/java/faang/school/godbless/meta_universe/Notification.java
src/main/java/faang/school/godbless/meta_universe/NotificationManager.java
src/test/java/faang/school/godbless/meta_universe/NotificationManagerTest.java

BJS2-21974

---

src/main/java/faang/school/godbless/BJS222551/ActionType.java
src/main/java/faang/school/godbless/BJS222551/Main.java
src/main/java/faang/school/godbless/BJS222551/User.java
src/main/java/faang/school/godbless/BJS222551/UserAction.java

Анализ активности пользователей в социальной сети
👩‍💻 🧠🧠
Условия задачи
Вам предоставлены данные о пользователях и их действиях на платформе социальной сети. Необходимо использовать Stream API для анализа этих данных и выявления наиболее активных пользователей и популярных тем обсуждения.
Данные представлены в виде списка объектов UserAction, у которых есть поля id юзера, имя юзера, actionType(возможные значения: “post", "comment", "like", "share”), actionDateи content (текст поста или комментария).
Этот список будет передаваться в ваши методы. Вам нужно лишь описать работу с ним. Самостоятельно его создавать не требуется.
Требуется разработать приложение, которое выполняет следующие задачи, используя Stream API:
Найти топ-10 самых активных пользователей (по количеству действий: посты, …

BJS2-22551

---

src/main/java/faang/school/godbless/BJS222421/Employee.java
src/main/java/faang/school/godbless/BJS222421/Main.java

Потренируем StreamAPI 2
👩‍💻 🧠🧠
Условия задачи
Напишите класс со статическими методами:
На вход дан список целых чисел и число. Найдите все уникальные пары чисел, сумма которых равна заданному числу. Порядок следования неважен.
Пример: Input List: [1, 9, 3, 6, 4, 5]
Target Sum: 10
Pairs: [[1, 9], [6, 4]]
На вход получаем мапу с названиями стран и их столицами. Отсортируйте страны по алфавиту, а затем выведите названия их столиц в виде списка.
Получаем список строк и букву в виде char. Отфильтруйте строки, которые начинаются с заданной буквы, и отсортируйте их по длине в порядке возрастания, и верните список этих строк.
Дана мапа, где ключами являются имена людей, а значениями — списки имен их друзей. Найдите все пары людей, которые не являются друзьями, но у них есть общие друзья. Считаем, …

Beksultan2005 bjs2 22421

---

build.gradle
src/main/java/vacancy/analizator/DataAnalyzer.java
src/main/java/vacancy/analizator/Job.java
src/main/java/vacancy/analizator/JobScraper.java
src/main/java/vacancy/analizator/JobStreamProcessor.java
src/main/java/vacancy/analizator/Main.java
src/main/java/vacancy/analizator/Range.java
src/main/java/vacancy/analizator/resources/jobsJSON.txt

Задача Анализ Вакансий
https://faang-school.atlassian.net/browse/BJS2-22771

Анализ вакансий

---

src/main/java/faang/school/godbless/BJS223649/MailSender.java
src/main/java/faang/school/godbless/BJS223649/SenderRunnable.java

Вы работаете в Microsoft!
👩‍💻 🧠
Условия задачи
Вы работаете на проекте, который занимается разработкой почтового клиента, например, Microsoft Outlook.
Сейчас отправление всех сообщений реализовано в один поток. Сообщения от пользователей становятся в очередь, а затем ваш сервис начинает разбирать их по порядку. Вы, как разработчик, активно предлагающий идеи по улучшению ваших продуктов, решаете сделать разбор сообщений параллельным.
Сейчас в очереди накопилось 1000 почтовых сообщений, которые нужно отправить. Необходимо создать 5 потоков, каждый из которых будет отправлять по 200 сообщений:
Создайте класс SenderRunnable, реализующий интерфейс Runnable. Так как каждый поток будет работать только со своей пачкой писем, нам нужно создать объект этого класса, передав туда int startIndex и int …

BJS2-23649

---

src/main/java/multithreading/microsoft/MailSender.java
src/main/java/multithreading/microsoft/SenderRunnable.java

Задача Вы работаете в Майкрософт!
https://faang-school.atlassian.net/browse/BJS2-23680

Вы работаете в Майкрософт!

---

src/main/java/spacex/Main.java
src/main/java/spacex/RocketLaunch.java

Задача Космическая программа SpaceX
https://faang-school.atlassian.net/browse/BJS2-23968

Космическая программа SpaceX

---

src/main/java/ru/kraiush/BJS2_19385/Angel.java
src/main/java/ru/kraiush/BJS2_19385/AppHeroes_of_Might_and_Magic.java
src/main/java/ru/kraiush/BJS2_19385/Battlefield.java
src/main/java/ru/kraiush/BJS2_19385/Creature.java
src/main/java/ru/kraiush/BJS2_19385/Griffin.java
src/main/java/ru/kraiush/BJS2_19385/Hero.java
src/main/java/ru/kraiush/BJS2_19385/Pikeman.java
src/main/java/ru/kraiush/BJS2_19385/Swordman.java

BJS2-19385: Heroes of Might and Magic

BJS2-19385: Heroes of Might and Magic

---

src/main/java/pigs/game/Main.java
src/main/java/pigs/game/players/Pig1Thread.java
src/main/java/pigs/game/players/Pig2Thread.java
src/main/java/pigs/game/players/Pig3Thread.java
src/main/java/pigs/game/players/PigThread.java

Задача Наконец-то нормальная игра
https://faang-school.atlassian.net/browse/BJS2-23357

Наконец-то нормальная игра

---

src/main/java/walmart/CashierThread.java
src/main/java/walmart/Item.java
src/main/java/walmart/Main.java

Задача Очередь в Walmart
https://faang-school.atlassian.net/browse/BJS2-23993

Очередь в Walmart

---

src/main/java/helping/Main.java
src/main/java/helping/Person.java
src/main/java/helping/PersonNamePrinter.java

Задача Помогите коллеге
https://faang-school.atlassian.net/browse/BJS2-23951
В условии написано вывести места работы, а в задании вывести имена. На всякий случай вывел и то, и то.

Помогите коллеге

---

src/main/java/faang/school/godbless/BJS2_23681/MailSender.java
src/main/java/faang/school/godbless/BJS2_23681/SenderRunnable.java

Пул потоков сознательно был создан не через `Thread[] threads = new Thread[5];`. В видео-лекции Влад не рекомендовал создавать потоки подобным образом, только в качестве тренировки. Логика с использованием класса executor вроде осталось такой же.

You work for Microsoft

---

src/main/java/faang/school/godbless/BJS223397/Archer.java
src/main/java/faang/school/godbless/BJS223397/Army.java
src/main/java/faang/school/godbless/BJS223397/Mage.java
src/main/java/faang/school/godbless/BJS223397/Main.java
src/main/java/faang/school/godbless/BJS223397/Swordsman.java
src/main/java/faang/school/godbless/BJS223397/Unit.java
src/main/java/faang/school/godbless/BJS223397/UnitThread.java

👩‍💻 🧠
Условия задачи
Вы являетесь командующим армией героев меча и магии. Ваша задача состоит в том, чтобы определить силу армии, состоящей из различных подразделений, таких как лучники, мечники, маги и т.д. Поскольку ваша армия огромна, вам необходимо распределить задачу расчёта общей силы среди нескольких потоков.
Цель: Напишите программу, которая моделирует армию героев меча и магии и определяет общую силу армии с использованием распараллеливания.
Требования:
Создайте классы Archer, Swordsman, Mage и дополнительные классы для других подразделений армии, если требуется. Все эти классы должны иметь поле power для хранения силы каждого бойца.
Создайте класс Army, который содержит список всех подразделений, а также метод calculateTotalPower(), …

Beksultan2005 bjs2 23397

---

src/main/java/faang/school/godbless/javamultithreading/task2/FoodDeliveryTask.java
src/main/java/faang/school/godbless/javamultithreading/task2/GriffinsFoodDelivery.java

add FoodDeliveryTask

---

src/main/java/faang/school/godbless/javamultithreading/task5/Chore.java
src/main/java/faang/school/godbless/javamultithreading/task5/WeasleyFamily.java

add WeasleyFamily

---

build.gradle
src/main/java/faang/school/godbless/BJS222750/DataAnalyzer.java
src/main/java/faang/school/godbless/BJS222750/JSONJobScraper.java
src/main/java/faang/school/godbless/BJS222750/Job.java
src/main/java/faang/school/godbless/BJS222750/JobScraper.java
src/main/java/faang/school/godbless/BJS222750/JobStreamProcessor.java
src/main/java/faang/school/godbless/BJS222750/TrendGranularity.java

Анализатор вакансий
👩‍💻 🧠🧠🧠
Условия задачи
Цель: Собирать и анализировать данные о вакансиях с различных платформ, чтобы выявить наиболее востребованные навыки, опыт работы и тенденции изменения рынка труда в отрасли.
1. Создать класс Job, представляющий собой модель вакансии с полями, такими как название позиции, требования к кандидатам (List<String>), предлагаемая зарплата, локация, дата добавления вакансии. 
2. Создать класс JobScraper: Базовый класс для парсеров, содержащий общие методы для извлечения данных о вакансиях из различных источников. Напишите одну его реализацию, которая будет преобразовывать String в формате JSON в объект типа Job.
3. Создать JobStreamProcessor. Это класс, отвечающий за обработку потока данных о вакансиях с использованием Stream API:
должен иметь метод, …

Beksultan2005 bjs2 22750

---

src/main/java/faang/school/godbless/BJS223449/King.java
src/main/java/faang/school/godbless/BJS223449/Knight.java
src/main/java/faang/school/godbless/BJS223449/Trial.java

Турнир в Королевской гавани
👩‍💻 🧠
Условия задачи
Король Роберт Баратеон собирается провести огромный турнир в Королевской Гавани. В турнире будет участвовать множество рыцарей, и каждый рыцарь должен пройти через серию испытаний, чтобы показать свою силу и мастерство. Король Роберт решил использовать ExecutorService для распараллеливания выполнения этих испытаний — это вы ему подсказали, конечно. Ну и писать, значит, тоже вам…
Создайте класс Knight, который будет представлять рыцаря. Объявите поля name типа String и trials типа List<Trial>, которое будет содержать список испытаний. Создайте конструктор, который принимает на вход имя рыцаря.
Создайте класс Trial, который будет представлять одно испытание. Объявите поля knightName типа String и trialName типа String, который будут содержать …

BJS2-23449

---

src/main/java/faang/school/godbless/BJS223950/FoodDeliveryTask.java
src/main/java/faang/school/godbless/BJS223950/GriffinsFoodDelivery.java

Накормите Питера Гриффина
👩‍💻 🧠
Условия задачи
В мультсериале «Гриффины» главным героям приходится постоянно бороться со своими проблемами и заботами. Одной из таких забот является получение пищи. Ваша задача — написать программу, которая будет помогать Гриффинам получать еду. Нужно запустить 3 задачи, каждая из которых имитирует получение еды персонажем, путем ожидания в течение случайного количества секунд (от 1 до 5). Тип еды также выбирается случайно из предопределенного списка. В конце каждой задачи выводится информация о том, какой персонаж получил сколько еды какого типа.
1. Создайте класс FoodDeliveryTask, который реализует интерфейс Runnable. Здесь нужно два поля:  
private String character;
private int foodAmount;
Добавьте соответствующий конструктор.
Также здесь необходим метод …

Beksultan2005 bjs2 23950

---

src/main/java/faang/school/godbless/task23455/Archer.java
src/main/java/faang/school/godbless/task23455/Army.java
src/main/java/faang/school/godbless/task23455/Mage.java
src/main/java/faang/school/godbless/task23455/Main.java
src/main/java/faang/school/godbless/task23455/Swordsman.java

BJS2 -23455 - Распределенная армия героев меча и магии

BJS2-23455 - Распределенная армия героев меча и магии

---

build.gradle
src/main/java/faang/school/godbless/AnalysisVacantion/DataAnalyzer.java
src/main/java/faang/school/godbless/AnalysisVacantion/Job.java
src/main/java/faang/school/godbless/AnalysisVacantion/JobScraper.java
src/main/java/faang/school/godbless/AnalysisVacantion/JobStreamProcessor.java
src/main/java/faang/school/godbless/AnalysisVacantion/Main.java

Добавил jobScrapper, который содержит метод парсинга json в объект job. JobStreamProcessor занимается парсингом потока Stringов в job. В классе DataAnalyzer методы для сбора данных о вакансиях

Добавил зависимость, что бы jackson мог работать с LocalDateTime.

---

src/main/java/faang/school/godbless/BJS224036/Chore.java
src/main/java/faang/school/godbless/BJS224036/WeasleyFamily.java

They were very nice but extremely poor
👩‍💻 🧠
Условия задачи
В семье Уизли всегда очень много дел по дому. Для магического выполнения этих задач Перси решил создать программу, которая будет использовать пул потоков с помощью метода newCachedThreadPool().
Создайте класс Chore, который реализует интерфейс Runnable.
В классе Chore объявите поле chore типа String, которое будет содержать название задачи. Создайте конструктор для класса Chore, который принимает на вход название задачи.
В методе run() класса Chore реализуйте логику выполнения задачи, используя методы Thread.currentThread().getName() для получения имени потока и Thread.sleep() для имитации выполнения задачи.
В методе main() класса WeasleyFamily создайте массив chores, который будет содержать список задач, которые нужно выполнить. …

BJS2-24036

---

src/main/java/faang/school/godbless/BJS224107/BigBangTheory.java
src/main/java/faang/school/godbless/BJS224107/Task.java

The Big Bang Theory
👩‍💻 🧠
Условия задачи
Представим, что Шелдон, Леонард, Говард и Раджеш работают над научным проектом. Им нужно выполнить несколько заданий, и они решают распределить задания между собой, чтобы ускорить работу. Вам нужно написать программу, которая создаёт пул из четырех потоков с помощью класса ExecutorService и распределяет выполнение заданий между ними:
Шелдон — подготовка теории.
Леонард — моделирование эксперимента.
Говард — разработка инструментов.
Раджеш — анализ данных.
Создать класс Task, который реализует интерфейс Runnable.
В классе Task создать два поля: name (имя исполнителя) и task (задание) и создать конструктор.
Реализовать метод run класса Task, который будет выводить сообщение о начале выполнения задания и имитировать выполнение задачи с помощью метода …

BJS2-24107

---

src/main/java/faang/school/godbless/BJS2_24100/FoodDeliveryTask.java
src/main/java/faang/school/godbless/BJS2_24100/GriffinsFoodDelivery.java

Создал классы: FoodDeliveryTask и GriffinsFoodDelivery с демонстрацией работы.

BJS2-24100   Накормите Питера Гриффина

---

src/main/java/faang/school/godbless/bbt/BigBangTheory.java
src/main/java/faang/school/godbless/bbt/Task.java

@20cognosce Подскажи, пожалуйста, правильно ли я понял, как ожидать завершения всех задач из executorService в основном потоке (awaitTermination) - этот реквест сразу после исправлений над предыдущим (Family Guy).

BJS2-24327 - Big Bang Theory

---

src/main/java/faang/school/godbless/task24226/Chore.java
src/main/java/faang/school/godbless/task24226/WeasleyFamily.java

BJS2-24226 - They were very nice but extremely poor

BJS2-24226 - They were very nice but extremely poor

---

src/main/java/ru/kraiush/BJS2_19557/AppCountingStudentsAbsenteeism.java
src/main/java/ru/kraiush/BJS2_20242/AppLRUCache.java
src/main/java/ru/kraiush/lambda/BJS2_21037/DruidProducer.java
src/main/java/ru/kraiush/lambda/BJS2_21037/DruidReceiver.java

BJS2-21037: update

---

src/main/java/faang/school/godbless/BJS2_24031/CashierThread.java
src/main/java/faang/school/godbless/BJS2_24031/Main.java

В задании было сказано работать с массивами и в доп материалах указан массив customers. Поэтому я не стал создавать класс Item для товара.

BJS2-24031 Очередь в Walmart

---

src/main/java/faang/school/godbless/BJS2_24485/Music.java
src/main/java/faang/school/godbless/BJS2_24485/Player.java

Созданы классы Music, Player c с демонстрацией работы программы.

BJS2-24485   Блокировка Spotify

---

src/main/java/faang/school/godbless/BJS2_24266/Music.java
src/main/java/faang/school/godbless/BJS2_24266/Player.java

Правильно ли понял, что в данной задаче, как таковой, нет параллельного выполнения, т.к. все методы класса синхронизированы и потоки лишь могут рандомно запуститься, не не выполняются одновременно?

BJS2-24266 Блокировка Spotify

---

src/main/java/BJS2_22025/Main.java
src/main/java/BJS2_22025/Notification.java
src/main/java/BJS2_22025/NotificationManager.java

Допишу доп метод (функционал) как чуть более разберусь в теме, на первичное ревью

Initial Commit for MetaVerse

---

src/main/java/faang/school/godbless/BJS2_22056/Main.java
src/main/java/faang/school/godbless/BJS2_22056/Notification.java
src/main/java/faang/school/godbless/BJS2_22056/NotificationManager.java

Не стал делать 5 пункт задачи, к сожалению нет времени на идеи, нужно переходить к стримам

1 версия решения задачи: Meta-вселенная?

---

src/main/java/faang/school/godbless/BJS2_24200/Main.java
src/main/java/faang/school/godbless/BJS2_24200/Person.java
src/main/java/faang/school/godbless/BJS2_24200/PersonNamePrinter.java

Тестил на разных количествах потоков и данных и все равно результат примерно одинаковый. Что я дам 500к объектов 1 потоку или что дам их 5 потокам - скорость +- одна. Странно как-то

BJS2-24200 Помогите коллеге

---

src/main/java/faang/school/godbless/BJS223887/City.java
src/main/java/faang/school/godbless/BJS223887/CityWorker.java
src/main/java/faang/school/godbless/BJS223887/Location.java
src/main/java/faang/school/godbless/BJS223887/Monster.java
src/main/java/faang/school/godbless/BJS223887/Witcher.java

Путь пальцем проложи…
👩‍💻 🧠🧠
Условия задачи
Ведьмак Геральт должен путешествовать по различным городам и убивать монстров. Для этого он использует магическую карту, которая позволяет определять оптимальный маршрут между городами и наименьшее количество времени, затраченного на путешествия.
Давайте посмотрим, как работает эта магическая карта!
1. Создать класс Monster, который будет содержать информацию о монстрах: имя и местоположение. Добавить конструктор и геттеры.
2. Создать класс City, который будет содержать информацию о городах: имя, местоположение (класс Location c полями-координатами x, y) и расстояние от местоположения ведьмака до каждого города. По умолчанию Геральт находится в Каэр Морхене. Конструктор и геттеры.
3. Создать класс CityWorker, который будет реализовывать …

Beksultan2005 bjs2 23887

---

src/main/java/ru/kraiush/lambda/BJS2_21169/Actionhandler.java
src/main/java/ru/kraiush/lambda/BJS2_21169/AppWeHandleErrorsBeautifully.java
src/main/java/ru/kraiush/lambda/BJS2_21169/ErrorHandler.java
src/main/java/ru/kraiush/lambda/BJS2_21169/ExceptionHandler.java
src/main/java/ru/kraiush/lambda/BJS2_21169/RemoteService.java
src/main/java/ru/kraiush/lambda/BJS2_21169/SomeService.java

BJS2-21169: We Handle Errors Beautifully!

BJS2-21169: We Handle Errors Beautifully!

---

src/main/java/youtube/Main.java
src/main/java/youtube/Video.java
src/main/java/youtube/VideoManager.java

Задача Счетчик просмотров Youtube
https://faang-school.atlassian.net/browse/BJS2-24294

Счетчик просмотров Youtube

---

src/main/java/tamagochi/Main.java
src/main/java/tamagochi/TamagochiVlad.java
src/main/java/tamagochi/VladContoller.java

Задача Тамагочи Влад
https://faang-school.atlassian.net/browse/BJS2-24201

Тамагочи Влад

---

src/main/java/faang/school/godbless/task/multithreading/finger/way/City.java
src/main/java/faang/school/godbless/task/multithreading/finger/way/CityWorker.java
src/main/java/faang/school/godbless/task/multithreading/finger/way/ConsoleOutputExample.txt
src/main/java/faang/school/godbless/task/multithreading/finger/way/Distance.java
src/main/java/faang/school/godbless/task/multithreading/finger/way/Location.java
src/main/java/faang/school/godbless/task/multithreading/finger/way/Monster.java
src/main/java/faang/school/godbless/task/multithreading/finger/way/Witcher.java

Расстояние от точки А до точки В на координатах рассчитываю по катетам

Путь пальцем проложи… BJS2-23883

---

src/main/java/faang/school/godbless/BJS2_24560/GooglePhotosAutoUploader.java
src/main/java/faang/school/godbless/BJS2_24560/Main.java

Созданы классы GooglePhotosAutoUploader, Main c с демонстрацией работы программы.

BJS2-24560   Google Photo sync

---

src/main/java/faang/school/godbless/BJS224396/Main.java
src/main/java/faang/school/godbless/BJS224396/Video.java
src/main/java/faang/school/godbless/BJS224396/VideoManager.java

Счетчик просмотров на YouTube
👩‍💻 🧠🧠
Условия задачи
Вы являетесь разработчиком YouTube и вам поручено написать класс для управления просмотрами видео. Класс VideoManager имеет следующие методы:
public void addView(String videoId) — добавляет один просмотр для видео с заданным идентификатором (videoId);
public int getViewCount(String videoId) — возвращает количество просмотров для видео с заданным идентификатором (videoId).
Однако, вы заметили, что при большом количестве пользователей, параллельно просматривающих одно и то же видео, возможно состояние гонки (race condition) при доступе к методам addView() и getViewCount(). Это может привести к неправильному подсчету количества просмотров для видео. Нужно это исправить!
Создайте класс VideoManager с приватным полем viewsMap, которое будет …

Beksultan2005 bjs2 24396

---

src/main/java/faang/school/godbless/BJS2_24167/House.java
src/main/java/faang/school/godbless/BJS2_24167/Main.java
src/main/java/faang/school/godbless/BJS2_24167/User.java

Немного запутанное задание, в условии было сказано добавить оповещение всех в addRole, но вроде как за освобождение роли отвечает removeRole. Поэтому я добавил notifyAll в метод removeRole

BJS2-24167 Железный трон любой ценой

---

src/main/java/faang/school/godbless/BJS223727/Food.java
src/main/java/faang/school/godbless/BJS223727/House.java
src/main/java/faang/school/godbless/BJS223727/Room.java

Mice are very nice!
👩‍💻 🧠🧠
Условия задачи
Том и Джерри живут в огромном доме. У них есть задача — собрать всю еду в доме. Нужно распараллелить выполнение этой задачи на несколько потоков с использованием newScheduledThreadPool.
Класс House содержит список всех комнат и еды, которая есть в доме. Нам нужно создать пять потоков, каждый из которых будет собирать еду из двух комнат, запускаясь с интервалом в 30 секунд. Когда все потоки закончат работу, программа должна вывести сообщение «Еда в доме собрана!».
Создайте класс House, который будет содержать список комнат и еды, а также метод для сбора еды из комнат.
В классе House создайте метод main, который будет запускать пул потоков и назначать каждому потоку задачу для сбора еды из двух комнат.
Создайте класс Room, который будет содержать …

Beksultan2005 bjs2 23727

---

src/main/java/heart/Chat.java
src/main/java/heart/ChatManager.java
src/main/java/heart/Main.java
src/main/java/heart/Message.java
src/main/java/heart/User.java
src/main/java/heart/UserList.java

Задача Matters of the heart
https://faang-school.atlassian.net/browse/BJS2-24334
Наворотил ужаса, адекватно не получилось сделать.

Matters of the heart

---

src/main/java/threadtwo/three/Boss.java
src/main/java/threadtwo/three/Main.java
src/main/java/threadtwo/three/Player.java

Я не запутался. У меня joinBattle работает как надо или нет?
Вроде, все проходят по списку пользователей, но как-то неправильно по ощущениям вывод сообщений происходит.
Player Tom создал лобби.
Цель: Победить босса Diablo
Player Mary присоединился.
Текущее число игроков в лобби:2
Это верно, а дальше...
Mary вышел из лобби. Текущее число игроков: 1
Лобби полное. Вы в очереди на подключение.  ------- почему тут выводится, что лобби полное.
Player Maks присоединился.

Решение задачи Supercow!

---

src/main/java/faang/school/godbless/BJS2_24060/Game.java
src/main/java/faang/school/godbless/BJS2_24060/GeneralStatistics.java
src/main/java/faang/school/godbless/BJS2_24060/Main.java
src/main/java/faang/school/godbless/BJS2_24060/Player.java

Я понимаю, что выглядит очень громоздко, но как сделать лучше я не знаю(
Вроде бы нашел все уязвимые места где могут данные повредится, но есть один момент в методе die.  Мне кажется, что если поток попадет в строки 35-36 и в этот момент другой поток начнет работать и выполнит update, то уже score будет поврежденным, ибо по сути игра кончилась, но после её завершения выполнился чей-то update несмотря на проверку в 18 - 21 (поток с update заработал после проверки на состояние потока)

BJS2-24060 Bro Force!

---

src/main/java/faang/school/godbless/BJS224523/Music.java
src/main/java/faang/school/godbless/BJS224523/Player.java

Блокировка Spotify
👩‍💻 🧠
Условия задачи
В Spotify есть функция "Group Session", которая позволяет нескольким пользователям управлять воспроизведением музыки в реальном времени, на одном устройстве или на разных устройствах. Давайте реализуем её! Мы хотим сделать так, чтобы несколько пользователей могли управлять воспроизведением музыки на разных устройствах одновременно, но при этом избежать ситуаций, когда один пользователь перебивает другого.
Когда один пользователь изменяет состояние воспроизведения, он должен сначала захватить блокировку, чтобы другой пользователь не мог изменить это состояние в то же время. После того как состояние воспроизведения изменено, блокировка освобождается и другой пользователь может захватить её и изменить состояние на своём устройстве.
Создайте класс …

BJS2-24523

---

src/main/java/faang/school/godbless/droids/Droid.java
src/main/java/faang/school/godbless/droids/DroidMessageEncryptor.java
src/test/java/faang/school/godbless/droids/DroidTest.java

Сделал ограничение для алфавита. Логика if-else, это если дошли до сдвига ниже Aa или выше Zz

BJS2-20991 - Секреты дроидов - шифрование и дешифрование через сдвиг

---

src/main/java/faang/school/godbless/sword_and_magic/Army.java
src/main/java/faang/school/godbless/sword_and_magic/Main.java
src/main/java/faang/school/godbless/sword_and_magic/UnitThread.java
src/main/java/faang/school/godbless/sword_and_magic/units/Archer.java
src/main/java/faang/school/godbless/sword_and_magic/units/Mage.java
src/main/java/faang/school/godbless/sword_and_magic/units/Swordsman.java
src/main/java/faang/school/godbless/sword_and_magic/units/Unit.java

@20cognosce Прочитал твое описание в Kraken ревью чате для этой задачи, надеюсь я тебя правильно понял.

BJS2-23530 - Распределенная армия меча и магии

---

src/main/java/faang/school/godbless/BJS2_24443/Main.java
src/main/java/faang/school/godbless/BJS2_24443/VideoManager.java

Созданы классы VideoManager, Main с демонстрацией работы программы.

BJS2-24443   Счетчик просмотров на YouTube

---

src/main/java/faang/school/godbless/BJS2_24250/House.java
src/main/java/faang/school/godbless/BJS2_24250/Main.java
src/main/java/faang/school/godbless/BJS2_24250/User.java

Созданы классы House, User, Main с демонстрацией работы программы.

BJS2-24250   Железный трон любой ценой

---

src/main/java/fan/Main.java
src/main/java/fan/ResultConsumer.java
src/main/java/fan/SquareRequest.java

Задача Fan Out - Fan In
https://faang-school.atlassian.net/browse/BJS2-24990

Fan Out - Fan In

---

src/main/java/faang/school/godbless/BJS224176/House.java
src/main/java/faang/school/godbless/BJS224176/Main.java
src/main/java/faang/school/godbless/BJS224176/Role.java
src/main/java/faang/school/godbless/BJS224176/User.java

Железный трон любой ценой
👩‍💻 🧠🧠
Условия задачи
Предположим, что мы разрабатываем приложение для сериала Игра Престолов, где пользователи могут присоединиться к различным домам и бороться за контроль над Вестеросом. Когда пользователь подключается к дому, он должен выбрать роль, которую он хочет играть в этом доме: лорд, рыцарь, маг и т.д.
Однако, количество доступных ролей может быть ограничено, и если все роли уже заняты, пользователь должен ожидать, пока один из игроков не покинет свою роль.
Создайте класс House, который будет представлять дом в Вестеросе. Добавьте в класс поля, хранящие список доступных ролей и количество доступных ролей.
Создайте класс User, который будет представлять пользователя в приложении. Добавьте в класс поля, хранящие имя пользователя, дом, в который он …

Beksultan2005 bjs2 24176

---

src/main/java/faang/school/godbless/sprint3/BJS2_24191/InterruptedVladException.java
src/main/java/faang/school/godbless/sprint3/BJS2_24191/TamagotchiVlad.java
src/main/java/faang/school/godbless/sprint3/BJS2_24191/VladController.java
src/main/java/faang/school/godbless/sprint3/BJS2_24191/VladMain.java
src/main/java/faang/school/godbless/sprint3/BJS2_24191/VladThread.java

Паша не бей палками, это такая задумка)

VladTamagothi BJS2-24191 done

---

src/main/java/ru/kraiush/threads/BJS2_23817/AppTournamentAtKingLanding.java
src/main/java/ru/kraiush/threads/BJS2_23817/Trial.java
src/main/java/ru/kraiush/threads/BJS2_23877/AppMiceAreVeryNice.java
src/main/java/ru/kraiush/threads/BJS2_23877/Food.java
src/main/java/ru/kraiush/threads/BJS2_23877/Missia.java
src/main/java/ru/kraiush/threads/BJS2_23877/Room.java

Some problem with sleep() in stream() ?!?

BJS2-23877: Mice Are Very Nice

---

src/main/java/faang/school/godbless/BJS2_24270/Bro.java
src/main/java/faang/school/godbless/BJS2_24270/Game.java
src/main/java/faang/school/godbless/BJS2_24270/Main.java

Созданы классы Game, Bro, Main с демонстрацией работы программы.

BJS2-24270   Bro Force!

---

src/main/java/faang/school/godbless/spotify/Main.java
src/main/java/faang/school/godbless/spotify/Player.java

@20cognosce Решил добавить немного реалистичности с плейлистом List<String>, а также написал приватный статический класс для более комфортного вывода между тредами. Если бы где-то еще пришлось его использовать, вынес бы в обычный класс - оставил в том же файле что и Main ради удобства. Жду пинков)

BJS2-24571 - Блокировка Spotify

---

src/main/java/computepi/Main.java
src/main/java/computepi/Point.java

Задача Вычислим число ПИ
https://faang-school.atlassian.net/browse/BJS2-25109

Вычислим число ПИ

---

src/main/java/faang/school/godbless/BJS2_25080/Difficulty.java
src/main/java/faang/school/godbless/BJS2_25080/Main.java
src/main/java/faang/school/godbless/BJS2_25080/Player.java
src/main/java/faang/school/godbless/BJS2_25080/Quest.java
src/main/java/faang/school/godbless/BJS2_25080/QuestSystem.java

Всего лишь ЧУТКА ушел от условия задачи - перенес вывод результата квеста в сам startQuest. Как по мне так куда лучше нежели ждать потоку main, пока завершатся все квесты для вывода их результата

BJS2-25080 WOW

---

src/main/java/faang/school/godbless/BJS2_25043/Main.java
src/main/java/faang/school/godbless/BJS2_25043/ResultConsumer.java
src/main/java/faang/school/godbless/BJS2_25043/SquareRequest.java

Были проблемы с инетом, поэтому так много одинаковых коммитов xD

Amirhan Fan out - Fan In

---

src/main/java/faang/school/godbless/BJS2_24668/Main.java
src/main/java/faang/school/godbless/BJS2_24668/TwitterAccount.java
src/main/java/faang/school/godbless/BJS2_24668/TwitterSubscriptionSystem.java

Я правильно понимаю, что тут 2 варианта решения - через synchronized, как у меня, либо через Atomic переменную? Если да, то какой из вариантов будет лучше с точки зрения производительности?

BJS2-24668 Становимся celebrity в Twitter

---

src/main/java/celebrity/Main.java
src/main/java/celebrity/TwitterAccount.java
src/main/java/celebrity/TwitterSubscriptionSystem.java

Задача Становимся celebrity в Twitter
https://faang-school.atlassian.net/browse/BJS2-24789

Становимся celebrity в Twitter

---

src/main/java/facebook/notifications/Main.java
src/main/java/facebook/notifications/Notification.java
src/main/java/facebook/notifications/NotificationManager.java

Задача Рассылаем уведомления Facebook
https://faang-school.atlassian.net/browse/BJS2-24755

Рассылаем уведомления Facebook

---

src/main/java/faang/school/godbless/task24871/Main.java
src/main/java/faang/school/godbless/task24871/MasterCardService.java

BJS2 - 24871 - Асинхронность и Future

BJS2-24871 - Асинхронность и Future

---

src/main/java/carry/Inventory.java
src/main/java/carry/Item.java
src/main/java/carry/Main.java

Задача Carry отожрался
https://faang-school.atlassian.net/browse/BJS2-25035

Carry отожрался

---

src/main/java/faang/school/godbless/BJS2_24810/Main.java
src/main/java/faang/school/godbless/BJS2_24810/Order.java
src/main/java/faang/school/godbless/BJS2_24810/OrderProcessor.java

Создал классы Order, OrderProcessor, Main.

BJS2-24810   Собираем заказы в Amazon

---

src/main/java/animals/care/Donation.java
src/main/java/animals/care/Main.java
src/main/java/animals/care/Organization.java

Задача Поддержим животных
https://faang-school.atlassian.net/browse/BJS2-25253

Поддержим животных

---

src/main/java/superheroes/battle/Main.java
src/main/java/superheroes/battle/Pair.java
src/main/java/superheroes/battle/Superhero.java
src/main/java/superheroes/battle/SuperheroBattle.java

Задача Superheroes battle
https://faang-school.atlassian.net/browse/BJS2-24621

Superheroes battle

---

src/main/java/faang/school/godbless/BJS2_25120/MagicalTournament.java
src/main/java/faang/school/godbless/BJS2_25120/School.java
src/main/java/faang/school/godbless/BJS2_25120/Student.java
src/main/java/faang/school/godbless/BJS2_25120/Task.java
src/main/java/faang/school/godbless/BJS2_25120/Tournament.java

Созданы классы Student, School, Task, Tournament, MagicalTournament.

BJS2-25120   Турнир трех волшебников

---

src/main/java/faang/school/godbless/bjs2_24947/MagicalTournament.java
src/main/java/faang/school/godbless/bjs2_24947/School.java
src/main/java/faang/school/godbless/bjs2_24947/Student.java
src/main/java/faang/school/godbless/bjs2_24947/Task.java
src/main/java/faang/school/godbless/bjs2_24947/Tournament.java

Получается, что тут не обязательно использовать `CompletableFuture<School>` и `CompletableFuture.supplyAsync()`, потому что мы потом эти школы, которые в результатах CompletableFuture, не используем никак?
И можно просто `CompletableFuture<Void>` и `CompletableFuture.runAsync()`?

BJS2-24947 The Triwizard Tournament

---

src/main/java/faang/school/godbless/task/multithreading/metters/of/the/hearts/Chat.java
src/main/java/faang/school/godbless/task/multithreading/metters/of/the/hearts/ChatManager.java
src/main/java/faang/school/godbless/task/multithreading/metters/of/the/hearts/ConsoleOutputExample.txt
src/main/java/faang/school/godbless/task/multithreading/metters/of/the/hearts/Main.java
src/main/java/faang/school/godbless/task/multithreading/metters/of/the/hearts/User.java
src/main/java/faang/school/godbless/task/multithreading/metters/of/the/hearts/UserList.java

Здесь пришлось поставить блок, я так и не понял как сделать что бы при одновременном поиске в нескольких потоках, не создавалось несколько чатов для оного пользователя:
```
public boolean startChat(User user) {
synchronized (this) {
```
**Это вообще возможно сделать? Что бы несколько потоков искали одновременно**
- Пользователь изъявляет желание найти чат, и переводи флаг в поиск чата
- И все кто хотят найти, по очереди заглядывают в список онлайн пользователей
- Если есть кто так же хочет в чат, создается пара, и флаги деактивируются
- Но если никто нет желающих, пользователь переводится в режим ожидания по таймеру
- Ждет до окончания отсчета, либо его будит другой пользователь и новая пара готова
*В логах аномалий нет, на вид все работает исправно*

Matters of the heart BJS2-24302

---

src/main/java/faang/school/godbless/BJS2_25130/Main.java
src/main/java/faang/school/godbless/BJS2_25130/Potion.java

BJS2-25130   Качаем алхимию

---

src/main/java/bot/Main.java
src/main/java/bot/TelegramBot.java

Задача Telegram-bot
https://faang-school.atlassian.net/browse/BJS2-24419

Telegram-bot

---

src/main/java/factorial/Factorial.java
src/main/java/factorial/Main.java

Задача Великий и ужасный факториал!
https://faang-school.atlassian.net/browse/BJS2-24688

Великий и ужасный факториал!

---

src/main/java/crow/CrowFailedException.java
src/main/java/crow/Kingdom.java
src/main/java/crow/Main.java

Задача Пошлите ворона!
https://faang-school.atlassian.net/browse/BJS2-24788

Пошлите ворона!

---

src/main/java/faang/school/godbless/BJS2_24966/Inventory.java
src/main/java/faang/school/godbless/BJS2_24966/Item.java
src/main/java/faang/school/godbless/BJS2_24966/Main.java

Не стал усложнять методы getItemFromChest(), getItemFromShop()

BJS2-24966 Carry отожрался

---

src/main/java/faang/school/godbless/BJS224566/GooglePhotosAutoUploader.java
src/main/java/faang/school/godbless/BJS224566/Main.java
src/main/java/faang/school/godbless/Example/Game.java

Google Photo sync
👩‍💻 🧠
Условия задачи
Итак, вы разработчик в Google. У вас есть приложение для автоматической загрузки фотографий в Google Photos. Приложение загружает фотографии из папки на компьютере пользователя и загружает их на сервер Google Photos. Однако, если в папке на компьютере пользователя нет новых фотографий, приложение должно перейти в режим ожидания и продолжить загрузку, когда в папку будут добавлены новые фотографии.
Создаем класс GooglePhotosAutoUploader c объектом lock для синхронизации потоков.
Создаем список photosToUpload, в котором будут храниться пути к фотографиям, которые нужно загрузить.
Создаем метод startAutoUpload(), где цикле проверяем, если список photosToUpload пуст, то ждём, пока не добавятся новые фотографии.
Когда в список photosToUpload добавляются …

Beksultan2005 bjs2 24566

---

src/main/java/threadtwo/five/Video.java
src/main/java/threadtwo/five/VideoManager.java

Тут нужно обязательно использовать map? Сначала сделал и потом открыл подсказку. 
Получается тогда в addView и getViewCount нужно делать synchronized(map), но без wait и notify просто, чтобы одновременно не меняли значения мапы?

Решение задачи Счетчик просмотров на YouTube

---

src/main/java/faang/school/godbless/TrainingAlchemy/Potion.java

Complete "Potions

---

src/main/java/faang/school/godbless/BJS2_25530/Comment.java
src/main/java/faang/school/godbless/BJS2_25530/Main.java
src/main/java/faang/school/godbless/BJS2_25530/Post.java
src/main/java/faang/school/godbless/BJS2_25530/PostService.java

Вообще не понимаю зачем тут нужен volatile. Он ведь не обеспечивает атомарность, а нам именно это нужно в решении

BJS2-25530 Оставляем комментарий

---

src/main/java/faang/school/godbless/sprint4/wizard/Main.java
src/main/java/faang/school/godbless/sprint4/wizard/School.java
src/main/java/faang/school/godbless/sprint4/wizard/Student.java
src/main/java/faang/school/godbless/sprint4/wizard/Task.java
src/main/java/faang/school/godbless/sprint4/wizard/Tournament.java

Решение использует тот факт, что все школы должны закончить каждый текущий этап для того, чтобы началась асинхронная обработка следующего этапа.

BJS2-25105 - Турнир Трех Волшебников

---

src/main/java/faang/school/godbless/sprint4/calculate_pi/Main.java
src/main/java/faang/school/godbless/sprint4/calculate_pi/RandomPoint.java

Обычное решение с последовательными стримами, завтра постараюсь переделать на параллельные стримы без join() основного потока.

BJS2-25202 - Calculate PI

---

src/main/java/faang/school/godbless/substationsMonitoring/Main.java
src/main/java/faang/school/godbless/substationsMonitoring/MonitoringSystem.java
src/main/java/faang/school/godbless/substationsMonitoring/Sensor.java
src/main/java/faang/school/godbless/substationsMonitoring/SensorData.java
src/main/java/faang/school/godbless/substationsMonitoring/Substation.java

Описание: 
Создаются электростанции -> в них добавляются сенсоры -> электростанции добавляются в систему мониторинга -> сенсоры начинают работу и получать данные каждую секунду, передавая их в объект SensorData, который как только получает новые показатели сразу считает среднее показаний этого сенсора за все время -> раз в 30 секунд электростанции получают новые данные из объекта SensorData -> раз в минуту система мониторинга получает средние данные по каждой электростанции и печатает отчет

BJS2-25380 Мониторинг электроподстанций

---

src/main/java/faang/school/godbless/wither/monster/map/City.java
src/main/java/faang/school/godbless/wither/monster/map/CityWorker.java
src/main/java/faang/school/godbless/wither/monster/map/Location.java
src/main/java/faang/school/godbless/wither/monster/map/Monster.java
src/main/java/faang/school/godbless/wither/monster/map/Witcher.java

С количеством потоков поигрался. Получается что делать потоков больше чем задач нет смысла, т.к время работы при этом не меняется практически. Если делать потоков меньше чем задач, то программа работает дольше

nf BJS2-23923 witcher herald profiling

---

src/main/java/faang/school/godbless/BJS224316/Boss.java
src/main/java/faang/school/godbless/BJS224316/Main.java
src/main/java/faang/school/godbless/BJS224316/Player.java

Supercow!
👩‍💻 🧠
Условия задачи
Все разработчики должны иногда отдыхать. Давайте напишем игру, которая поможет другим развлечься.
Supercow — игра, где игроки могут сражаться с боссами на различных уровнях. Каждый босс имеет свой уровень сложности и максимальное количество игроков, которые могут сражаться с ним одновременно. Когда игроки подключаются к боссу, они должны сначала проверить, есть ли для игрока место в этом сражении с боссом, и только после этого они могут присоединиться к сражению. Если все слоты заняты, игроки должны ждать, пока один из них завершит сражение.
Создайте класс Boss с полями maxPlayers и currentPlayers.
Реализуйте метод joinBattle(Player player), который будет использоваться игроками для присоединения к сражению с боссом. В методе используйте блок synchronized …

BJS2-24316

---

src/main/java/faang/school/godbless/BJS2_24548/Main.java
src/main/java/faang/school/godbless/BJS2_24548/VideoManager.java

не могу понять, как сделать вывод последовательным, а то общее кол-вол верное, а выводятся они как попало

Счетчик просмотров на YouTube

---

src/main/java/faang/school/godbless/BJS2_25280/DataCollector.java
src/main/java/faang/school/godbless/BJS2_25280/Main.java
src/main/java/faang/school/godbless/BJS2_25280/ReportGenerator.java
src/main/java/faang/school/godbless/BJS2_25280/Sales.java
src/main/java/faang/school/godbless/BJS2_25280/SalesData.java
src/main/java/faang/school/godbless/BJS2_25280/Store.java

Не очень я допер где мне юзать CountDownLatch. Я уже работал с ним, а вот с тем же  Callable знаком плохо)
Поэтому решил СНОВА ЧУТКА изменить условие задачи - пойти по своему решению с использованием Callable.
p.s Если наглею, то могу переделать с CountDownLatch

BJS2-25280  Сбор данных для отчета

---

src/main/java/faang/school/godbless/BJS2_25304/Comment.java
src/main/java/faang/school/godbless/BJS2_25304/Main.java
src/main/java/faang/school/godbless/BJS2_25304/Post.java
src/main/java/faang/school/godbless/BJS2_25304/PostService.java

Какой вообще смысл использовать volatile в данной задаче, если оба метода, которые влияют на список, синхронизированы?

BJS2-25304 Оставляем комментарий

---

src/main/java/faang/school/godbless/sprint4/wow/Main.java
src/main/java/faang/school/godbless/sprint4/wow/Player.java
src/main/java/faang/school/godbless/sprint4/wow/Quest.java
src/main/java/faang/school/godbless/sprint4/wow/QuestSystem.java

@20cognosce Подскажи, пожалуйста, как лучше обрабатывать CompletableFuture если я хочу разом это сделать для списка. Еще решил попробовать CompletableFuture.failedFuture, но неуверен, что его корректно именно так использовать. В конце сделал join потому, что основной поток не дожидается вывода уведомлений о завершении квеста (я в курсе, что так делать не нужно - просто для вывода поставил).

BJS2-25090 - WOW

---

src/main/java/faang/school/godbless/BJS224391/Chat.java
src/main/java/faang/school/godbless/BJS224391/ChatManager.java
src/main/java/faang/school/godbless/BJS224391/Main.java
src/main/java/faang/school/godbless/BJS224391/User.java
src/main/java/faang/school/godbless/BJS224391/UserList.java

Matters of the heart
👩‍💻 🧠🧠🧠
Условия задачи
Вы — разработчик Tinder. Приложение содержит список пользователей, которые ищут свою вторую половинку. Приложение работает в многопоточной среде, используя класс UserList, который представляет список пользователей.
Некоторые пользователи хотят общаться с другими пользователями в реальном времени, но не хотят показывать свой статус в списке.
В классе UserList есть метод getOnlineUsers(), который возвращает список пользователей, которые в данный момент находятся онлайн. В классе ChatManager есть метод startChat(User user), который вызывается, когда пользователь хочет начать чат. Метод startChat() должен найти другого пользователя, который также хочет начать чат, и создать для них новый чат. Если в данный момент никто не желает общаться в реальном …

Beksultan2005 bjs2 24391

---

src/main/java/BJS2_24914_WorldOfWarcraft/Main.java
src/main/java/BJS2_24914_WorldOfWarcraft/Player.java
src/main/java/BJS2_24914_WorldOfWarcraft/Quest.java
src/main/java/BJS2_24914_WorldOfWarcraft/QuestSystem.java

Не понимаю как проверить на awaitTermination() здесь... все рушится он ждет почему то все потоки до конца , а не делает их асинхронно, в этом варианте все работает как надо, но без проверки

World Of Warcraft

---

src/main/java/faang/school/godbless/task/multithreading/async/carry/ate/ConsoleOutputExample.txt
src/main/java/faang/school/godbless/task/multithreading/async/carry/ate/Inventory.java
src/main/java/faang/school/godbless/task/multithreading/async/carry/ate/Item.java
src/main/java/faang/school/godbless/task/multithreading/async/carry/ate/Main.java

Я сначала не был уверен по поводу .join() в следующем методе, влияет ли он на выполнение действий асинхронно:
```
private static void addCombineItem() {
log.info("Start: addCombineItem() method");
var chestItem = inventory.chestGetItem();
var storeItem = inventory.buyItem();
chestItem.thenCombine(storeItem, inventory::combineItems)
.thenCompose(item -> CompletableFuture.runAsync(() -> inventory.addItem(item)))
.join();
}
```
Без него main завершался раньше времени, но потом понял что .join() в том месте не влияет на main, и на асинхронное выполнение других потоков, он только просит ждать .allOff() до выполнения всех потоков.
*Я верно понял, или ошибаюсь?*

Carry отожрался BJS2-24925

---

src/main/java/faang/school/godbless/BJS2_25666/Location.java
src/main/java/faang/school/godbless/BJS2_25666/Main.java
src/main/java/faang/school/godbless/BJS2_25666/TransportManagementSystem.java
src/main/java/faang/school/godbless/BJS2_25666/Vehicle.java
src/main/java/faang/school/godbless/BJS2_25666/VehicleTracker.java

Созданы классы Location, Vehicle, VehicleTracker, TransportManagementSystem, Main.

BJS2-25666   Система трекинга

---

src/main/java/faang/school/godbless/BJS2_25660/Conference.java
src/main/java/faang/school/godbless/BJS2_25660/Main.java
src/main/java/faang/school/godbless/BJS2_25660/Participant.java

Создал классы Conference, Participant, Main.

BJS2-25660   Мини Zoom

---

src/main/java/faang/school/godbless/sprint4/send_crow/Kingdom.java
src/main/java/faang/school/godbless/sprint4/send_crow/Main.java

BSJ2-24944 - Пошлите ворона

---

src/main/java/faang/school/godbless/sprint4/star_wars/Battle.java
src/main/java/faang/school/godbless/sprint4/star_wars/Robot.java

Implementation design notes:
- different battles can happen at the same time (e.g. different battles throughout the campaign);
- same instance of a battle can happen at the same time (e.g. different users doing the same battle in the campaign);
- ScheduledExecutorService used instead of plain ExecutorService, for simpler executor shutdown (in case no battle was started before timeout);
- inactivity timeout is shared between all instances of Battle, therefore a constant.

BJS2-24653 - Star Wars Arena

---

src/main/java/faang/school/godbless/BJS224253/Game.java
src/main/java/faang/school/godbless/BJS224253/Main.java
src/main/java/faang/school/godbless/BJS224253/Player.java

Bro Force!
👩‍💻 🧠🧠
Условия задачи
Вы разрабатываете новую версию игры Bro Force. В игре множество игровых объектов одновременно обновляют свои состояния. Враги, игроки и препятствия, могут взаимодействовать друг с другом и изменять общие переменные, такие как здоровье, позиция и т.д. Это может привести к проблемам с доступом к общим ресурсам и возможным нарушениям целостности данных. Чтобы избежать этих проблем, необходимо использовать блокировку synchronized.
Создать класс Game с приватными полями score (счётчик набранных очков за игру всеми участниками) и lives (количество потерянных всеми участниками жизней), а также с двумя объектами для доступа к общему счётчику очков и количеству потерянных жизней соответственно. Подумайте, как вы можете это сделать.
Создать метод update(), который …

BJS2-24253

---

src/main/java/tracking/Location.java
src/main/java/tracking/Main.java
src/main/java/tracking/StatusState.java
src/main/java/tracking/TransportManagementSystem.java
src/main/java/tracking/Vehicle.java
src/main/java/tracking/VehicleTracker.java

Задача Система трекинга
https://faang-school.atlassian.net/browse/BJS2-25512

Система трекнига

---

src/main/java/faang/school/godbless/BJS2_25600/DesignDepartment.java
src/main/java/faang/school/godbless/BJS2_25600/DesignResources.java
src/main/java/faang/school/godbless/BJS2_25600/Main.java
src/main/java/faang/school/godbless/BJS2_25600/MarketingDepartment.java
src/main/java/faang/school/godbless/BJS2_25600/MarketingResources.java

В первом коммите ситуация с дедлоком, во втором - разрешение дедлока.

BJS2-25600   Работа стоит

---

src/main/java/faang/school/godbless/BJS2_25374/DesignDepartment.java
src/main/java/faang/school/godbless/BJS2_25374/Main.java
src/main/java/faang/school/godbless/BJS2_25374/MarketingDepartment.java
src/main/java/faang/school/godbless/BJS2_25374/Resources.java

В задаче нужно было написать классы DesignResources и MarketingResources. Я сделал один класс Resources, чтобы не дублировать код.

Работа стоит 25374

---

src/main/java/faang/school/godbless/BJS225092/MagicalTournament.java
src/main/java/faang/school/godbless/BJS225092/School.java
src/main/java/faang/school/godbless/BJS225092/Student.java
src/main/java/faang/school/godbless/BJS225092/Task.java
src/main/java/faang/school/godbless/BJS225092/Tournament.java

Качаем алхимию
👩‍💻 🧠🧠
Условия задачи
Задача: В сеттинге "The Elder Scrolls", вы работаете с алхимиком, который собирается создать несколько зелий. Ваша задача: написать программу на Java, используя CompletableFuture и Stream API, которая асинхронно собирает ингредиенты для каждого зелья и возвращает общее количество собранных ингредиентов.
Пример классов:
Класс Potion — описывает зелье. name — название зелья.requiredIngredients — количество требуемых ингредиентов для создания зелья. int
Основные шаги:
Создайте список объектов класса Potion для разных зелий.
Напишите асинхронный метод gatherIngredients(Potion), который собирает ингредиенты для зелья. По сути, просто ждёт какое-то время, а затем возвращает количество требуемых ингредиентов для переданного зелья.
Используйте Stream API для …

BJS2-25092

---

src/main/java/faang/school/godbless/BJS225196/Main.java
src/main/java/faang/school/godbless/BJS225196/Potion.java

Качаем алхимию
👩‍💻 🧠🧠
Условия задачи
Задача: В сеттинге "The Elder Scrolls", вы работаете с алхимиком, который собирается создать несколько зелий. Ваша задача: написать программу на Java, используя CompletableFuture и Stream API, которая асинхронно собирает ингредиенты для каждого зелья и возвращает общее количество собранных ингредиентов.
Пример классов:
Класс Potion — описывает зелье. name — название зелья.requiredIngredients — количество требуемых ингредиентов для создания зелья. int
Основные шаги:
Создайте список объектов класса Potion для разных зелий.
Напишите асинхронный метод gatherIngredients(Potion), который собирает ингредиенты для зелья. По сути, просто ждёт какое-то время, а затем возвращает количество требуемых ингредиентов для переданного зелья.
Используйте Stream API для …

BJS2-25196

---

src/main/java/faang/school/godbless/BJS225183/Main.java
src/main/java/faang/school/godbless/BJS225183/ResultConsumer.java
src/main/java/faang/school/godbless/BJS225183/SquareRequest.java

Fan out – Fan In
👩‍💻 🧠🧠
Условия задачи
Представьте, что вам дали задание, вычислить сумму квадратов чисел от 1 до n — 1^2 + 2^2 + 3^2 + … n^2.
Вы, как опытный программист, решили оптимизировать задачу и выполнить её параллельно, используя паттерн Fan out – Fan in. Этот алгоритм разбивает большую задачу на меньшие подзадачи, которые обрабатываются параллельно на различных узлах, а затем объединяют результаты их выполнения.
Он состоит из 2 этапов:
Fan Out — данные распределяются по нескольким узлам, где каждый узел выполняет свою часть работы;
Fan In — результаты собираются обратно в единую систему.
1.  Вам дан класс SquareRequest, метод longTimeSquare которого вычисляет квадрат числа, и может это делать от 3 до 4 секунд. В конце “вычислений” longTimeSquare копит результат у некого …

Beksultan2005 bjs2 25183

---

src/main/java/faang/school/godbless/task/multithreading/async/leave/comment/Comment.java
src/main/java/faang/school/godbless/task/multithreading/async/leave/comment/Configuration.java
src/main/java/faang/school/godbless/task/multithreading/async/leave/comment/ConsoleOutputExample.txt
src/main/java/faang/school/godbless/task/multithreading/async/leave/comment/Main.java
src/main/java/faang/school/godbless/task/multithreading/async/leave/comment/Post.java
src/main/java/faang/school/godbless/task/multithreading/async/leave/comment/PostService.java
src/main/java/faang/school/godbless/task/multithreading/async/leave/comment/User.java

Использовал `ConcurrentHashMap` что позволяет не делать явную синхронизацию на уровне методов, и можно одновременно добавлять и удалять посты/комментарии разным потокам безопасно, потому что они работают с конкретными бакетами.
Но есть вероятность удаления поста одним потоком, кода другие потоки работают с комментариями этого поста, и решил сделать блокировку на конкретных постах, при помощи вызова `ReentrantLock` на каждом посте, это обеспечит потока безопасность? Я правильно сделал?

Оставляем комментарий BJS2-25292

---

src/main/java/BJS2_25457/Comment.java
src/main/java/BJS2_25457/Main.java
src/main/java/BJS2_25457/Post.java
src/main/java/BJS2_25457/PostService.java

Задача - Оставляем комментарий - реализация

---

src/main/java/ru/kraiush/threads/BJS2_18331/AppFeedPeterGriffin.java
src/main/java/ru/kraiush/threads/BJS2_18331/FoodDeliveryTask.java
src/main/java/ru/kraiush/threads/BJS2_24251/AppTamagotchiVlad.java
src/main/java/ru/kraiush/threads/BJS2_24251/Food.java
src/main/java/ru/kraiush/threads/BJS2_24251/TamagotchiVlad.java
src/main/java/ru/kraiush/threads/BJS2_24251/VladController.java

BJS2 24251: TamagotchiVlad. v.01
Проблема с реализацией многопоточности - как запустить экземпляры <TamagotchiVlad> в разных полтоках и управлять ими через контроллер <VladController>?!?

BJS2 24251: TamagotchiVlad. v.01

---

src/main/java/faang/school/godbless/BJS225078/Game.java
src/main/java/faang/school/godbless/BJS225078/Inventory.java
src/main/java/faang/school/godbless/BJS225078/Item.java
src/main/java/faang/school/godbless/BJS225078/Main.java

Carry отожрался
👩‍💻 🧠🧠🧠
Условия задачи
Задача: В мире Dota 2, игроки собирают предметы, которые могут быть скомбинированы для создания более мощных предметов. Вам нужно написать программу, которая асинхронно собирает предметы и комбинирует их в более сильные предметы.
Используйте методы thenCombine и thenCompose у CompletableFuture для асинхронного получения предметов и их объединения.
Пример классов и предметов:
Класс Item — описывает предметы и их характеристики. name — название предмета;power — сила предмета.
Класс Inventory — описывает инвентарь игрока. items — список предметов в инвентаре;addItem(Item) — добавляет предмет в инвентарь;combineItems(Item, Item) — комбинирует два предмета и создаёт новый с суммарной силой и новым названием.
Создайте асинхронные методы, которые выполняют …

Beksultan2005 bjs2 25078

---

src/main/java/faang/school/godbless/BJS225138/Main.java
src/main/java/faang/school/godbless/BJS225138/Point.java

Вычислим число ПИ
👩‍💻 🧠🧠🧠
Условия задачи
Нам дан рандомный генератор чисел, который возвращает число от 0 до 1. Нам сказали с помощью него вычислить число Пи. Мы придумали решение, которое выглядит следующим образом:
1. Воспользуемся генератором 2 раза, назовём результаты x и y. В итоге у нас получилась точка A с координатами (x, y) на координатной плоскости.  
2. Заметим, что эта точка попадёт внутрь квадрата на изображении, при этом она может расположиться как внутри окружности, так и вне её Точка попала внутрь окружности, если выполняется неравенство:
x^2 + y^2 <= R^2 (значит попали внутрь окружности)
Так, например точка (0.5, 0.5) попадёт внутрь окружности радиуса 1, а точка (0.8, 0.8) не попадёт
3. Повторим это действие множество раз, — так у нас будут точки: какая-то часть из них …

BJS2-25138

---

src/main/java/faang/school/godbless/comment/Author.java
src/main/java/faang/school/godbless/comment/Comment.java
src/main/java/faang/school/godbless/comment/Main.java
src/main/java/faang/school/godbless/comment/Post.java
src/main/java/faang/school/godbless/comment/PostService.java

Вопрос по законности следующего метода:
```
public void addComment(@NonNull Comment comment, @NonNull Post post) {
synchronized (post) {
post.addComment(comment);
}
}
```
Возможна ли синхронизация на таком объекте? И нужен ли тут вообще синхронизация, если:
```
public void addComment(Comment comment) {
synchronized (this) {
comments.add(comment);
}
}
```
Вот тут по идее идет блокировка на определенном посте.
Так то все отработало, добавилось 500 комментариев успешно (Возможно я вообще что-то не то сделал?). 
Не вижу причин для лока всего списка постов, по хорошему нам надо блокировать определенный пост на изменение, чтобы ко всем остальным постам можно было добавлять комментарии. Вообще в идеале наверное тут не лист взять а какую-нибудь concurrent коллекцию. Но еще не дошел до этого.

BJS2-25334 - Оставляем комментарий

---

src/main/java/faang/school/godbless/superBattle/Main.java
src/main/java/faang/school/godbless/superBattle/MyPair.java
src/main/java/faang/school/godbless/superBattle/Superhero.java
src/main/java/faang/school/godbless/superBattle/SuperheroBattle.java

Pair не завелся : Cannot be accessed from outside package
Создал свой аналог

BJS2-24618 - Superheroes battle

---

src/main/java/school/BJS2_31329/Main.java
src/main/java/school/BJS2_31329/User.java
src/test/java/faang_school/Main.java
src/test/java/faang_school/User.java

Сделал задачу BJS2-28996

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/User.java

Группировка пользователей по возрасту, наверное проверку я в мэйне пушнул зря?)

init commit

---

src/main/java/school/faang/bjs2_31392/Main.java
src/main/java/school/faang/bjs2_31392/User.java

https://faang-school.atlassian.net/browse/BJS2-31392?atlOrigin=eyJpIjoiMDJiZjA1OTk0ZDA2NDc1YTg3Mzk5ZWZmNmFmOWMyMGEiLCJwIjoiaiJ9

BJS2-31392

---

src/main/java/school/faang/grouping_users_by_age/Main.java
src/main/java/school/faang/grouping_users_by_age/User.java

Task: Grouping users by age, added User class, Main class (for test)

BJS2-31330 - Группировка пользователей по возрасту

---

src/main/java/groupUsers/Main.java
src/main/java/groupUsers/User.java

Naku bjs2 31340

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/User.java

task: grouping users by age

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/User.java
src/test/java/school/faang/UserTest.java

Создал класс User со статическим методом groupUsers.

Group users by their age

---

src/main/java/school/faang/Main.java

Создан класс User и реализован метод groupUsers

Создан класс User и реализован метод groupUsers

---

src/main/java/dima/evseenko/vesteros/Book.java
src/main/java/dima/evseenko/vesteros/Library.java
src/main/java/dima/evseenko/vesteros/Main.java
src/test/java/dima/evseenko/vesteros/LibraryTest.java

Java HashMap: Библиотека Вестероса

---

src/main/java/school/faang/godbless/bjs2_28996/Main.java
src/main/java/school/faang/godbless/bjs2_28996/User.java

validation

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/Person.java

feat: Person class and grouping method implemented.

Denis Ignatenko bjs2 31362

---

src/main/java/faang/school/godbless/Main.java
src/main/java/school/faang/godbless/Main.java
src/main/java/school/faang/task1/Main.java
src/main/java/school/faang/task1/User.java
src/test/java/school/faang/task1/UserTest.java

Task 1 - Sorting users by age

---

src/main/java/school/faang/usersgroup/Main.java
src/main/java/school/faang/usersgroup/Users.java

Не знал как по другому сравнить возраст если есть студенты с одинаковым возрастом, сделал вложенный цикл. Первую задачу решал больше чем пол дня это пугает.

First project Users

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/User.java
src/test/java/UserTest.java

В тесте проверил выбрасывание исключений при каждом из неправильных вводов + проверил на правильном пользователе все ли поля инициализируются правильным образом

BJS2-31529

---

src/main/java/school/faang/collectUsers/User.java
src/test/java/TestUser.java

Сделал простенький тестик, все работает по условию

BJS2-31488

---

src/main/java/school/faang/t02/Archer.java
src/main/java/school/faang/t02/Character.java
src/main/java/school/faang/t02/Main.java
src/main/java/school/faang/t02/Warrior.java

BJS2-31282

---

src/main/java/school/faang/BJS2_31403/Main.java
src/main/java/school/faang/BJS2_31403/User.java
src/test/java/school/faang/BJS2_31403/UserTest.java

new User class + tests for its constructor and groupUsers method

---

src/main/java/User.java
src/test/java/UserTest.java

add class User with attributes name,age,placeOfWork and address and add function groupUsers which grouping users by age and return Map<Integer, List<User>>

group users by age

---

src/main/java/school/faang/godbless/bjs2_31411/Example.java
src/test/java/school/faang/godbless/bjs2_31411/ExampleTest.java

task complete

---

src/main/java/school/faang/Example.java

Решения задачи по Развернитесь! BJS2-31425

Решения задачи по Развернитесь! BJS2-31425

---

src/main/java/school/faang/godbless/bjs2_31494/User.java
src/test/java/school/faang/godbless/bjs2_31494/UserTest.java

users with activities mapping

---

src/main/java/school/faang/bjs2_31313/Archer.java
src/main/java/school/faang/bjs2_31313/Character.java
src/main/java/school/faang/bjs2_31313/Main.java
src/main/java/school/faang/bjs2_31313/Warrior.java

В целом работает, но не очень нравится реализация:
1. Я не понял зачем 2 конструктора, так как дублируют друг друга и по сути используется один с параметром Имени, а остальные параметры заполняются по дефолту в зависимости от класса.
2. Для использования полей из абстрактного класса при переопределении абстрактного метода в наследниках пришлось применить модификатор protected, что сделало его уязвимым для переопределения. Для инкапсуляции сделал эти поля final, но пришлось отказаться от неиспользуемого конструктора из п. 1.
3. До конца не смог придумать защиту для hp: их нельзя делать final, т.к. значение меняется, но при этом не знаю как защитить от багов из-за protected модификатора.

BJS2-31313 Initial commit for review

---

src/main/java/Person.java
src/test/java/PersonTest.java

instead of create User class I create Person because User class already exits and add to Person class static method findHobbyLovers() which find Users with given activity list

Collect Users

---

src/main/java/school/faang/abstraction/Archer.java
src/main/java/school/faang/abstraction/Character.java
src/main/java/school/faang/abstraction/Main.java
src/main/java/school/faang/abstraction/Warrior.java

Были сложности в конструкторах дочернего класса, и с методом аттак.

Третья задача

---

src/main/java/school/faang/BJS2_31430/Main.java
src/main/java/school/faang/BJS2_31430/User.java

finish completing the task "Grouping users by age"

finish completing the task "Grouping users by age"

---

src/main/java/school/faang/turn/around/Example.java
src/main/java/school/faang/turn/around/Main.java
src/test/java/ru/kraiush/BJS2_18616/turn/around/ExampleTest.java

1. Создал класс Example
2. Добавил метод reverse
3. Покрыл тестами

Задача Развернитесь!

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/User.java

Думаю в этот раз все получилось  правильно !

Munir dev bjs2 31436

---

src/main/java/school/faang/userregistration/Main.java
src/main/java/school/faang/userregistration/Users.java

Не знал что можно передавать методы в конструктор. До того как узнал, долго разбирался как можно проверить валидацию для хэш сет внутри класса если они final static.

Вторая задча

---

src/main/java/school/faang/User.java
src/main/java/school/faang/solution/userSignUp/abstractTask/Archer.java
src/main/java/school/faang/solution/userSignUp/abstractTask/Character.java
src/main/java/school/faang/solution/userSignUp/abstractTask/Warrior.java

Lightselect bjs2 31299 Абстракция абстракция 

---

src/main/java/school/faang/bsj2_32454_abscenceCount/Main.java
src/main/java/school/faang/bsj2_32454_abscenceCount/Student.java

Я немного поэкпериментировал. Для составного ключа в HashMap я сделал отдельный класс, но решил его разместить как вложенный класс в Main, т.к. он является частью этой логики и нигде больше не должен применяться. Не могу оценить это с точки зрения улучшения читаемости и дизайна

BJS2-32454 Abscence Count task is done

---

src/main/java/school/faang/t08/Main.java
src/main/java/school/faang/t08/WebPage.java

BJS2-32766

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/usercollection/HobbyTypes.java
src/main/java/school/faang/usercollection/Test.java
src/main/java/school/faang/usercollection/User.java

Поэкспериментировал с enum. Вместо множества строк сделал множество из enum.

[BJS2-31528] - user collection

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/User.java

Created map and filtered by age

---

src/main/java/SortByAge/Main.java
src/main/java/SortByAge/User.java

- Create User class with general fields 
- Create a constructor and getter, setter methods (with Annotations that Lombok provides)
- Add groupUsers static method which returns a hash of users where the key is the age and values is the List of Peer Users

Create groupUsers static method to group them by age

---

src/main/java/school/faang/collectingusers/Main.java
src/main/java/school/faang/collectingusers/User.java

Вчера делал задачу "Регистрация пользователя" ревьювер этой задачи объяснил как сократить код. Там нужно было проверить содержится ли элемент во множестве. Оказывается что в той задаче можно было без цикла. Хотел попробовать использовать это здесь и сократить код но не получилось ))

Задача: Коллекционируем пользователей

---

src/main/java/Archer.java
src/main/java/Character.java
src/main/java/User.java
src/main/java/Warrior.java
src/main/java/model/Character.java
src/test/java/CharacterTest.java
src/test/java/UserTest.java

add constant VALID_ADDRESSES, VALID_JOBS and add constructor which validated all user parameters

registration users with validation

---

src/main/java/school/faang/bjs2_32476_DoubleCache/Main.java
src/main/java/school/faang/bjs2_32476_DoubleCache/Student.java
src/main/java/school/faang/bjs2_32476_DoubleCache/Subject.java

В процессе решения немного изменил логику по сравнению с условием. Условие задачи предлагает делать отдельные методы для изменения мапов. Но они должны меняться одновременно, т.к. являются разными отображениями одной базы. Т.е. добавление студента  с оценками в одну мапу должно одновременно выполняться и для второй мапы.
P.S. Страдаю, что еще не научился делать тесты. Запихивание всего и эксперименты в Main это такое себе...
P.P.S. Некоторые модификаторы методов в Main я сделал public осознанно, чтобы разграничить с private методами, которые являются вспомогательными.

Regis bjs2 32476 - Double Cache

---

src/main/java/school/faang/bsj2_32566_Cache/Main.java
src/main/java/school/faang/bsj2_32566_Cache/WeatherData.java
src/main/java/school/faang/bsj2_32566_Cache/WeatherService.java
src/main/java/school/faang/bsj2_32566_Cache/WeatherWebMock.java

Не уверен, что на 100% понял тему мок-класса и заглушек, но сделанное работает :)

BJS2-32566 Cache, Cache first commit: task is done

---

src/main/java/school/faang/bjs2_32790/Main.java
src/main/java/school/faang/bjs2_32790/WebPage.java

В решении был использован HashSet для хранения страниц, кажется более эффективным, чем список

BJS2-32790 Web Search Engine task is done

---

src/main/java/school/faang/t09/Main.java
src/main/java/school/faang/t09/Product.java

BJS2-32281

---

src/main/java/school/faang/t11/Main.java
src/main/java/school/faang/t11/User.java

BJS2-31554

---

src/main/java/school/faang/truancy/Main.java
src/main/java/school/faang/truancy/Student.java
src/main/java/school/faang/truancy/StudentRecord.java

Считаем прогулы

---

src/main/java/school/faang/countingAbsence/Main.java
src/main/java/school/faang/countingAbsence/Student.java

Не уверен, что методы с удалением и поиском студентов оптимизированные, придумал только проходом через циклы.

BJS2-32467

---

src/main/java/school/faang/googleEngine/Main.java
src/main/java/school/faang/googleEngine/WebPage.java

Снова не уверен, что мои методы - лучшие и оптимизированные способы для добавления/удаления, но всё работает, и я не знаю как сделать лучше :/

BJS2-32751

---

src/main/java/school/faang/godbless/bjs2_33028/Book.java
src/main/java/school/faang/godbless/bjs2_33028/Library.java
src/test/java/school/faang/godbless/bjs2_33028/LibraryTest.java

library fro books

---

src/main/java/school/faang/library/of/westeros/Book.java
src/main/java/school/faang/library/of/westeros/Main.java

Added Book class. Tested the Book class in the Main class

BJS2-33045 - Java HashMap: Библиотека Вестероса

---

src/main/java/school/faang/bjs_33090_vesterosLibrary/Book.java
src/main/java/school/faang/bjs_33090_vesterosLibrary/Main.java

Я проявил немного инициативы и вместо String как значения полки применял Enum с перечнем возможных мест хранения книг. Поленился выносить его в отдельный файл, оставил специально в Main, т.к. функционально он привязан к библиотеке.
Комменты по коду в Main просто для визуального разделения шагов

BJS2-33090 Library of Westeros task is done

---

src/main/java/school/faang/Archer.java
src/main/java/school/faang/Character.java
src/main/java/school/faang/Main.java
src/main/java/school/faang/Warrior.java

feat: abstract Character class and two subclasses implemented

feat: abstract Character class and two subclasses implemented

---

src/main/java/school/faang/catchEvents/Main.java
src/main/java/school/faang/catchEvents/StreamEvent.java

Вроде всё учел в удалении, не знаю правда насколько это оптимизированно и быстро, по-другому не придумал.

BJS2-33212

---

src/main/java/school/faang/CollectUsers/BJS231489/User.java
src/main/java/school/faang/CollectUsers/User.java
src/main/java/school/faang/User.java

Коллекционируем пользователей Lightselect bjs2 31489

---

src/main/java/school/faang/doublecache/Main.java
src/main/java/school/faang/doublecache/Student.java
src/main/java/school/faang/doublecache/Subject.java

Двойной кэш-кэш

---

src/main/java/SortByAge/Main.java
src/main/java/SortByAge/User.java

- Add validation for age field to make sure it is not less than 18
- Add validation for name field to avoid it being empty
- Add validation for address field
- Add validation for workplace field
- Handle IllegalArgumentExceptions for all validations

Update User class by adding validations for class fields

---

src/main/java/school/faang/doubleCash/Main.java
src/main/java/school/faang/doubleCash/Student.java
src/main/java/school/faang/doubleCash/Subject.java

Есть ощущение, что я навалил лютого кринжа, но вроде методы простенькие и рабочие. Надеюсь я правильно понял все условия...

BJS2-32422

---

src/main/java/school/faang/abstraction/Archer.java
src/main/java/school/faang/abstraction/Character.java
src/main/java/school/faang/abstraction/Warrior.java
src/test/java/CharacterAttackTest.java

BJS2-31354

---

src/main/java/school/faang/countabsences/FacyltyAndCours.java
src/main/java/school/faang/countabsences/Main.java
src/main/java/school/faang/countabsences/Student.java
src/main/java/school/faang/countabsences/University.java

Это было жестко
По третьему пункту в условии задачи "faculty и year". Как я понял я подумал что хэш мапа уже должна по умолчанию содержать какие то данные и добавление в значение из аррай листа производить исходя из этих данных. То есть допустим: факультет: Филология, курс 3 и потом добавляются из входящего аррай листа только те студенты у которых такие поля факультет: Филология, курс 3.

Задача: Считаем прогулы

---

src/main/java/school/faang/minigooglesearch/Main.java
src/main/java/school/faang/minigooglesearch/WebPage.java
src/main/java/school/faang/minigooglesearch/WebPageService.java

Создал классы WebPage и WebPageService, где хранятся методы для операций.

Поисковой мини движок Google

---

src/main/java/school/faang/bsj2_32890_homm/Angel.java
src/main/java/school/faang/bsj2_32890_homm/Army.java
src/main/java/school/faang/bsj2_32890_homm/Battlefield.java
src/main/java/school/faang/bsj2_32890_homm/Creature.java
src/main/java/school/faang/bsj2_32890_homm/Griffin.java
src/main/java/school/faang/bsj2_32890_homm/Hero.java
src/main/java/school/faang/bsj2_32890_homm/Main.java
src/main/java/school/faang/bsj2_32890_homm/Peasant.java
src/main/java/school/faang/bsj2_32890_homm/Pikeman.java
src/main/java/school/faang/bsj2_32890_homm/Skeleton.java
src/main/java/school/faang/bsj2_32890_homm/Swordsman.java

К сожалению, понял, что не получается по времени успеть сделать классную реализацию с индивидуальными боями для каждого персонажа, рандомами в каждой новой битве.
Пришлось сделать относительно тупую реализацию битвы на основе суммарной статистики существ в армии.
Классная версия будет сделана на досуге :)

BJS2-32890 Heros of MM: alpha version complete 

---

src/main/java/tasks/Main.java
src/main/java/tasks/User.java

Добавлен класс User
Добавлен метод groupUser группирующий список пользователей по возрасту и возвращает полученную коллекцию. Добавлен метод Main в пакет для проверки работоспособности функционала.

bjs2-31377 : Группировка пользователей.

---

src/main/java/school/faang/t07/Main.java
src/main/java/school/faang/t07/StreamEvent.java

BJS2-33221

---

src/main/java/school/faang/user/registration/User.java
src/test/java/UserRegistrationTest.java

BJS2-31779

---

build.gradle
src/main/java/school/faang/library/Book.java
src/main/java/school/faang/library/Library.java
src/main/java/school/faang/library/Main.java
src/test/java/ru/kraiush/BJS2_18616/library/LibraryTest.java

1. Создал класс Book
2. Переопределил методы equals и hashCode
3. В классе Main созда HashMap и добавил информацию про пару книг
4. Создал класс Library
5. Реализовал методы добавления, удаления, поиска и печати
6. Покрыл тестами

Задача Библиотека Вестероса BJS2-33078

---

src/main/java/collectingUsers/Main.java
src/main/java/collectingUsers/User.java

Во избежание конфликта мержа я смержил основную ветку в эту ветку и создал PR

Alekseyb86 bsj2 31507 colecting users

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/library/Book.java
src/main/java/school/faang/library/TestLibrary.java

Alexeyzimin5726 bjs2 33081

---

src/main/java/school/faang/eventtask_BJS2_33278/StreamEvent.java
src/main/java/school/faang/eventtask_BJS2_33278/Test.java

смю пакет eventtask_BJS2_33278

[BJS2-33278] - event stream

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/User.java
src/main/java/school/faang/group_by_age/Main.java
src/main/java/school/faang/group_by_age/User.java

Task is done, please do code review. Thanks

Group by age BJS2-313333

---

src/main/java/school/faang/heroes/Angel.java
src/main/java/school/faang/heroes/BattleField.java
src/main/java/school/faang/heroes/Creature.java
src/main/java/school/faang/heroes/Griffin.java
src/main/java/school/faang/heroes/Hero.java
src/main/java/school/faang/heroes/Main.java
src/main/java/school/faang/heroes/Pikeman.java
src/main/java/school/faang/heroes/Swordman.java

1. Создал абстрактный класс Creature
2. Создал подклассы существ
3. Создал класс героя
4. Создал класс поля битвы
5. Протестировал работу класса в методе Main

Герои меча.

---

src/main/java/abstraction/Archer.java
src/main/java/abstraction/Character.java
src/main/java/abstraction/Main.java
src/main/java/abstraction/Warrior.java

- Add Character abstract class which can be used as a parent class for all characters
- Add 2 children classes (Warrior and Archer)
- The instances of the children classes can fight each other and reduce their opponents' health based on the their power and skill value

Character class with 2 children classes

---

src/main/java/school/faang/bjs2_32420_game_of_thrones/House.java
src/main/java/school/faang/bjs2_32420_game_of_thrones/Main.java

В первый раз использовал Iterator в задачах для удаления записи из мапы во время поиска

BJS2-32420 Game of Thrones: Task completed

---

src/main/java/school/faang/bjs2_32707/Main.java
src/main/java/school/faang/bjs2_32707/Student.java
src/test/java/school/faang/bjs2_32707/MainTest.java

Немного отошел от задания, метод, группирующий студентов, работает на основе общего списка студентов.
Так же автоматически группирует студентов, при добавлении нового.

deema-bjs2-32707

---

src/main/java/school/faang/library/Book.java
src/main/java/school/faang/library/Main.java

BJS2-33130

---

src/main/java/HashMap_Westeros/Book.java
src/main/java/HashMap_Westeros/Main.java

- Add Book class with overridden equals and hashCode methods
- In main method, put a few Book objects as keys in HashMap
- Put, Remove, Iterate over values in HashMap
- Verify the correct implementation of the HashMap

Add Book class with overridden equals and hashCode methods.

---

src/main/java/school/faang/Book.java
src/main/java/school/faang/Main.java

Completed a new taask BJS2-33118 and ready for review

---

src/main/java/school/faang/vesteroslibrary/Book.java
src/main/java/school/faang/vesteroslibrary/Main.java

В лекции по hashmap во втором видео "HashMap Basics 2: Practice" в самом начале разбирали задачу "Игра престолов". Я сделал по аналогии. 
Но я так и не понял зачем делать все в мэйне и в статике мне кажется это как то не гибко.
А как по другому или как правильно я не знаю.
То есть если у меня в мэйне будет еще один hashmap то что делать? 
Допустим будет новый hashmap "newBookMap" то мне нужно будет переделывать во всех статичных методах "bookMap" на  "newBookMap"?
Заранее спасибо за ответ.

Задача: Библиотека Вестероса

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/User.java

Created user class, groupUsers method

Created user class, groupUsers method

---

src/main/java/school/faang/event/Main.java
src/main/java/school/faang/event/StreamEvent.java

BJS2-33303 clean

---

src/main/java/school/faang/searching_mini_engine_google/Main.java
src/main/java/school/faang/searching_mini_engine_google/Webpage.java

 Поисковой мини-движок Google

---

src/main/java/school/faang/minisearchengine/Main.java
src/main/java/school/faang/minisearchengine/WebPage.java

Если есть какие то варианты как сократить оптимизировать код. Напишите пожалуйста буду очень благодарен

Задача: Поисковый мини-движок Google

---

src/main/java/school/faang/google/Main.java
src/main/java/school/faang/google/WebPage.java

BJS2-32900

---

src/main/java/school/faang/BJS2_32782/Main.java
src/main/java/school/faang/BJS2_32782/WebPage.java

Долго парился хотел сделать как на видео в котором Влад рассказывал про использование второй Маппы, но не вывез.
Не могли бы вы пожалуйста  показать как это реализуется?

Поисковый мини-движок Google BJS2-32782

---

src/main/java/school/faang/count/skipping/AccountingSystem.java
src/main/java/school/faang/count/skipping/Course.java
src/main/java/school/faang/count/skipping/Main.java
src/main/java/school/faang/count/skipping/Student.java
src/test/java/ru/kraiush/BJS2_18616/count/skipping/AccountingSystemTest.java

1. Создал Student
2. Создал AccountingSystem - система учета студентов
3. Добавил метод добавления, поиска, удаления, печати.
4. Покрыл тестами

Задача Java HashMap: Считаем прогулы

---

src/main/java/tasks/bjs2_31449/Example.java
src/main/java/tasks/bjs2_31449/Main.java

Создан класс Example в котором был реализован статический метод reverse, переворачивая переданный массив.
Создан класс Main для тестирования функционала изменений.

bjs2-31499 : Развернитесь!

---

src/main/java/school/faangSprint2/t3/FilterProcessor.java
src/main/java/school/faangSprint2/t3/Image.java
src/main/java/school/faangSprint2/t3/Main.java

BJS2-34748

---

src/main/java/school/faang/student/Course.java
src/main/java/school/faang/student/Main.java
src/main/java/school/faang/student/Student.java

BJS2-32700

---

src/main/java/searchEngine/Main.java
src/main/java/searchEngine/WebPage.java

- Add Webpage class with general fields and methods
- Implement methods in Main class to index, search and remove webpages from indexed List

Mini Google search engine

---

src/main/java/school/faang/catchingevents/Main.java
src/main/java/school/faang/catchingevents/Service.java
src/main/java/school/faang/catchingevents/StreamEvent.java

commit catchingEvents

---

src/main/java/usergrouping/Main.java
src/main/java/usergrouping/User.java

Решение задачи "Группировка пользователей по возрасту.

Решение задачи "Группировка пользователей по возрасту"

---

.gitignore
Readme.txt
src/main/java/tasks/bjs2_33128/Book.java
src/main/java/tasks/bjs2_33128/Library.java
src/main/java/tasks/bjs2_33128/Main.java

Добавлен класс Book
Добавлен класс Library в котором можно добавлять\убирать книги в библиотеке, а так же отобразить список в порядке доступных полок.
Добавлен класс Main для тестирования функционала.

bjs2-33128 : Библиотека Вестеросса

---

src/test/java/Book.java
src/test/java/Main.java

Розовым выделено - это делала когда тренировалась работать с Гит. Не очень пока понимаю как оказалось в этой ветке)

задача библиотека Вестероса

---

src/main/java/school/faang/catching/events/Event.java
src/main/java/school/faang/catching/events/Main.java
src/main/java/school/faang/catching/events/StreamEvent.java
src/test/java/ru/kraiush/BJS2_18616/catching/events/StreamEventTest.java

1. Создал Event
2. Создал StreamEvent - структура данных для работы с Event
3. Добавил метод добавления, поиска, удаления, печати.

Задача Java HashMap: Ловим события

---

src/main/java/school/faang/bjs2_32134/User.java

first task

---

src/main/java/school/faang/godbless/bjs2_32286/Main.java
src/main/java/school/faang/godbless/bjs2_32286/Product.java

Java HashMap: Разбираем склад Amazon

grouping products

---

src/main/java/userregistration/Main.java
src/main/java/userregistration/User.java

Решение задачи "Регистрация пользователей".

Решение задачи "Регистрация пользователей"

---

src/main/java/school/faang/JavaBasic/BJS2_31659/Main.java
src/main/java/school/faang/JavaBasic/BJS2_31659/User.java

Согласно условию я так понял, то что эта задача продолжение предыдущей и написал все шо требуется в нее

https://faang-school.atlassian.net/browse/BJS2-31659

---

.gitignore
Readme.txt
src/main/java/tasks/User.java
src/main/java/tasks/bjs2_31732/Main.java

Изменен класс User, добавлены константы, добавлена валидация пользователя в конструктор.
Создан класс Main для тестирования функционала изменений.

bjs2-31732 : Регистрация пользователей

---

src/main/java/school/faang/double_hash_map/Main.java
src/main/java/school/faang/double_hash_map/Student.java
src/main/java/school/faang/double_hash_map/Subject.java

methods for students and subjects implemented

Двойной кэш-кэш kev1n BJS2 32464

---

src/main/java/school/faang/BJS232615/Main.java
src/main/java/school/faang/BJS232615/MockClass.java
src/main/java/school/faang/BJS232615/WeatherData.java
src/main/java/school/faang/BJS232615/WeatherService.java

BJS2-32615. Жду от вас фитбека. Спасибо

BJS2-32615. Жду фитбека. Спасибо большое

---

src/main/java/school/faang/m1s2/bsj2_34734_instagram/FilterProcessor.java
src/main/java/school/faang/m1s2/bsj2_34734_instagram/Image.java
src/main/java/school/faang/m1s2/bsj2_34734_instagram/Main.java

1. Конечно вы редиски, что запихнули andThen() в подсказки, и я посмотрел их перед отправкой. А то я вручную сначала собрал метод, который при помощи второй мапы собирает комбинацию фильтров. И пришлось удалить, чтобы переписать в одну строку :)
2. Делал по заданию, но мне кажется можно поизящнее, если фильтр сделать отдельным классом. Но времени на художества нет, главное понимаю как лямбды работают

BJS2-34734 Instagram: Task done

---

src/main/java/dima/evseenko/heroes/Battlefield.java
src/main/java/dima/evseenko/heroes/Fraction.java
src/main/java/dima/evseenko/heroes/Hero.java
src/main/java/dima/evseenko/heroes/Main.java
src/main/java/dima/evseenko/heroes/entity/Angel.java
src/main/java/dima/evseenko/heroes/entity/Attacking.java
src/main/java/dima/evseenko/heroes/entity/Creature.java
src/main/java/dima/evseenko/heroes/entity/Griffin.java
src/main/java/dima/evseenko/heroes/entity/Pikeman.java
src/main/java/dima/evseenko/heroes/entity/Swordman.java
src/test/java/dima/evseenko/heroes/BattlefieldTest.java
src/test/java/dima/evseenko/heroes/HeroTest.java
src/test/java/dima/evseenko/heroes/entity/CreatureTest.java

Java HashMap: Герои Меча и Магии

---

src/main/java/school/faang/lordOfTheRings/Character.java
src/main/java/school/faang/lordOfTheRings/InventoryManager.java
src/main/java/school/faang/lordOfTheRings/Item.java
src/test/java/InventoryManagerTest.java

После нескольких заданий по этой теме появилось ощущение что я немного неправильно пишу тесты, буду рад если поправишь)

BJS2-33620

---

src/main/java/school/faang/BJS2_33711/Main.java
src/main/java/school/faang/BJS2_33711/SpellAction.java
src/main/java/school/faang/BJS2_33711/SpellCaster.java

}{огвартс, Хогвартс, наш любимый хогвартс

}{огвартс, Хогвартс, наш любимый хогвартс

---

src/main/java/school/faang/hogwarts/Main.java
src/main/java/school/faang/hogwarts/SpellAction.java
src/main/java/school/faang/hogwarts/SpellCaster.java

Задача: Хогвартс, Хогвартс, наш любимый Хогвартс.

BJS2-33752 - Java 8: Хогвартс, Хогвартс, наш любимый Хогвартс

---

src/main/java/school/faang/hogwards/Main.java
src/main/java/school/faang/hogwards/SpellAction.java
src/main/java/school/faang/hogwards/SpellCaster.java

я целый день мучился с маленькой задачкой ) и сделал ее методом тыка похоже так и не понял ничего (истерический смех)

Задача: Хогвартс, Хогвартс, наш любимый Хогвартс. целый день мучился

---

src/main/java/school/faang/BJS233826/SpellAction.java
src/main/java/school/faang/BJS233826/SpellCaster.java

BJS2-33826. Надеюсь понял правильно

BJS2-33826. Жду фитбека. Спасибо большое

---

src/main/java/school/faang/hogwarts/Main.java
src/main/java/school/faang/hogwarts/SpellAction.java
src/main/java/school/faang/hogwarts/SpellCaster.java

BJS2-33833

---

src/main/java/school/faangSprint2/t1/Main.java
src/main/java/school/faangSprint2/t1/SpellAction.java
src/main/java/school/faangSprint2/t1/SpellCaster.java

BJS2-33850

---

src/main/java/school/faang/hogwarts/Main.java
src/main/java/school/faang/hogwarts/SpellAction.java
src/main/java/school/faang/hogwarts/SpellCaster.java

1. Создайте функциональный интерфейс SpellAction, который имеет один метод, принимающий строку с названием заклинания и возвращающий строку с результатом выполнения заклинания.
2. Создайте класс SpellCaster с методом cast, который:
- Принимает два аргумента: строку с названием заклинания и лямбда-выражение типа SpellAction.
- Вызывает лямбда-выражение для выполнения заклинания и выводит результат выполнения заклинания в консоль.
3. Продемонстрируйте использование класса SpellCaster для выполнения различных заклинаний.

BJS2-33900 Хогвартс, Хогвартс, наш любимый Хогвартс

---

src/main/java/westeroslibrary/Book.java
src/main/java/westeroslibrary/Main.java

Решение задачи "Java HashMap: Библиотека Вестероса"

Решение задачи "Java HashMap: Библиотека Вестероса"

---

src/main/java/school/faang/BS232492/House.java
src/main/java/school/faang/BS232492/Main.java

Игра престолов BJS2-32492. Проверьте пожалуйста. Спасибо

BJS2-32492. Жду фитбека. Спасибо большое

---

src/main/java/school/faang/gmailFilters/Email.java
src/main/java/school/faang/gmailFilters/EmailProcessor.java
src/test/java/EmailProcessorTest.java

Мб надо было побольше тестов сделать, но мне в голову не пришло ничего другого.

BJS2-33549

---

src/main/java/school/faangSprint2/t4/Email.java
src/main/java/school/faangSprint2/t4/EmailProcessor.java
src/main/java/school/faangSprint2/t4/Main.java

BJS2-33552

---

src/main/java/org/example/model/googleRichFilter/Email.java
src/main/java/org/example/service/googleRichFilter/EmailProcessor.java

added model Email and service EmailProcessor with method processEmails which filtered the emails

Email Rich FIlter

---

src/main/java/school/faangSprint2/t7/Droid.java
src/main/java/school/faangSprint2/t7/DroidMessageEncryptor.java
src/main/java/school/faangSprint2/t7/Main.java

BJS2-34154

---

src/main/java/school/faang/t16/Angel.java
src/main/java/school/faang/t16/Battlefield.java
src/main/java/school/faang/t16/Creature.java
src/main/java/school/faang/t16/Griffin.java
src/main/java/school/faang/t16/Hero.java
src/main/java/school/faang/t16/Main.java
src/main/java/school/faang/t16/Pikeman.java
src/main/java/school/faang/t16/Swordsman.java

BJS2-32867

---

src/main/java/school/faang/t15/Main.java
src/main/java/school/faang/t15/Query.java
src/main/java/school/faang/t15/User.java

BJS2-32627

---

src/main/java/school/faangSprint2/t5/Character.java
src/main/java/school/faangSprint2/t5/InventoryManager.java
src/main/java/school/faangSprint2/t5/Item.java
src/main/java/school/faangSprint2/t5/Main.java

BJS2-33633

---

src/main/java/school/faang/insta/FilterProcessor.java
src/main/java/school/faang/insta/Image.java
src/main/java/school/faang/insta/Main.java

Задача: Фильтры Instagram

---

src/main/java/school/faang/m1s2/bjs2_33610_lotr/Character.java
src/main/java/school/faang/m1s2/bjs2_33610_lotr/InventoryManager.java
src/main/java/school/faang/m1s2/bjs2_33610_lotr/Item.java
src/main/java/school/faang/m1s2/bjs2_33610_lotr/Main.java

Не баг, а фича :)
Я немного изменил код в части обновления стоимости предмета. В примере используется создание нового предмета через `Function<>`, но это не рационально. Тогда нам надо удалять существующий, а это дополнительный код и время выполнения. Вместо этого лучше использовать `Consumer<>` чисто для обновления значения.

BJS2-33610 LOTR: Task done

---

src/main/java/school/faang/gmail/Email.java
src/main/java/school/faang/gmail/EmailProcessor.java
src/main/java/school/faang/gmail/Main.java

BJS2-33624 - Java 8: Gmail Rich Filters

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/SpellAction.java
src/main/java/school/faang/SpellCaster.java

Here we have a code for the task BJS2-33807

---

src/main/java/school/faang/meta/Notification.java
src/main/java/school/faang/meta/NotificationManager.java
src/test/java/NotificationManagerTest.java

Слегка трудновато давалось создание своего фильтра, но вроде сделал правильно. Сделал простенькие тесты, очевидно с фильтром можно и заморочиться, чтобы он фильтровал получше, но я подумал что простеньких примеров хватит для демонстрации работоспособности.

BJS2-34621

---

src/main/java/school/faang/lightsect/BJS233245/Event.java
src/main/java/school/faang/lightsect/BJS233245/Main.java
src/main/java/school/faang/lightsect/BJS233245/StreamEvent.java

Проверьте пожалуйста.

---

src/main/java/school/faangSprint2/t2/Main.java
src/main/java/school/faangSprint2/t2/Notification.java
src/main/java/school/faangSprint2/t2/NotificationManager.java

BJS2-34655

---

src/main/java/dima/evseenko/query/Main.java
src/main/java/dima/evseenko/query/Query.java
src/main/java/dima/evseenko/query/QueryService.java
src/main/java/dima/evseenko/query/User.java
src/test/java/dima/evseenko/query/QueryServiceTest.java

Java HashMap: Индекс запросов ELK

---

src/main/java/school/faang/bjs2_33205_streamCatch/Main.java
src/main/java/school/faang/bjs2_33205_streamCatch/StreamEvent.java

В целом по аналогии с предыдущими задачами, но тут добавил исключение в один из методов для проверки правильности указанного id перед удалением записей

BJS2-33205 Stream Events Catch task is done

---

src/main/java/school/faang/handlingErrors/ExceptionHandler.java
src/main/java/school/faang/handlingErrors/Main.java
src/main/java/school/faang/handlingErrors/MockService.java

Что-то очень туго эта задачка давалась, чувствую одновременно что понимаю и не понимаю нифига))

BJS2-33419

---

src/main/java/school/faangSprint2/t6/ErrorHandler.java
src/main/java/school/faangSprint2/t6/Main.java

BJS2-33424

---

src/main/java/org/example/model/handleError/ExceptionHandler.java
src/main/java/org/example/model/handleError/HandledErrorSupplier.java
src/main/java/org/example/model/handleError/Main.java

added model ExceptionHandler for use as own functional interface and HandledErrorSupplier because the Supplier redirect taken exception to method withErrorHandling();

Handle error beautifully 

---

src/main/java/school/faang/handleerrors/ErrorHandler.java
src/main/java/school/faang/handleerrors/ExceptionHandler.java
src/main/java/school/faang/handleerrors/Main.java

Задача: Обрабатываем ошибки красиво.

BJS2-33436 - Java 8: Обрабатываем ошибки красиво

---

src/main/java/school/faang/bjs2_31996/User.java

https://github.com/CorporationX/god_bless/pull/11728

vovohka777-BJS2-31996

---

src/main/java/school/faang/gmail/Email.java
src/main/java/school/faang/gmail/EmailProcessor.java
src/main/java/school/faang/gmail/Main.java

BJS2-33573

---

src/main/java/school/faang/sprint_2/bjs2_33455/ErrorHandler.java
src/main/java/school/faang/sprint_2/bjs2_33455/Main.java
src/main/java/school/faang/sprint_2/bjs2_33455/RemoteService.java

Changed packages, divided into sprints.

deema-bjs2-33455

---

src/main/java/school/faang/truancy/Main.java
src/main/java/school/faang/truancy/Student.java
src/main/java/school/faang/truancy/StudentGrouper.java

1. Создайте класс Student, который будет содержать поля name (имя студента), faculty (факультет) и year (курс).
2. В классе Main, создайте список студентов и заполните его данными о студентах разных факультетов и курсов.
3. Создайте метод, который будет принимать список студентов и возвращать HashMap с ключом, состоящим из пары faculty и year, и значением — списком студентов, соответствующих данному факультету и курсу.
4. Реализуйте методы для следующих действий: добавление нового студента в список; удаление студента из списка по его имени, факультету и курсу; поиск всех студентов определённого факультета и курса; вывод списка всех студентов сгруппированных по факультетам и курсам

BJS2-32769 Считаем прогулы

---

src/main/java/school/faang/doublecache/Main.java
src/main/java/school/faang/doublecache/Student.java
src/main/java/school/faang/doublecache/Subject.java

1. Создайте класс Student, который будет содержать поля id (ID студента) и name (имя студента).
2. Создайте класс Subject, который будет содержать поля id (ID предмета) и name (название предмета).
3. В классе Main, создайте две HashMap: Первая HashMap с ключом типа Student и значением типа Map<Subject, Integer> (список предметов и оценок студента по каждому предмету); Вторая HashMap с ключом типа Subject и значением типа List<Student> (список студентов, изучающих данный предмет).
4. Реализуйте методы для следующих действий: добавление нового студента и его предметов с оценками; добавление нового предмета для существующего студента с оценкой; удаление студента и его предметов с оценками; вывод списка всех студентов и их оценок по предметам.
5. Реализуйте методы для работы со второй …

BJS2-32666 Двойной кэш-кэш

---

src/main/java/school/faang/lord/Character.java
src/main/java/school/faang/lord/InventoryManager.java
src/main/java/school/faang/lord/Item.java
src/main/java/school/faang/lord/Main.java

BJS2-33655

---

src/main/java/school/faang/lordofrherings/Character.java
src/main/java/school/faang/lordofrherings/InventoryManager.java
src/main/java/school/faang/lordofrherings/Item.java
src/main/java/school/faang/lordofrherings/Main.java

метод updateItem не понятен 
сам до него полностью додуматься не смог

Задача: Lord of the Rings RPG

---

src/main/java/school/faang/insta/FilterProcessor.java
src/main/java/school/faang/insta/Image.java
src/main/java/school/faang/insta/Main.java

BJS2-34775

---

src/main/java/school/faang/meta/Notification.java
src/main/java/school/faang/meta/NotificationManager.java
src/test/java/school/faang/meta/NotificationManagerTest.java

По тестам понимаю что ничего не проверяют, просто по выводу в консоль смотрю

added meta

---

src/main/java/school/faang/cash/Main.java
src/main/java/school/faang/cash/Student.java
src/main/java/school/faang/cash/Subject.java

BJS2-32447

---

src/main/java/BJS2_34855_Instagramm/FilterProcessor.java
src/main/java/BJS2_34855_Instagramm/Image.java
src/main/java/BJS2_34855_Instagramm/Main.java

Частично решил задачу благодаря ИИ, очень долго ломал голову над комбинированием фильтром, сказывается не хватка примеров использования функций в материалах по этой теме. Приходится использовать ИИ либо сторонние материалы, чтобы решить и понять как это работает.

BJS2-34855 Instagram

---

src/main/java/school/faangSprint2/t9/Main.java
src/main/java/school/faangSprint2/t9/Solution.java

BJS2-35145

---

src/main/java/tasks/bjs2_31534/Main.java
src/main/java/tasks/bjs2_31534/User.java

Создан класс User, реализован метод fingHobbyLovers для поиска пользователей у которых есть любимое хобби из списка. Создан класс Main для тестирования функционала.

bjs2-31534 : Коллекционируем пользователей

---

src/main/java/school/faang/meta/Main.java
src/main/java/school/faang/meta/Notification.java
src/main/java/school/faang/meta/NotificationManager.java

Создал метод registerHandler, которы записывает в мапу тип оповещения и действие, которое должно быть выполнено для данного типа оповещения. И метод sendNotification, который принимает оповещение и выполняет действие взависимости от оповещения.

Мета вселенная?

---

.gitignore
Readme.txt
src/main/java/tasks/bjs2_33307/EventController.java
src/main/java/tasks/bjs2_33307/EventType.java
src/main/java/tasks/bjs2_33307/Main.java
src/main/java/tasks/bjs2_33307/StreamEvent.java

Решил чуть расширить задание для себя:  
Создал класс StreamEvent. (Базовое задание)
Создал перечисления EventType. Изменил в коллекция "тип события" со String на EventType.
Создал класс EventController, в котором реализована возможность управления событиями.
Реализовал возможности генерации событий(при инициализации конструктора), вывода, поиска, добавление и удаления событий.
Создал класс Main для тестирования функционала.

bjs2-33307 : Ловим события

---

src/main/java/school/faang/droidSecrets/Droid.java
src/main/java/school/faang/droidSecrets/DroidMessageEncryptor.java
src/test/java/DroidEncryptorTest.java

Метод на шифрацию конечно отвал башки, частично сделал сам, частично подсмотрел в доп.материалах, плюс от себя немного изменил то как происходит шифрация/дешифрация цифр.

BJS2-34177

---

src/main/java/school/faang/error/ErrorHandler.java
src/main/java/school/faang/error/ExceptionHandler.java
src/main/java/school/faang/error/Main.java
src/main/java/school/faang/error/ThrowableSupplier.java

BJS2-33430

---

src/main/java/school/faang/instagram/FilterProcessor.java
src/main/java/school/faang/instagram/Image.java
src/main/java/school/faang/instagram/Main.java

1. Создать класс Image, который хранит информацию о фотографии:
name (имя файла),
description (описание, которое обновляется с каждым применённым фильтром).
2. Создать класс FilterProcessor с двумя методами:
- applyFilter: применяет фильтр к изображению. Фильтр — это функция, которая берёт одно изображение и возвращает новое с изменениями. Метод applyFilter принимает объект типа Image и функцию высокого порядка для применения фильтра, возвращает новый объект типа Image с применённым фильтром
- combineFilters: объединяет два фильтра в один, чтобы они применялись последовательно. Принимает две функции высокого порядка и возвращает новую функцию высокого порядка, которая последовательно применяет обе функции.
3. Создать несколько фильтров (например, "черно-белый", "сепия" и "виньетка") с …

BJS2-35030 Фильтры Instagram

---

src/main/java/school/faangSprint2/t11/DictionaryProcessor.java
src/main/java/school/faangSprint2/t11/Main.java

BJS2-33477

---

src/main/java/school/faang/translator/DictionaryProcessor.java
src/main/java/school/faang/translator/Main.java

Задача: Google Переводчик под нашим контролем.

BJS2-33478 - Java 8: Google Переводчик под нашим контролем

---

src/main/java/metaUniverse/Main.java
src/main/java/metaUniverse/Notification.java
src/main/java/metaUniverse/NotificationManager.java

`@Getter
private static final List<String> BAN_WORDS = List.of("golang", "c#");`
Есть вопрос по целесообразности такого доступа или лучше сделать package private (default)?
В остальном, 4 пункт конечно больно для первого раз для осознания.

Meta universe

---

src/main/java/school/faang/meta/Main.java
src/main/java/school/faang/meta/Notification.java
src/main/java/school/faang/meta/NotificationManager.java

Задача: Meta-вселенная

---

src/main/java/school/faang/BJS233548/Email.java
src/main/java/school/faang/BJS233548/EmailProcessor.java
src/main/java/school/faang/BJS233548/Main.java

Долго парился с stream(). Искал возможность все красиво в одну строчку бахнуть но столкнулся с проблемой Consumer и Function не получилось логику запихнуть в лямбды, поэтому выписал их так. Если есть возможность их как-то более красивше сделать, дайте знать)

Slava bjs2 33548

---

src/main/java/tasks/bjs2_32536/Main.java
src/main/java/tasks/bjs2_32536/Student.java

Добавлен класс Student
Добавлен класс Main для тестирования функционала.

bjs2-32536 : Считаем прогулы

---

src/main/java/school/faang/metauniverse/Main.java
src/main/java/school/faang/metauniverse/Notification.java
src/main/java/school/faang/metauniverse/NotificationManager.java

1. Создайте класс Notification с полями type (тип оповещения) и message (сообщение оповещения).
2. Создайте класс NotificationManager, который будет содержать:
- Метод registerHandler, принимающий идентификатор оповещения и функциональный интерфейс (например, Consumer<Notification>), и добавляющий их в Map.
- Метод sendNotification, который принимает объект Notification и вызывает соответствующий обработчик оповещения из Map по типу этого оповещения.
3. Зарегистрируйте несколько обработчиков оповещений с помощью лямбда-выражений и функционального интерфейса Consumer<Notification>.

BJS2-34930 Meta-вселенная?

---

src/main/java/school/faangSprint2/t8/ListOperations.java
src/main/java/school/faangSprint2/t8/Main.java

BJS2-35512

---

src/main/java/catchingevents/Main.java
src/main/java/catchingevents/StreamEvent.java

Решение задачи "Java HashMap: Ловим события"

Решение задачи "Java HashMap: Ловим события"

---

src/main/java/school/faangSprint2/t12/Main.java
src/main/java/school/faangSprint2/t12/MessageFilter.java
src/main/java/school/faangSprint2/t12/MessageProcessor.java

BJS2-34563

---

src/main/java/school/faang/lordoftherings/Character.java
src/main/java/school/faang/lordoftherings/InventoryManager.java
src/main/java/school/faang/lordoftherings/Item.java
src/main/java/school/faang/lordoftherings/Main.java

1. Создайте класс Item с полями:
name — название предмета (например, "Кольцо"),
value — стоимость предмета (например, 1000).
2. Создайте класс Character, у которого есть поле:
inventory — список предметов (объекты Item), которые персонаж носит с собой.
3. Создайте класс InventoryManager с тремя методами:
- addItem: добавляет предмет в инвентарь персонажа и выполняет дополнительное действие (например, выводит сообщение о добавлении предмета).
- removeItem: удаляет предмет из инвентаря, если он удовлетворяет условию, заданному предикатом (например, удалить все кольца).
- updateItem: находит предмет в инвентаре по условию и обновляет его с помощью функции (например, удвоить стоимость предмета).

BJS2-33887 Lord of the Rings RPG

---

src/main/java/tasks/bjs2_32886/Main.java
src/main/java/tasks/bjs2_32886/WebPage.java

Добавлен класс WebPage
Добавлен класс Main для тестирования функционала.

bjs2-32886 : Поисковый мини-движок Google

---

src/main/java/belovedhogwarts/Main.java
src/main/java/belovedhogwarts/SpellAction.java
src/main/java/belovedhogwarts/SpellCaster.java

Решение задачи: "Хогвартс, Хогвартс, наш любимый Хогвартс".

Решение задачи: "Хогвартс, Хогвартс, наш любимый Хогвартс".

---

src/main/java/school/faangSprint2/t13/FareCalculator.java
src/main/java/school/faangSprint2/t13/Main.java

BJS2-34350

---

src/main/java/school/faang/BJS234735/Notification.java
src/main/java/school/faang/BJS234735/NotificationManager.java

BJS2-34735. Жду фитбека. Спасибо большое

---

src/main/java/school/faang/meta/Main.java
src/main/java/school/faang/meta/Notification.java
src/main/java/school/faang/meta/NotificationManager.java

BJS2-34747

---

src/main/java/school/faang/BJS234742/Main.java
src/main/java/school/faang/BJS234742/dto/Notification.java
src/main/java/school/faang/BJS234742/service/NotificationManager.java

https://faang-school.atlassian.net/browse/BJS2-34742

BJS2-34742: Meta-вселенная?

---

src/main/java/school/faang/bjs231347/dto/User.java
src/main/java/school/faang/bjs231564/Main.java

https://faang-school.atlassian.net/browse/BJS2-31564

BJS2-31564: Регистрация пользователей

---

src/main/java/school/faang/collection/Main.java
src/main/java/school/faang/collection/User.java

Abz9286 to 31612

---

src/main/java/school/faangSprint2/t10/Main.java
src/main/java/school/faangSprint2/t10/UserAction.java
src/main/java/school/faangSprint2/t10/UserActionAnalyzer.java

BJS2-35388

---

src/main/java/metauniverse/Main.java
src/main/java/metauniverse/Notification.java
src/main/java/metauniverse/NotificationManager.java

Решение задачи: "Meta-вселенная?".

Решение задачи: "Meta-вселенная?".

---

src/main/java/school/faang/countAbsenteeism/Main.java
src/main/java/school/faang/countAbsenteeism/Student.java

solved сounting absenteeism task

Abz9286 bjs2 32572

---

src/main/java/school/faang/errorhandling/ErrorHandler.java
src/main/java/school/faang/errorhandling/Main.java

1. Написать статический метод withErrorHandling, который принимает две лямбды: одна выполняет основное действие (например, вызов удалённого сервиса), вторая — обрабатывает ошибки, если они возникнут.
2. Метод должен быть универсальным и возвращать тип T.
3. Вторая лямбда должна принимать исключение Exception и делать что-то с ним (например, возвращать дефолтное значение).
4. Придумайте подходящий функциональный интерфейс для первого действия?

BJS2-33577 Обрабатываем ошибки красиво

---

src/main/java/gmail_rich_filter_33710/Email.java
src/main/java/gmail_rich_filter_33710/EmailProcessor.java
src/main/java/gmail_rich_filter_33710/Main.java

ура, решил без подсказок ИИ, но через stream

Alekseyb86 bsj2 33710 gmail rich filter

---

src/main/java/school/faangSprint2/t14/Calculator.java
src/main/java/school/faangSprint2/t14/CalculatorImplementation.java
src/main/java/school/faangSprint2/t14/Main.java

BJS2-33916

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/StringAndNumberOperator.java

Задача: Потренируем StreamAPI 1

BJS2-35591 - Java 8: Потренируем StreamAPI 1

---

src/main/java/school/faang/richfilters/Email.java
src/main/java/school/faang/richfilters/EmailProcessor.java
src/main/java/school/faang/richfilters/Main.java

1. Создайте класс Email с полями:
subject — тема письма;
body — текст письма;
isImportant — флаг, указывающий, важное письмо или нет.
2. Создайте класс EmailProcessor с методом processEmails.
3. Метод processEmails должен:
принимать список входящих писем;
фильтровать их с помощью Predicate<Email>
преобразовывать тело письма с помощью Function<Email, String>.
обрабатывать каждое письмо с помощью Consumer<Email>
4. Создайте несколько лямбда-выражений для Predicate, Consumer, и Function, чтобы настроить фильтрацию и обработку писем по вашему выбору.
5. Протестируйте систему, обрабатывая несколько писем и выводя результаты в консоль.

BJS2-33820 Gmail Rich Filters

---

src/main/java/school/faang/googlesearch/Main.java
src/main/java/school/faang/googlesearch/SearchEngine.java
src/main/java/school/faang/googlesearch/WebPage.java

https://faang-school.atlassian.net/browse/BJS2-33030

Java HashMap: Поисковой мини-движок Google

---

src/main/java/school/faang/droid/Droid.java
src/main/java/school/faang/droid/DroidMessageEncryptor.java
src/main/java/school/faang/droid/Main.java

BJS2-34216

---

src/main/java/practiceStreamAPI_2/Main.java

не знал что List.of() возвращает неизменяемый список, голову сломал пока не загуглил)))

Alekseyb86 bsj2 35237 practice stream api 2

---

src/main/java/school/faangSprint2/t16/TriangleAreaCalculator.java

BJS2-34031

---

src/main/java/school/faangSprint2/t17/CsvConverter.java
src/main/java/school/faangSprint2/t17/Main.java
src/main/java/school/faangSprint2/t17/MatrixJoiner.java
src/main/java/school/faangSprint2/t17/VectorJoiner.java

BJS2-34247

---

src/main/java/school/faang/spam/Main.java
src/main/java/school/faang/spam/MessageFilter.java
src/main/java/school/faang/spam/MessageProcessor.java

BJS2-34568 - Java 8: Фильтруем спам

---

src/main/java/school/faang_sprint_2/intagram_filters/FilterProcessor.java
src/main/java/school/faang_sprint_2/intagram_filters/Image.java
src/main/java/school/faang_sprint_2/intagram_filters/Main.java

Фильтры Instagram, 

---

src/test/java/StreamApi1/ListOperation.java
src/test/java/StreamApi1/Main.java

в двух местах комментарии - это для меня, чтобы запоминать что откуда берется

stream api1

---

src/main/java/gmailfilters/Email.java
src/main/java/gmailfilters/EmailProcessor.java
src/main/java/gmailfilters/Main.java

Решение задачи: "Gmail Rich Filters".

Решение задачи: "Gmail Rich Filters".

---

src/main/java/school/faangSprint2/t15/Location.java
src/main/java/school/faangSprint2/t15/LocationSearchEngine.java
src/main/java/school/faangSprint2/t15/Main.java

BJS2-34482

---

src/main/java/exceptionhandling/ErrorHandler.java
src/main/java/exceptionhandling/ExceptionHandler.java
src/main/java/exceptionhandling/Main.java
src/main/java/exceptionhandling/RemoteService.java

Решение задачи "Обрабатываем ошибки красиво".

Решение задачи "Обрабатываем ошибки красиво".

---

src/main/java/school/faang/m1s2/bjs2_34700_meta/Main.java
src/main/java/school/faang/m1s2/bjs2_34700_meta/Notification.java
src/main/java/school/faang/m1s2/bjs2_34700_meta/NotificationManager.java

Часть с * сделал с помощью Function<>, чтобы было. Но такое себе решение, чувствуется костыль, а без лямбды можно быть прописать проще :)

BJS2-34700 Notifications: Task done

---

src/main/java/school/faang/bjs2_33881/ErrorMassagesValidate.java
src/main/java/school/faang/bjs2_33881/Main.java
src/main/java/school/faang/bjs2_33881/SpellAction.java
src/main/java/school/faang/bjs2_33881/SpellCaster.java
src/test/java/school/faang/bjs2_33881/SpellCasterTest.java

…terTest.
added method:cast and validateObject for SpellCaster,cast for SpellCasterTest

mikhailshapjr-BJS2-33881 Хогвартс, Хогвартс, наш любимый Хогвартс

---

src/main/java/school/faangSprint2/t19/DataAnalyzer.java
src/main/java/school/faangSprint2/t19/Job.java
src/main/java/school/faangSprint2/t19/JobScraper.java
src/main/java/school/faangSprint2/t19/JobStreamProcessor.java
src/main/java/school/faangSprint2/t19/Main.java

BJS2-34926

---

src/main/java/org/example/service/trainingStream1/ListOperations.java
src/main/java/org/example/service/trainingStream1/Main.java

feat(): operations to list with stream
add functions which operate the list with stream API

Training with stream api

---

src/main/java/school/faang/jobanalysis/DataAnalyzer.java
src/main/java/school/faang/jobanalysis/Job.java
src/main/java/school/faang/jobanalysis/JobScraper.java
src/main/java/school/faang/jobanalysis/JobStreamProcessor.java
src/main/java/school/faang/jobanalysis/Main.java
src/main/java/school/faang/jobanalysis/vacancies.json

я фиг знает как, но оно работает

Анализатор вакансий

---

src/main/java/school/faang/stream/two/StreamOperations.java

BJS2-35150

---

src/main/java/school/faang/streamapi1/ListOperations.java
src/main/java/school/faang/streamapi1/Main.java

Плохо что в доп. материалах на платформе все решение дано явно)

BJS2-35707 Потренируем StreamAPI 1

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/Operations.java

Использование примера для проверки работоспособности

Реализация статических методов

---

src/main/java/school/faang/stream/one/ListOperations.java

BJS2-35500

---

src/main/java/school/faang/sprint_2/bjs2_34689/Main.java
src/main/java/school/faang/sprint_2/bjs2_34689/Notification.java
src/main/java/school/faang/sprint_2/bjs2_34689/NotificationManager.java
src/main/java/school/faang/sprint_2/bjs2_35511/Main.java
src/main/java/school/faang/sprint_2/bjs2_35511/UserAction.java
src/main/java/school/faang/sprint_2/bjs2_35511/UserActionAnalyzer.java

Task "Анализ активности пользователей в социальной сети" solution.

deema-bjs2-35511

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/UserAction.java
src/main/java/school/faang/UserActionAnalyzer.java

Задача: Анализ активности пользователей в социальной сети.

BJS2-35458 - Java 8: Анализ активности пользователей в социальной сети

---

src/main/java/org/example/model/usersActionInSocialMedia/UserAction.java
src/main/java/org/example/service/usersActionInSocialMedia/Main.java
src/main/java/org/example/service/usersActionInSocialMedia/UserActionAnalyzer.java

add methods about get statistics into UserActionAnalyzer class and tested it in Main with given data

feat(user action): get user action statistics with stream

---

src/main/java/school/faangSprint2/t18/Main.java
src/main/java/school/faangSprint2/t18/Student.java
src/main/java/school/faangSprint2/t18/StudentManagementSystem.java

BJS2-35216

---

src/main/java/school/faang/godbless/bjs2_33922/Calculations.java
src/main/java/school/faang/godbless/bjs2_33922/Calculator.java
src/main/java/school/faang/godbless/bjs2_33922/Main.java

calculations

---

src/main/java/school/faang/godbless/bjs2_35446/Main.java
src/main/java/school/faang/godbless/bjs2_35446/UserAction.java
src/main/java/school/faang/godbless/bjs2_35446/UsersActivityManager.java

Анализ активности пользователей в социальной сети

Annaaplavina bjs2 35446

---

src/main/java/tasks/bjs2_37752/MailSender.java
src/main/java/tasks/bjs2_37752/SenderRunnable.java

Добавлен класс SenderRunnable
Добавлен класс MailSender

bjs2-37752 : Вы работаете в Microsoft!

---

src/main/java/school/faang/bjs2_31447/Archer.java
src/main/java/school/faang/bjs2_31447/Character.java
src/main/java/school/faang/bjs2_31447/Main.java
src/main/java/school/faang/bjs2_31447/Warrior.java

added classes: Character,Warrior,Archer
added: implementation of the attack method, tests

mikhailshapjr-BJS2-31447

---

src/main/java/school/faang/bjs233834/Main.java
src/main/java/school/faang/bjs233834/SpellAction.java
src/main/java/school/faang/bjs233834/SpellCaster.java

https://faang-school.atlassian.net/browse/BJS2-33834

BJS2-33834: Хогвартс, Хогвартс, наш любимый Хогвартс

---

src/main/java/trainingstream1/ListOperations.java
src/main/java/trainingstream1/Main.java

Решение задачи "Потренируем StreamAPI 1".

Решение задачи "Потренируем StreamAPI 1".

---

src/main/java/school/faang/user/activitiy/Main.java
src/main/java/school/faang/user/activitiy/UserAction.java

BJS2-35400

---

src/main/java/tasks/bjs2_35850/Archer.java
src/main/java/tasks/bjs2_35850/Army.java
src/main/java/tasks/bjs2_35850/Character.java
src/main/java/tasks/bjs2_35850/Mage.java
src/main/java/tasks/bjs2_35850/Main.java
src/main/java/tasks/bjs2_35850/PowerCalculator.java
src/main/java/tasks/bjs2_35850/Swordsman.java
src/main/java/tasks/bjs2_35850/Warrior.java

Добавлены классы. Родительский Character и дочерние (Archer, Mage, Warrior, Swordsman) 
Добавлен класс Army хранящий список класса Character 
Добавлен класс PowerCalculator занимающийся расчетом мощи всех бойцов в армии, а точнее для каждого бойца в отдельном потоке.

bjs2-35850 : Распределенная армия героев меча и магии

---

src/main/java/school/faang/stream/practice/ListOperations.java
src/main/java/school/faang/stream/practice/Main.java
src/main/java/school/faang/user_registration/User.java

completed BJS2-35647 and ready for review

---

src/main/java/activityanalysis/Main.java
src/main/java/activityanalysis/UserAction.java
src/main/java/activityanalysis/UserActionAnalyzer.java

Решение задачи "Анализ активности пользователей в социальной сети".

Решение задачи "Анализ активности пользователей в социальной сети".

---

src/main/java/school/faang/bjs2_33737/Main.java
src/main/java/school/faang/bjs2_33737/constans/ErrMessagesValidate.java
src/main/java/school/faang/bjs2_33737/model/Email.java
src/main/java/school/faang/bjs2_33737/model/ValidatorEmailProcessor.java
src/main/java/school/faang/bjs2_33737/sevice/EmailProcessor.java
src/test/java/school/faang/bjs2_33737/sevice/EmailProcessorTest.java

…Processor.
added Method: processEmails for EmailProcessor; validateNotNull,validateProcessEmails for ValidatorEmailProcessor.

mikhailshapjr-BJS2-33737 Gmail Rich Filters

---

src/main/java/school/faang/BJS2_31948/App.java

I finished the third task about the rare book store

Urmat feature b bjs2 31948

---

bookDescription
src/main/java/school/faang/BJS2_31948/App.java

I finished the fourth task about the rare book store

Urmat bjs2 31596

---

.gitignore
Readme.txt

от ветки lexsandr-bsj2-31966 создал 2 ветки ветки lexsandr-bsj2-31966-feature1 и lexsandr-bsj2-31966-feature2.
feature1 добавил в readme изменения, сделал PR и смержил код. Далее в ветке feature2 в том же  файле поправил ту же строку. Создал PR, появился конфликт. С поможешь IDE решил конфликт и замержил изменения соединив изменившиеся строки из ветки feature1 и feature2
Ссылки на связанные PR.
feature1 - https://github.com/CorporationX/god_bless/pull/11577
feature2 - https://github.com/CorporationX/god_bless/pull/11579/

bjs2-31966 : Магазин редких книг, Шаг 3.

---

src/main/java/school/faang/m1s3/bjs2_36254_walmart/CashierThread.java
src/main/java/school/faang/m1s3/bjs2_36254_walmart/Main.java

Какая-то корявая задача :) Вроде и абстракции в условии много, но зачем-то делать рандом между обезличенными кассирами. Покупатель идет туда, где нет очереди, а между пустыми кассами разницы нет. А тут рандомом можно нагрузить всех в один поток при прочих пустых кассах (потоках).
Кароч, сделано (лениво) и работает :)

BJS2-36254 Walmart: task done

---

src/main/java/school/faang/godbless/bjs2_31293/Archer.java
src/main/java/school/faang/godbless/bjs2_31293/Attack.java
src/main/java/school/faang/godbless/bjs2_31293/Character.java
src/main/java/school/faang/godbless/bjs2_31293/Main.java
src/main/java/school/faang/godbless/bjs2_31293/Warrior.java

characters

---

src/main/java/doubleCache/Grade.java
src/main/java/doubleCache/Main.java
src/main/java/doubleCache/Student.java
src/main/java/doubleCache/Subject.java

Double Caching

---

src/main/java/school/faang/bjs2_34911/Main.java
src/main/java/school/faang/bjs2_34911/constants/ErrMessagesValidate.java
src/main/java/school/faang/bjs2_34911/model/Filter.java
src/main/java/school/faang/bjs2_34911/model/FilterDescription.java
src/main/java/school/faang/bjs2_34911/model/Image.java
src/main/java/school/faang/bjs2_34911/service/FilterProcessor.java
src/main/java/school/faang/bjs2_34911/service/ValidatorFilterProcessor.java
src/test/java/school/faang/bjs2_34911/service/FilterProcessorTest.java

…erProcessor,ValidatorFilterProcessor.
added Method: applyFilter,combineFilters for FilterProcessor; validateApplyFilter,validateCombineFilters for ValidatorFilterProcessor.

mikhailshapjr-BJS2-34911 Фильтры Instagram

---

src/main/java/school/faang/micenice/Food.java
src/main/java/school/faang/micenice/House.java
src/main/java/school/faang/micenice/Main.java
src/main/java/school/faang/micenice/Room.java

Поигрался в инициализации с распаралеливанием самого процесса инициализации, понимаю что это совсем необязательно, но все-таки об этом тема, хотелось что-то попробовать самому)

"Mice are very nice!"

---

src/main/java/school/faang/godbless/bjs2_37771/MailSender.java
src/main/java/school/faang/godbless/bjs2_37771/SenderRunnable.java

bjs2 37771 Вы работаете в Microsoft!

---

src/main/java/school/faang/lambda/metaverse/Main.java
src/main/java/school/faang/lambda/metaverse/Notification.java
src/main/java/school/faang/lambda/metaverse/NotificationManager.java
src/main/java/school/faang/user_registration/User.java

completed BJS2-34808 ready for review

---

src/main/java/school/faangSprint3/t03/Chore.java
src/main/java/school/faangSprint3/t03/WeasleyFamily.java

BJS2-36657

---

src/main/java/school/faang/multithreading/spotify/Music.java
src/main/java/school/faang/multithreading/spotify/Player.java

BJS2-37173

---

src/main/java/school/faang/godbless/bjs2_36735/Chore.java
src/main/java/school/faang/godbless/bjs2_36735/Main.java
src/main/java/school/faang/godbless/bjs2_36735/WeasleyFamily.java

They were very nice but extremely poor

They were very nice but extremely poor BJS2-36735

---

src/main/java/school/faang/microsoft/MailSender.java
src/main/java/school/faang/microsoft/SenderRunnable.java

Задача: Вы работаете в Microsoft!

BJS2-37765 - Многопоточность: Вы работаете в Microsoft!

---

src/main/java/school/faangSprint3/t01/MailSender.java
src/main/java/school/faangSprint3/t01/SenderRunnable.java

BJS2-37756

---

src/main/java/school/faang/mice/Food.java
src/main/java/school/faang/mice/House.java
src/main/java/school/faang/mice/Room.java

1. Создайте класс House, который будет содержать список всех комнат дома.
2. Создайте класс Room, который будет содержать список еды, находящейся в этой комнате.
3. Создайте класс Food, который будет описывать еду (например, её название).
4. В классе House реализуйте метод collectFood(), который будет:
- Собрать еду из двух случайно выбранных комнат.
- Удалить собранную еду из списков еды этих комнат.
- Добавить собранную еду в общий список собранной еды.
5. В методе main() класса House:
- Создайте объект класса House и заполните его комнаты и еду в каждой комнате.
- Создайте пул потоков на 5 потоков с помощью newScheduledThreadPool.
- Для каждого потока назначьте задачу, которая будет запускать сбор еды из двух комнат с интервалом в 30 секунд c помощью метода scheduleAtFixedRate
- Когда …

BJS2-36245 Mice are very nice!

---

src/main/java/school/faang/BJS2_37787/MailSender.java
src/main/java/school/faang/BJS2_37787/SenderRunnable.java

complete the task "Вы работаете в Microsoft!

---

src/main/java/school/faang/multithreading/microsoft/MailSender.java
src/main/java/school/faang/multithreading/microsoft/SenderRunnable.java

BJS2-37799

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/task2102/Filter.java
src/main/java/school/faang/task2102/FilterType.java
src/main/java/school/faang/task2102/Main.java
src/main/java/school/faang/task2102/Notification.java
src/main/java/school/faang/task2102/NotificationManager.java

Два вопроса оставил в самом коде с комментом TODO

roman.shipilov-BJS2-34786

---

src/main/java/school/faangSprint3/t02/Archer.java
src/main/java/school/faangSprint3/t02/Army.java
src/main/java/school/faangSprint3/t02/Mage.java
src/main/java/school/faangSprint3/t02/Main.java
src/main/java/school/faangSprint3/t02/PowerCalculator.java
src/main/java/school/faangSprint3/t02/Swordsman.java
src/main/java/school/faangSprint3/t02/Unit.java

BJS2-35858

---

src/main/java/org/example/model/microsoft/SenderRunnable.java
src/main/java/org/example/service/microsoft/MailSender.java

add model SenderRunnable which take in constructor start and end indexes for number of notification which call in main method and add service MailSender where the methods call

feat(you work in microsoft): added SenderRunnable class which call the method run with thread from MailSender class

---

src/main/java/school/faang/multithreading/cachedpool/Chore.java
src/main/java/school/faang/multithreading/cachedpool/Main.java
src/main/java/school/faang/multithreading/cachedpool/WeasleyFamily.java

BJS2-36678

---

src/main/java/school/faang/weasleychores/Chore.java
src/main/java/school/faang/weasleychores/WeasleyFamily.java

Задача: They were very nice but extremely poor.

BJS2-36685 - Многопоточность: They were very nice but extremely poor

---

src/main/java/school/faang/sprint_3/bjs2_36880_weasleyFamily/Chore.java
src/main/java/school/faang/sprint_3/bjs2_36880_weasleyFamily/WeasleyFamily.java

Task "They were very nice but extremely poor" solution.

deema-bjs2-36880

---

src/main/java/school/faangSprint3/t05/Music.java
src/main/java/school/faangSprint3/t05/Player.java

BJS2-37218

---

src/main/java/school/faang/BJS2_35881/Army.java
src/main/java/school/faang/BJS2_35881/Main.java
src/main/java/school/faang/BJS2_35881/characters/Archer.java
src/main/java/school/faang/BJS2_35881/characters/Character.java
src/main/java/school/faang/BJS2_35881/characters/Mage.java
src/main/java/school/faang/BJS2_35881/characters/Swordsman.java

complete the task "Распределенная армия героев меча и магии"

---

src/main/java/school/faang/m1s3/bjs2_36789_supercow/Boss.java
src/main/java/school/faang/m1s3/bjs2_36789_supercow/Main.java
src/main/java/school/faang/m1s3/bjs2_36789_supercow/Player.java

BJS2-36789 Supercow: task done

---

src/main/java/school/faang/m1s3/bjs2_37080_broforce/Game.java
src/main/java/school/faang/m1s3/bjs2_37080_broforce/Main.java
src/main/java/school/faang/m1s3/bjs2_37080_broforce/Player.java

Просто кайф!
А делать задачу по великой игре - кайф вдвойне!
Параллелизм + синхронизация - суперкомбо!

BJS2-37080 Broforce: task done

---

src/main/java/school/faangSprint2/t22/Coordinates.java
src/main/java/school/faangSprint2/t22/FlipDirection.java
src/main/java/school/faangSprint2/t22/MatrixTransformProcessor.java
src/main/java/school/faangSprint2/t22/MatrixTransformer.java

BJS2-33976

---

src/main/java/school/faangSprint2/t23/Employee.java
src/main/java/school/faangSprint2/t23/Main.java

BJS2-34868

---

src/main/java/school/faangSprint2/t20/CompanyDataLoader.java
src/main/java/school/faangSprint2/t20/EnvironmentalImpact.java
src/main/java/school/faangSprint2/t20/EnvironmentalImpactAnalyzer.java
src/main/java/school/faangSprint2/t20/Main.java
src/main/java/school/faangSprint2/t20/StatisticsAggregator.java

BJS2-35022

---

src/main/java/school/faangSprint2/t21/LocalDateTimeAdapter.java
src/main/java/school/faangSprint2/t21/Product.java
src/main/java/school/faangSprint2/t21/ProductOrder.java
src/main/java/school/faangSprint2/t21/RecommendationDemo.java
src/main/java/school/faangSprint2/t21/RecommendationService.java
src/main/java/school/faangSprint2/t21/UserProfile.java
src/main/java/school/faangSprint3/t01/MailSender.java
src/main/java/school/faangSprint3/t01/SenderRunnable.java

BJS2-35319

---

src/main/java/school/faang/spaceX/Main.java
src/main/java/school/faang/spaceX/RocketLaunch.java

Не до конца уверен что правильно понял суть задания, но вроде сделал как надо.

"Космическая программа SpaceX"

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/distributedarmy/Archer.java
src/main/java/school/faang/distributedarmy/Army.java
src/main/java/school/faang/distributedarmy/Calculator.java
src/main/java/school/faang/distributedarmy/Mage.java
src/main/java/school/faang/distributedarmy/Main.java
src/main/java/school/faang/distributedarmy/Swordsman.java
src/main/java/school/faang/distributedarmy/Unit.java

Задача: Распределенная армия героев меча и магии

BJS2-35877 - Многопоточность: Распределенная армия героев меча и магии

---

src/main/java/school/faang/multithreading/army/Archer.java
src/main/java/school/faang/multithreading/army/Army.java
src/main/java/school/faang/multithreading/army/Mage.java
src/main/java/school/faang/multithreading/army/Main.java
src/main/java/school/faang/multithreading/army/PowerCalculator.java
src/main/java/school/faang/multithreading/army/Powerable.java
src/main/java/school/faang/multithreading/army/Swordsman.java
src/main/java/school/faang/multithreading/army/Unit.java

BJS2-35880

---

src/main/java/school/faang/sprint_3/bjs2_35887_distributedArmyHomm/Archer.java
src/main/java/school/faang/sprint_3/bjs2_35887_distributedArmyHomm/Army.java
src/main/java/school/faang/sprint_3/bjs2_35887_distributedArmyHomm/Mage.java
src/main/java/school/faang/sprint_3/bjs2_35887_distributedArmyHomm/Main.java
src/main/java/school/faang/sprint_3/bjs2_35887_distributedArmyHomm/PowerCalculator.java
src/main/java/school/faang/sprint_3/bjs2_35887_distributedArmyHomm/Swordsman.java
src/main/java/school/faang/sprint_3/bjs2_35887_distributedArmyHomm/Unit.java

Task "Распределенная армия героев меча и магии" solution.

deema-bjs2-35887

---

src/main/java/tasks/bjs2_36650/Chore.java
src/main/java/tasks/bjs2_36650/WeasleyFamily.java

Создан класс Chore для хранения задач.
Создан класс WeasleyFamily и метод main для тестирования функционала.

bjs2-36650 : They were very nice but extremely poor

---

src/main/java/school/faang/task2104/Email.java
src/main/java/school/faang/task2104/EmailProcessor.java
src/main/java/school/faang/task2104/Main.java
src/main/java/school/faang/task2104/task.md

task2104 / Gmail Rich Filters

---

src/main/java/school/faangSprint3/t04/Food.java
src/main/java/school/faangSprint3/t04/House.java
src/main/java/school/faangSprint3/t04/Main.java
src/main/java/school/faangSprint3/t04/Room.java

BJS2-36105

---

src/main/java/school/faang/multithreading/supercow/Boss.java
src/main/java/school/faang/multithreading/supercow/Game.java
src/main/java/school/faang/multithreading/supercow/Player.java

BJS2-36799

---

src/main/java/school/faangSprint3/t07/Boss.java
src/main/java/school/faangSprint3/t07/Main.java
src/main/java/school/faangSprint3/t07/Player.java

BJS2-36806

---

src/main/java/school/faang/streamapithree/AverageSalaryCalculator.java
src/main/java/school/faang/streamapithree/CommonFriendsFinder.java
src/main/java/school/faang/streamapithree/Main.java
src/main/java/school/faang/streamapithree/PalindromeNumbersFinder.java
src/main/java/school/faang/streamapithree/PalindromeSubstringFinder.java
src/main/java/school/faang/streamapithree/PerfectNumberFinder.java

https://faang-school.atlassian.net/browse/BJS2-35007

Потренируем StreamAPI 3

---

src/main/java/tomandjerry/Food.java
src/main/java/tomandjerry/House.java
src/main/java/tomandjerry/Room.java

feat: House, Food and Room class with grabFood methods implemented.
Пришлось использовать syncronized к методу grabAllFood(), чтобы потоки корректно собирали еду. Не решил вопрос о том, как потокам не обращаться повторной к одной и той же комнате, но общий сбор еды происходит корректно.

Denis ignatenko bjs2 36092

---

src/main/java/school/faang/stream_2/practice/ListOfSorting.java
src/main/java/school/faang/stream_2/practice/Main.java
src/main/java/school/faang/user_registration/User.java

completed BJS2-35253

---

src/main/java/bjs2_35742/Boss.java
src/main/java/bjs2_35742/Main.java
src/main/java/bjs2_35742/Player.java

Пару вопросов:
1) Насколько правильно создавать лист из игроков, которые учавствуют в битве с боссом? Сделал это сугубо для того, чтобы можно было дернуть игрока и убрать его из битвы. Иначе если забрать игрока из списка в main, то есть опасения, что все может упасть из-за того, что порядок добавления игроков к битве не гарантирован
2) Есть какой-нибудь более элегантный способ дождаться пока некоторые потоки отработают прежде чем продолжать работу в основном потоке (речь о 30-32 строчках в Main)? По сути у меня два потока полностью отрабатывают, а третий уходит в режим ожидания, и не продолжит свою работу, пока не удалю одного из игроков. Но, без Thread.sleep() главный поток опережает остальные и пытается достать несуществуюшего игрока, что приводит к IndexOutOfBoundsException. Кажется, …

feat: added boss battles (Boss and Player)

---

src/main/java/school/faang/paveTheWay/City.java
src/main/java/school/faang/paveTheWay/CityWorker.java
src/main/java/school/faang/paveTheWay/ListsInitializer.java
src/main/java/school/faang/paveTheWay/Locatable.java
src/main/java/school/faang/paveTheWay/Location.java
src/main/java/school/faang/paveTheWay/Monster.java
src/main/java/school/faang/paveTheWay/WitcherMultithread.java
src/main/java/school/faang/paveTheWay/WitcherSingleThread.java

Сравнил время выполнения с использованием потоков и без, с потоками действительно на пару миллисекунд быстрее выполняется программа, в более комплексных программах думаю разница будет более ощутимая.

"Путь пальцем проложи…"

---

src/main/java/school/faang/multithreading/photo/GooglePhotos.java
src/main/java/school/faang/multithreading/photo/GooglePhotosAutoUploader.java

BJS2-37118

---

src/main/java/school/faang/multithreading/youtube/Main.java
src/main/java/school/faang/multithreading/youtube/VideoManager.java

BJS2-37522

---

src/main/java/school/faang/multithreading/bro/Game.java
src/main/java/school/faang/multithreading/bro/Main.java
src/main/java/school/faang/multithreading/bro/Player.java

BJS2-37073

---

src/main/java/school/faangSprint3/t08/Game.java

BJS2-37097

---

src/main/java/Microsoft_BJS2_37798/MailSender.java
src/main/java/Microsoft_BJS2_37798/SennderRunnable.java

Очень хотелось сделать эту задачу через thread pools, но в ТЗ было задано, что надо использовать класс Tread и метод join

Ivan238502 bjs2 37798

---

src/main/java/school/faang/sender/MailSender.java
src/main/java/school/faang/sender/SenderRunnable.java

Создание потоков

---

src/main/java/tasks/bjs2_35987/Food.java
src/main/java/tasks/bjs2_35987/House.java
src/main/java/tasks/bjs2_35987/Room.java

Созданы класс House, Food, Room
Реализованы методы по сборы продуктов из комнаты.
Не смог реализовать задачу без synchronized (уж слишком замороченный получился год для обеспечения "синхронизации"), поэтому решил реализовать задачу с использованием данной конструкции для обеспечения сбора продуктов в каждой комнате каждым потоком , а так же обеспечить перенос продуктов из комнаты в общую корзину.

bjs2-35987 : Mice are very nice!

---

src/main/java/school/faang/streamAPI/ListOperations.java
src/main/java/school/faang/streamAPI/TestListOperations.java

"Задание 'StreamAPI 1' было выполнено."

"Задание 'StreamAPI 1' было выполнено."

---

src/main/java/school/faangSprint3/t09/Main.java
src/main/java/school/faangSprint3/t09/VideoManager.java

BJS2-37647

---

src/main/java/school/faang/multithreading/throne/House.java
src/main/java/school/faang/multithreading/throne/Main.java
src/main/java/school/faang/multithreading/throne/Role.java
src/main/java/school/faang/multithreading/throne/User.java

BJS2-37060

---

src/main/java/school/faangSprint3/t10/House.java
src/main/java/school/faangSprint3/t10/Main.java
src/main/java/school/faangSprint3/t10/User.java

BJS2-37063

---

src/main/java/school/faang/godbless/bjs2_36704/BigBangTheory.java
src/main/java/school/faang/godbless/bjs2_36704/Task.java

The Big Bang Theory BJS2-36704

---

src/main/java/org/example/model/theyWereVeryNiceButExtremelyPoor/Chore.java
src/main/java/org/example/service/theyWereVeryNiceButExtremelyPoor/Main.java
src/main/java/org/example/service/theyWereVeryNiceButExtremelyPoor/WeasleyFamily.java

added model Chore and service WeasleyFamily which add works in chore list and execute all chores with newCachedThreadPool and all this tested in Main

feat(newCachedThreadPool practice): made functions works with newCachedThreadPool

---

src/main/java/school/faang/spotifyblocking/Music.java
src/main/java/school/faang/spotifyblocking/Player.java

BJS2-37188 - Многопоточность: Блокировка Spotify

---

src/main/java/school/faang/godbless/bjs2_37246/Music.java
src/main/java/school/faang/godbless/bjs2_37246/Player.java
src/main/java/school/faang/godbless/bjs2_37246/Track.java

Блокировка Spotify bjs2 37246

---

src/main/java/school/faang/godbless/bjs2_36018/FoodDeliveryTask.java
src/main/java/school/faang/godbless/bjs2_36018/GriffinsFoodDelivery.java

Накормите Питера Гриффина BJS2-36018

---

src/main/java/microsoftmail/MailSender.java
src/main/java/microsoftmail/SenderRunnable.java

Решение задачи "Вы работаете в Microsoft!".

Решение задачи "Вы работаете в Microsoft!".

---

src/main/java/school/faang/heartMatters/Chat.java
src/main/java/school/faang/heartMatters/ChatManager.java
src/main/java/school/faang/heartMatters/Main.java
src/main/java/school/faang/heartMatters/User.java
src/main/java/school/faang/heartMatters/UserList.java

Получилось что-то вот такое, чувствую что есть что переделать, но не знаю что именно, буду рад комментам

"Matters of the heart"

---

src/main/java/tasks/bjs2_37214/GooglePhotosAutoUploader.java

Реализован класс GooglePhotosAutoUploader для эмуляции загрузки фото на сервер.
Добавлен метод main для тестирования функционала.

bjs2-37214 : Google Photo sync

---

src/main/java/org/example/model/spotifyBlocking/Music.java
src/main/java/org/example/model/spotifyBlocking/Player.java

add sync to all methods to all users listen common playlist in real time and to they don't disturb each other

feat(spotify block): add sync in Player methods

---

src/main/java/school/faang/mattersoftheheart/Chat.java
src/main/java/school/faang/mattersoftheheart/ChatManager.java
src/main/java/school/faang/mattersoftheheart/Main.java
src/main/java/school/faang/mattersoftheheart/User.java
src/main/java/school/faang/mattersoftheheart/UserList.java

1. Создайте класс User, который представляет пользователя приложения. В нем должны быть следующие поля и методы:
name — имя пользователя.
isOnline — флаг, который показывает, находится ли пользователь в сети.
isLookingForChat — флаг, который показывает, хочет ли пользователь начать чат.
Методы для получения и изменения этих полей.
2. Создайте класс UserList, который будет содержать список всех пользователей и методы для работы с этим списком:
getOnlineUsers() — возвращает список пользователей, которые находятся онлайн и хотят начать чат.
addUser(User user) — добавляет пользователя в список.
removeUser(User user) — удаляет пользователя из списка.
3. Создайте класс Chat, который будет представлять чат между двумя пользователями:
Поля: user1 и user2 — пользователи, участвующие в чате.
Методы …

BJS2-37737 Matters of the heart

---

src/main/java/school/faang/wow/Main.java
src/main/java/school/faang/wow/Player.java
src/main/java/school/faang/wow/Quest.java
src/main/java/school/faang/wow/QuestSystem.java

BJS2-38469 - Многопоточность: WOW

---

src/main/java/school/faang/mastercard/Main.java
src/main/java/school/faang/mastercard/MasterCardService.java

Задача: Асинхронность и Future

BJS2-38010 - Многопоточность: Асинхронность и Future

---

src/main/java/school/faang/async/future/MasterCardService.java

BJS2-38005

---

src/main/java/school/faang/bjs2_36844/Chore.java
src/main/java/school/faang/bjs2_36844/Main.java
src/main/java/school/faang/bjs2_36844/WeasleyFamily.java

added method: run for Chore implements Runnable

mikhailshapjr-BJS2-36844  They were very nice but extremely poor

---

src/main/java/school/faangSprint3/t13/BigBangTheory.java
src/main/java/school/faangSprint3/t13/Task.java

BJS2-36708

---

src/main/java/school/faangSprint4/t01/MasterCardService.java

BJS2-38035

---

src/main/java/school/faang/microsoft3sprint/MaleSender.java
src/main/java/school/faang/microsoft3sprint/SenderRunnable.java

Извиняюсь за решение из подсказки, реализовал изначально свое, но оказалось слишком примитивным, ознакомился с кодом из подсказки максимально.

first commit of task "Microsoft".

---

src/main/java/school/faangSprint3/t12/FoodDeliveryTask.java
src/main/java/school/faangSprint3/t12/GriffinsFoodDelivery.java

BJS2-36029

---

src/main/java/school/faang/bjs2_35926/Main.java
src/main/java/school/faang/bjs2_35926/model/Archer.java
src/main/java/school/faang/bjs2_35926/model/Fighter.java
src/main/java/school/faang/bjs2_35926/model/Mage.java
src/main/java/school/faang/bjs2_35926/model/Swordsman.java
src/main/java/school/faang/bjs2_35926/service/Army.java
src/test/java/school/faang/bjs2_35926/service/ArmyTest.java

added method: calculateTotalPower,addUnit for Army; calculateTotalPower,addUnit for ArmyTest

mikhailshapjr-BJS2-35926 Распределенная армия героев меча и магии

---

src/main/java/school/faang/godbless/bjs2_38026/AppWithPayments.java
src/main/java/school/faang/godbless/bjs2_38026/Main.java
src/main/java/school/faang/godbless/bjs2_38026/MasterCardService.java

Асинхронность и Future BJS2-38026

---

src/main/java/school/faang/godbless/bjs2_36289/Launcher.java
src/main/java/school/faang/godbless/bjs2_36289/RocketLaunch.java
src/main/java/school/faang/godbless/bjs2_36289/SpaceProgram.java

Космическая программа SpaceX BJS2-36289

---

src/main/java/school/faangSprint3/t11/Chat.java
src/main/java/school/faangSprint3/t11/ChatManager.java
src/main/java/school/faangSprint3/t11/Main.java
src/main/java/school/faangSprint3/t11/Message.java
src/main/java/school/faangSprint3/t11/User.java
src/main/java/school/faangSprint3/t11/UserList.java

BJS2-37497

---

src/main/java/school/faang/telegrambot/Main.java
src/main/java/school/faang/telegrambot/TelegramBot.java

https://faang-school.atlassian.net/browse/BJS2-37333

Telegram-бот

---

src/main/java/tasks/bjs2_36987/Boss.java
src/main/java/tasks/bjs2_36987/Game.java
src/main/java/tasks/bjs2_36987/Player.java

Решил чуть поменять реализацию программы. 
Решил устроить реальное сражение, пока не погибнет босс или не закончаться игроки. 
Раз в секунду у боса отнимается урон равный кол-ву игроков участвующих в сражении.
Окончанием сражения считается убийства босса или смерть всех бойцов. 
Боец живёт случайном в диапазоне от 2 до 10 секунд (Thread.Sleep)
В конце останавливаются все процессы и выводится информация о сражении. 
Данной задачей хотел попрактиковать возможность запуска 2-х задач, а так же попытке синхронизировать обе логики.
Так же были проблемы с wait и notify которые так же хотел дополнительно попрактиковать.

Lexsandr bjs2 36987

---

src/main/java/Sprint_3/BJS2_36019/Main.java
src/main/java/Sprint_3/BJS2_36019/Person.java
src/main/java/Sprint_3/BJS2_36019/PersonInfoPrinter.java

Так же переопределил метод ран, что бы выводить информацию по потокам.

Помогите коллеге задача.

---

src/main/java/school/faang/thread2/Archer.java
src/main/java/school/faang/thread2/Army.java
src/main/java/school/faang/thread2/Mage.java
src/main/java/school/faang/thread2/Main.java
src/main/java/school/faang/thread2/PowerCalculator.java
src/main/java/school/faang/thread2/Soldier.java
src/main/java/school/faang/thread2/Swordsman.java

Был создан абстрактный класс "Soldier", чтобы его могли расширять конкретные группы солдат армии. Были созданы несколько потоков для расчета общей мощи армии.

Army of heros

---

src/main/java/org/example/service/stripe/Main.java
src/main/java/org/example/service/stripe/MasterCardService.java

added service MasterCardService with methods sendAnalytic(), collectPayment() and doAll() which work async

feat(BJS2-38117): practice async

---

src/main/java/school/faang/bjs2_35278/Operators.java
src/main/java/school/faang/bjs2_35278/OperatorsTest.java
src/main/java/school/faang/bjs2_35278/UseOperators.java

Reverts CorporationX/god_bless#11729

StreamAPI 2

---

src/main/java/school/faang/async/magician/School.java
src/main/java/school/faang/async/magician/Student.java
src/main/java/school/faang/async/magician/Task.java
src/main/java/school/faang/async/magician/Tournament.java

BJS2-38911

---

src/main/java/school/faangSprint4/t06/Main.java
src/main/java/school/faangSprint4/t06/TwitterAccount.java
src/main/java/school/faangSprint4/t06/TwitterSubscriptionSystem.java

BJS2-38918

---

src/main/java/school/faangSprint4/t05/Potion.java
src/main/java/school/faangSprint4/t05/PotionGathering.java

BJS2-38795

---

src/main/java/school/faangSprint4/t05/Main.java
src/main/java/school/faangSprint4/t05/Order.java
src/main/java/school/faangSprint4/t05/OrderProcessor.java
src/main/java/school/faangSprint4/t05/OrderStatus.java

BJS2-38064

---

src/main/java/school/faang/amazonorderprocessor/AmazonOrderProcessing.java
src/main/java/school/faang/amazonorderprocessor/Order.java
src/main/java/school/faang/amazonorderprocessor/OrderProcessor.java

Собираем заказы в Amazon

---

src/main/java/school/faangSprint3/t14/King.java
src/main/java/school/faangSprint3/t14/Knight.java
src/main/java/school/faangSprint3/t14/Trial.java

BJS2-35773

---

src/main/java/school/faangSprint3/t15/Main.java
src/main/java/school/faangSprint3/t15/Person.java
src/main/java/school/faangSprint3/t15/PersonInfoPrinter.java

BJS2-35976

---

src/main/java/school/faangSprint3/t16/CashierThread.java
src/main/java/school/faangSprint3/t16/Main.java

BJS2-36268

---

src/main/java/school/faangSprint3/t17/Main.java
src/main/java/school/faangSprint3/t17/Pig1Thread.java
src/main/java/school/faangSprint3/t17/Pig2Thread.java
src/main/java/school/faangSprint3/t17/Pig3Thread.java
src/main/java/school/faangSprint3/t17/PigThread.java

BJS2-36385

---

src/main/java/school/faangSprint4/t08/Kingdom.java
src/main/java/school/faangSprint4/t08/Main.java
src/main/java/school/faangSprint4/t08/RavenService.java

BJS2-37908

---

src/main/java/school/faang/java/thread1/familyweasley/Chore.java
src/main/java/school/faang/java/thread1/familyweasley/Main.java
src/main/java/school/faang/java/thread1/familyweasley/WeasleyFamily.java
src/main/java/school/faang/java/thread1/microsoft/MailSender.java
src/main/java/school/faang/java/thread1/microsoft/SenderRunnable.java

school.faang.java.thread1.familyweasley;
- Классы созданы;
- все задания создаются;
- все задания завершаются;
- Работа пула потоков завершена.

Alex thread1 t1 family uisly bjs2 36896

---

src/main/java/school/faang/BJS2_38691/Main.java
src/main/java/school/faang/BJS2_38691/Player.java
src/main/java/school/faang/BJS2_38691/Quest.java
src/main/java/school/faang/BJS2_38691/QuestSystem.java

Проверка работы кода на примере из условия

Реализация асинхронности

---

src/main/java/school/faang/sprint_4/bjs2_38983_twitterCelebrity/Main.java
src/main/java/school/faang/sprint_4/bjs2_38983_twitterCelebrity/TwitterSubscriptionSystem.java
src/main/java/school/faang/sprint_4/bjs2_38983_twitterCelebrity/account_manager/AccountManager.java
src/main/java/school/faang/sprint_4/bjs2_38983_twitterCelebrity/account_manager/TwitterAccount.java

Можно еще улучшить производительность изменив некоторые коллекции на ConcurrentHashMap и наверняка еще много разных вариантов есть, но я хочу уже двигаться дальше по задачам 🤣 
Простите, если это не читабельно. 😞 
ps.
модификаторы default чтобы методы были package-private

deema-bjs2-38983 twitter

---

src/main/java/org/example/model/wow/Player.java
src/main/java/org/example/model/wow/Quest.java
src/main/java/org/example/service/wow/Main.java
src/main/java/org/example/service/wow/QuestSystem.java

added model Player, Quest and service QuestSystem with method startQuest which start the quest async

feat(BJS2-38698): Warcraft quest system

---

src/main/java/school/faang/sendnotificationsfacebook/FacebookNotificationSystem.java
src/main/java/school/faang/sendnotificationsfacebook/Notification.java
src/main/java/school/faang/sendnotificationsfacebook/NotificationManager.java

https://faang-school.atlassian.net/browse/BJS2-38899

Рассылаем уведомления в Facebook

---

src/main/java/school/faangSprint3/t20/Main.java
src/main/java/school/faangSprint3/t20/TamagotchiVlad.java
src/main/java/school/faangSprint3/t20/VladController.java

BJS2-36745

---

src/main/java/school/faangSprint4/t04/Main.java
src/main/java/school/faangSprint4/t04/Player.java
src/main/java/school/faangSprint4/t04/Quest.java
src/main/java/school/faangSprint4/t04/QuestSystem.java

BJS2-38630

---

src/main/java/org/example/model/facebookNotification/Notification.java
src/main/java/org/example/service/facebookNotification/Main.java
src/main/java/org/example/service/facebookNotification/NotificationManager.java

added functional which async add the notifications to list and compliance true access to list

feat(BJS2-38821): notification FaceBook

---

src/main/java/school/faangSprint4/t09/Main.java
src/main/java/school/faangSprint4/t09/ResultConsumer.java
src/main/java/school/faangSprint4/t09/SquareRequest.java

BJS2-38029

---

src/main/java/school/faangSprint4/t10/Main.java
src/main/java/school/faangSprint4/t10/Pair.java
src/main/java/school/faangSprint4/t10/Superhero.java
src/main/java/school/faangSprint4/t10/SuperheroBattle.java

BJS2-38426

---

src/main/java/school/faangSprint4/t14/GameSystem.java
src/main/java/school/faangSprint4/t14/Inventory.java
src/main/java/school/faangSprint4/t14/Item.java
src/main/java/school/faangSprint4/t14/Main.java

BJS2-38836

---

src/main/java/school/faangSprint4/t06/Main.java
src/main/java/school/faangSprint4/t06/School.java
src/main/java/school/faangSprint4/t06/Student.java
src/main/java/school/faangSprint4/t06/Task.java
src/main/java/school/faangSprint4/t06/Tournament.java

BJS2-39063

---

src/main/java/school/faangSprint4/t07/Battle.java
src/main/java/school/faangSprint4/t07/BattleManager.java
src/main/java/school/faangSprint4/t07/Robot.java
src/main/java/school/faangSprint4/t07/StarWarsArena.java

BJS2-38310

---

src/main/java/school/faang/java/thread1/supercow/Boss.java
src/main/java/school/faang/java/thread1/supercow/Main.java
src/main/java/school/faang/java/thread1/supercow/Player.java

Thread1-T2-Supercow-BJS2-36937

---

src/main/java/school/faangSprint4/t12/Donation.java
src/main/java/school/faangSprint4/t12/DonationSystem.java
src/main/java/school/faangSprint4/t12/Organization.java

BJS2-40115

---

src/main/java/school/faangSprint4/t11/Comment.java
src/main/java/school/faangSprint4/t11/Main.java
src/main/java/school/faangSprint4/t11/Post.java
src/main/java/school/faangSprint4/t11/PostService.java
src/main/java/school/faangSprint4/t11/UserAction.java

BJS2-39234

---

src/main/java/school/faang/starwarsarena/Battle.java
src/main/java/school/faang/starwarsarena/Main.java
src/main/java/school/faang/starwarsarena/Robot.java

BJS2-38311 - Многопоточность: Star Wars Arena

---

src/main/java/school/faang/synchronizedthreads2/Main.java
src/main/java/school/faang/synchronizedthreads2/VideoManager.java

Example of the synchronized threads

YouTube view counter. 

---

src/main/java/heroarmy/Archer.java
src/main/java/heroarmy/Army.java
src/main/java/heroarmy/Mage.java
src/main/java/heroarmy/Main.java
src/main/java/heroarmy/PowerCalculator.java
src/main/java/heroarmy/Swordsman.java
src/main/java/heroarmy/Unit.java

Решение задачи "Распределенная армия героев меча и магии".

Решение задачи "Распределенная армия героев меча и магии".

---

src/main/java/school/faangSprint3/t19/RocketLaunch.java
src/main/java/school/faangSprint3/t19/RocketLaunchSimulator.java

BJS2-36279

---

src/main/java/school/faang/googledocs/App.java
src/main/java/school/faang/googledocs/CollaborativeDocument.java
src/main/java/school/faang/googledocs/DocumentSection.java
src/main/java/school/faang/googledocs/DocumentSectionProcessor.java

https://faang-school.atlassian.net/browse/BJS2-39394

Google Docs

---

src/main/java/school/faang/leavecomment/Comment.java
src/main/java/school/faang/leavecomment/Main.java
src/main/java/school/faang/leavecomment/Post.java
src/main/java/school/faang/leavecomment/PostService.java

https://faang-school.atlassian.net/browse/BJS2-39291

Оставляем комментарий

---

src/main/java/school/faang/BJS238312/Battle.java
src/main/java/school/faang/BJS238312/Robot.java
src/main/java/school/faang/BJS238312/Runner.java

Star Wars Arena BJS2-38312

---

src/main/java/school/faang/async/wow/Player.java
src/main/java/school/faang/async/wow/Quest.java
src/main/java/school/faang/async/wow/QuestSystem.java

BJS2-38466

---

src/main/java/school/faangSprint4/t13/FacebookNotificationSystem.java
src/main/java/school/faangSprint4/t13/Notification.java
src/main/java/school/faangSprint4/t13/NotificationManager.java

BJS2-38841

---

src/main/java/school/faang/workstopped/DesignDepartment.java
src/main/java/school/faang/workstopped/DesignResources.java
src/main/java/school/faang/workstopped/Main.java
src/main/java/school/faang/workstopped/MarketingDepartment.java
src/main/java/school/faang/workstopped/MarketingResources.java

https://faang-school.atlassian.net/browse/BJS2-39393

Работа стоит

---

src/main/java/school/faang/async/amazon/AmazonOrderProcessing.java
src/main/java/school/faang/async/amazon/Order.java
src/main/java/school/faang/async/amazon/OrderProcessor.java

BJS2-38077

---

src/main/java/school/faang/async/alchemist/Potion.java
src/main/java/school/faang/async/alchemist/PotionGathering.java

BJS2-38665

---

src/main/java/school/faang/async/twitter/Twitter.java
src/main/java/school/faang/async/twitter/TwitterAccount.java
src/main/java/school/faang/async/twitter/TwitterSubscriptionSystem.java

BJS2-38908

---

src/main/java/school/faang/trackingsystem/Location.java
src/main/java/school/faang/trackingsystem/Main.java
src/main/java/school/faang/trackingsystem/TransportManagementSystem.java
src/main/java/school/faang/trackingsystem/Vehicle.java
src/main/java/school/faang/trackingsystem/VehicleTracker.java

https://faang-school.atlassian.net/browse/BJS2-40300

Система трекинга

---

src/main/java/school/faang/fieldbasecomein/App.java
src/main/java/school/faang/fieldbasecomein/EncryptionUtils.java
src/main/java/school/faang/fieldbasecomein/MilitaryBase.java

https://faang-school.atlassian.net/browse/BJS2-39700

База, прием!

---

src/main/java/school/faang/monitorelectrsubstations/Main.java
src/main/java/school/faang/monitorelectrsubstations/MonitoringSystem.java
src/main/java/school/faang/monitorelectrsubstations/Sensor.java
src/main/java/school/faang/monitorelectrsubstations/SensorData.java
src/main/java/school/faang/monitorelectrsubstations/Substation.java

https://faang-school.atlassian.net/browse/BJS2-39293

Мониторинг электроподстанций

---

src/main/java/school/faang/fourthStream/BJS2_38324/Factorial.java
src/main/java/school/faang/fourthStream/BJS2_38324/Main.java

complete the task "Великий и ужасный факториал!

---

src/main/java/school/faang/sprint_4/bjs2_37937_raven/Kingdom.java
src/main/java/school/faang/sprint_4/bjs2_37937_raven/Main.java
src/main/java/school/faang/sprint_4/bjs2_37937_raven/RavenLostException.java
src/main/java/school/faang/sprint_4/bjs2_37937_raven/RavenService.java

Все работает, единственное, чего я не понял, не слишком ли излишне у меня вышло, что log.error дважды логирует по сути одну и ту же ошибку, получается в логах какой-то спам)

deema-bjs2-37937 raven

---

src/main/java/school/faang/BJS238131/Order.java
src/main/java/school/faang/BJS238131/OrderProcessor.java
src/main/java/school/faang/BJS238131/Runner.java

Ну практикую максимально стримы. И дайте фитбек пожалуйста, не только касаемо ошибок, но и стиля кода

BJS2-38131. Собираем заказы в Amazon

---

src/main/java/school/faang/m1s4/bjs2_38323_factorial/Factorial.java
src/main/java/school/faang/m1s4/bjs2_38323_factorial/Main.java

Вот тут я рад собой. Сделал задачу, но решил накинуть звезду сверху и попробовать еще оптимизировать. Возможно это простой и наивный алгоритм, но когда придумываешь и реализуешь его сам, то прям приятно :))
Просто оставлю это здесь, цифры за себя говорят (причем эффективность растет по экспоненте) :)
Список из 15_000 рандомных цифр с лимитом до 10_000 (пул 10 потоков):
15:48:25.866082: Speed experiment #1 --- For cycle, brute force
Time spent: 138_647 ms
- - - - - - - - - - - - - - - 
15:50:44.520912: Speed experiment #2 --- Multithreading
Time spent: 20_580 ms
- - - - - - - - - - - - - - - 
15:51:05.100335: Speed experiment #3 --- Multithreading Optimized
Time spent: 10_442 ms
P.S. В Main много повторяющегося кода, он там исключительно для проведения экспериментов.

BJS2-38323 Factorial: task done

---

src/main/java/school/faang/m1s4/bsj2_38762_dota/Inventory.java
src/main/java/school/faang/m1s4/bsj2_38762_dota/Item.java
src/main/java/school/faang/m1s4/bsj2_38762_dota/Main.java

Я осознанно (ленился) не добавил Executor Service. Работает на собственном пуле Concurrency, основной задачей было отработать связку Combine - Compose

BJS2-38762 Dota: task done

---

src/main/java/school/faang/BJS239060/Runner.java
src/main/java/school/faang/BJS239060/TwitterAccount.java
src/main/java/school/faang/BJS239060/TwitterSubscriptionSystem.java

Проверьте пожалуйста. Есть вопрос: Если мы делаем синхронизированным метод (как дано по условию) то метод main тоже будет выводить сообщение...

BJS2-39060. Становимся celebrity в Twitter

---

src/main/java/school/faang/m1s4/bjs2_38347_pi/Calculator.java
src/main/java/school/faang/m1s4/bjs2_38347_pi/Main.java
src/main/java/school/faang/m1s4/bjs2_38347_pi/Point.java

Альтернативный подход. Мы с Димой решили, что мы современники Архимеда, простые греки, которые не знают формул, кроме суммы квадратов Пифагора открытых двести лет назад, вооруженные только своей смекалкой и силой Эппл Силикон. Решили победить задачу, накинув сверху еще один мозг сложности, и найти эту удивительную пи, отринув любые известные формулы, данные в условии. 
И мы справились. Разницу в 6 стотысячных я считаю успехом.

BJS2-38347 Pi: Task done

---

src/main/java/school/faang/BJS238043/Main.java
src/main/java/school/faang/BJS238043/MasterCardService.java

slava-BJS2-38043

---

src/main/java/school/faang/playbank/Account.java
src/main/java/school/faang/playbank/Bank.java
src/main/java/school/faang/playbank/BankDemo.java

https://faang-school.atlassian.net/browse/BJS2-39899

Поиграем в банк!

---

src/main/java/school/faang/deliverycoupons/DeliveryService.java
src/main/java/school/faang/deliverycoupons/Main.java
src/main/java/school/faang/deliverycoupons/Order.java
src/main/java/school/faang/deliverycoupons/Product.java
src/main/java/school/faang/deliverycoupons/PromoCode.java

https://faang-school.atlassian.net/browse/BJS2-40204

Купоны на доставку

---

src/main/java/school/faang/collectingdatareport/DataCollector.java
src/main/java/school/faang/collectingdatareport/Main.java
src/main/java/school/faang/collectingdatareport/ReportGenerator.java
src/main/java/school/faang/collectingdatareport/Sales.java
src/main/java/school/faang/collectingdatareport/SalesData.java

https://faang-school.atlassian.net/browse/BJS2-39876

Сбор данных для отчета

---

src/main/java/school/faangSprint4/t17/Main.java
src/main/java/school/faangSprint4/t17/Point.java

BJS2-38368

---

src/main/java/school/faangSprint4/t15/DeadlockDemo.java
src/main/java/school/faangSprint4/t15/DesignDepartment.java
src/main/java/school/faangSprint4/t15/DesignDepartmentSafe.java
src/main/java/school/faangSprint4/t15/DesignResources.java
src/main/java/school/faangSprint4/t15/DesignResourcesSafe.java
src/main/java/school/faangSprint4/t15/MarketingDepartment.java
src/main/java/school/faangSprint4/t15/MarketingDepartmentSafe.java
src/main/java/school/faangSprint4/t15/MarketingResources.java
src/main/java/school/faangSprint4/t15/MarketingResourcesSafe.java

BJS2-39313

---

src/main/java/school/faangSprint4/t16/Account.java
src/main/java/school/faangSprint4/t16/Bank.java
src/main/java/school/faangSprint4/t16/BankingSystem.java

BJS2-39866

---

src/main/java/blockingspotify/Main.java
src/main/java/blockingspotify/Player.java

BJS2-37394-Блокировка Spotify

---

src/main/java/asyncfuture/Main.java
src/main/java/asyncfuture/MasterCardService.java

BJS2-38135-Асинхронность и Future.

BJS2-38135-Асинхронность и Future.

---

src/main/java/school/faangSprint4/t19/App.java
src/main/java/school/faangSprint4/t19/CollaborativeDocument.java
src/main/java/school/faangSprint4/t19/DocumentSection.java
src/main/java/school/faangSprint4/t19/DocumentSectionProcessor.java

BJS2-39373

---

src/main/java/wow/Main.java
src/main/java/wow/Player.java
src/main/java/wow/Quest.java
src/main/java/wow/QuestSystem.java

BJS2-38673-WOW.

---

src/main/java/school/faang/BJS237933/Kingdom.java
src/main/java/school/faang/BJS237933/Runner.java

Максимально постарался причесать код :)

BJS2-37933. Пошлите (Пните) ворона

---

src/main/java/comments/Comment.java
src/main/java/comments/Main.java
src/main/java/comments/Post.java
src/main/java/comments/PostService.java
src/main/java/comments/User.java

BJS2-39372-Оставляем комментарий.

BJS2-39372-Оставляем комментарий.

---

src/main/java/school/faang/workSuspended/Deadlock/DesignDepartment.java
src/main/java/school/faang/workSuspended/Deadlock/DesignResources.java
src/main/java/school/faang/workSuspended/Deadlock/MainDeadlock.java
src/main/java/school/faang/workSuspended/Deadlock/MarketingDepartment.java
src/main/java/school/faang/workSuspended/Deadlock/MarketingResources.java
src/main/java/school/faang/workSuspended/Fixed/DesignDepartment.java
src/main/java/school/faang/workSuspended/Fixed/DesignResources.java
src/main/java/school/faang/workSuspended/Fixed/MainFixed.java
src/main/java/school/faang/workSuspended/Fixed/MarketingDepartment.java
src/main/java/school/faang/workSuspended/Fixed/MarketingResources.java

Сделал два пакета - один, с дедлоком, второй с фиксом дедлока.

"Работа стоит"

---

src/main/java/school/faang/java/thread2/wow/Main.java
src/main/java/school/faang/java/thread2/wow/Player.java
src/main/java/school/faang/java/thread2/wow/Quest.java
src/main/java/school/faang/java/thread2/wow/QuestSystem.java
src/main/java/school/faang/java/thread2/wow/readme.txt

Thread1-BJS2-38728

---

src/main/java/school/faang/thread4/Music.java
src/main/java/school/faang/thread4/Player.java

Example with Lock to create synchronized threads

Synchronized threads

---

src/main/java/school/faangSprint4/t18/Factorial.java

BJS2-38335

---

src/main/java/school/faangSprint4/t22/Location.java
src/main/java/school/faangSprint4/t22/Main.java
src/main/java/school/faangSprint4/t22/TransportManagementSystem.java
src/main/java/school/faangSprint4/t22/Vehicle.java
src/main/java/school/faangSprint4/t22/VehicleTracker.java

BJS2-40241

---

src/main/java/school/faangSprint4/t25/DeliveryService.java
src/main/java/school/faangSprint4/t25/Main.java
src/main/java/school/faangSprint4/t25/Order.java
src/main/java/school/faangSprint4/t25/Product.java
src/main/java/school/faangSprint4/t25/PromoCode.java

BJS2-40189

---

src/main/java/school/faangSprint4/t21/Main.java
src/main/java/school/faangSprint4/t21/MonitoringSystem.java
src/main/java/school/faangSprint4/t21/Sensor.java
src/main/java/school/faangSprint4/t21/SensorData.java
src/main/java/school/faangSprint4/t21/Substation.java

BJS2-39156

---

src/main/java/school/faangSprint4/t20/Conference.java
src/main/java/school/faangSprint4/t20/Main.java
src/main/java/school/faangSprint4/t20/Participant.java

BJS2-39457

---

src/main/java/school/faang/java/thread2/threemags/Main.java
src/main/java/school/faang/java/thread2/threemags/School.java
src/main/java/school/faang/java/thread2/threemags/Student.java
src/main/java/school/faang/java/thread2/threemags/Task.java
src/main/java/school/faang/java/thread2/threemags/Timeout.java
src/main/java/school/faang/java/thread2/threemags/Tournament.java
src/main/java/school/faang/java/thread2/threemags/readme.txt

Three mags-BJS2-39184

---

src/main/java/school/faang/task4207/Main.java

2 варианта
Сначала сделал с CountDownLatch, посмотрел в подсказки, сделал CyclicBarrier

roman.shipilov-BJS2-39898

---

src/main/java/school/faangSprint4/t23/App.java
src/main/java/school/faangSprint4/t23/EncryptionUtils.java
src/main/java/school/faangSprint4/t23/MilitaryBase.java

BJS2-39638

---

src/main/java/school/faangSprint3/t21/Main.java
src/main/java/school/faangSprint3/t21/TelegramBot.java

BJS2-37275

---

src/main/java/org/example/model/countAmazonOrders/Order.java
src/main/java/org/example/service/countAmazonOrders/Main.java
src/main/java/org/example/service/countAmazonOrders/OrderProcessor.java

added functional where count the order process async and safety threads

feat(BJS2-38156): amazon order counter

---

src/main/java/school/faang/Main.java

Развернитесь! №3

---

src/main/java/school/faang/task_43600/Example.java
src/main/java/school/faang/task_43600/Main.java

Задача BJS2-43600 (Развернись!)  была выполнена.

BJS2-43600  The task BJS2-43600 was completed.

---

src/main/java/school/faang/Example.java
src/main/java/school/faang/Main.java

Revers array

---

src/main/java/school/faang/Example.java

Update Example.java
Make void reverse method
Add empty array check 
Add main method as entry point

rostexlivew-BJS2-43607-fix

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/task_43600/Example.java

Задача BJS2-43600 (Развернись!) была выполнена. Пробелы после for добавлены.

Leshak-bjs2-43600

---

src/main/java/school/faang/task_43500/Example.java
src/main/java/school/faang/task_43500/Main.java

Create Example class and reverse method

---

src/main/java/school/faang/task_43501/Main.java
src/main/java/school/faang/task_43501/User.java

Задача Регистрация пользователей

Register users

---

src/main/java/school/faang/bjs243613/Example.java

В данной задаче реализовал функцию по развороту массива и протестировал в методе main на целочисленном массиве

Task reverse array

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/task_43656/Main.java
src/main/java/school/faang/task_43656/User.java

BJS2-43656 was completed. Branch LeshaK-BJS2-43656 was added.

BJS2-43656 was completed. Branch LeshaK-BJS2-43656 was added.

---

src/main/java/school/faang/bjs243922/Main.java
src/main/java/school/faang/bjs243922/User.java

Create class User and groupUsers fun.

Task number : BJS2-43922

---

src/main/java/school/faang/bjs243659/Main.java
src/main/java/school/faang/bjs243659/User.java

Create class User and add checked.

Task number : BJS2-43659

---

src/main/java/school/faang/bjs2_44686_rarebs3/App.java
src/main/java/school/faang/task_44686/App.java

Vvz3zzv bjs2 44686 rare bs3 feature a

---

src/main/java/school/faang/task_44686/App.java

vvz3zzv-BJS2-44354-raraBS3-featureB

---

src/main/java/school/faang/Exemple.java
src/main/java/school/faang/Main.java

BJS2-43602

---

src/main/java/GroupUsers/Main.java
src/main/java/GroupUsers/User.java

Второй PR. Первый был в master(

Группировка пользователей

---

src/main/java/school/faang/BJS2_45234/programm/Main.java
src/main/java/school/faang/Main.java
src/main/java/school/faang/bjs245234/model/Book.java
src/main/java/school/faang/bjs245234/programm/Main.java
src/main/java/school/faang/bjs245234/repository/LibrarySystem.java

Artemon-BJS2-45234

---

src/main/java/school/module1/task43685/Main.java
src/main/java/school/module1/task43685/User.java

added registration user

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/task_43858/Main.java
src/main/java/school/faang/task_43858/User.java

- Добавлена группировка пользователей по возрасту.
- Метод groupUsers без использования Stream API.

Pa1adium bjs2 43858

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/task_43890/Main.java
src/main/java/school/faang/task_43890/User.java

BJS2-43890 was completed.

---

src/main/java/school/faang/sprint_1/task_bjs243909/Main.java
src/main/java/school/faang/sprint_1/task_bjs243909/User.java

BJS2-43909 Группировка пользователей по возрасту.

---

src/main/java/school/faang/BJS2x43911/User.java
src/main/java/school/faang/bjs2x43911/User.java

Jira не работает, не могу ничего сделать там

ibai86 BJS2_43911

---

src/main/java/school/faang/Main.java
src/main/java/school/faang/task_43807/Archer.java
src/main/java/school/faang/task_43807/Character.java
src/main/java/school/faang/task_43807/Main.java
src/main/java/school/faang/task_43807/Warrior.java

BJS2-43807 was completed. Branch LeshaK-BJS2-43807 was added.

BJS2-43807 was completed. Branch LeshaK-BJS2-43807 was added.

---

src/main/java/school/faang/Example.java
src/main/java/school/faang/Main.java

Artur bjs2 43632

---

src/main/java/school/faang/sprint_1/task_bjs243608/Example.java
src/main/java/school/faang/sprint_1/task_bjs243608/Main.java

Test method is main in Example class. Method reverse is static only because we don't write tests, but test in the main class.

BJS2-43608 Развернитесь!

---

src/main/java/school/faang/sprint_1/task_43688/Main.java
src/main/java/school/faang/sprint_1/task_43688/User.java

BJS2-43688: Регистрация пользователей
